fix: Make `dx` histogram behavior consistent with `px`
deephaven/deephaven-plugins pull request #1002
Opened 2024-11-08 16:24 UTC by jnumainville

Fixes: #668 

The following examples are now basically consistent. 
During testing I discovered https://github.com/deephaven/deephaven-plugins/issues/1001 so the legend titles are not set in a couple of these, but that is beyond the scope of this ticket as that is a general plot by issue, not a histogram specific one.

Note a few intentional differences in the args. It's not expected that `dx` histograms and `px` histograms aggregate in the same exact way. Plotly infers the equivalent of `range_bins` hence the extra argument. Additionally we have `barmode="group"` as our default whereas in Plotly it is `barmode="relative"`. I believe this was an intentional choice on our end because it's hard to compare the different traces with `barmode="relative"` although I don't have a record of it.

```
import plotly.express as px
import deephaven.plot.express as dx

df = px.data.tips()
fig = px.histogram(df, x="size", y="total_bill")
fig2 = px.histogram(df, x="size", y="total_bill", histfunc="count", nbins=6)
fig3 = px.histogram(df, x="size", y="total_bill", orientation="h", nbins=6)
fig4 = px.histogram(df, x="size", y="total_bill", orientation="h", histfunc="count", nbins=6)
fig5 = px.histogram(df, x=["tip", "total_bill"], y="size", nbins=6)
fig6 = px.histogram(df, x=["tip", "total_bill"], y="size", orientation="h", nbins=6)
fig7 = px.histogram(df, x="size", y=["tip", "total_bill"], nbins=6)
fig8 = px.histogram(df, x="size", y=["tip", "total_bill"], orientation="h", nbins=6)
fig9 = px.histogram(df, x=["tip", "total_bill"], y="size", histfunc="count", nbins=6)
fig10 = px.histogram(df, x=["tip", "total_bill"], y="size", orientation="h", histfunc="count")
fig11 = px.histogram(df, x="size", y=["tip", "total_bill"], histfunc="count", nbins=6)
fig12 = px.histogram(df, x="size", y=["tip", "total_bill"], orientation="h", histfunc="count", nbins=6)
fig13 = px.histogram(df, x="size", y=["tip", "total_bill"], histnorm="probability", barnorm="percent")
fig14 = px.histogram(df, x="size")
fig15 = px.histogram(df, y="size")

fig1d = dx.histogram(df, x="size", y="total_bill", nbins=6, range_bins=[0, 7])
fig2d = dx.histogram(df, x="size", y="total_bill", histfunc="count", nbins=6, range_bins=[0, 7])
fig3d = dx.histogram(df, x="size", y="total_bill", orientation="h", nbins=6, range_bins=[0, 60])
fig4d = dx.histogram(df, x="size", y="total_bill", orientation="h", histfunc="count", nbins=6, range_bins=[0, 60])
fig5d = dx.histogram(df, x=["tip", "total_bill"], y="size", nbins=6, range_bins=[0, 60], barmode="relative")
fig6d = dx.histogram(df, x=["tip", "total_bill"], y="size", orientation="h", nbins=6, range_bins=[0, 7], barmode="relative")
fig7d = dx.histogram(df, x="size", y=["tip", "total_bill"], nbins=6, range_bins=[0, 7], barmode="relative")
fig8d = dx.histogram(df, x="size", y=["tip", "total_bill"], orientation="h", nbins=6, range_bins=[0, 60], barmode="relative")
fig9d = dx.histogram(df, x=["tip", "total_bill"], y="size", histfunc="count", nbins=6, range_bins=[0, 60], barmode="relative")
fig10d = dx.histogram(df, x=["tip", "total_bill"], y="size", orientation="h", histfunc="count", nbins=6, range_bins=[0, 7], barmode="relative")
fig11d = dx.histogram(df, x="size", y=["tip", "total_bill"], histfunc="count", nbins=6, range_bins=[0, 7], barmode="relative")
fig12d = dx.histogram(df, x="size", y=["tip", "total_bill"], orientation="h", histfunc="count", nbins=6, range_bins=[0, 60], barmode="relative")
fig13d = dx.histogram(df, x="size", y=["tip", "total_bill"], histnorm="probability", barnorm="percent", range_bins=[0,7], nbins=6, barmode="relative")
fig14d = dx.histogram(df, x="size", nbins=6)
fig15d = dx.histogram(df, y="size", nbins=6)
```

2024-11-08 19:25 UTC, margaretkennedy submitted a review, later dismissed

2024-11-20 20:44 UTC, mattrunyon requested changes

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/generate.py
> +    if hist_agg_label_h:
Might be a bit clearer to make the args `hist_agg_label` and `hist_orientation`

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/plots/distribution.py
> +        the bars are drawn horizontally by default.
Just making sure this has different behavior from bar in that the columns must be numeric. From the bar orientation docstring it looks like 1 value can be non-numeric

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/HistPreprocessor.py
> +        )
Is the ternary necessary here? Since there's a default empty dict for `labels`, I think you can just get rid of the ternary since the `else` should never hit? I guess unless a user specified `labels=None` maybe?

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/HistPreprocessor.py
> +                hist_agg_label = f"percent of sum of {hist_agg_label}"
Why are these `X of sum of Y`? Looks like this is the case where `histfunc` is not count or sum. So is there a `histfunc` that should be required for these cases?

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariateAwarePreprocessor.py
> +    Should be inherited from.
Should this be abstract?

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariateAwarePreprocessor.py
> +        list_var: The var that was passed in as a list
I'm confused by what these do. Is `pivot_vars` column renames? Is `list_var` supposed to be something like `x` or `y`?

2024-11-20 20:44 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariateAwarePreprocessor.py
> +            self.agg_col = self.bin_col
Should the comment in the else say `agg_var`? The if only checks `agg_var`, not `bar_var`

2024-12-18 16:23 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariateAwarePreprocessor.py
> +        list_var: The var that was passed in as a list
`pivot_vars` is kind of a rename - it's for when you pass in a list so the tables need to be stacked with resulting `value` and `variable` columns, although they may or may not be named exactly that if those columns already exist in the table. It's not a great name for that dict. I think I'll go ahead and refactor it as part of this.
`list_var` would be `x` or `y` yes, whichever parameter was a list originally

2024-12-18 16:31 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/distribution.py
> +        the bars are drawn horizontally by default.
I don't really love how plotly does that because I think it could be error prone in our case due to all the complex data types, but I've got some code to check for numeric columns in `PartitionManager` I can refactor anyways so I'll pull that in at least.

2024-12-18 19:37 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/distribution.py
> +        the bars are drawn horizontally by default.
Yes, that's intentional. Our histogram never allows non-numeric data. Our bar does. It's worth noting that the logic in `calculate_bar_orientation` isn't called by bar when both `x` and `y` are specified, only when `x` or `y` is (as that is the logic that was formally known as `frequency_bar`) so the `orientation` in that case is set by the wrapped `px.bar` function.

2024-12-18 19:39 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/HistPreprocessor.py
> +        )
Yeah it's for when `labels=None`

2024-12-18 19:41 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/generate.py
> +    if hist_agg_label_h:
done

2024-12-18 19:41 UTC, jnumainville commented on plugins/plotly-express/docs/histogram.md
> +If both `x` and `y` are specified, the histogram will be binned across one column and aggregated on the other.
done

2024-12-18 19:42 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariateAwarePreprocessor.py
> +    Should be inherited from.
done

2024-12-18 19:42 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/UnivariateAwarePreprocessor.py
> +            self.agg_col = self.bin_col
done

2025-03-20 21:02 UTC, mattrunyon approved these changes

2025-03-20 21:09 UTC, merged