feat: ui.inline_alert
deephaven/deephaven-plugins pull request #1007
Opened 2024-11-11 18:37 UTC by AkshatJawne

Closes #937 and Closes #867

2024-11-13 15:41 UTC, mofojed submitted a review, later dismissed
Code looks good. Should also add to e2e tests, `ui_render_all.py` and update snapshots (we've missed this with a couple of the last few components merged I think).

2024-11-13 15:47 UTC, margaretkennedy submitted a review, later dismissed

2024-11-15 11:33 UTC, margaretkennedy commented on plugins/ui/docs/components/inline_alert.md
> +Consider using [`ui.heading`](./heading.md) if you want to create different types of headings.
Without first knowing an inline alert contains a ui.heading, this feels out of context.

2024-11-15 11:33 UTC, margaretkennedy commented on plugins/ui/docs/components/inline_alert.md
> +A variant can be set using the `variant` prop to give inline alerts a semantic meaning.
```suggestion
The `variant` prop can set a variant to give inline alerts a semantic meaning.
```

2024-11-15 11:34 UTC, margaretkennedy commented on plugins/ui/docs/components/inline_alert.md
> +        ui.inline_alert(
should this be the same as above? not sure what notice vs negative should do here

2024-11-15 17:47 UTC, AkshatJawne commented on plugins/ui/docs/components/inline_alert.md
> +        ui.inline_alert(
<img width="634" alt="Screenshot 2024-11-15 at 12 47 08 PM" src="https://github.com/user-attachments/assets/554dec5d-8403-4216-9211-4e2fb7802f51">
The notice has a yellow outline, making it slightly different.

2024-11-15 22:13 UTC, mofojed approved these changes
Thanks for adding `ui.badge` and `ui.link` as well!

2024-11-16 15:30 UTC, margaretkennedy approved these changes

2024-11-19 15:36 UTC, dsmmcken requested changes
Heading is required to be styled correctly, should this have the same structure as contextual help?

2024-11-20 14:58 UTC, margaretkennedy approved these changes

2024-11-20 15:22 UTC, mofojed requested changes

2024-11-20 15:22 UTC, mofojed commented on plugins/ui/docs/components/inline_alert.md
> +For the contextual help component, both the `heading` and `content` props are required.
```suggestion
For the inline alert component, both the `heading` and `content` props are required. 
```

2024-11-21 17:02 UTC, dsmmcken approved these changes

2024-11-21 17:24 UTC, margaretkennedy approved these changes

2024-11-22 17:19 UTC, merged