docs: Add docs for use_callback, hooks overview page
deephaven/deephaven-plugins pull request #1012
Opened 2024-11-12 14:14 UTC by mofojed

- Added a Hooks overview page detailing some of the rules about hooks, and linking to some of the hooks
- Also add the `use_callback` docs page
- Closes #808

2024-11-12 15:11 UTC, dsmmcken requested changes

2024-11-12 15:59 UTC, mofojed commented on plugins/ui/docs/hooks/README.md
> +- [`use_cell_data`](use_cell_data.md) lets you use the cell data of one cell.
Created tickets #1014, #1015, #1016 and added to this PR

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +_State_ lets a component remember some data between renders. State is a way to preserve data between renders and to trigger a re-render when the data changes. For example, a counter component might u
```suggestion
_State_ lets a component remember some data between renders and trigger a re-render when the data changes. For example, a counter component might use state to keep track of the current count.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +_State_ lets a component remember some data between renders. State is a way to preserve data between renders and to trigger a re-render when the data changes. For example, a counter component might u
feels a little redundant?

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +To add state to a component, use the [`use_state`](use_state.md) hook.
```suggestion
The [`use_state`](use_state.md) hook adds state to a component. 
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +_Refs_ provide a way to hold a value that isn't used for re-rendering. Unlike with state, updating a ref does not re-render your component.
```suggestion
A _ref_ provides a way to hold a value that isn't used for re-rendering. Unlike with state, updating a ref does not re-render your component.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +_Effects_ let you perform side effects in your components. Data fetching, setting up a subscription, and manually synchronizing with an external system are all examples of side effects.
```suggestion
An _effect_ hook lets you perform side effects in your components; for example, data fetching, setting up a subscription, and manually synchronizing with an external system.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +- [`use_column_data`](use_column_data.md) lets you use the column data of one column.
```suggestion
- [`use_column_data`](use_column_data.md) lets you use the data of one column.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/README.md
> +- [`use_cell_data`](use_cell_data.md) lets you use the cell data of one cell.
```suggestion
- [`use_cell_data`](use_cell_data.md) lets you use the data of one cell.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_callback.md
> +In the example above, the `create_server` callback is memoized using `use_callback`. The `connect` function is then passed to [`use_effect`](./use_effect.md) with `create_server` as a dependency. Thi
```suggestion
In the example above, `use_callback` memoizes the `create_server` callback. The `connect` function is then passed to [`use_effect`](./use_effect.md) with `create_server` as a dependency. This ensures the effect will not be triggered on every re-render because the `create_server` callback is memoized.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_callback.md
> +1. **Use memoization when callbacks passed into expensive effects**: If the callback is being passed into an expensive `use_effect` or `use_memo` call, `use_callback` so that it maintains referential
```suggestion
1. **Use memoization when callbacks are passed into expensive effects**: If the callback is being passed into an expensive `use_effect` or `use_memo` call, use `use_callback` so that it maintains referential equality.
```

or 
```suggestion
1. **Use memoization when callbacks are passed into expensive effects**: If the callback is being passed into an expensive `use_effect` or `use_memo` call, `use_callback` will maintain referential equality.
```

2024-11-12 16:10 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_callback.md
> +2. **Use dependencies**: Pass in only the dependencies that the memoized callback relies on. If any of the dependencies change, the memoized callback will be re-computed.
The recommendations are always under the first example, which is the case here.

2024-11-12 16:12 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_cell_data.md
> +`use_cell_data` lets you use the cell data of the first cell in a table. This is useful when you want to listen to an updating table and use the data in your component.
I'm not sure if it's worth mentioning that you can tell it what cell to listen to—always the top-left cell—but you can dictate what the first cell is.

2024-11-12 16:16 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_cell_data.md
> +2. **Use table operations to filter to one cell**: If your table has multiple rows and columns, use table operations such as `.where` and `.select` to filter to the cell you want to listen to. `use_c
```suggestion
2. **Use table operations to filter to one cell**: Because `use_cell_data` always uses the top-left cell of the table, you can filter your table to determine what cell to listen to. If your table has multiple rows and columns, use table operations such as `.where` and `.select` to filter to the desired cell.
```

2024-11-12 16:16 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_column_data.md
> +`use_column_data` lets you use the column data of a table. This is useful when you want to listen to an updating table and use the data in your component.
mention always uses the first column of data?

2024-11-12 16:16 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_ref.md
> +Here's an example of a stopwatch using `use_ref`. Press the Start button to start the stopwatch, and the Stop button to stop it. The elapsed time will be displayed in the text field:
```suggestion
Here's an example of a stopwatch using `use_ref`. Press the **Start** button to start the stopwatch and the **Stop** button to stop it. The elapsed time will be displayed in the text field:
```

2024-11-12 18:53 UTC, mofojed commented on plugins/ui/docs/sidebar.json
> +            "path": "hooks/README.md"
My intent was that it would show up as the base page when going to https://github.com/deephaven/deephaven-plugins/tree/main/plugins/ui/docs/hooks in GitHub. Is it bad practice to name it README? What are the consequences?

2024-11-12 18:54 UTC, mofojed commented on plugins/ui/docs/hooks/README.md
> +_Hooks_ let you use state and other deephaven.ui features in your components. They are a way to reuse stateful logic between components. Hooks are functions that let you "hook into" state and lifecyc
Yes that all applies. I'll re-word.

2024-11-12 21:28 UTC, dsmmcken commented on plugins/ui/docs/sidebar.json
> +            "path": "hooks/README.md"
or the url would be docs/hooks/readme

2024-11-12 23:15 UTC, margaretkennedy approved these changes

2024-11-13 00:38 UTC, mofojed commented on plugins/ui/docs/sidebar.json
> +            "path": "hooks/README.md"
Eh docs/hooks or docs/hooks/overview would be better URLs. How expensive is it to do second check/could we cache that?

2024-11-14 15:06 UTC, dsmmcken commented on plugins/ui/docs/sidebar.json
> +            "path": "hooks/README.md"
probably 150ms worst case, which is actually quite a lot of page load time.

2024-11-19 14:14 UTC, mofojed commented on plugins/ui/docs/sidebar.json
> +            "path": "hooks/README.md"
@dsmmcken renamed

2024-11-19 14:33 UTC, dsmmcken approved these changes

2024-11-19 14:59 UTC, merged