fix: missing sidebar docs
deephaven/deephaven-plugins pull request #1018
Opened 2024-11-14 03:45 UTC by ethanalvizo

Closes #1005

2024-11-14 03:48 UTC, ethanalvizo commented on plugins/ui/docs/sidebar.json
> +            "label": "table",
The label for Table started with an uppercase. Not sure if this was intentional?

2024-11-14 15:02 UTC, dsmmcken commented on plugins/ui/docs/sidebar.json
> +            "label": "table",
no, thanks for fixing

2024-11-14 15:03 UTC, dsmmcken requested changes

2024-11-14 15:03 UTC, dsmmcken commented on plugins/ui/docs/sidebar.json
> +          {
line above this looks like a missing open/close bracket pair

2024-11-15 05:09 UTC, dsmmcken approved these changes

2024-11-18 14:44 UTC, merged