feat: ui.avatar
deephaven/deephaven-plugins pull request #1027
Opened 2024-11-19 16:56 UTC by AkshatJawne

Closes #940 and Closes #875

2024-11-19 17:13 UTC, margaretkennedy commented on plugins/ui/docs/components/avatar.md
> +The `is_disabled` prop disables avatars to prevent user interaction, and gives it a silenced style.
```suggestion
The `is_disabled` prop disables avatars to prevent user interaction and gives them a silenced style.
```

2024-11-20 15:08 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +    "avatar-sie-100",
```suggestion
    "avatar-size-100",
```

2024-11-20 15:09 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +    "avatar-size-600",
```suggestion
    "avatar-size-700",
```

2024-11-20 15:09 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +    "avatar-size-50",
You skipped 75
```suggestion
    "avatar-size-50",
    "avatar-size-75",
```

2024-11-20 15:17 UTC, mofojed commented on plugins/ui/docs/components/avatar.md
> +my_avatar_sizing_examples = ui_avatar_sizing_examples()
Side note, for both this and `ui.image`, we may also want to include an example for loading a local image, which would require sending it as base64 encoded... though we don't really have a "local" image with the user that could be used... but we could download one first to show that, and then reading from that locally saved file. @dsmmcken think there's any value in adding examples like this?:

```python
import urllib.request
from deephaven import ui

# Download the file from `url`, save it in a temporary directory and get the
# path to it (e.g. '/tmp/tmpb48zma.txt') in the `file_name` variable:
url = 'https://github.com/deephaven.png'
file_name, headers = urllib.request.urlretrieve(url)

# Read the file from it's temporary file location
with open(file_name, 'rb') as f:
    file_content = f.read()

b64_avatar = ui.avatar(f"data:image/png;base64,{base64.b64encode(file_content).decode()}", size=300)
```

2024-11-20 15:40 UTC, dsmmcken commented on plugins/ui/docs/components/avatar.md
> +my_avatar_basic = ui.avatar(src="https://i.imgur.com/kJOwAdv.png", alt="default avatar")
yes, use the github avatar please.

2024-11-20 15:53 UTC, dsmmcken commented on plugins/ui/docs/components/avatar.md
> +my_avatar_sizing_examples = ui_avatar_sizing_examples()
What I really want is to be able to just serve anything from the mounted volume.

`/data/my-image.png`

2024-11-25 19:22 UTC, mofojed requested changes

2024-11-25 19:22 UTC, mofojed commented on plugins/ui/docs/components/avatar.md
> +
This example as-is is half-baked. I think we should just remove it for now, and there's a follow-up ticket for loading local images: https://github.com/deephaven/deephaven-plugins/issues/1040
We can point to the base64 workaround if someone is asking for this, but the example as-is is half-baked and should just be removed:
- Incorrect grammar in the introductory paragraph ("examples shows to download")
- Called "Local image" but we're fetching an image remotely.
- As Don mentioned, he'd like to just do `ui.avatar(src="/path/to/image.png")`, while this is a workaround for doing something like that.

2024-11-26 21:55 UTC, AkshatJawne commented on plugins/ui/docs/components/avatar.md
> +
I have removed the example, I can create a follow-up ticket to add an example for the local image (once a PR #1040 merges)

2024-11-27 16:00 UTC, mofojed approved these changes

2024-11-27 20:53 UTC, margaretkennedy approved these changes

2024-11-29 18:19 UTC, dsmmcken approved these changes

2024-11-29 18:19 UTC, dsmmcken approved these changes

2024-11-29 18:24 UTC, merged