feat: ui.labeled_value
deephaven/deephaven-plugins pull request #1029
Opened 2024-11-20 15:29 UTC by AkshatJawne

Closes #938 and Closes #869

**Additional Notes:**
- After conversation with @mofojed yesterday, I will be creating separate PR to implement the ability to pass in dates and have date formatting (given that it will require a fair share of logic)
- Have put up this PR in the interim so that docs and the other functionality can be reviewed

2024-11-21 14:40 UTC, mofojed requested changes
Add an e2e test as well

2024-11-22 17:51 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/labeled_value.py
> +    # format_options: TODO Add date formatting options
I was planning to have a follow-up ticket for it, I can add the number format options right now.

2024-11-25 19:27 UTC, mofojed commented on plugins/ui/docs/components/labeled_value.md
> +
Subsection for Numbers showing how to use formatting.
Also looks like they allow for a `start`/`end` `RangeValue` to be passed in, which we don't seem to be supporting but would be a nice feature to have.

2024-11-27 16:01 UTC, mofojed submitted a review, later dismissed

2024-11-27 20:55 UTC, margaretkennedy commented on plugins/ui/docs/components/labeled_value.md
> +A Labeled Value displays a non-editable value with a label.
```suggestion
A labeled value displays a non-editable value with a label. 
```

2024-11-27 20:55 UTC, margaretkennedy commented on plugins/ui/docs/components/labeled_value.md
> +By default, the position of a labeled value's label is above the labeled value, but it can be changed to the side using the `label_position` prop.
```suggestion
By default, the label is positioned above the labeled value, but it can be changed to the side using the `label_position` prop. 
```

2024-11-27 20:55 UTC, margaretkennedy commented on plugins/ui/docs/components/labeled_value.md
> +Using the `contextual_help` prop, a `ui.contextual_help` can be placed next to the labeled value to provide additional information about the labeled value.
```suggestion
Using the `contextual_help` prop, a `ui.contextual_help` can be placed next to the labeled value to provide additional information.
```

2024-11-29 18:01 UTC, mofojed approved these changes

2024-11-29 18:40 UTC, dsmmcken submitted a review, later dismissed

2024-11-29 19:05 UTC, mofojed requested changes

2024-11-29 19:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/labeled_value.py
> +from ..types import Date
Import doesn't seem to be used yet, can remove.
```suggestion
```

2024-12-04 16:25 UTC, dsmmcken approved these changes

2024-12-04 19:05 UTC, margaretkennedy submitted a review, later dismissed

2024-12-06 15:36 UTC, mofojed requested changes
I think just merge in the latest main, should have those snapshots updated already.

2024-12-06 15:36 UTC, mofojed commented on tests/express.spec.ts-snapshots/Histogram-loads-1-webkit-linux.png
Not sure why this snapshot updated. ...

2025-01-22 21:41 UTC, mofojed approved these changes

2025-01-23 15:06 UTC, margaretkennedy commented on plugins/ui/docs/components/labeled_value.md
> +By default, the label is positioned above the labeled value, but it can be changed to the side using the `label_position` prop.
```suggestion
By default, the label is positioned above the labeled value, but it can be moved to the side using the `label_position` prop. 
```

2025-01-23 16:26 UTC, margaretkennedy approved these changes

2025-01-23 16:44 UTC, merged