docs: use_render_queue, use_liveness_scope, use_table_listener docs
deephaven/deephaven-plugins pull request #1044
Opened 2024-11-26 20:43 UTC by mofojed

- Adding some more missing hooks documentation
- Closes #823, closes #659

2024-11-26 20:45 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
> +        [table, description, do_replay] + list(dependencies),
@jnumainville I removed `listener` from the dependencies, as per the docstring we're using the `dependencies` passed in as the deps are already passed in for an argument; otherwise you also need to call `ui.use_callback` for the callback being passed in (and pass the same deps into that) or else this re-fires on every render.

2024-11-27 15:15 UTC, margaretkennedy submitted a review, later dismissed

2024-12-05 15:55 UTC, jnumainville requested changes

2024-12-05 15:55 UTC, jnumainville commented on plugins/ui/docs/hooks/use_row_data.md
> +`use_row_data` lets you use the data of the first row of a table. This is useful when you want to listen to an updating table and use the data in your component.
It's not entirely clear what the format of a row of data is here by just looking at the document. Perhaps a contrast with `use_row_list` as someone would likely be trying to figure out which they want of those two.

2024-12-05 15:55 UTC, jnumainville commented on plugins/ui/docs/hooks/use_render_queue.md
> +Now when we run this example and press the button, we'll see only one toast with the updated values of `a` and `b`, and they will always be the same value when the component re-renders (since the upd
I noticed a few usages of "we" - I think that's something we want to avoid per docs guidelines

2024-12-05 16:12 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_render_queue.md
> +Now when we run this example and press the button, we'll see only one toast with the updated values of `a` and `b`, and they will always be the same value when the component re-renders (since the upd
Yes!

2024-12-05 16:14 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_render_queue.md
> +When running the above example, we'll see _two_ toasts with each press of the button: a red one where `a != b` (as `a` gets updated first), then a neutral one where `a == b` (as `b` gets updated seco
```suggestion
When running the above example,  _two_ toasts appear with each button press: a red one where `a != b` (as `a` gets updated first), then a neutral one where `a == b` (as `b` gets updated second). Use the `use_render_queue` hook to ensure the updates are always batched together when working with a background thread:
```

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +`use_liveness_scope` allows your to interact with the [liveness scope](https://deephaven.io/core/docs/conceptual/liveness-scope-concept/) for a component. Some functions which interact with a compone
```suggestion
`use_liveness_scope` allows you to interact with the [liveness scope](https://deephaven.io/core/docs/conceptual/liveness-scope-concept/) to manage live objects within a component. Some functions that interact with a component will create live objects that need to be managed by the component to ensure they are kept active.
```

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +`use_liveness_scope` allows your to interact with the [liveness scope](https://deephaven.io/core/docs/conceptual/liveness-scope-concept/) for a component. Some functions which interact with a compone
Not 100% sure of accuracy, but the sentence needed help.

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +The primary use case for this is when creating tables outside the component's own function, and passing them as state for the component's next update. If the table is not kept alive by the component,
```suggestion
The primary use case is when creating tables outside the component's own function, and passing them as state for the component's next update. If the table is not kept alive by the component, it will be garbage collected and the component will not be able to update with the new data.
```

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +1. **Avoid using `use_liveness_scope` unless necessary**: This is an advanced feature that should only be used when you need to manage the liveness of objects outside of the component's own function.
```suggestion
1. **Avoid using `use_liveness_scope` unless necessary**: This is an advanced feature that should only be used when you need to manage the liveness of objects outside of the component's own function. Instead, derive a live component based on state rather than setting a live component within state.
```

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_render_queue.md
> +The above example listens to table updates and displays a toast message when the table updates. The `toast` function must be triggered on the render thread, whereas the listener is not fired on the r
It would useful to define toast or link to its docs - comes out of nowhere.

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_render_queue.md
> +## Batching updates
```suggestion
## Batch updates
```

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_table_listener.md
> +1. **Use table data hooks instead when possible**: `use_table_listener` is an advanced feature, requiring understanding of how the [table listeners](https://deephaven.io/core/docs/how-to-guides/table
```suggestion
1. **Use table data hooks instead when possible**: `use_table_listener` is an advanced feature requiring an understanding of how [table listeners](https://deephaven.io/core/docs/how-to-guides/table-listeners-python/) work and limitations of running code while the Update Graph is running. Most usages of this are more appropriate to implement with [the table data hooks](./overview.md#data-hooks).
```

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_table_listener.md
> +`use_table_listener` lets you listen to a table for updates. This is useful when you want to listen to a table and perform an action when the table updates.
The "this is an advanced feature" caveat should be mentioned in the paragraph, IMO. Stop someone in their tracks before getting to UI recommendations.

2024-12-10 19:44 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_table_listener.md
> +Here's an example that listens to table updates and will display a toast message when the table updates. This is a simple example to demonstrate how to use `use_table_listener` to listen to table upd
```suggestion
Here is a simple example that listens to table updates and displays a toast message when the table updates. Note you must use a [render queue](./use_render_queue.md) to trigger the toast, as the listener is not fired on the render thread.
```

2024-12-12 14:41 UTC, mofojed commented on plugins/ui/docs/hooks/use_row_data.md
> +`use_row_data` lets you use the data of the first row of a table. This is useful when you want to listen to an updating table and use the data in your component.
I'll specify one returns a dictionary and the other returns a list in the intro paragraph.

2024-12-16 14:47 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_row_data.md
> +2. **Use table operations to filter to one row**: If your table has multiple rows and columns, use table operations such as `.where`, `.select` and `.reverse` to filter to the row you want to listen
Linking on method names would be consistent with the community docs

2024-12-16 14:47 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_table_listener.md
> +`use_table_listener` lets you listen to a table for raw updates. This is an advanced feature requiring an understanding of how [table listeners](https://deephaven.io/core/docs/how-to-guides/table-lis
```suggestion
`use_table_listener` lets you listen to a table for raw updates. This is an advanced feature requiring an understanding of how [table listeners](https://deephaven.io/core/docs/how-to-guides/table-listeners-python/) work and the limitations of running code while the Update Graph is running. Most usages of this are more appropriate to implement with [table data hooks](./overview.md#data-hooks). This is useful when you want to listen to the raw updates from a table and perform a custom action when the table updates.
```

2024-12-16 14:47 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_table_listener.md
> +1. **Use table data hooks instead when possible**: `use_table_listener` is an advanced feature requiring an understanding of how [table listeners](https://deephaven.io/core/docs/how-to-guides/table-l
```suggestion
1. **Use table data hooks instead when possible**: `use_table_listener` is an advanced feature requiring an understanding of how [table listeners](https://deephaven.io/core/docs/how-to-guides/table-listeners-python/) work and limitations of running code while the Update Graph is running. Most usages of this are more appropriate to implement with [table data hooks](./overview.md#data-hooks).
```

2024-12-16 14:47 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_table_listener.md
> +1. **Use table data hooks instead when possible**: `use_table_listener` is an advanced feature requiring an understanding of how [table listeners](https://deephaven.io/core/docs/how-to-guides/table-l
Do we need this note repeated? In the intro seems fine?

2024-12-16 21:43 UTC, mofojed commented on plugins/ui/docs/hooks/use_row_data.md
> +2. **Use table operations to filter to one row**: If your table has multiple rows and columns, use table operations such as `.where`, `.select` and `.reverse` to filter to the row you want to listen
@dsmmcken how should I link to a function like `.where` from community docs?

2024-12-17 16:10 UTC, jjbrosnan commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +`use_liveness_scope` allows you to interact with the [liveness scope](https://deephaven.io/core/docs/conceptual/liveness-scope-concept/) to manage live objects within a component. Some functions that
I've reviewed other PRs that use the absolute linking syntax as if linking from enterprise to core:

```
/core/docs/conceptual/liveness-scope-concept/
```

This is better for now because the link will actually work, but it's also something that might have to change once Salmon is live.

2024-12-17 16:11 UTC, jjbrosnan commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +The primary use case is when creating tables outside the component's own function, and passing them as state for the component's next update. If the table is not kept alive by the component, it will
```suggestion
The primary use case is to create tables outside the component's own function, and pass them as state for the component's next update. If the table is not kept alive by the component, it will be garbage collected and the component will not be able to update with the new data.
```

2024-12-17 16:22 UTC, jjbrosnan commented on plugins/ui/docs/hooks/use_liveness_scope.md
> +## Refactoring to avoid liveness scope
No `ing` in headings.

2024-12-17 16:29 UTC, jjbrosnan commented on plugins/ui/docs/hooks/use_render_queue.md
> +The above example listens to table updates and displays a toast message when the table updates. The [`toast` function](../components/toast.md) must be triggered on the render thread, whereas the list
I prefer when explanation is before an example, as without the explanation above I get confused first and have to have that confusion alleviated by the text afterwards.

2024-12-17 16:33 UTC, jjbrosnan commented on plugins/ui/docs/hooks/use_render_queue.md
> +`use_render_queue` lets you use the render queue in your component. This is useful when you want to queue updates on the render thread from a background thread.
I don't know what a render queue is. I'm assuming there's an analogue in react?

2024-12-17 16:40 UTC, jjbrosnan reviewed
Two overarching comments:

- Link to other docs (`use_state`, `toast`, etc.) every time you mention a method in backticks. 
- Some images or GIFs would be greatly beneficial to these docs, so I could actually see what happens without having to start up a server myself to run code.

2024-12-18 19:25 UTC, mofojed commented on plugins/ui/docs/hooks/use_render_queue.md
> +`use_render_queue` lets you use the render queue in your component. This is useful when you want to queue updates on the render thread from a background thread.
Not really. React is in JS which is single-threaded, so it is irrelevant. I'll add a bit more of a description here of what the render queue is.

2024-12-18 20:56 UTC, jnumainville approved these changes

2024-12-19 01:22 UTC, margaretkennedy submitted a review, later dismissed

2024-12-19 15:28 UTC, mofojed commented
@jnumainville I noticed the docs failing when I try to autodoc the `use_render_queue` method. Seems like it doesn't like methods that don't have parameters. Filed a ticket: https://deephaven.atlassian.net/browse/DH-18247

2025-01-03 21:59 UTC, margaretkennedy approved these changes

2025-01-08 21:13 UTC, merged