feat: ui.divider
deephaven/deephaven-plugins pull request #1047
Opened 2024-11-27 18:26 UTC by AkshatJawne

Closes #1038 and Closes #877

Need to clarify:
- Currently, I have noted that if we set the orientation to vertical, we should set a height. 

--> From my testing, Spectrum does not have any height specified, so it doesn't render when I set the orientation to vertical.  I have it defaulting to a height of 20 right now, but if wanted (not sure given the potential usage of this component), we could add logic on the JS side to handle the height.

2024-11-27 19:00 UTC, mofojed requested changes

2024-11-27 19:00 UTC, mofojed commented on plugins/ui/docs/components/divider.md
> +my_checkbox_group_orientation_example = ui_divider_orientation_example()
Need to include a flex row so that this orientation makes sense, also set `flex_grow=0` so it doesn't grow to fill the panel:
```suggestionfrom deephaven import ui


@ui.component
def ui_divider_orientation_example():
    return ui.flex(
        "Content before",
        ui.divider(orientation="vertical"),
        "Content after",
        flex_grow=0
    )


my_checkbox_group_orientation_example = ui_divider_orientation_example()
```

2024-11-27 19:00 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/divider.py
> +    height: DimensionValue | None = 20,
We should not set a default height
```suggestion
    height: DimensionValue | None = None,
```

2024-11-27 19:00 UTC, mofojed commented on tests/app.d/ui_render_all.py
> +        ui.divider(),
Put this in a flex instead, e.g.
```
ui.flex("Content before", ui.divider(orientation="vertical"), "Content after")
```

2024-11-29 18:30 UTC, mofojed submitted a review, later dismissed

2024-11-29 18:48 UTC, dsmmcken commented
make docs is failing

2024-12-02 14:57 UTC, margaretkennedy commented on plugins/ui/docs/components/divider.md
> +The thickness (height of the divider) can be set through the `size`.s
```suggestion
The thickness (height of the divider) can be set through the `size` property.
```

2024-12-02 14:57 UTC, margaretkennedy commented on plugins/ui/docs/components/divider.md
> +The thickness (height of the divider) can be set through the `size`.s
?

2024-12-02 15:10 UTC, margaretkennedy submitted a review, later dismissed

2025-01-17 01:39 UTC, mofojed approved these changes
Great work! Thanks for picking this up!

2025-01-17 15:43 UTC, merged