DH-18089: Menu and MenuTrigger Docs
deephaven/deephaven-plugins pull request #1051
Opened 2024-12-02 15:36 UTC by dgodinez-dh

Jira ticket: https://deephaven.atlassian.net/browse/DH-18089

2024-12-09 19:54 UTC, mofojed requested changes

2024-12-09 19:54 UTC, mofojed commented on plugins/ui/docs/components/menu.md
> +Menu supports multiple selection modes. By default, selection is disabled, however this can be changed using the `selection_mode` prop. Use `default_selected_keys` to provide a default set of selecte
Changing and to or - since you can only set one or the other.
```suggestion
Menu supports multiple selection modes. By default, selection is disabled, however this can be changed using the `selection_mode` prop. Use `default_selected_keys` to provide a default set of selected items (uncontrolled) or `selected_keys` to set the selected items (controlled). The value of the selected keys must match the key prop of the items.
```

2024-12-09 19:54 UTC, mofojed commented on plugins/ui/docs/components/menu.md
> +
Would be cool to show use with a ticking table as well.

2024-12-09 19:54 UTC, mofojed commented on plugins/ui/docs/components/menu_trigger.md
> +`menu_trigger` accepts an `on_open_chnage` handler which is triggered whenever the `menu` is opened or closed.
```suggestion
`menu_trigger` accepts an `on_open_change` handler which is triggered whenever the `menu` is opened or closed.
```

2024-12-09 20:47 UTC, dgodinez-dh commented on plugins/ui/docs/components/menu.md
> +
Would we really want to use a ticking table as item source for a menu? I suppose it would work, but I dislike the idea of menu items appearing / disappearing as the table ticks. Also, what would happen if the menu was open while the table ticked? Does it update, or is the menu now out of date?

2024-12-09 21:06 UTC, mofojed commented on plugins/ui/docs/components/menu.md
> +
Guess we should clarify the behaviour with @dsmmcken , but I see a few possible options when the table ticks while the menu is open (ordered by my preference):
1. Update the menu in place. Seems this is what Spectrum will do by default: https://codesandbox.io/p/sandbox/react-spectrum-playground-forked-rfctrs
2. Dismiss the menu. They need to re-open the menu.
3. Freeze the items in the menu while it's open. Could mean some actions are out of date and will error when selected.

We definitely need to decide on what to do with a ticking table... and if you're hooking up a ticking table to a menu, I imagine having it update in place is acceptable.

2024-12-30 16:32 UTC, dgodinez-dh commented on plugins/ui/docs/components/menu.md
> +
Spun this off into another ticket:
https://deephaven.atlassian.net/browse/DH-18305
Going to remove this section from the doc for now.

2024-12-30 16:33 UTC, closed without merging