docs: deephaven.ui dashboard crash course
deephaven/deephaven-plugins pull request #1057
Opened 2024-12-06 18:00 UTC by jnumainville

Continued from https://github.com/deephaven/deephaven.io/pull/4567

Contains a deephaven.ui crash course

Idea is to progressively build an iris dashboard, creating a panel with some basic components, then move to a dashboard with several panels and more components, than add a custom panel with a picker and ui.use_state for a bit of interactivity. If someone just cares about putting some components together they could easily skip the last section, but I think it's important to include at least a basic example as that's where the power of deephaven.ui is.

2024-12-06 18:02 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +  species, set_species = ui.use_state()
Unresolved comment from @mofojed for further discussion

https://github.com/deephaven/deephaven.io/pull/4567#discussion_r1873516746

2024-12-09 20:08 UTC, dsmmcken requested changes

2024-12-09 20:08 UTC, dsmmcken commented on plugins/ui/docs/describing/deephaven-ui.md
> +Wrap your chart and `ui.table` in a `ui.flex` component. `ui.flex` enables responsive layouts that adjust as you resize panels.
explain what a flex is, that is is an implementation of a flexbox [mdn link] and that it is one way to lay things out within a panel.

2024-12-09 20:08 UTC, dsmmcken commented on plugins/ui/docs/describing/deephaven-ui.md
> +
I think we need more introduction of the plan, and the parts. What is a dashboard, what is a panel. The idea that we will iterate and create all our panels, then arrange them in a dashboard.

2024-12-09 20:08 UTC, dsmmcken commented on plugins/ui/docs/describing/deephaven-ui.md
> +### `ui.use_state`
I would expect and example of showing state within a panel, and also state hoisted to the dashboard level that controls things across multiple panels.

2024-12-09 20:08 UTC, dsmmcken commented on plugins/ui/docs/describing/deephaven-ui.md
> +### Stack
there's no stacks in the final example

2024-12-09 20:08 UTC, dsmmcken commented on plugins/ui/docs/describing/deephaven-ui.md
> +### Row
I would expect at least one example of manually setting a row or columns width or height.

2024-12-09 20:08 UTC, dsmmcken commented on plugins/ui/docs/describing/deephaven-ui.md
> +ui_iris = ui.table(
should show off table interactivity, with a row on_double_press handler

2024-12-09 22:09 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +![img](../_assets/deephaven-ui-crash-course/iris_dashboard_species.png)
This is a more general comment, but especially pertinent to this comment. 
One thing that I'm not entirely sure about is what the scope of this tutorial should be. I was under the impression that the original intended scope is really the sections of `Basic Components` and `Dashboard`. I added `Interactivity` as I think it's important, but could be skipped easily by someone only interested in the first two sections. If I start pulling in tons of different component this becomes a very tutorial from that original objective.
Maybe that's fine, but I think we still want something incredibly basic, perhaps in a different PR, of "I just want to build a super basic dashboard because I don't need tons of complex things, and maybe I'll pick up those complex things later, but really I just want to know how `deephaven.ui` works to get my feet wet."

2024-12-12 14:14 UTC, mofojed commented on plugins/ui/docs/describing/deephaven-ui.md
> +  species, set_species = ui.use_state()
It's worth showing both _somewhere_, not sure that needs to be here.

2024-12-12 22:56 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +  species, set_species = ui.use_state()
added badges with data hooks

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +This guide shows you how to build a dashboard with `deephaven.ui`. [`deephaven.ui`](https://github.com/deephaven/deephaven-plugins/tree/main/plugins/ui) is Deephaven’s Python library to create user i
I did try to contextualize a bit more, but I think I'd need more specific examples/guidance throughout to write something more creative if that's still needed

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +![img](../_assets/deephaven-ui-crash-course/iris_dashboard_species.png)
Added all suggestions

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +Wrapping a table in `ui.table` unlocks visual functionality on the table. With `iris`, create a `ui.table` that:
Done

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +Wrap your chart and `ui.table` in a `ui.flex` component. `ui.flex` enables responsive layouts that adjust as you resize panels.
Done

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +
Done

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +### `ui.use_state`
Done

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +### Stack
Done

2024-12-12 22:57 UTC, jnumainville commented on plugins/ui/docs/describing/deephaven-ui.md
> +ui_iris = ui.table(
Done

2024-12-13 14:29 UTC, mofojed reviewed
Seems good overall, couple small things I noticed that could be cleaned up/improved.

2024-12-13 14:29 UTC, mofojed commented on plugins/ui/docs/tutorial.md
> +You also need simulated data and charts from [`deephaven.plot.express`](https://pypi.org/project/deephaven-plugin-ui/). You’ll create the simulated `iris` data below.
```suggestion
You also need simulated data and charts from [`deephaven.plot.express`](https://pypi.org/project/deephaven-plugin-ui/). You’ll create the simulated [`iris` data set](https://en.wikipedia.org/wiki/Iris_flower_data_set) below. 
```

2024-12-13 14:29 UTC, mofojed commented on plugins/ui/docs/tutorial.md
> +iris_agg_stack = ui.stack(ui_iris_avg, ui_iris_max, ui_iris_min)
This block doesn't work as is. Getting an error on the `ui.stack` ..

2024-12-13 14:29 UTC, mofojed commented on plugins/ui/docs/tutorial.md
> +def summary_badges(species):
This will be a nice place to use `dx.indicator`. But I like the use of badge in the meantime.

2024-12-13 15:41 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +You also need simulated data and charts from [`deephaven.plot.express`](https://pypi.org/project/deephaven-plugin-ui/). You’ll create the simulated `iris` data below.
added

2024-12-13 15:41 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +iris_agg_stack = ui.stack(ui_iris_avg, ui_iris_max, ui_iris_min)
removed that chunk. Shouldn't have been there yet anyways

2024-12-13 15:41 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +def summary_badges(species):
Agreed!

2024-12-13 17:11 UTC, dsmmcken commented on plugins/ui/docs/sidebar.json
> +      {
Order after installation please.

2024-12-13 17:34 UTC, jnumainville commented on plugins/ui/docs/sidebar.json
> +      {
done

2024-12-16 18:52 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +This guide shows you how to build a dashboard with [`deephaven.ui`](https://github.com/deephaven/deephaven-plugins/tree/main/plugins/ui), Deephaven’s Python library to create user interfaces. You’ll
I did a big grammar edit - I made it in a new branch, but I couldn't create a PR. I didn't change anything other than bullets and sentence structure. Two additional small questions

2024-12-16 18:52 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +- Component State
TODO: for these links

2024-12-16 19:51 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +- Component State
@dsmmcken what should these links look like?

2024-12-16 19:54 UTC, jnumainville commented
Took into account the feedback from the Friday demo. Specifically I added a small section on memoization. I didn't mention the flickering explicitly because of https://github.com/deephaven/deephaven-plugins/issues/1063 but that step does fix it.

2024-12-17 21:46 UTC, mofojed requested changes
Just that one block that throws an error didn't get removed, looks good to me otherwise.

2024-12-17 21:46 UTC, mofojed commented on plugins/ui/docs/tutorial.md
> +iris_agg_stack = ui.stack(ui_iris_avg, ui_iris_max, ui_iris_min)
Still getting an error here. Chunk not removed?

2024-12-17 22:08 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +iris_agg_stack = ui.stack(ui_iris_avg, ui_iris_max, ui_iris_min)
Ooops. Absolutely, definitely removed this time.

2024-12-18 23:07 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +There is lots of empty space in the top row. Resize the height of the top row to 1 and the bottom row to 2 for a ratio of 1:2, so the bottom row is twice the height of the top row.
```suggestion
The top row contains lots of empty space. Resize the height of the top row to 1 and the bottom row to 2 for a ratio of 1:2, so the bottom row is twice the height of the top row.  
```

2024-12-18 23:07 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +Since you're investigating `SepalLength` and `SepalWidth`, create a [`dx.densityheatmap`](../../plotly-express/main/density_heatmap.md) chart that shows the density of `SepalLength` and `SepalWidth`,
```suggestion
Since this walkthrough investigates `SepalLength` and `SepalWidth`, this section shows you how to create a [`dx.densityheatmap`](../../plotly-express/main/density_heatmap.md) chart that shows the density of `SepalLength` and `SepalWidth`, with a `Species` filter.
```

2024-12-18 23:07 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +Wrap the values in [`ui.badge`](components/badge.md) components to display them. `ui.badge` components draw attention to specific values.
```suggestion
To display the values, wrap them in [`ui.badge`](components/badge.md) components, which draw attention to specific values.  
```

2024-12-18 23:07 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +`ui.use_memo` allows you to cache expensive calculations so they are only recalculated when needed. `ui.use_memo` takes a function and a list of dependencies. If the dependencies change, the function
```suggestion
`ui.use_memo` allows you to cache expensive calculations so they are only recalculated when needed. It takes a function and a list of dependencies. If the dependencies change, the function is recalculated.
```

2024-12-18 23:07 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +Heatmap is a fairly expensive chart to create, requires a filtered table in this case, and changes rarely, so pull the heatmap creation into a separate function and use `ui.use_memo` to cache the hea
```suggestion
Heatmap is a fairly expensive chart to create (it requires a filtered table in this case) and changes rarely, so pull the heatmap creation into a separate function and use `ui.use_memo` to cache the heatmap creation.
```

2024-12-18 23:07 UTC, margaretkennedy commented on plugins/ui/docs/tutorial.md
> +Finally, you’ve completed this dashboard crash course, with your custom component and interactivity.
```suggestion
You've now completed this dashboard crash course with your custom component and interactivity.
```

2024-12-19 15:15 UTC, mofojed submitted a review, later dismissed

2024-12-19 16:01 UTC, margaretkennedy submitted a review, later dismissed

2025-01-03 20:49 UTC, mofojed approved these changes

2025-01-03 20:57 UTC, dsmmcken requested changes

2025-01-03 20:57 UTC, dsmmcken commented on plugins/ui/docs/tutorial.md
> +- [`dx.densityheatmap`](../../plotly-express/main/density_heatmap.md)
these links won't work

2025-01-03 21:40 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +- [`dx.densityheatmap`](../../plotly-express/main/density_heatmap.md)
done

2025-01-09 15:43 UTC, dsmmcken requested changes

2025-01-09 15:43 UTC, dsmmcken commented on plugins/ui/docs/tutorial.md
> +- [`dx.density_heatmap`](core/plotly/docs/density_heatmap)
you need the leading slash.

/core

is not a relative path.

2025-01-09 15:43 UTC, dsmmcken commented on plugins/ui/docs/tutorial.md
> +- Custom Components
remove if not linking to anything

2025-01-13 16:14 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +- Custom Components
done

2025-01-13 16:14 UTC, jnumainville commented on plugins/ui/docs/tutorial.md
> +- [`dx.density_heatmap`](core/plotly/docs/density_heatmap)
done

2025-01-13 16:59 UTC, mofojed approved these changes

2025-01-13 20:21 UTC, dsmmcken approved these changes

2025-01-21 14:43 UTC, merged