docs: Conditional Rendering
deephaven/deephaven-plugins pull request #1060
Opened 2024-12-11 16:31 UTC by dgodinez-dh

https://deephaven.atlassian.net/browse/DOC-224

2024-12-11 17:00 UTC, dsmmcken commented
screenshots would probably look nicer in context if it was just the full panel, but no wider than 860

2024-12-12 12:26 UTC, margaretkennedy commented on plugins/ui/docs/describing/conditional_rendering.md
> +Your components will often need to display different things depending on different conditions. In `deephaven.ui`, you can conditionally render components using Python syntax like if statements, `and`
```suggestion
Your components will often need to display different things depending on different conditions. In `deephaven.ui`, you can conditionally render components using Python syntax like if statements, the `and` operator, and the ternary operator.
```

2024-12-12 12:26 UTC, margaretkennedy commented on plugins/ui/docs/describing/conditional_rendering.md
> +Some of the `item` components have their `is_packed` prop set to `True` instead of `False`. You want to add a checkmark (✅) to packed items if `is_packed=True`.
```suggestion
Some of the `item` components have their `is_packed` prop set to `True` instead of `False`. 

To add a checkmark (✅) to packed items if `is_packed=True`, you can write an if/else statement like so:
```

2024-12-12 12:26 UTC, margaretkennedy commented on plugins/ui/docs/describing/conditional_rendering.md
> +You can write this as an if/else statement like so:
```suggestion
```

2024-12-12 12:26 UTC, margaretkennedy commented on plugins/ui/docs/describing/conditional_rendering.md
> +In some situations, you do not want to render anything at all. For example, you do not want to show packed items at all. A component must return something. In this case, you can return `None`:
```suggestion
In some situations, you do not want to render anything at all. For example, you do not want to show any packed items. A component must return something. In this case, you can return `None`:
```

2024-12-12 12:26 UTC, margaretkennedy commented on plugins/ui/docs/describing/conditional_rendering.md
> +In practice, returning `None` from a component is not common because it might surprise a developer trying to render it. More often, you would conditionally include or exclude the component in the par
```suggestion
In practice, returning `None` from a component is not common because it might surprise a developer trying to render it. More often, you would conditionally include or exclude the component in the parent component. The next section explains how to do that.
```

2024-12-12 12:26 UTC, margaretkennedy commented on plugins/ui/docs/describing/conditional_rendering.md
> +Another common shortcut you will encounter is the Python logical `and` operator. Inside `deephaven.ui` components, it often comes up when you want to render a component when the condition is `True`,
```suggestion
Another common shortcut is the Python logical `and` operator. Inside `deephaven.ui` components, it often comes up when you want to render a component when the condition is `True`, or render nothing otherwise. With `and`, you could conditionally render the checkmark only if `is_packed` is `True`:
```

2024-12-12 14:27 UTC, mofojed requested changes

2024-12-12 14:27 UTC, mofojed commented on plugins/ui/docs/describing/conditional_rendering.md
> +Notice you are creating branching logic with Python's if and return statements. In `deephaven.ui`, control flow (like conditions) is handled by Python.
```suggestion
Notice you are creating branching logic with Python's `if` and `return` statements. In `deephaven.ui`, control flow (like conditions) is handled by Python.
```

2024-12-12 14:27 UTC, mofojed commented on plugins/ui/docs/describing/conditional_rendering.md
> +If `is_packed` is True, the component will return nothing. Otherwise, it will return a component to render.
```suggestion
If `is_packed` is `True`, the component will return nothing. Otherwise, it will return a component to render.
```

2024-12-12 14:27 UTC, mofojed commented on plugins/ui/docs/describing/conditional_rendering.md
> +In the previous example, you controlled which component would be returned by using an if/else statement. This led to some code duplication. You can remove this duplication by conditionally including
```suggestion
In the previous example, you controlled which component would be returned by using an [`if`/`else` statement](https://docs.python.org/3/tutorial/controlflow.html#if-statements). This led to some code duplication. You can remove this duplication by conditionally including components.
```

2024-12-12 14:27 UTC, mofojed commented on plugins/ui/docs/describing/conditional_rendering.md
> +Python has a ternary conditional in the form: `a if condition else b`. This can simplify the `item` component.
```suggestion
Python has a [ternary conditional](https://docs.python.org/3/reference/expressions.html#conditional-expressions) in the form: `a if condition else b`. This can simplify the `item` component.
```

2024-12-12 14:27 UTC, mofojed commented on plugins/ui/docs/describing/conditional_rendering.md
> +Another common shortcut is the Python logical `and` operator. Inside `deephaven.ui` components, it often comes up when you want to render a component when the condition is `True`, or render nothing o
```suggestion
Another common shortcut is the Python [logical `and` operator](https://docs.python.org/3/reference/expressions.html#and). Inside `deephaven.ui` components, it often comes up when you want to render a component when the condition is `True`, or render nothing otherwise. With `and`, you could conditionally render the checkmark only if `is_packed` is `True`:
```

2024-12-12 14:27 UTC, mofojed commented on plugins/ui/docs/describing/conditional_rendering.md
> +When the shortcuts get in the way of writing plain code, try using an if statement and a variable. You can reassign variables, so start by providing the default content you want to display. Use an if
```suggestion
When the shortcuts get in the way of writing plain code, try using an `if` statement and a variable. You can reassign variables, so start by providing the default content you want to display. Use an `if` statement to reassign an expression to `item_content` if `is_packed` is `True`.
```

2024-12-13 14:30 UTC, mofojed approved these changes

2024-12-13 15:50 UTC, merged