docs: Pure Components
deephaven/deephaven-plugins pull request #1064
Opened 2024-12-16 15:21 UTC by dgodinez-dh

https://deephaven.atlassian.net/browse/DOC-237

2024-12-16 16:17 UTC, mofojed requested changes
Yea I guess this is still valuable information. Interesting this section on the React docs site don't mention anything about memoization or the `PureComponent` class.

2024-12-16 16:17 UTC, mofojed commented on plugins/ui/docs/describing/pure_components.md
> +If the `cups` variable was outside the TeaGathering function, this would be a problem. You would be changing a preexisting object by appending items to that list.
```suggestion
If the `cups` variable was outside the `tea_set` function, this would be a problem. You would be changing a preexisting object by appending items to that list.
```

2024-12-16 16:17 UTC, mofojed commented on plugins/ui/docs/describing/pure_components.md
> +        print("button pressed")
In the opening paragraph of this section, you say "update the screen, start an animation, or change data", then in this example you're just printing a log message. I think it would be more powerful to match the two; either include "print a message" in the opening paragraph, or change this example to update some data.

2024-12-17 13:34 UTC, dgodinez-dh commented on plugins/ui/docs/describing/pure_components.md
> +        print("button pressed")
Updated

2024-12-17 21:10 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +However, because you created them during the same render, no code outside of `tea_set` will be impacted by this. This a local mutation.
```suggestion
However, because you created them during the same render, no code outside of `tea_set` will be impacted by this. This is a local mutation.
```

2024-12-17 21:10 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +## Unintentional Side effects
```suggestion
## Unintentional side effects
```

2024-12-17 21:10 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +## Local Mutations
```suggestion
## Local mutations
```

2024-12-17 21:10 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +## Intentional Side Effects
```suggestion
## Intentional side effects
```

2024-12-17 21:10 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +While the rendering process must remain pure, at some point, something needs to change. You may need to print a message, update the screen, start an animation, or change data. These changes are calle
```suggestion
While the rendering process must remain pure, at some point, something needs to change. You may need to print a message, update the screen, start an animation, or change data. These changes are called side effects. They must happen on the side rather than during rendering.
```

2024-12-17 21:10 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +If an event handler is not the correct place for a certain side effect, you can place it in a [`use_effect`](../hooks/use_effect.md) hook. This tells `deephaven.ui` to execute it later, after renderi
```suggestion
If an event handler is not the correct place for a certain side effect, you can place it in a [`use_effect`](../hooks/use_effect.md) hook. This tells `deephaven.ui` to execute it later, after rendering, when side effects are allowed.
```

2024-12-17 21:14 UTC, dgodinez-dh commented on plugins/ui/docs/describing/pure_components.md
> +A [pure function](https://en.wikipedia.org/wiki/Pure_function) returns the same value given the same arguments and has no side effects. By writing `deephaven.ui` components as pure functions, you can
It is part of the definition that it has no side effect. If you write a function with side effects, then you have not written a pure function.

2024-12-17 21:18 UTC, margaretkennedy commented on plugins/ui/docs/describing/pure_components.md
> +A [pure function](https://en.wikipedia.org/wiki/Pure_function) returns the same value given the same arguments and has no side effects. By writing `deephaven.ui` components as pure functions, you can
I'm reading as an English person and not a programmer - you can dismiss my comment.

2024-12-18 15:36 UTC, mofojed approved these changes

2024-12-18 23:09 UTC, margaretkennedy approved these changes

2024-12-20 13:15 UTC, merged