docs: ui as a tree
deephaven/deephaven-plugins pull request #1067
Opened 2024-12-17 21:22 UTC by dgodinez-dh

https://deephaven.atlassian.net/browse/DOC-240

2024-12-18 14:14 UTC, dsmmcken commented on plugins/ui/docs/describing/your_ui_as_a_tree.md
> +# Your UI as a Tree
This is commentary on all the meta docs.

your_ui_as_a_tree should be your-ui-as-a-tree

I think you started using underscores to match the pattern of the components, but the components are literally the function names, where as these are just articles and should match the seperators used everywhere else.


Just noticed this now.

2024-12-18 15:55 UTC, mofojed requested changes
Looks good, a couple of small changes.

2024-12-18 15:55 UTC, mofojed commented on plugins/ui/docs/describing/your_ui_as_a_tree.md
> +Another relationship in a `deephaven.ui` query that can be modeled with a tree are an query's dependencies. Each node in a dependency tree is a module and each branch represents an import statement i
```suggestion
Another relationship in a `deephaven.ui` query that can be modeled with a tree are a query's dependencies. Each node in a dependency tree is a module and each branch represents an import statement in that module.
```

2024-12-18 15:55 UTC, mofojed commented on plugins/ui/docs/describing/your_ui_as_a_tree.md
> +## The dependency tree
I'm not sure this section really makes sense to include... or at least we should continue using the phrase "app" instead of "query", since we use the word "app" above.

2024-12-20 13:15 UTC, dgodinez-dh commented on plugins/ui/docs/describing/your_ui_as_a_tree.md
> +# Your UI as a Tree
Updated

2024-12-20 13:15 UTC, dgodinez-dh commented on plugins/ui/docs/describing/your_ui_as_a_tree.md
> +## The dependency tree
Removed this section.

2024-12-20 16:25 UTC, mofojed approved these changes

2024-12-20 16:47 UTC, margaretkennedy commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +`deephaven.ui`, and many other UI libraries, model UI as a tree. Thinking of your app as a tree is useful for understanding the relationship between components. This understanding will help you debug
```suggestion
`deephaven.ui`, and many other UI libraries, model UI as a tree. This approach helps clarify the relationships between components and aids in debugging issues related to performance and state management.
```

2024-12-20 16:47 UTC, margaretkennedy commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +Although render trees may differ across render passes, these trees are generally helpful for identifying what the top-level and leaf components are in a `deephaven.ui` component. Top-level components
```suggestion
Although render trees may differ across render passes, these trees are generally helpful for identifying what the top-level and leaf components are in a `deephaven.ui` component. Top-level components are those nearest to the root component and affect the rendering performance of all the components beneath them and often contain the most complexity. Leaf components are near the bottom of the tree and have no child components. They are often frequently re-rendered.
```

2024-12-20 16:47 UTC, margaretkennedy commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +Identifying these categories of components are useful for understanding data flow and performance of your component.
```suggestion
Identifying these categories of components is useful for understanding the data flow and performance of your component.
```

2024-12-20 17:27 UTC, jjbrosnan commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +`deephaven.ui`, and many other UI libraries, model UI as a tree. Thinking of your app as a tree is useful for understanding the relationship between components. This understanding will help you debug
```suggestion
`deephaven.ui`, and many other UI libraries, model a UI as a tree. Thinking of your app as a tree is useful for understanding the relationship between components. This understanding will help you debug future concepts like performance and state management.
```

2024-12-20 17:34 UTC, jjbrosnan reviewed
Not many comments

2024-12-20 17:34 UTC, jjbrosnan commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +`deephaven.ui`, and many other UI libraries, model UI as a tree. Thinking of your app as a tree is useful for understanding the relationship between components. This understanding will help you debug
I actually see that you refer to UI in the same way `and UI is often...`, so maybe this is correct. If it's not, it should be changed throughout.

2024-12-20 17:34 UTC, jjbrosnan commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +```python
Grab a screenshot or GIF of the UI with this code like with the previous one.

2024-12-20 17:36 UTC, dgodinez-dh commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +`deephaven.ui`, and many other UI libraries, model UI as a tree. Thinking of your app as a tree is useful for understanding the relationship between components. This understanding will help you debug
I think it is correct.

2024-12-20 17:43 UTC, dgodinez-dh commented on plugins/ui/docs/describing/your-ui-as-a-tree.md
> +```python
Added

2024-12-20 18:49 UTC, jjbrosnan approved these changes

2024-12-20 21:17 UTC, mofojed approved these changes

2024-12-20 21:54 UTC, margaretkennedy approved these changes

2024-12-30 14:54 UTC, dsmmcken approved these changes

2024-12-30 14:57 UTC, merged