feat: disclosure
deephaven/deephaven-plugins pull request #1068
Opened 2024-12-18 17:01 UTC by ethanalvizo

Closes #1037 

Implementation done but docs are not yet

2025-01-03 22:00 UTC, margaretkennedy approved these changes

2025-01-06 18:07 UTC, mofojed reviewed
You'll need to update `plugins/ui/src/js/package.json` to use the v102 versions of the `@deephaven/` packages that include Disclosure to fix the build errors.

2025-01-21 21:48 UTC, mofojed requested changes
Should add Disclosure to e2e tests as well. Would be cool to add your own e2e test instead of the render_all catchall.

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +            ),
Should pass `is_expanded` into this example as well to show it in the "controlled" state. https://react-spectrum.adobe.com/react-spectrum/Disclosure.html#events
```suggestion
            ),
            is_expanded=is_expanded
```

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +                True if is_expanded == False else False
In Python instead of writing something like `!is_expanded` like you would in JS, you write `not is_expanded` to toggle something. Better than what you've got now.
```suggestion
                not is_expanded
```

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +        ui.text("Expanded" if is_expanded == True else "Collapsed"),
You don't need the `== True`. Also say "Disclosure is ..." so it's a little clearer.
```suggestion
        ui.text("Disclosure is ", "expanded" if is_expanded else "collapsed"),
```

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +
I think bad copy/paste
```suggestion
```

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +my_disclosure_disabled = ui.disclosure(title="Heading", panel="Content", is_quiet=True)
Why doesn't the little arrow appear when it's collapsed? It does in Spectrum's example.
```suggestion
my_disclosure_expanded = ui.disclosure(title="Heading", panel="Content", is_quiet=True)
```

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +my_disclosure_disabled = ui.disclosure(
```suggestion
my_disclosure_expanded = ui.disclosure(
```

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +```
Add some examples using `disclosure_title` and `disclosure_panel`, showing off disclosures with different levels in the `disclosure_title`, and a `disclosure_panel` with some padding.

2025-01-21 21:48 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
> +  Disclosure,
Need to add `DisclosureTitle` and `DisclosurePanel` as well (just import from `@deephaven/components` and add them to the element map below).

2025-01-22 21:57 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +my_disclosure_disabled = ui.disclosure(title="Heading", panel="Content", is_quiet=True)
Looks like the issue is in the version of Spectrum we're using: https://github.com/adobe/react-spectrum/pull/7456
So should be fixed when we update Spectrum.

2025-01-27 06:11 UTC, ethanalvizo commented on plugins/ui/docs/components/disclosure.md
> +```
Added this code snippet as an example but investigating why they all render with the same style. When inspecting the elements they are rendering as H1, H2, H3,... respectively. Style overwriting seems to be coming from elsewhere

```
from deephaven import ui


@ui.component
def ui_disclosure_title_levels():
    return [
        ui.disclosure(
            ui.disclosure_title("H1", level=1),
            ui.disclosure_panel("Content", margin="10px"),
        ),
        ui.disclosure(
            ui.disclosure_title("H2", level=2),
            ui.disclosure_panel("Content", margin="10px"),
        ),
        ui.disclosure(
            ui.disclosure_title("H3", level=3),
            ui.disclosure_panel("Content", margin="10px"),
        ),
        ui.disclosure(
            ui.disclosure_title("H4", level=4),
            ui.disclosure_panel("Content", margin="10px"),
        ),
        ui.disclosure(
            ui.disclosure_title("H5", level=5),
            ui.disclosure_panel("Content", margin="10px"),
        ),
        ui.disclosure(
            ui.disclosure_title("H6", level=6),
            ui.disclosure_panel("Content", margin="10px"),
        ),
    ]


my_disclosure_title_levels = ui_disclosure_title_levels()
```

2025-01-27 15:30 UTC, mofojed commented on plugins/ui/docs/components/disclosure.md
> +```
Hmm it looks like that's actually an issue in React spectrum.
In which case, remove this example, don't bother mentioning `level`, create a follow up ticket that tracks a ticket I filed against React-spectrum: https://github.com/adobe/react-spectrum/issues/7671

2025-02-03 05:57 UTC, ethanalvizo commented on tests/app.d/ui_render_all.py
> +        ui.disclosure(title="Heading", panel="Content"),
When I add this do I not need to update the e2e snapshots? I ran the command locally and no snapshots were updating

2025-02-03 14:42 UTC, ericlln commented on tests/app.d/ui_render_all.py
> +        ui.disclosure(title="Heading", panel="Content"),
There might be too many components in that panel, causing yours to be in the overflow and not showing in the snapshot. Try adding it to one of the other panels.

2025-02-03 15:15 UTC, mofojed requested changes
As Eric mentioned, you'll need to add it to another panel and update the snapshots for the e2e tests. Or add it as a separate component and add a new test for it.

2025-02-05 04:22 UTC, ethanalvizo commented on tests/app.d/ui_render_all.py
> +        ui.disclosure(title="Heading", panel="Content"),
Yes this did the trick thank you!

2025-02-05 14:42 UTC, mofojed approved these changes

2025-02-06 14:17 UTC, merged