feat: delta updates
deephaven/deephaven-plugins pull request #1069
Opened 2024-12-18 17:08 UTC by wusteven815

2024-12-19 18:58 UTC, mofojed requested changes

2024-12-19 18:58 UTC, mofojed commented on plugins/ui/setup.cfg
> +    pyjsonpatch
We should pin json-rpc and pyjsonpatch. Right now if either of these libraries update with a breaking change, users with new installs may not work correctly.

```suggestion
    json-rpc>=1.15.0
    pyjsonpatch>=0.1.1
```

Docs on compatible release notation: https://peps.python.org/pep-0440/#compatible-release

2024-12-19 18:58 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +        'ticket_0' in newObj
This is a little sketchy

2024-12-19 18:58 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +          applyPatch(uiDomRef.current, patch);
Ideally what we should do is only traverse the patch itself to know which elements have changed/need updates - rather than applying the patch and diffing afterwards. I think this can be achieved by iterating through the patch and using [`applyOperation`](https://www.npmjs.com/package/fast-json-patch#function-applyoperationtdocument-t-operation-operation-validateoperation-boolean--validatort--false-mutatedocument-boolean--true-banprototypemodifications-boolean--true-index-number--0-operationresultt) instead of `applyPatch`.
I think we can _also_ look at the value in the patch, and check if it's an object/element node or whatever, and replace that value _before_ we actually call `applyOperation`.
Then in the returned result, take a look at `removed` for any objects we may need to cleanup/close.

2024-12-19 18:58 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +  const reactDomNewRef: any = useRef(null); // eslint-disable-line @typescript-eslint/no-explicit-any
We shouldn't need to use `any` here - may need to add typing to the `parseDocumentFromObject` and use that typing for these.

2024-12-19 19:54 UTC, wusteven815 commented
Here's the example I use to test around delta updates:
```python
from deephaven import ui,empty_table
from random import randint
from time import time

counter = 0
_tables = []
for i in range(10):
    _tables.append(empty_table(i).update(f"X{i}=i"))

@ui.component
def delta_test():
    global counter
    items, set_items = ui.use_state([])
    i1, seti1 = ui.use_state(0)
    i2, seti2 = ui.use_state(0)
    colour, set_colour = ui.use_state([255, 255, 255])

    def handle_add():
        global counter
        num = counter
        set_items([*items, ui.button(f"{num}", on_press=lambda: print(num)), ui.table(_tables[num], width="80px")])
        counter += 1

    def handle_swap():
        items[i1], items[i2] = items[i2], items[i1]
        set_items([*items])

    return [
        ui.flex(
            ui.button("Add", on_press=handle_add),
            ui.button("Delete", on_press=lambda: set_items([*items[:-1]])),
            ui.button("Swap", on_press=handle_swap),
            ui.text_field(value=i1, on_change=lambda x: seti1(int(x)), width="80px"),
            ui.text_field(value=i2, on_change=lambda x: seti2(int(x)), width="80px"),
            ui.button("Colour", on_press=lambda: set_colour([randint(0, 255), randint(0, 255), randint(0, 255)])),
            ui.view(width="80px", background_color=f"rgb({colour[0]}, {colour[1]}, {colour[2]})",  key="test"),
            max_height="32px"
        ),
        ui.flex(*items, direction="row", flex_grow=1),
    ]

my_delta = delta_test()
```

2024-12-20 17:50 UTC, mattrunyon requested changes
Didn't go too in depth on the logic as I assume some of this is going to change in a potentially significant way with a refactor

2024-12-20 17:50 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        document = json.loads(encoded_document)
We should see if we can do this before the node is stringified. Or is this necessary? Just don't want an unnecessary stringify -> parse -> stringify on the server

2024-12-20 17:50 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  makeWidgetEventDocumentPatched,
Idk if it's worth changing the name of this event on client/server from update to patch. Update seems fine still. Just reduces the size of the PR since there is no separate update action. Update might even be a clearer name to describe what is happening since patched could imply "fixed"

@mofojed thoughts? I know it's a bit pedantic and I'm fine leaving it as patch. Just thought I'd mention it

2024-12-20 17:50 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  const patch2: Operation[] = [{ op: 'add', path: '/FOO', value: 'BAR' }];
We should test other operations too. I'm assuming there's remove and modify/change at least

2025-02-19 20:05 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  makeWidgetEventDocumentPatched,
I don't think it should keep the same name, as the message being sent is a different format. Since the JS and Python are packaged together, we _shouldn't_ have a mismatch, but I'm still inclined to change the name to patch just to be sure we're actually using the newest format.

2025-02-19 20:30 UTC, mofojed commented
Superceded by https://github.com/deephaven/deephaven-plugins/pull/1119

2025-02-19 20:30 UTC, closed without merging