fix: Allow autodoc functions to have no parameters
deephaven/deephaven-plugins pull request #1072
Opened 2024-12-19 17:53 UTC by jnumainville

Fixes https://deephaven.atlassian.net/browse/DH-18247

Allows autodoc functions to have no parameters and adds better error checking for params to ensure that all expected parameters are there in a fine-tuned way.

Tested on all existing docs as well as a local `use_render_queue` doc.

2024-12-19 18:27 UTC, mofojed requested changes
Works for `use_render_queue`, but had a question about the error case when a function is missing parameters.

2024-12-19 18:27 UTC, mofojed commented on sphinx_ext/deephaven_autodoc.py
> +UNDOCUMENTED_PARAMS = {"*"}
I imagine this is the param that separates positional args from keyword args? May want to add `"/"` to this list as well then, that's used in a couple spots. Comment would be useful here as well.

2024-12-19 18:27 UTC, mofojed commented on sphinx_ext/deephaven_autodoc.py
> +    if missing_params:
When does this case actually get hit? I tried removing an arg from a docstring, but instead got a different error:
```
Exception occurred:
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/sphinx_ext/deephaven_autodoc.py", line 117, in extract_list_item
    raise ValueError(
ValueError: Could not match auto_focus (bool | None) to extract param data. Verify this parameter is documented correctly within 'Args:' with type and description.
The full traceback has been saved in /tmp/sphinx-err-0n2f4ewq.log, if you want to report the issue to the developers.
```

Not sure there's any way for this missing case to actually trigger, since the error is raised when parsing the docstring.

2024-12-19 18:59 UTC, jnumainville commented on sphinx_ext/deephaven_autodoc.py
> +    if missing_params:
You're right in that this isn't going to be triggered much as is.
This did catch that we had `*children` documented as `children` in a couple of docs. This also would grab `kwargs` if it should be `**kwargs`. I think what's happening is sphinx autodocing will match, for example, `*children` up to `children` no problem. How `hildren` is of a matter of opinion I suppose, but it does make sure we're consistent.

2024-12-19 19:05 UTC, jnumainville commented on sphinx_ext/deephaven_autodoc.py
> +UNDOCUMENTED_PARAMS = {"*"}
Done

2024-12-19 19:08 UTC, jnumainville commented on sphinx_ext/deephaven_autodoc.py
> +    if missing_params:
Since that should be the only case hit I narrowed down the error message.

2024-12-23 18:55 UTC, mofojed approved these changes

2024-12-23 18:55 UTC, merged