feat: Load widgets from plugin context
deephaven/deephaven-plugins pull request #114
Opened 2023-11-13 14:51 UTC by mattrunyon

Fixes #59 

Changes UI to load widgets from the plugin context which allows for any widget (as long as it's a `WidgetPlugin` w/ the proper `supportedTypes`) to be part of a deephaven UI panel without any extra setup from the user.

2023-11-20 14:18 UTC, mofojed requested changes
Minor cleanup, marking as requesting changes as we need to update with a published build (0.55 after https://github.com/deephaven/web-client-ui/pull/1644 merges).

2023-11-22 23:57 UTC, mofojed requested changes
Rebase off the latest as well to get the latest test-results action

2023-11-22 23:57 UTC, mofojed commented on plugins/ui/src/js/src/ObjectView.tsx
> +  const fetch = useCallback(() => object.fetch() as Promise<Widget>, [object]);
Don't need the cast at all:
```suggestion
  const fetch = useCallback(() => object.fetch(), [object]);
```

2023-11-22 23:57 UTC, mofojed commented on plugins/ui/src/js/src/ObjectView.tsx
> +  const fetch = useCallback(() => object.fetch() as Promise<Widget>, [object]);
You'll need to remove the unused `Widget` import as well.

2023-11-23 05:13 UTC, mattrunyon commented on plugins/ui/src/js/src/ObjectView.tsx
> +  const fetch = useCallback(() => object.fetch() as Promise<Widget>, [object]);
Nope I can't remove the cast.

The `jsapi-types` is `Promise<unknown>`. The `WidgetComponent` expects `Promise<Widget>`. Should probably update the `jsapi-types`, although table and figure don't conform to the `Widget` class, so really it should be `Promise<Widget | Table | Figure>` and we should have some TS type guards. I don't think table and widget have a type on the instances like widgets do.

2023-11-23 17:48 UTC, mofojed approved these changes

2023-11-23 17:48 UTC, merged