spec: use_viewport hook
deephaven/deephaven-plugins pull request #118
Opened 2023-11-16 17:51 UTC by jnumainville

Spec for use_viewport_data, modeled after [setViewport](https://deephaven.io/core/docs/reference/js-api/documentation/#methods-2)

One question - it seems like the best way to achieve the row subsetting is to use the `slice` method. Would it be reasonable to also allow percents like `slice_pct` or perhaps heads or tails of data? maybe different hooks?

2023-11-16 18:08 UTC, dsmmcken commented
If I am returning one column does it need to be dict, could it just be an array? If I am returning one cell can it just be a value?

2023-11-16 18:13 UTC, jnumainville commented
@dsmmcken Personally, I would prefer to keep the output of this consistent and have other hooks for specific data structure such as `use_column_data` (which you could still provide rows to) or `use_cell_data` and maybe `use_row_data`
Those hooks would be built on this one to be fair, and just coerce the data to the desired structure. Just having lots of funky edge cases like that (even if controlled through args) seems like it could be confused and lead to unexpected behavior at times.

2023-11-16 18:16 UTC, dsmmcken commented
Ok, I am just trying to push my agenda of wanting to easily go from a specific cell to a reactive variable.

2023-11-16 22:00 UTC, jnumainville commented
I've added some additional hook possibilities. I also added some other arguments based on the `pct`, `head`, `tail` possibilities. I do not feel strongly about added them, as they could be done with a memoized table (and if you want a combination or where filters you're going to need to do that anyways) but they are naturally viewporty and could simplify simple use cases.

2023-11-17 15:22 UTC, mofojed requested changes

2023-11-17 15:22 UTC, mofojed commented on plugins/ui/DESIGN.md
> +    columns: str | Sequence[str] = None,
Use `ColumnName` instead of `str`. It's defined in the glossary and it just points to str, but it makes it clearer what kind of str we want here.

2023-11-17 15:22 UTC, mofojed commented on plugins/ui/DESIGN.md
> +If none of the above are specified, all rows will be returned.
I don't really like having to split up the different ways to get a viewport as different groups of parameters you can pass in... I think it'd be better if we just had different hooks if it's going to take a different set of parameters, e.g.
```py
use_table_data(table: Table, first_row: Optional[int] = None, last_row: Optional[int] = None, columns: Optional[ColumnName | Sequence[ColumnName]] = None) -> ViewportData | Sentinel
use_table_head(table, Table, row_count: int, columns: Optional[ColumnName | Sequence[ColumnName]] = None) -> ViewportData | Sentinel
# etc...
```
I'm willing to get outvoted on this though if @dsmmcken thinks the current spec is better.

2023-11-17 15:22 UTC, mofojed commented on plugins/ui/DESIGN.md
> +TableData = dict[ColumnName, RowData]
This isn't the right type - a dictionary from `ColumnName` to `RowData` doesn't make sense, `RowData` is a dict with the `ColumnName` as the key.
The above `RowData` definition should be:
```py
RowData = dict[ColumnName, Any]
```
But then this `TableData` would just need to be `list[RowData]` I believe. We don't need to provide the offset as the hook will only return the data once retrieved, so they've already got the offset (if they specified it)... Though if you get into the `slice` type of hooks, then it might make sense to have the explicit offset/range returned... I just wouldn't worry about the slice methods right now.

2023-11-17 15:22 UTC, mofojed commented on plugins/ui/DESIGN.md
> +Capture the data in a specific viewport. If there is no data in the viewport, a sentinel value will be returned.
"If there is no data in the viewport" - I don't think that's right, we just want to return a Sentinel while we're fetching the viewport. If all the values in the viewport are None or something, we should still be returning a `TableData` with `None` for the values.

Same wording needs to be fixed on the other methods.
```suggestion
Capture the data in a specific viewport. If the viewport is still loading, a sentinel value will be returned.
```

2023-11-17 15:39 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +If none of the above are specified, all rows will be returned.
It's an interesting idea, but I think directly writing the query on the table you pass is more than acceptable.

I wouldn't add the additional complication.

2023-11-17 17:50 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +TableData = dict[ColumnName, RowData]
I think what I was going for a more natural table format but messed it up. I think it should be `TableData = dict[ColumnName, ColumnData]` where `ColumnData = list[any]`. The only practical differences are you access column then row rather than row then column, which makes sense given that our system is column based, and we're only storing the column names once in that case.

2023-11-20 14:09 UTC, mofojed requested changes
Minor cleanup, looks good to me.

2023-11-20 14:09 UTC, mofojed commented on plugins/ui/DESIGN.md
> +) -> list[Any] | Sentinel:
```suggestion
) -> ColumnData | Sentinel:
```

2023-11-20 14:09 UTC, mofojed commented on plugins/ui/DESIGN.md
> +) -> list[Any] | RowData | Sentinel:
```suggestion
) -> RowData | Sentinel:
```

2023-11-20 15:30 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +) -> list[Any] | RowData | Sentinel:
With this one, I use `list[Any]` as an option because of the `as_list` flag. I think, by default, `RowData` should be returned but it's possible you don't actually care about the column names, just the values, and just want a list.

2023-11-20 16:43 UTC, jnumainville commented
@dsmmcken @mofojed 
I was discussing with @niloc132 and his perspective is that these hooks should assume that the data is already in the desired format.
For example, instead of using a viewport with `first_row`, `last_row`, `columns`, the user should have already filtered their table down to the desired rows and columns with `slice`, `view` etc. 
Thoughts on that?

2023-11-20 16:47 UTC, dsmmcken commented
> Thoughts on that?

That works for me, as in it would always take the full size of the data right? That's probably actually better, as dealing with growing number of row would be difficult otherwise.

2023-11-20 16:51 UTC, jnumainville commented
> That works for me, as in it would always take the full size of the data right? That's probably actually better, as dealing with growing number of row would be difficult otherwise.

Yes, it would just do the whole table (and extract to row, column, etc. for the higher level hooks)

2023-11-20 16:52 UTC, niloc132 commented
> as dealing with growing number of row would be difficult otherwise.

Exactly - and if you know you just performed an operation that gives the exact rows/columns you want (aggAllBy, view+head etc), then there's no need to apply other operations like this.

We should take care to call out that the "whole table" hook isn't suitable for just handing it an arbitrary table - and further that the "cell" hook deliberately takes the first row+column as an extension of this idea.

2023-11-20 17:10 UTC, mofojed commented
Yup makes sense. That's why we write/review specs!

2023-11-21 15:08 UTC, mofojed commented on plugins/ui/DESIGN.md
> +) -> list[Any] | RowData | Sentinel:
Ah yea. I'd rather use overloaded functions (Python single dispatch?) or a different function name for this. As it is right now, using this method, you'd need to check the result each time to see if it's a `list[Any]` or a `RowData`, even though you should know what the return type is based on what you're calling.

2023-11-21 15:08 UTC, mofojed commented on plugins/ui/DESIGN.md
> +it is best to filter before data is retrieved.
We should link to the Table Operations available on a table here: https://deephaven.io/core/docs/reference/table-operations/filter/head/
Or perhaps here: https://deephaven.io/core/docs/how-to-guides/use-select-view-update/

So we guide them to what operations we want them to use. Filter/head/tail/sorting for rows, select/view for columns.

2023-11-21 18:36 UTC, mofojed approved these changes
Looks good to me, should get @dsmmcken 's approval though.

2023-11-21 19:09 UTC, dsmmcken approved these changes

2023-11-21 19:20 UTC, merged