feat(ui): Only send new exported objects
deephaven/deephaven-plugins pull request #129
Opened 2023-11-21 20:51 UTC by mofojed

- Instead of resending the full list of exported objects each time, just send the newly exported objects
- Increment the ID for each new object that is created
- Keep a weak reference to old objects so they are released when no longer referenced
- Objects remain the same between renders, this fixes #128 
- Tested using the steps in #128 
- One issue still outstanding is how to handle re-opening the same object twice. Using the testing steps, opening the widget, and then opening it again, results in blank panels where the tables should be and an error message: `java.lang.IllegalStateException: already exists TableTicket{ticket=101,243,255,255,255, state=PENDING, isConnected=true}`. We should decide how we want to resolve that issue before merging this ticket.

BREAKING CHANGE: JSON protocol now keeps the IDs of objects and callables stable between re-renders, and only exports new objects with each documentUpdated event. The client must track the old objects independently.

2023-11-27 20:33 UTC, mofojed commented
@niloc132 I want to ensure this approach is valid given our discussions about exported objects. Though I think one thing I'll need to change is to export an object multiple times if it is used multiple times in the document (since we're only allowing one `fetch` per exported object). Otherwise, need to allow client to call `fetch` multiple times on the same exported object to fetch it again.

2023-12-11 22:18 UTC, mattrunyon requested changes

2023-12-11 22:18 UTC, mattrunyon commented on plugins/ui/src/js/src/WidgetHandler.tsx
> +  const exportedObjectCount = useRef(0);
In the deephaven express version of this, we added an array of new object IDs to the message from the server to align with the array received instead of doing the same incrementing on the client. We weren't sure if it was fully safe to just increment on the client. If messages can somehow arrive out of order, then the client is now in a bad state and doesn't know it. We also send an array of object IDs that can be closed to the client

This is fine if we can guarantee message order from the server

2023-12-12 20:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/renderer/NodeEncoder.py
> +        return super().encode(o)
This method is overriding `JSONEncoder.encode`, not best practice to override it and return a different type.
But I will add a new method to make it clear.

2023-12-12 20:59 UTC, mofojed commented on plugins/ui/src/deephaven/ui/renderer/NodeEncoder.py
> +CallableId = str
Yea this comment is out of date.

2023-12-12 21:05 UTC, mofojed commented on plugins/ui/src/js/src/WidgetHandler.tsx
> +  const exportedObjectCount = useRef(0);
Messages will arrive in the order they are sent.

2023-12-12 22:41 UTC, mattrunyon requested changes

2023-12-12 22:41 UTC, mattrunyon commented on plugins/ui/src/js/src/ObjectView.tsx
> +    // We reexport the object in case this object is used in multiplate places or closed/opened multiple times
```suggestion
    // We re-export the object in case this object is used in multiple places or closed/opened multiple times
```

2023-12-12 22:41 UTC, mattrunyon commented on plugins/ui/src/js/src/UITable.tsx
> +      const newTable = (await reexportedTable.fetch()) as Table;
Should we add this to the main table plugin too?

2023-12-13 00:26 UTC, mofojed commented on plugins/ui/src/js/src/UITable.tsx
> +      const newTable = (await reexportedTable.fetch()) as Table;
We shouldn't need it there - see that `fetch` is wrapped in `ObjectView` to do the re-export already.

2023-12-13 18:15 UTC, mattrunyon approved these changes

2023-12-13 20:00 UTC, merged