feat: ui.fragment, ui.tabs, ui.tab_list, ui.tab_panels
deephaven/deephaven-plugins pull request #138
Opened 2023-11-24 17:42 UTC by mofojed

- When decoding the JSON document, convert the element nodes right to their components then
  - Eliminates wrapper components like `ElementView`, which was causing some issues when used within components that expected children of a certain type (such as Tabs/TabPanels/TabList from spectrum)
  - Wraps exported objects in the `ObjectView` only when they are rendered as children of an element
  - Still checks for mixed panel/non-panels at root, and implicitly wraps root if no panels
- Fix styling on table to `display: contents`
  - Now it sizes correctly by default when used within tabs
- Use a context (ReactPanelManagerContext) to handle the opening/closing of react panels within a document
  - Concept can be extended for opening/closing dashboards as well
- Need Tabs example still

2023-12-18 16:11 UTC, mattrunyon requested changes

2023-12-18 16:11 UTC, mattrunyon commented on plugins/ui/src/js/src/styles.scss
> +  overflow: hidden;
I don't think we should hide overflow by default anywhere in Deephaven UI. Makes things seem like bugs that aren't. See #177

2023-12-18 16:11 UTC, mattrunyon commented on plugins/ui/src/js/src/spectrum/mapSpectrumProps.ts
> +export function mapSpectrumProps<
Comment should mention props

2023-12-18 16:11 UTC, mattrunyon commented on plugins/ui/src/js/src/WidgetUtils.tsx
> +    if (Array.isArray(children)) {
Why handle this case of children specially? Couldn't this check of the children be removed and just use this? I guess the keys wouldn't get created in that case, but not sure they're valid keys as is

```ts
if (isExportedObject(newElement) {
  return <ObjectView object={child} />
}
```

2023-12-18 16:11 UTC, mattrunyon commented on plugins/ui/src/js/src/WidgetUtils.tsx
> +          return <ObjectView key={child.type} object={child} />;
I don't think this key is guaranteed to be unique among sibling elements

2023-12-18 16:41 UTC, mofojed commented on plugins/ui/src/js/src/styles.scss
> +  overflow: hidden;
I don't think this is causing #177, and your comment on #177 seems to be incorrect. That said, we may not need the hidden here, I'll see if I can remove it.
The implicit sizing of the grids/plots in a flex layout is annoying.

2023-12-18 17:04 UTC, mattrunyon commented on plugins/ui/src/js/src/WidgetUtils.tsx
> +    if (Array.isArray(children)) {
This function is called from within the JSON.parse reviver, so I was thinking the children are already iterated over by the time you reach the parent.

Looking at that reviver though, we do a separate replacement and I think we'd have to wrap it in an `ObjectView` or something if we wanted to add its type here.

Instead, maybe the reviver should return the actual `<ObjectView />` on line 103 instead of the object (since we're then replacing the object anyway).

2023-12-18 17:08 UTC, mattrunyon commented on plugins/ui/src/js/src/styles.scss
> +  overflow: hidden;
Ya I didn't see the screenshot wasn't overflowing in #177, but when I ran the code it was overflowing. Might have been because I resized the panel and the internal size of grids didn't update causing the overflow.

Either way, I don't think we should hide overflow here. What's the point of it other than scroll bars are ugly? The problem of "I can't access my data/content" if we hide the overflow from the user is significantly worse IMO

2023-12-18 17:23 UTC, mattrunyon commented on plugins/ui/src/js/src/WidgetUtils.tsx
> +    if (Array.isArray(children)) {
Nevermind that won't work with the `object_view` wrapper from Python because you'd end up w/ 2 objects. That said, is there a point/use case for `object_view` in Python?

2023-12-18 19:55 UTC, mofojed commented on plugins/ui/src/js/src/WidgetUtils.tsx
> +    if (Array.isArray(children)) {
We can't replace with an `ObjectView` there because you may want to pass an exported object as a prop, not as a child (like we do with a table to `UITable`). We only want to implicitly wrap an exported object like a table with a `UITable` or some other React component when it is passed as a child from an element... 
I had toyed with implicitly wrapping in the python layer (hence the `object_view`), but ultimately settled to implicitly wrap in the client side parsing instead (when parsing out the element, as we are here). I think that gives more flexibility. `object_view` I can just remove at this point... the only case I think it would make sense would be if you were passing a rendered component as a prop other than `children` on another component (e.g. if you tried to pass a `table` as a `description` to a `CheckboxGroup`). But even that doesn't really make sense, so I'll just remove it for now.

2023-12-18 20:03 UTC, mofojed commented on plugins/ui/src/js/src/UITableUtils.tsx
> +  props: UITableProps;
Yea we need some way to specify the props are required in this case, whereas they're not required in all cases.
I can wrap the whole thing in a `Required`, that may be a little bit nicer.

2023-12-19 14:27 UTC, mofojed commented on plugins/ui/src/js/src/ReactPanel.tsx
> +        title ?? (typeof metadata?.name === 'string' ? metadata.name : '');
Right now they're all the same name. I can do a change to this behaviour, but figure it may make more sense to merge this/your changes and then revisit that instead? Up to you.

2023-12-20 18:36 UTC, mattrunyon requested changes

2023-12-20 18:36 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/spectrum/basic.py
> +def button(*children, **props: int):
This typehint seems accidental

2023-12-20 18:36 UTC, mattrunyon commented on plugins/ui/src/js/src/DocumentUtils.tsx
>  export function getRootChildren(
Should have an `@returns`

2023-12-20 18:38 UTC, mattrunyon commented on plugins/ui/src/js/src/ReactPanel.tsx
> +        title ?? (typeof metadata?.name === 'string' ? metadata.name : '');
Ya just leave it for now

2023-12-20 21:40 UTC, mattrunyon approved these changes

2023-12-20 21:40 UTC, merged