feat: Added scripts to serve plugins locally for dev
deephaven/deephaven-plugins pull request #140
Opened 2023-11-28 23:20 UTC by bmingles

- Added an `npm run serve` script to serve plugins locally. This can be used with Vite proxy for DHC or DHE locally
- Fixed missing nx native dependencies in package lock

2023-11-29 15:54 UTC, devinrsmith commented
Slightly related - would be reasonable for these use cases to disable js plugins on the server side: https://github.com/deephaven/deephaven-core/pull/4695

2023-11-30 14:39 UTC, mofojed requested changes
Nice! Just a couple minor suggestions. We'll need a follow up PR in web-client-ui as well.
One thing this doesn't give us is source maps - but that will need a change from web-client-ui I think to achieve.

2023-11-30 14:39 UTC, mofojed commented on README.md
> +npm serve
```suggestion
npm run serve
```

2023-11-30 14:39 UTC, mofojed commented on vite.config.js
> +  publicDir: 'plugins',
I'd like if we used port `4100` instead of the default port, and have the option to set it via environment variable/`.env` like in web-client-ui. Then we have:
3000: Enterprise
4000: web-client-ui
4010: Embedded grid
4020: Embedded chart
4100: JS Plugins

2023-11-30 14:39 UTC, mofojed commented on README.md
> +```
We should have a follow up PR to have a flag for this, something like `JS_PLUGINS_PORT` or something that only kicks the proxy in if the value is set.

2023-11-30 14:39 UTC, mofojed commented
Also rebase off the latest so tests run correctly

2023-11-30 14:41 UTC, bmingles commented on README.md
> +```
I have another option for this that I've been playing with in my other PR.

https://github.com/deephaven/web-client-ui/pull/1661/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

2023-11-30 15:49 UTC, mofojed commented on README.md
> +```
Yea a vite.config.local.ts could be useful for some things as well... annoying to add that extra flag for it, but I guess either way we're adding an extra flag somewhere

2023-11-30 15:50 UTC, mofojed approved these changes

2023-11-30 16:20 UTC, merged

2023-11-30 20:26 UTC, bmingles commented on README.md
> +This will serve the `plugins` directory at `http://localhost:5173`
Yes, I'll fix in another PR