build: Have docker scripts for starting up the deephaven-plugins repo with the latest
deephaven/deephaven-plugins pull request #143
Opened 2023-11-30 19:52 UTC by mofojed

- Docker scripts to automatically start up containers to build all of the JS/python, start up the deephaven-core container, install all the plugins appropriately, and serve them up
- Use by running `npm run docker`, then going to http://localhost:10000
- Useful to test latest deephaven-plugins without having to build/configure deephaven-core locally (@dsmmcken)
- Will also be useful when adding e2e tests to this repo, as CI can use the docker script to start up a box before executing the e2e tests (@ethanalvizo)
- Regenerated the package-lock.json. Was getting errors with it in the docker container for some reason, seems to be somewhat corrupted.

2023-12-04 17:49 UTC, mattrunyon requested changes

2023-12-04 17:49 UTC, mattrunyon commented on package.json
> +    "docker": "docker build --tag ghcr.io/deephaven/deephaven-plugins:local-build . && docker run --publish 10000:10000 ghcr.io/deephaven/deephaven-plugins:local-build",
We could do this how core does as a build step via npm then add a `docker-compose.yml` so you can just `docker compose up` or `docker compose up -d` from the root

I guess the main thing is we might want to just run this in detached mode which would require you to copy the 2nd half and add the `-d` after the ports

2023-12-04 17:49 UTC, mattrunyon commented on docker/data/storage/notebooks/DEMO.md
> +Deephaven is a new framework for building reactive UI components for real-time data apps, entirely in Python. No front-end engineering needed. Users can turn kafka feeds, event streams, and data lake
Should start w/ `Deephaven UI` probably. Also, the 2nd part of this feels somewhat redundant.

Probably we should just have Margaret modify the prose in this separately

2023-12-04 17:49 UTC, mattrunyon commented on README.md
> +Instead of running deephaven-core from source and building all plugins yourself, you can run a docker container that automatically builds the plugins and installs them in an instance of deephaven-cor
The part about running w/o npm is incorrect since removing the shell script. Should just include the docker commands to build and run the container here

Maybe we want a `docker-compose.yml` for ease

2023-12-04 18:17 UTC, dsmmcken commented on README.md
> +Instead of running deephaven-core from source and building all plugins yourself, you can run a docker container that automatically builds the plugins and installs them in an instance of deephaven-cor
docker-compose local that I can add a volume mount mount for my local data notebooks folder would be useful.

2023-12-04 20:41 UTC, mofojed commented on package.json
> +    "docker": "docker build --tag ghcr.io/deephaven/deephaven-plugins:local-build . && docker run --publish 10000:10000 ghcr.io/deephaven/deephaven-plugins:local-build",
I'll add a docker-compose.yml for flexibility.

2023-12-04 21:34 UTC, mattrunyon requested changes

2023-12-04 21:34 UTC, mattrunyon commented on README.md
> +Instead of running deephaven-core from source and building all plugins yourself, you can run a docker container that automatically builds the plugins and installs them in an instance of deephaven-cor
Looks like the props file actually only includes deephaven UI and deephaven-express. Should either make it include all or change the wording.

Probably use `up` instead of `run`. `run` is meant for one-offs and also I believe you need `--service-ports` w/ `run` to make the exposed ports work. Also `run` can specify a command to override the default for a service. I used it in the e2e docker so I could change the e2e flags (and also b/c e2e is a one-off run)

2023-12-04 21:34 UTC, mattrunyon commented on README.md
> +If you wish to customize what data is used for the docker container or what port it should open on, you can create a [docker-compose.override.yml file](https://docs.docker.com/compose/multiple-compos
Looks like for ports at least, it would just concatenate the entries. So it would try to expose on both ports. Probably just stick a `PORT` or `DH_PORT` env variable in the compose file instead that defaults to 10000

2023-12-04 21:34 UTC, mattrunyon commented on README.md
> +      - /path/to/mydata/:/data
Will this remove the demo file?

2023-12-06 16:27 UTC, mofojed commented on README.md
> +      - /path/to/mydata/:/data
The demo file will not be accessible, but it doesn't delete it or anything.

2023-12-06 20:40 UTC, mattrunyon commented on README.md
> +      - /path/to/mydata/:/data
Might want to include a comment that the demo file will be inaccessible?

2023-12-06 22:22 UTC, mattrunyon commented
Looks like I had an old image tagged as `edge` for the server locally and Docker only pulls missing by default when building.

Should be able to add `pull: true` to the `build` section in the compose file to always pull when building. I tested by changing the tag to `latest` which was 0.29.0 for me locally. Adding `pull: true` bumped to 0.30.3 just using `docker compose up --build`

2023-12-07 19:36 UTC, dsmmcken approved these changes

2023-12-11 20:02 UTC, mattrunyon approved these changes

2023-12-12 19:19 UTC, merged