feat: ui.table functionality
deephaven/deephaven-plugins pull request #145
Opened 2023-11-30 22:45 UTC by jnumainville

This is not ready for review but I am putting this up just in case as I know Bender mentioned possibly working on some of the js functionality while I am on vacation. What's implemented is not thoroughly tested, needs to be refactored, and subject to change but I have sorts, quick filters, and the search bar hooked up. 

Example:
```
from deephaven import SortDirection
import deephaven.ui as ui
import deephaven.plot.express as dx

stocks = dx.data.stocks()

@ui.component
def searchable_filtered_sorted_table(source):
    return [
        ui.panel(
            ui.table(source)
            .sort("price", SortDirection.DESCENDING)
            .quick_filter({"side": "sell"})
            .can_search("SHOW"),
            title="Stock Table I",
        )
    ]

sti = searchable_filtered_sorted_table(stocks)
```

2023-12-12 15:13 UTC, mofojed requested changes

2023-12-19 16:37 UTC, mofojed requested changes
Need to run eslint as well

2023-12-19 16:37 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        self._props = props if props is not None else {}
A little confused why you did this instead of defaulting to ` = {}` - getting lint errors this way:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/bf6f0cba-255e-49a4-9ff1-8fcaf8712d8c)

2023-12-19 16:37 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/types.py
> +ContextMenuAction = Dict[str, Any]
When we implement `context_menu`, we'll want to have this be a TypedDict with the actual types.

2023-12-19 21:52 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        self._props = props if props is not None else {}
Can change the type to `dict[str, Any] | None`
The reason I am not defaulting to `{}` is mutable default arguments is not a good practice. The empty dictionary will be only created once and used in all calls to that function
https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
I suppose in this case it could be fine if we are sure we don't ever do any modification to the dictionary, but I prefer to just avoid that risk

2023-12-19 23:13 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        self._props = props if props is not None else {}
I'd rather do something like `self._props = {**props}` in that case then. If we're worried about mutability, we should be concerned about a dictionary being passed in as well.

I wish there was an easy way to mark a dict as readonly or immutable ...

2023-12-21 22:36 UTC, jnumainville commented
I was mostly able to merge the refactors in, but for some reason the quick filters are not coming through. Still investigating.

2024-01-02 20:43 UTC, mofojed requested changes
Couple minor cleanups

2024-01-02 20:43 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        direction: SortDirection | Sequence[SortDirection] | None = None,
Should take the `Literal["ASC", "DESC"]` here as well ... and only re-map it if it's one of the enums provided.

Pydoc will need to be up to date as well

2024-01-02 20:43 UTC, mofojed commented on plugins/ui/src/js/src/UITable.tsx
> +  const [utils] = useState(new IrisGridUtils(dh));
Should `useMemo` instead - doing a `useState` will not update it if `dh` changes.
```suggestion
  const utils = useMemo(() => new IrisGridUtils(dh), [dh]);
```

2024-01-03 20:19 UTC, jnumainville commented
@mofojed I still can't seem to get quick filters appearing after the refactor. Any ideas? It seems like the same exact `quickFilter` prop is being passed to the `IrisGrid`

2024-01-04 21:30 UTC, mofojed approved these changes

2024-01-04 21:49 UTC, merged