feat: Table hooks
deephaven/deephaven-plugins pull request #168
Opened 2023-12-13 20:56 UTC by jnumainville

Fixes #112 

This requires some core changes from [here](https://github.com/deephaven/deephaven-core/compare/main...niloc132:deephaven-core:4942-api?expand=1) before being ready to merge

Verified unit tests worked by modifying `tox.ini` to use local wheels
```
deps = 
    {toxinidir}/../../../deephaven-core/py/server/build/wheel/deephaven_core-0.31.0+snapshot-py3-none-any.whl
    {toxinidir}/../../../deephaven-core/py/embedded-server/build/wheel/deephaven_server-0.31.0+snapshot-py3-none-any.whl
    #deephaven-server
```

I will add better usage examples but this is a quick example to see all of the hooks working
```
import deephaven.ui as ui
from deephaven import time_table

@ui.component
def watch_cell(source: Table):

    current_table = ui.use_table_data(source)
    current_row = ui.use_row_data(source)
    current_row_list = ui.use_row_list(source)
    current_column = ui.use_column_data(source)
    current_cell = ui.use_cell_data(source)

    view1 = ui.view(f"current time: ${current_table}")
    view2 = ui.view(f"current time: ${current_row}")
    view3 = ui.view(f"current time: ${current_row_list}")
    view4 = ui.view(f"current time: ${current_column}")
    view5 = ui.view(f"current time: ${current_cell}")

    return [view1, view2, view3, view4, view5]

t = time_table("PT1S").tail(1)

watch = watch_cell(t)
```

2023-12-19 17:05 UTC, mofojed requested changes

2023-12-19 17:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_table_data.py
> +    submit_task(executor_name, partial(_deferred_update, ctx, func))
I'm not too familiar with this `submit_task` functionality. Will need to take a closer look...

2023-12-19 19:20 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_table_data.py
> +) -> tuple[pd.DataFrame | Sentinel, bool]:
I think `is_sentinel` is necessary as otherwise you can't distinguish between a sentinel and a returned value in some edge cases
For example, say I'm calling `use_row_data` with a sentinel of `{"numbers": [1, 2, 3]}`
It's not possible without some sort of extra check to tell if this was returned as the sentinel (and should just be returned) or if it was returned from pulling data from a table (and should be extracted to a row)
It would be a bit weird to have a data frame returned like that if you're looking for row data, but there's no reason that shouldn't be possible

I do like the transformation function though

2023-12-19 19:27 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_table_data.py
> +) -> tuple[pd.DataFrame | Sentinel, bool]:
I think is_sentinel is necessary as otherwise you can't distinguish between a sentinel and a returned value in some edge cases
For example, say I'm calling `use_row_data` with a sentinel of a pandas dataframe such as 
```
    size   price
0  23193  259.92
```
It's not possible without some sort of extra check to tell if this was returned (currently from `_use_table_data`) as the sentinel (and should just be returned) or if it was returned from pulling data from a table (and should be extracted to a row)

I do like the transformation function though

2023-12-21 15:56 UTC, mofojed commented on plugins/ui/DESIGN.md
> +| `transform`        | `Callable[[pd.DataFrame, bool], Any]`  | A function to transform the data from a pandas Dataframe to a custom object. The function takes a pandas dataframe or `Sentinel` as the
Above you have the signature accepting the `Sentinel`, here you do not. They should match.

2023-12-22 19:19 UTC, mofojed approved these changes
We probably should make a hook just for submitting tasks with the execution context, similar to how I made the `use_render_queue` hook for submitting tasks on the render thread.

2023-12-22 19:41 UTC, merged