fix: Close panels when object is nulled out
deephaven/deephaven-plugins pull request #170
Opened 2023-12-14 14:09 UTC by mofojed

- Needed to listen for the `PanelEvent.CLOSE` event
- Fixes #167

2023-12-14 20:22 UTC, mattrunyon requested changes

2023-12-14 20:22 UTC, mattrunyon commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  }, []);
Should this close all panels in the widget map instead? I think this is really if the document is closed/deleted so it should close all panels/widgets in the document

2023-12-15 15:04 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  }, []);
Each open widget has one document which can have multiple panels. This is closing the top level widget which will unmount/close all panels opened by that widget.

2023-12-15 15:04 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  }, []);
I tested with the following snippet opening multiple panels:
```
from deephaven import ui
from deephaven.plot import express as dx

_stocks = dx.data.stocks()

@ui.component
def stock_table_input(source, default_sym="", default_exchange=""):
    sym, set_sym = ui.use_state(default_sym)
    exchange, set_exchange = ui.use_state(default_exchange)

    t1 = source.select_distinct(["sym", "exchange"])
    t2 = source.where([f"sym=`{sym.upper()}`", f"exchange=`{exchange}`"])
    p = dx.line(t2, x="timestamp", y="price")

    def handle_row_double_press(row, data):
        set_sym(data["sym"]["value"])
        set_exchange(data["exchange"]["value"])

    return [
        ui.panel(
            # Add a callback for when user double clicks a row in the table
            ui.table(t1).on_row_double_press(handle_row_double_press),
            title="Stock Table Input",
        ),
        ui.panel(t2, title="Stock Filtered Table"),
        ui.panel(p, title="Stock Plot"),
    ]


sti = stock_table_input(_stocks, "CAT", "TPET")
```
And then `sti = None`. All panels cleared out.

2023-12-15 16:59 UTC, mattrunyon commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  }, []);
Oh ya for some reason I thought this was in the document handler

2023-12-15 17:00 UTC, mattrunyon approved these changes

2023-12-15 20:00 UTC, merged