feat: UI dashboard
deephaven/deephaven-plugins pull request #176
Opened 2023-12-14 20:36 UTC by mattrunyon

Closes #148, closes #149, closes #126, closes #62, closes #61

Working on web-client-ui changes to support this. Right now the dashboaord will replace the existing layout and width/height won't work because of how golden-layout handles calculating size. Those will be addressed in web-client-ui.

2023-12-19 15:51 UTC, mofojed commented on plugins/ui/src/js/src/ReactPanel.tsx
> +        LayoutUtils.closeComponent(parent, { id: panelId });
Any reason to do it like this instead of doing a `parent.addChild` as we're doing with `Column` and `Row`?

2024-01-16 21:05 UTC, mattrunyon commented on plugins/ui/src/js/src/ReactPanel.tsx
> +        LayoutUtils.closeComponent(parent, { id: panelId });
Keeping the `LayoutUtils.openComponent` at least should retain the behavior of finding a stack w/ the same type of component when we're just opening individual panels/components. When it's within a dh.ui dashboard, then specify the root as the parent (should always be a stack) so we get the layout right

2024-01-22 16:51 UTC, mofojed requested changes

2024-01-22 16:51 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/DashboardElement.py
> +        super(DashboardElement, self).__init__(
Is this actually necessary in Python 3? Pretty sure you can just call `super().__init__(`: https://docs.python.org/3.5/library/functions.html#super

2024-01-22 16:51 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/dashboard.py
> +        children: Elements to render in the dashboard. Must have only 1 root element.
If we're saying you must only have 1 root element, why do we even allow multiple children to be passed in? Either only accept one param (e.g. `def dashboard(root: Element, **kwargs: Any)`) or detail how we implicitly wrap it if multiple children are provided (I'm thinking former is probably simpler).

2024-01-22 16:51 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/stack.py
> +    Each element will get a tab and only one element can be visible at a time.
A question I"m sure that will come up is how do we give a name to the tabs. I'm guessing you need a `ui.panel` to specify a title. Do we even allow non-ui.panel things here? Should we enforce only passing in PanelElements as the children?

2024-01-22 16:51 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  useListener(layout.eventHub, PanelEvent.OPEN, handleDashboardOpen);
I'd rather it call into one method, and from there check the type and split off.

2024-01-22 16:51 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +      log.info('Loading dashboard', pluginData);
Put the log after the `pluginData == null` check, no need to log a "Loading dashboard `null`" line every time user opens a dashboard.

2024-01-23 19:17 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/stack.py
> +    Each element will get a tab and only one element can be visible at a time.
Yes you'd need to use a panel w/ the title param

In this first pass we don't allow non panels here. This would be something we consider auto-wrapping in an update to make it nicer to use. I think it's reasonable to allow `ui.stack(some_table, some_other_table)` if you're fine with the default panel titles

2024-01-23 23:35 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/dashboard.py
> +        children: Elements to render in the dashboard. Must have only 1 root element.
Ya I'll just change this to take `root: FunctionElement` for now as the only param and we can expand as needed

2024-01-23 23:37 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/elements/DashboardElement.py
> +        super(DashboardElement, self).__init__(
Apparently not. Guess the answer I found was for Python 2

2024-01-24 20:17 UTC, mofojed submitted a review, later dismissed

2024-01-26 22:59 UTC, mofojed approved these changes

2024-01-26 23:04 UTC, merged