feat: Queue render state updates on a thread
deephaven/deephaven-plugins pull request #182
Opened 2023-12-20 23:58 UTC by mofojed

- Create a thread and queue for applying state updates
- Now callbacks and state updates are all queued on the same thread
- Fixes #116
- Tested using the snippet from #116:
```python
import deephaven.ui as ui
from deephaven.ui import use_state

@ui.component
def foo():
    a, set_a = use_state(0)
    b, set_b = use_state(0)

    print(f"Render with a {a} and b {b}")

    def handle_press():
        set_a(a + 1)
        set_b(b + 1)

    return ui.action_button(
        f"a is {a} and b is {b}", on_press=handle_press
    )

f = foo()
```
- Ensured that the print out was only printed once per press of the button, and both values stayed the same

2023-12-21 10:45 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            dispatcher[callable_id] = wrapped_callable
This is incorrect - it's no longer returning the value from the callable correctly. Need to wire this up differently to respond with the result correctly.

2023-12-21 15:09 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            dispatcher[callable_id] = wrapped_callable
Fixed it up

2023-12-21 19:19 UTC, jnumainville requested changes

2023-12-21 19:19 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            raise Exception(
Would prefer a more specific exception
probably ValueError?

2023-12-21 19:19 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        except Exception as e:
is this intentionally generic to make sure we catch any error or is there specific errors that could arise?

2023-12-22 18:13 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        except Exception as e:
Intentionally generic - if something fails in the state update, we don't want the render thread to stop.

2023-12-22 18:15 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +    if _render_thread is None or _render_thread.is_alive() is False:
Yea that looks easier to grok.

2023-12-22 19:34 UTC, jnumainville submitted a review, later dismissed

2024-01-03 20:54 UTC, mofojed commented
Thread pools now exposed to Python: https://github.com/deephaven/deephaven-core/pull/4949

2024-01-09 00:41 UTC, niloc132 commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +def use_state(initial_value: T | None = None) -> tuple[T | None, Callable[[T], None]]:
```suggestion
def use_state(initial_value: T | Callable[[], T] | None = None) -> tuple[T | None, Callable[[T], None]]:
```

Can you union the permitted Callable type for the param here while you're changing this line?

2024-01-10 15:47 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +def use_state(initial_value: T | None = None) -> tuple[T | None, Callable[[T], None]]:
I've also added the callable type to the setter function as well.

2024-01-11 02:19 UTC, niloc132 commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +                new_value = value(old_value)
Two thoughts/questions:
 * If new_value is the same as old_value, we shouldn't re-render at all after all
 * If `value` happens to be a Callable, then one of two things has happened - either this is the initial render, and old_value is meaningless... or you can assign callables into a use_state, and they will be invoked with the previous (callable) instance?!? 

That doesn't seem right, so I'm probably missing something.

2024-01-11 02:19 UTC, niloc132 commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +StateValue = T | Callable[[T | None], T]
It seems like the Callable flavor of this should be permitted to return None too?

2024-01-11 02:19 UTC, niloc132 commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +) -> tuple[T, Callable[[StateValue[T]], None]]:
As above, this seems to imply the following:

```python
foo, set_foo = ui.use_state(None)

#... much later
set_foo(lambda old: do_something_new(old, other_vars))
```
Did I just assign a function that `foo` will now be equal to the next time my component renders? Or did I just pass a function that should be called with the old value as a parameter?

2024-01-11 13:15 UTC, mofojed commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +                new_value = value(old_value)
- Yup good call, I'll update that so it doesn't re-render if value is the same
- You can pass an updater function in to the setter function. From React docs: https://react.dev/reference/react/useState#setstate
> If you pass a function as nextState, it will be treated as an updater function.
So then you can do stuff like:
```
const value, set_value = ui.use_state(5)

def handle_click():
  # Updater function takes the old value
  set_value(lambda v: v + 1)
...
```

I have another example in the PR description of this as well.

2024-01-11 13:16 UTC, mofojed commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +StateValue = T | Callable[[T | None], T]
I should probably distinguish between the initializer function and the updater function. Initializer function always has `None`, whereas updater function always has `T` (which could include `None`). I'll make that a little more clear.

2024-01-11 13:18 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +) -> tuple[T, Callable[[StateValue[T]], None]]:
Passed a function that should be called with the old value. If you _do_ want to set a function in a state variable, you need to have it be the return value of an updater function, e.g.
```
foo, set_foo = ui.use_state(None)

# Need to pass the function back as a result of the updater function
set_foo(lambda old: lambda : print("hello"))
```

Generally storing a function in a state variable is not a common use case.

2024-01-17 18:29 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +) -> tuple[T | None, Callable[[T | UpdaterFunction[T]], None]]:
I was using `@overload` incorrectly - I should only have had to define the two `@overload` and then not define typing in the actual implementation: https://docs.python.org/3/library/typing.html#typing.overload
But when I do that, pylance complains about no typings in the `use_state` implementation.
In any case, I think I need Python 3.12 to describe the typings correctly using the [type parameter syntax](https://docs.python.org/3/reference/compound_stmts.html#type-params) on the `use_state` functions. I'll just get rid of the overload for now and always allow `None`

2024-01-17 19:11 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +) -> tuple[T | None, Callable[[T | UpdaterFunction[T]], None]]:
Also see discussion here about default parameters in generic functions: https://github.com/python/mypy/issues/3737#issuecomment-316263133
Without type parameter syntax to allow for doing something like `x, set_x = use_state[int]()`, which would result in `x: int | None`, I think the best we can do for now is use type `T` when an `initial_value` is passed in, then allow `Any` when no `initial_value` is passed in.

```
# Initial value provided, only accepts the type that was initially provided
x, set_x = use_state(4)

set_x(5)     # This is valid
set_x("foo") # ERROR
set_x(None)  # ERROR

# No initial_value provided, accepts being set to any value
y, set_y = use_state()

set_y(5)     # valid
set_y("foo") # valid
set_y(None)  # valid

def foo(val: int | None):
    # Initial value provided, only accepts the type that was initially provided, including `None`
    z, set_z = use_state(val)

    set_z(5)     # valid
    set_z("foo") # ERROR
    set_z(None)  # valid

    print(z)
```
At least this way we get proper type checking when you start with an `initial_value`, and we don't block you from assigning a value if you don't declare an `initial_value`.

Filed a ticket to improve typing in 3.12: https://github.com/deephaven/deephaven-plugins/issues/208

2024-01-19 21:58 UTC, niloc132 approved these changes
Approved api details, would prefer if @jnumainville gives it a +1 too.

2024-01-19 22:14 UTC, jnumainville approved these changes

2024-01-19 22:23 UTC, merged