feat: Update Matplotlib plugin to register widget view
deephaven/deephaven-plugins pull request #189
Opened 2023-12-23 01:44 UTC by mofojed

- Now can be embedded and/or used in deephaven.ui
- Renamed components from MatPlotLib to Matplotlib to match the product name
- Styling set directly on element... can't register a styles component, should we have an app level render for components?
- Tested with deephaven.ui:
```
from deephaven import ui

@ui.component
def foo():
    import matplotlib.pyplot as plt
    import numpy as np

    from matplotlib.patches import PathPatch
    from matplotlib.path import Path

    N = 400
    t = np.linspace(0, 2 * np.pi, N)
    r = 0.5 + np.cos(t)
    x, y = r * np.cos(t), r * np.sin(t)

    fig, ax = plt.subplots()
    ax.plot(x, y, "k")
    ax.set(aspect=1)
    return fig

f = foo()
```

2023-12-23 02:53 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/MatplotlibPlugin.ts
> +  panelComponent: MatplotlibPanel,
You can omit this and it will get wrapped in a panel automatically when necessary. Since the panel component provided doesn't do anything other than render the view

2024-01-02 20:44 UTC, mattrunyon requested changes

2024-01-02 20:44 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/MatplotlibView.tsx
> +export type MatplotlibPanelState = {
This type doesn't seem to be used anywhere. Might as well remove it

2024-01-02 20:44 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/MatplotlibView.tsx
> +};
You can just use `WidgetComponentProps` from the plugin package which is this except returns `Promise<Widget>`

2024-01-02 20:44 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/MatplotlibView.tsx
> +        const widget = (await fetch()) as Widget;
Don't need this cast if you use the prop type from the plugin package

2024-01-02 20:44 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/MatplotlibView.tsx
> +MatplotlibView.COMPONENT = 'MatplotlibView';
You shouldn't need this line w/ widget plugins. For widget plugins, we register to the golden layout registry w/ plugin name. In the hook we created for registering components before this, we use `elem.COMPONENT ?? elem.displayName`. So the widget plugin will have a stable name for golden layout (as long as the main plugin config doesn't change its name) regardless of what this component is called.

2024-01-02 20:44 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/index.ts
> +export * from './MatplotlibView';
Any reason to export this here? In the plotly express plugin I have additional exports so the model can be used in the docs snapshot tool

2024-01-03 15:36 UTC, mofojed commented on plugins/matplotlib/src/js/src/index.ts
> +export * from './MatplotlibView';
Any reason _not_ to?

2024-01-03 20:41 UTC, mattrunyon commented on plugins/matplotlib/src/js/src/index.ts
> +export * from './MatplotlibView';
I don't like exporting more things than necessary. In this case it's highly unlikely it would be consumed by anything else (since it's a CJS bundle), but mostly why increase the public API footprint unless we need it?

All that's being exported is component specific styles (which shouldn't be exported from the component anyway) and the component itself

2024-01-10 16:15 UTC, mattrunyon approved these changes

2024-01-10 16:30 UTC, merged