docs: More specs for ui.table functionality
deephaven/deephaven-plugins pull request #198
Opened 2024-01-09 22:23 UTC by jnumainville

Here are how my initial attempts line up with the requests:
Display names (#105): `column_display_names`
event listener (#180): `add_event_listener`

requests from #77:
Show/hide quick filter by default: `display_quick_filters`
density: `density`
Ability to hide column headers: `display_column_headers`
Ability for the server to specify rows to select: `selected`
Allow multi/single selection: added `multi_select` arg to `selection_mode`
Allow row selection to be visible with checkboxes (vs just styled as highlighted, etc): `selection_style`
Allow columns to be kept hidden, even though they are subscribed (and so in the payload to be sent to the server on events): I believe this is already spec'd as `always_fetch_columns`

2024-01-09 22:59 UTC, dsmmcken reviewed
1. I think anything that is a setting should be a prop to ui.table, not method. Especially things that exist on other components as props. Like density would be prop on list for example.
2. display_X would be show_X in spectrum, we should be consistent.
3. Probably should just have a bunch of on_* events, not add_listener

2024-01-09 22:59 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +    multi_select: bool = False
Should default to true, but is this actually an option in our grid though?

2024-01-09 22:59 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +ui_table.display_column_headers(
This isn't supported by grid, nor do I think we would add support for it any time soon.

2024-01-09 22:59 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +| `mode`    | `QuickFilterMode`  | `"SHOW"` for the filters to be visible, `"HIDDEN"` for the filters to be hidden, and `"DEFAULT"` to use the system default |
what about true/false, and not set or null is default. Why do we need an explicit default? And by default what does that mean for a most of these?

2024-01-09 22:59 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +Specify the style that is used to show that data is selected. This can by `"HIGHLIGHT"`, `"CHECKBOX"`, a combination of those, or `"DEFAULT"` to use the system default.
also not supported, but I wouldn't mind this. Is this based on looking at the spectrum table docs?

2024-01-09 22:59 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +ui_table.add_event_listener(
Feels weird. We do on_* events everywhere elsewhere, this breaks from that, and isn't very react-like.

Also, you wouldn't ever combine or use All. You likely always want separate callbacks for each event that happens. The callback results wouldn't even be compatible.

2024-01-09 22:59 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +EventType = Literal["ALL", "SORT", "QUICK_FILTER", "CAN_SEARCH", "ON_ROW_DOUBLE_PRESS"]
CAN_SEARCH is not an event type.

2024-01-10 14:36 UTC, mofojed commented on plugins/ui/DESIGN.md
> +ui_table.display_column_headers(
I added support for display names on columns with https://github.com/deephaven/web-client-ui/pull/1636, and this is something Charles specifically asked for recently.

2024-01-10 14:41 UTC, mofojed commented on plugins/ui/DESIGN.md
> +| `multi_select` | `bool`           | True if always multiple select on press. False by default.
I'm not sure I understand exactly what this option does...

2024-01-10 15:15 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +    multi_select: bool = False
For many of these I don't think they're an option yet, but either way we have lots of work that needs to be done in the grid so I put them here for consideration.
As for the default, I understood this as multi_select being the default (instead of single select) so the default is False unless I'm misunderstanding.

2024-01-10 15:18 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `mode`    | `QuickFilterMode`  | `"SHOW"` for the filters to be visible, `"HIDDEN"` for the filters to be hidden, and `"DEFAULT"` to use the system default |
I'm not sure. I modeled these after `can_search`, which was spec'd in #82
in the current implementation, providing `DEFAULT` just clears out the prop if it is set
@mofojed thoughts?

2024-01-10 15:18 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +Specify the style that is used to show that data is selected. This can by `"HIGHLIGHT"`, `"CHECKBOX"`, a combination of those, or `"DEFAULT"` to use the system default.
This was a request from Colin in #77

2024-01-10 15:20 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +ui_table.add_event_listener(
My thought was if someone wanted to provide one callback function for all events then handle the event type within it they could do that but I am fine not supporting that as it complicates the implementation anyways

2024-01-10 15:22 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `multi_select` | `bool`           | True if always multiple select on press. False by default.
See https://github.com/deephaven/deephaven-plugins/pull/198#discussion_r1447525268 but my intention was that this allows you to select multiple rows, columns, etc. by default, inverting multiple and single select.

2024-01-10 15:27 UTC, jnumainville commented
> 1. I think anything that is a setting should be a prop to ui.table, not method. Especially things that exist on other components as props. Like density would be prop on list for example.

What defines a setting vs not a setting?

2024-01-17 19:36 UTC, mofojed requested changes

2024-01-17 19:36 UTC, mofojed commented on plugins/ui/DESIGN.md
> +| `mode`    | `QuickFilterMode`  | `"SHOW"` for the filters to be visible, `"HIDDEN"` for the filters to be hidden, and `"DEFAULT"` to use the system default |
Yea, I'd be fine with `Optional[bool]` as a type here. So it'd be `ui_table.quick_filters(show: True)`.
`can_search` was modelled after the existing SearchDisplayMode: https://github.com/deephaven/deephaven-core/blob/2120b16e5b2a0a0d1360d03d154c2c83abaa566e/py/server/deephaven/table.py#L91
Using literals allows for more than just binary or ternary options, and can make sense if the options don't translate well to bool (e.g. `"Row" | "Column"`)

2024-01-17 19:36 UTC, mofojed commented on plugins/ui/DESIGN.md
> +ui_table.add_event_listener(
Yes I'd stick with `on_*` for each type of event. Then we can be more specific about what detail is in the event, e.g.
```
ui_table.on_sort(listener: Callable[[SortEvent], None]) -> UITable
```
`SortEvent` could be the column name or the list of sorts or something like that.

2024-01-24 20:05 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +ui_table.add_event_listener(
I've added a new version with arguments modeled after `on_row_press` etc., but I'm wondering if those as well as the new ones should really have, for example, a `SortEvent` with a dictionary payload

2024-02-05 20:12 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +Add a callback for when a column is pressed.
ah, this should have the additional text "Only valid if the selection mode is `"COLUMN"`."
so it's getting fired the same as a row or cell press is in the case that columns are the pressable unit, meaning inside a cell

2024-02-05 21:16 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +Add a callback for when a column is pressed.
Added that text, let me know if additional clarification is needed

2024-02-07 19:34 UTC, mofojed requested changes

2024-02-07 19:34 UTC, mofojed commented on plugins/ui/DESIGN.md
> +Add a callback for when a cell is pressed. Only valid if the selection mode is `"CELL"`.
I don't think the selection mode should restrict these methods. Even with selection mode `"CELL"`, you may want to retrieve the whole row when a row is pressed.

2024-02-08 20:26 UTC, jnumainville commented
@dsmmcken any further thoughts on props vs functions?
Bender and I were thinking that it should all be functions. 
It's definitely a bit odd in how it behaves compared to other components, but it mirrors what is already done with table styling, which I think is more important.

2024-02-08 22:46 UTC, dsmmcken commented
> mirrors what is already done with table styling?

What do you mean by that?

My opinion is:
1. Anything that is a prop on spectrum components should be a prop. (ie Density is a spectrum prop, we shouldn't break that pattern).
2. Anything that only accepts one parameter should just be a prop, especially if it's a Boolean. The only reason we have so many methods here is because things like data_bars needs a million args.

2024-02-08 23:12 UTC, jnumainville commented
like`format_columns` - it returns a new table

2024-02-09 21:04 UTC, jnumainville commented
Decision is single variable functions should be props instead
if there is desire, individual props could be added as functions easily in the future

2024-02-09 21:24 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +| `mode`         | `SelectionMode`  | The selection mode to use. Must be one of `"ROW"`, `"COLUMN"`, or `"CELL"`:<li>`"ROW"` selects the entire row of the cell you click on.</li><li>`"COLUMN"` select
https://react-spectrum.adobe.com/react-spectrum/TableView.html#selection

selection mode should be a prop, and it should be `single` or `multiple`, rather then the multi_select true/false to match spectrum behaviour (so it matches our list view component once that exists).

We will need to rename what you labeled selection_mode to something else for row/column/cell, and since it would now also be a single option, it could also be moved to a prop.

`selection_type`? I don't know.


It needs to fit in with:
`selection_style` and `selection_mode`

2024-02-09 21:25 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +Specify the style that is used to show that data is selected. This can by `"HIGHLIGHT"`, `"CHECKBOX"`, a combination of those, or `"DEFAULT"` to use the system default.
Good. I see this on spectrum table as well with the same props. 👍

2024-02-09 21:30 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +| `callback` | `Callable[[CellIndex, Any], None]` | The callback function to run when a column is clicked. The first parameter is the column name, and the second is the column data, which is a list o
what's risky about this is tables tend to be tall not wide, so what would it return? It would only have the viewport of the current column on the client? Is that useful? The entire column, that is infeasible on a billion row table?

on_row makes sense in that you can get specific columns by name, where on_column isn't really equivelent.

2024-02-12 17:09 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `callback` | `Callable[[CellIndex, Any], None]` | The callback function to run when a column is clicked. The first parameter is the column name, and the second is the column data, which is a list o
I see this as similar to the `use_column_data` hook. I think what we need to emphasize here is filtering first before creating a `ui.table`
We could have a separate event `on_column_viewport_press`. I think that's handy if someone desired linking data in the viewport to other components on click, like clicking a column leads to a chart displaying the data for that column.
side not, the type here is incorrect and I need to modify it to match `on_column_double_press`
well, it is also moving to a prop anyways

2024-02-13 18:53 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +| `callback` | `Callable[[CellIndex, Any], None]` | The callback function to run when a column is clicked. The first parameter is the column name, and the second is the column data, which is a list o
I disagree with the utility of getting the data in that case.

I do see value in knowing which column was pressed though. Maybe on_column_press returns just the column name. Then the server can use the column data server side if it needs it.

row_press we want the row data at the time it was pressed so it makes sense to get that from the client. Where as columns won't have much column data in the client side state beyond the viewport.

2024-02-13 19:25 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `callback` | `Callable[[CellIndex, Any], None]` | The callback function to run when a column is clicked. The first parameter is the column name, and the second is the column data, which is a list o
only the column name is a good idea

2024-02-13 19:47 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `mode`         | `SelectionMode`  | The selection mode to use. Must be one of `"ROW"`, `"COLUMN"`, or `"CELL"`:<li>`"ROW"` selects the entire row of the cell you click on.</li><li>`"COLUMN"` select
modified to `selection_area`

2024-02-13 19:56 UTC, jnumainville commented
I've moved every single argument as well as others that decomposed easily (specifically `selected`) into props

Honestly, I think all of the methods could be refactored into props. `data_bars` is one of the more complicated ones but I don't think it would be that much more complicated as a dictionary of column name to attributes that's passed in instead. That's what many of these more complicated methods are going to become under the hood anyways. 

Others like `format` for example could easily be a dictionary prop. And others like `context_menu` could just be two different props. But, I won't do these unless we want to go full on props and step away from the immutable fluent model completely or convert a few others to props, either way.

2024-02-13 20:02 UTC, dsmmcken commented
Looking good.

I know `can_search` was an existing layout hint, but we should lean into the feature disabling/enabling thing for ui table. We've had asks like this before.

My proposal. Remove `can_search` as a prop and backlog it. Add a backlog ticket to flesh this out in the future as its own method with a million options.

Something like:
```
ui.table(...).permissions(
  search=false,
  filter=false,
  rollup=false,
  ...
  sidebar_menu 
  sort
  copy
  download
  re-order
  etc.
)
```

Not sure what exactly to call it. Permissions? features? disable?

2024-02-13 21:02 UTC, jnumainville commented
I think that's a good idea
Maybe `allowed` if that's not too broad 
I like `permissions` although not with bool options, maybe with sets so you don't have to type all the bools out? although it has it's own downsides
```
ui.table(...).permissions(allowed={'search'}, not_allowed={'filter', 'rollup'})
```
maybe with enums so it more closely resembles other access control
Although I can save further syntax discussion for the ticket

2024-02-14 19:01 UTC, dsmmcken approved these changes
No further comments.

2024-02-16 20:00 UTC, mofojed approved these changes

2024-02-16 20:02 UTC, merged