Add cocogitto/bump.sh to perform releases
deephaven/deephaven-plugins pull request #206
Opened 2024-01-13 00:00 UTC by JamesXNelson

2024-01-16 16:58 UTC, mofojed requested changes
I tried running this bump.sh script on Mac, and it doesn't seem to work. The first time I ran it, it asked to install Cocogitto (good). I installed, then I ran again and it just shows a screen:

<img width="358" alt="image" src="https://github.com/deephaven/deephaven-plugins/assets/4505624/747d206d-503d-47ed-b9fb-b728a4d2bd5d">

I then don't know what to press? I tried press Enter, does nothing; I hit "Q" and then I just get the following output:

<img width="723" alt="image" src="https://github.com/deephaven/deephaven-plugins/assets/4505624/d19388cb-5a58-4117-bc5b-b96da021dc4a">

2024-01-18 02:27 UTC, mofojed commented on cog.toml
> +dashboard-object-viewer = { path = "plugins/dashboard-object-viewer" }
I think we'll also want to set `public_api=false`: https://docs.cocogitto.io/config/#public-api

2024-01-18 21:07 UTC, JamesXNelson commented on cog.toml
> +generate_mono_repository_global_tag = true
the framework of this file was generated "for free" when I ran `cog init`.  Their documentation appears to lag the implementation a little, as I noticed a couple tags that didn't line up.

2024-01-18 21:07 UTC, JamesXNelson commented on cog.toml
> +skip_ci = "[skip ci]"
it was a template file, to help new users figure out how it works. I can just delete this if you prefer to keep things minimal.

2024-01-18 21:07 UTC, JamesXNelson commented on cog.toml
> +dashboard-object-viewer = { path = "plugins/dashboard-object-viewer" }
sure. afaict, the difference is that if we leave them all public_api, then each bump of any plugin will also bump the main version along with it.  It's extra tags that are effectively noise though, so if you want it false, just say so and I'll make them all false.

2024-01-18 21:07 UTC, JamesXNelson commented on releases/README.md
> +You have to un-gitignore this location of git add --force to update this readme.
one less `mkdirs`.  If you prefer it w/o the extra readme explaining what the directory is for, that's fine.  I figured this would be helpful if after running, it's noticed that a bunch of "random" files showed up.

Now that I've done a release and determined that the source zip/tar are created "for free", though, the only thing worth writing here is the changelog file... and if we figure out how to do it, artifacts downloaded after running the main release job in ci to produce final artifacts.

2024-01-18 21:08 UTC, JamesXNelson commented on bump.sh
> +# This script is designed to automate the version bump + github release process.
hm.  want me to move the scripts I'm making to a directory?  perhaps this would be better as `tools/release.sh`.  The other script I'm working on now is `update_version.sh`, to handle updating the various file locations w/ the new tag.

2024-01-18 22:18 UTC, mofojed commented on cog.toml
> +dashboard-object-viewer = { path = "plugins/dashboard-object-viewer" }
The thing is there is no "main" version to be bumped - all these plugins are to be independently versioned.

2024-01-19 09:45 UTC, JamesXNelson commented on cog.toml
> +dashboard-object-viewer = { path = "plugins/dashboard-object-viewer" }
set them all to false

2024-01-19 09:48 UTC, JamesXNelson commented on cog.toml
> +generate_mono_repository_global_tag = true
I changed it to false regardless, since we don't want a global version tag.

2024-01-19 09:49 UTC, JamesXNelson commented on cog.toml
> +skip_ci = "[skip ci]"
left a comment about it.

2024-01-19 09:49 UTC, JamesXNelson commented on releases/README.md
> +You have to un-gitignore this location of git add --force to update this readme.
deleted the readme and gitignored the whole thing.

2024-01-19 09:50 UTC, JamesXNelson commented
> I tried running this bump.sh script on Mac, and it doesn't seem to work. The first time I ran it, it asked to install Cocogitto (good). I installed, then I ran again and it just shows a screen:

Try again w/ the latest.  If you set your git remote `origin` to your fork, you can safely push test releases there.

2024-01-19 15:06 UTC, mofojed requested changes
Looks like it's close! Getting an error on mac with the sed step:
```
(.venv) ➜  deephaven-plugins git:(main) ./tools/release.sh -d ui            
+ shift
+ ((  1 > 0  ))
+ case "$1" in
+ '[' -n '' ']'
+ grep -q ui
+ package=ui
+ shift
+ ((  0 > 0  ))
+ '[' -z ui ']'
+ grep -q plugins/ui /Users/bender/dev/deephaven/oss/deephaven-plugins/cog.toml
bender   -  2024-01-19 10:06:04  |--- Releasing package 'ui'
+ cd /Users/bender/dev/deephaven/oss/deephaven-plugins
+ cog bump --package ui --auto
        Found bug fix commit 0533cd
[pre-bump-ui]
[echo Updating ui to version 0.1.1]
Updating ui to version 0.1.1

[../../tools/update_version.sh ui 0.1.1]
sed: 1: "/Users/bender/dev/deeph ...": undefined label 'ender/dev/deephaven/oss/deephaven-plugins/plugins/ui/src/deephaven/ui/__init__.py'
Error: prehook run `../../tools/update_version.sh ui 0.1.1` failed
        All changes made during hook runs have been stashed on `cog_bump_ui-v0.1.1`
        you can run `git stash apply stash@0` to restore these changes.
```

2024-01-19 15:16 UTC, mofojed requested changes

2024-01-19 15:16 UTC, mofojed commented on tools/update_version.sh
> +            update_file ui/src/deephaven/ui/__init__.py '__version__ = "' '"' "$extra"
I added a ticket for harmonizing the version info: https://github.com/deephaven/deephaven-plugins/issues/212

I know I also said not to worry about JS packages here ... but it looks like it would be very easy to add them as well (even though we expect them to only be published in the short term), e.g.
```suggestion
            update_file ui/src/deephaven/ui/src/js/package.json '"version": "' '",'
            update_file ui/src/deephaven/ui/__init__.py '__version__ = "' '"' "$extra"
```

2024-01-19 18:43 UTC, JamesXNelson commented on tools/update_version.sh
> +        -h) usage ; exit 0 ;;
It's in the bash docs.
 https://www.gnu.org/software/bash/manual/bash.html#index-case
  
 chances are likely that it wasn't added until bash 4, so not appearing on mac's default bash 3.
 sigh, so annoying to standardize on something 20 years old, but licensing isn't a problem I can fix.

2024-01-19 18:48 UTC, JamesXNelson commented on cog.toml
> +    "../../tools/validate.sh",
`pre_package_bump_hooks` is still part of pre-bump.  I simply removed the `rm`, since the part of code that creates that file uses `> GITHUB_CHANGELOG.md`, which will just overwrite it as needed.

2024-01-19 18:56 UTC, JamesXNelson commented on tools/update_version.sh
> +while (( $# > 0 )); do
ya, bash can be gross like that.

in this case, the amount of code I can safely extract amounts to about 10 lines.  I think it's better to have a complete, self-contained script, even if that script is a few lines longer. I would find it more annoying to have to open and read another sourced script just to know "where things came from".

2024-01-19 19:03 UTC, mofojed commented on tools/update_version.sh
> +while (( $# > 0 )); do
Sounds good

2024-01-19 19:10 UTC, mofojed commented on cog.toml
> +    "../../tools/validate.sh",
I think there's still something up here, the `CHANGELOG.md` never gets committed when I run the release action:
```
(.venv) ➜  deephaven-plugins git:(main) ./tools/release.sh -d ui  
+ shift
+ ((  1 > 0  ))
+ case "$1" in
+ '[' -n '' ']'
+ grep -q ui
+ package=ui
+ shift
+ ((  0 > 0  ))
+ '[' -z ui ']'
+ grep -q plugins/ui /Users/bender/dev/deephaven/oss/deephaven-plugins/cog.toml
bender   -  2024-01-19 14:09:37  |--- Releasing package 'ui'
+ cd /Users/bender/dev/deephaven/oss/deephaven-plugins
+ cog bump --package ui --auto
        Found bug fix commit 20cfbf
[pre-bump-ui]
[echo Updating ui to version 0.1.1]
Updating ui to version 0.1.1

[rm -f GITHUB_CHANGELOG.md]

[../../tools/validate.sh]
github.com
  ✓ Logged in to github.com account mofojed (keyring)
  - Active account: true
  - Git operations protocol: ssh
  - Token: gho_************************************
  - Token scopes: 'admin:public_key', 'gist', 'read:org', 'repo'

bender   -  2024-01-19 14:09:38  |--- Listing previous release to ensure gh is setup correctly:
no releases found

bender   -  2024-01-19 14:09:38  |--- [ERROR] Detected uncommitted files via git status: 
?? CHANGELOG.md
bender   -  2024-01-19 14:09:38  |--- [ERROR] Releases can only be performed with a clean git status 
bender   -  2024-01-19 14:09:38  |--- [ERROR] You must commit/stash your changes, or `git reset --hard` to erase them 
Error: prehook run `../../tools/validate.sh` failed
        All changes made during hook runs have been stashed on `cog_bump_ui-v0.1.1`
        you can run `git stash apply stash@0` to restore these changes.
```

2024-01-19 19:11 UTC, mofojed requested changes

2024-01-19 19:11 UTC, mofojed commented on tools/validate.sh
Need to `chmod +x` this file

2024-01-19 21:12 UTC, mofojed requested changes
Even with me fixing the two issues below, I'm still getting an issue when running release where it complains about the CHANGELOG:
```
(.venv) ➜  deephaven-plugins git:(main) ./tools/release.sh -d ui  
+ shift
+ ((  1 > 0  ))
+ case "$1" in
+ '[' -n '' ']'
+ grep -qE '^ui$'
+ package=ui
+ shift
+ ((  0 > 0  ))
+ '[' -z ui ']'
+ grep -q plugins/ui /Users/bender/dev/deephaven/oss/deephaven-plugins/cog.toml
bender   -  2024-01-19 16:08:53  |--- Releasing package 'ui'
+ cd /Users/bender/dev/deephaven/oss/deephaven-plugins
+ cog bump --package ui --auto
  Skipping irrelevant commits:
    - chore: 1

        Found bug fix commit 221221
[pre-bump-ui]
[echo Updating ui to version 0.1.1]
Updating ui to version 0.1.1

[../../tools/validate.sh]
github.com
  ✓ Logged in to github.com account mofojed (keyring)
  - Active account: true
  - Git operations protocol: ssh
  - Token: gho_************************************
  - Token scopes: 'admin:public_key', 'gist', 'read:org', 'repo'

bender   -  2024-01-19 16:08:54  |--- Listing previous release to ensure gh is setup correctly:
no releases found

bender   -  2024-01-19 16:08:54  |--- [ERROR] Detected uncommitted files via git status: 
?? CHANGELOG.md
bender   -  2024-01-19 16:08:54  |--- [ERROR] Releases can only be performed with a clean git status 
bender   -  2024-01-19 16:08:54  |--- [ERROR] You must commit/stash your changes, or `git reset --hard` to erase them 
Error: prehook run `../../tools/validate.sh` failed
        All changes made during hook runs have been stashed on `cog_bump_ui-v0.1.1`
        you can run `git stash apply stash@0` to restore these changes.
```

2024-01-19 21:12 UTC, mofojed commented on tools/update_version.sh
> +all_plugins="$(cd "$ROOT_DIR/plugins" ; find ./ -mindepth 1 -maxdepth 1 -type d | sed  's|./||g')"
Now that you have exact matching, this is failing because the plugin names all have `/` prefixed, e.g.
```
(.venv) ➜  deephaven-plugins git:(main) ./tools/release.sh -d ui
+ shift
+ ((  1 > 0  ))
+ case "$1" in
+ '[' -n '' ']'
+ grep -qE '^ui$'
bender   -  2024-01-19 16:12:11  |--- [ERROR] Illegal argument ui. Expected one of:
/ui
/table-example
/plotly
/dashboard-object-viewer
/json
/plotly-express
/auth-keycloak
/matplotlib 
+ exit 93
```

2024-01-20 00:22 UTC, mofojed requested changes
Great work! One minor change to the TODO (need to have an associated ticket for TODOs).

Also for posterity I don't know why I need to press Q when doing a release to advance. Seems odd, and I'll probably dig into that at some point.

2024-01-20 00:22 UTC, mofojed commented on cog.toml
> +authors = []
Slightly annoying it doesn't figure this out automatically, but no biggy. Added a ticket to update this: https://github.com/deephaven/deephaven-plugins/issues/218
```suggestion
# TODO (#218): commit everyone's handle
authors = []
```

2024-01-20 00:35 UTC, JamesXNelson commented
Fixes #218

2024-01-20 00:35 UTC, JamesXNelson commented on cog.toml
> +authors = []
ah, per slack, I went ahead and just added everyone's usernames, and added a `Fixes #218`

2024-01-20 00:39 UTC, mofojed approved these changes

2024-01-20 00:51 UTC, merged