fix: Initial set of type fixes
deephaven/deephaven-plugins pull request #217
Opened 2024-01-19 23:09 UTC by jnumainville

Adds a first set of type fixes for deephaven.ui and plotly-express
Most of the fixes are of the following:
`| None` added to parameters that can take `None`
`any` to `Any` and `callable` to `Callable`
Added necessary args to `Generator` and `dict` types
Associated documentation

2024-01-25 14:50 UTC, mofojed requested changes
Don't put the types in the docstrings, as we have them already in the code.

Need to resolve the issue on <3.10

2024-01-25 14:50 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
We have the type in the code, we should _not_ be putting it in the docstring as well. From Google's styleguide: https://google.github.io/styleguide/pyguide.html#doc-function-args
> The description should include required type(s) **if the code does not contain a corresponding type annotation**.

That will apply in a lot of areas in plotly-express

2024-01-25 14:50 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +            revision: int | None: The revision to send
```suggestion
            figure: The figure to send
            revision: The revision to send
```

2024-01-25 15:31 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
I don't love that in the case of the user facing functions (`scatter`, `line`, etc.) because they have lots of args so you'll have to jump back and forth a lot between the type hints and the doc string

2024-01-25 15:44 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +            revision: int | None: The revision to send
Mainly was the backslash I wanted removed here, types can be removed when we resolve the other discussion.

2024-01-25 15:46 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
Ehhhh but then we need to make sure the docstrings and typings are in sync, we're only enforcing the typings so we're bound to make mistakes there.
Also when you enter a parameter, it puts the docstring at the top of the parameters list and bolds the parameter and type above, so you shouldn't have to scroll too far:

![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/6117c278-2ef0-4184-a039-1f31296ae952)
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/d434d849-bd25-4d91-9e7d-350b67890dcb)

Aside from that - I am trying to stick to the Google styleguide as it is defined. Otherwise we need to define our own styleguide, which we could base off Google's but then would need to our modifications to their guide.

Unsure how it looks in PyCharm... 
Perhaps something to raise in #dev-python as well, since they also list both types in the parameters and in the docstrings (though they are including the types differently in the docstrings).

2024-01-25 15:56 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
I'm definitely generally for removing the args in the docstring as maintenance is much easier. 
I am more wondering about a small exception to high argument, user-facing functions, theoretically just the plotly express functions as I don't foresee having massive functions everywhere. Even a small scroll is quite annoying when you're dealing with several types.

2024-01-25 16:17 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
Heh, I wanted to check what plotly express does... they dynamically create the docstrings: https://github.com/plotly/plotly.py/blob/0b0cc229d2e2642bb6ecfc762665204bba0e9453/packages/python/plotly/plotly/express/_chart_types.py#L69
I haven't seen that before, that's kind of neat. So they don't need to re-define docs for common parameters. Though it raises other questions, like how you keep the types in sync with the docstrings... but still neat that you can dynamically add docstrings to functions.

For exceptions - when do you draw the line on "high argument" functions? I'd be willing to have an exception for something well defined, e.g. all of plotly-express... but in general I'd just stick to the google styleguide.

2024-01-25 16:35 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
That's a very interesting way to do it although it makes it a bit harder if you're looking at the code directly. Does reduce maintenance a ton though. The amount of copy-pasting or copilot generation I've done on common parameters...

Even within plotly-express I'd only want the user facing functions to have this, so I think it should be a case by case basis, with a legitimate ease-of-use argument because it does make maintenance harder. I'm mostly concerned about people creating charts, especially if they only generate a chart once in a while and I want that to be as frictionless as possible. 

We could have a comment at the top of the file to mark these exemptions
> #The functions in this file are exempt from the styleguide rule that types should not be in the description if there is a type annotation.

or, for cases where  only some functions need this exemption
> #The functions scatter, scatter_3d, other_scatters in this file are exempt from the styleguide rule that types should not be in the description if there is a type annotation.

2024-01-25 16:38 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/__init__.py
> +          obj: Any: The object to check
Sounds good

2024-01-26 15:22 UTC, mofojed requested changes
Need to fix 3.8 still, and one minor typo to fix

2024-01-26 15:22 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/generate.py
> +      table: TThe table to pull columns from
```suggestion
      table: The table to pull columns from
```

2024-01-26 17:30 UTC, jnumainville commented
The 3.8 and 3.9 failures are due to a core change. Opening an issue

2024-01-29 13:56 UTC, mofojed approved these changes

2024-02-09 20:35 UTC, mofojed approved these changes

2024-02-09 20:36 UTC, merged