fix: Use ObjectFetcher to retrieve objects
deephaven/deephaven-plugins pull request #234
Opened 2024-01-29 20:03 UTC by mofojed

- In Enterprise environment, there may be multiple connections. We should not be accessing the connection directly from the plugin for fetching objects, instead use the ObjectFetcher registered by the app
- Pass in the object metadata to fetch the object
- Needs https://github.com/deephaven/web-client-ui/pull/1753

2024-01-29 22:21 UTC, mattrunyon requested changes

2024-01-29 22:21 UTC, mattrunyon commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +        };
Feels like `metadata` should just include the `widget` info. Otherwise we're going to see this everywhere we want to fetch an object like this

Looks like in community for normal tables at least we store `id`, `name`, and `type`. I think this would actually error if you tried to fetch because if you specify `id` and `name` the API throws

2024-01-29 22:21 UTC, mattrunyon commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +        const metadata = pluginData as unknown as ObjectMetadata;
`pluginData` already has a type defined here. So if this cast is needed then something is off

2024-02-01 16:09 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +        };
Yea I added `getVariableDescriptor` to translate from a `VariableDefinition` to a descriptor, then `sanitizeVariableDescriptor` to ensure we don't try and fetch something with both a name and an id.
The definition object itself contains both the `name` and `id`, we use the `name` to display a friendly panel name.

2024-02-05 17:14 UTC, mattrunyon requested changes

2024-02-05 17:51 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  widget: WidgetDescriptor;
Yea the only reason I kept them separate is the `@deephaven/dashboard` package has no dependencies on the JS API, and therefore cannot reference `VariableDescriptor`. And I think I'm alright with that - there's nothing saying we can't use dashboard with a different backend entirely... that being said, to smooth it out I'd probably argue that the `WidgetDescriptor` should require `type` and `id`, and then `name` should just be a friendly display name. Then the `VariableDescriptor` maps the `id` to the `id` or `name` field depending on the type of `WidgetDescriptor` (e.g. `v: VariableDescriptor = { name: 'fiz', type: 'foo' }` => `w: WidgetDescriptor = { name: 'fiz', id: 'fiz', type: 'foo', variableType: 'name' }`). Kludginess of having a `VariableDescriptor` defined and requires exactly one of `id` or `name` is already odd though and I didn't feel like adding another layer of indirection at this time made sense.

2024-02-05 17:53 UTC, mattrunyon commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  widget: WidgetDescriptor;
Ya that's fair. I'll put it back in on my jsapi-types branch

2024-02-05 17:55 UTC, mattrunyon approved these changes

2024-02-05 17:56 UTC, merged