feat: Serialize press events for press event callbacks
deephaven/deephaven-plugins pull request #236
Opened 2024-01-29 22:37 UTC by mofojed

- Serialize press events so they get passed back to the server (Fixes #76)
- Add pydocs for `action_button` (Fixes #235)

BREAKING CHANGE: All button `on_press` handlers now must take a positional argument for the event.

2024-01-30 17:17 UTC, jnumainville requested changes

2024-01-30 17:17 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/spectrum/action_button.py
> +    UNSAFE_className: str | None = None,
This is a little funky. I'd prefer using `UNSAFE_class_name` and slicing off the `UNSAFE_` and converting the rest from snake case to camel case instead of skipping them.

2024-01-30 21:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/action_button.py
> +    UNSAFE_className: str | None = None,
Made this change and added some unit tests around that

2024-01-31 20:46 UTC, jnumainville approved these changes

2024-02-01 18:23 UTC, merged