Version bump + fixes
deephaven/deephaven-plugins pull request #243
Opened 2024-01-30 21:31 UTC by bmingles

- DHC version bump
- Fixed infinite loading spinner
 
fixes #241

2024-02-05 22:25 UTC, mattrunyon requested changes

2024-02-05 22:25 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +
We should remove the id from this set in `removeTable`. Just in case we get into some weird situation where the server tells us about a table and then immediately tells us to forget it and we don't end up with data for some reason. I think it's highly unlikely, but just in case

2024-02-05 22:25 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    }
This might cause issues with plot_by if it's checked every time new data arrives. We could have a scenario where tables are added and removed almost every tick like the following. The layered plot has new tables added every second (from the UI perspective) because of the partitions changing.

Might need to add something to check if we ever finished loading or only track the initial tables for either data or removal and then after that just consider any state as already loaded and fire the updates on every data received.

```python
import deephaven.plot.express as dx
from deephaven import time_table
import random 

sourceh = time_table("PT1S").update(formulas=[
    "X = (int)random.gauss(20, 5)", 
    "Y = (int)random.gauss(20, 5)", 
    "Z = (float)random.gauss(30, 3)",
    "l1 = i % 20",
    "l2 = i % 30",
    ]).tail(10)

fig1 = dx.scatter(sourceh, x="Z", y="Y",
    by="l1",
    color_discrete_sequence=["lemonchiffon"]
)

fig2 = dx.scatter(sourceh, x="Z", y="Y",
    by="l2",
    color_discrete_sequence=["salmon"]
)

layered = dx.layer(fig1, fig2)
```

2024-02-06 16:01 UTC, bmingles commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    }
@mattrunyon  I don't see this example causing any trouble when I run it. Is there some specific problem you are expecting to see?

2024-02-06 20:18 UTC, bmingles commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +
Good catch. Fixed

2024-02-06 22:17 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    }
Possibly that we skip rendering an update after the load is finished because we've added another table but haven't received data from it yet.

This also adds more overhead from adding a `fireLoadFinished` to each update. It should effectively be a no-op because at the end of the day it just calls `setState` w/ an equivalent state, but no need for the overhead

2024-02-07 19:46 UTC, mattrunyon approved these changes

2024-02-07 22:08 UTC, mattrunyon approved these changes

2024-02-07 22:56 UTC, mattrunyon approved these changes

2024-02-07 22:56 UTC, merged