feat: Widget re-hydration
deephaven/deephaven-plugins pull request #288
Opened 2024-02-15 20:57 UTC by mofojed

- Reload widgets on dashboard reload
- Needs my draft PR that stores default dashboard data with the workspace for this to work (https://github.com/deephaven/web-client-ui/pull/1810)
- Opened deephaven.ui widgets from the examples, then refreshed the page. Widgets re-opened in the same positions/panels they were in. Widget internal state (such as input in a text field, or filter set on a table) and ui.dashboards do _not_ re-hydrate correctly yet
  - ui.dashboard will do after dashboard storage is properly done, but that shouldn't be needed for this to work in Enterprise
- Fixes #160 
- Fixes #161  
- Fixes #162

2024-02-22 01:51 UTC, mattrunyon requested changes

2024-02-22 01:51 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +      initializeData();
Why call `initializeData` in the `handleClose` method? Seems odd. And based on `initilizeData` like it would usually/always be a no-op when called here?

2024-02-22 01:51 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  }, [documentData]);
You could just do this in a `useState` initializer function. Not sure if there's another reason you need a ref or callback here

2024-02-22 01:51 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +      documentData.current.panelIds = newPanelIds;
This doesn't need to be a new array since you're using a ref to hold it. Or if it does, then the ref isn't the right thing since changes to the ref won't trigger updates to the component

2024-02-22 16:19 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +  ) as unknown as [DashboardPluginData, (data: DashboardPluginData) => void];
Yea I'll add that to my web-client-ui PR: https://github.com/deephaven/web-client-ui/pull/1810

But don't want to hold this up for a new publish.

2024-02-22 18:26 UTC, mofojed commented on plugins/ui/src/js/src/layout/PortalPanelEvent.ts
> +  };
Yea, I'll extract it out to show you what that's like - the only downside is the docs don't make it through. But it does cut down a lot on the boilerplate, and these are pretty straightforward events. Could argue either way.

2024-02-22 18:51 UTC, mofojed commented on plugins/ui/src/js/src/layout/ReactPanelManager.ts
> +  getPanelId: () => string;
Yea from this perspective it's just getting the panel ID. I'll add more comments around the actual panel ID generation instead about how it's re-using/generating panel IDs, because it's clearer there.

2024-02-22 18:54 UTC, mofojed commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +  );
Mañana

2024-02-22 19:00 UTC, mofojed commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +  const panelId = useMemo(() => getPanelId(), [getPanelId]);
I refactored this into a separate hook, `useReactPanel` instead.

2024-02-22 19:02 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  data = {},
Doesn't appear to be, `EMPTY_OBJECT` is defined a few times in `web-client-ui` but never exported.

2024-02-22 19:03 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +      initializeData();
Mistake I think

2024-02-22 19:13 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +      documentData.current.panelIds = newPanelIds;
I modified the `WidgetData` type to have a `ReadonlyWidgetData` and `WidgetData` type to help with this.

2024-02-22 19:50 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +        return newWidgetMap;
Yea, I guess that brings into question where the debouncing for plugin data should be as well.
It would be nice if it was derived directly from the state... but if the `WidgetWrapper` changes, it triggers a reload in the `WidgetHandler`... which probably means that widget data should just be completely separate from the WidgetMap, and then I think everything kind of falls into place. I'll make those changes.

2024-02-22 19:58 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/PortalPanelEvent.ts
> +  };
What docs would need to pass through? I was talking about just the logic of the function. So a `listenForEvent(eventHub, event, handler)` method and then the individual event methods are all 1 line that just `return listenForEvent(eventHub, PORTAL_OPENED, handler)`

2024-02-22 20:43 UTC, mofojed commented on plugins/ui/src/js/src/layout/PortalPanelEvent.ts
> +  };
Oh. Yea that's cool too, I'll show you what I did as well taking it a step further with a `makeEventFunctions` function.

2024-02-23 17:57 UTC, mattrunyon requested changes

2024-02-23 17:57 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +  const element = portalManager.get(panelId);
Minor. Rename to `portal` so the variable name is more descriptive

2024-02-23 17:57 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +    function openIfNecessary() {
You could probably do this without an effect. You're already tracking and checking the the metadata doesn't match the previous metadata, so most of this could just be logic in the main block. Or pull the logic of opening up above the component and then the component just does something like

```ts
if (isPanelOpenRef.current === false || openedMetadataRef.current !== metadata) {
  openIfNecessary(parent, metadata, panelId, title, onOpen);
  isPanelOpenRef.current = true;
  openedMetadataRef.current = metadata;
}
```

Just a thought

2024-02-23 17:57 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanelManager.ts
> +  onClose: () => void;
Maybe "Must be called by the panel when it is opened/closed"? Since it's the panel's responsibility

2024-02-23 17:57 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  initialData?: ReadonlyWidgetData;
Feels like the 2nd sentence in this comment is off. Use the data from `onDataChange` doesn't really make sense to me since this is supposed to call `onDataChange` when the data changes

2024-02-23 17:57 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  );
This deep copy is fine, but just wanted to note `structuredClone` is a new API that also does deep copy. I haven't looked into it much to know its quirks and limitations compared to the tried and true stringify/parse

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

2024-02-23 17:57 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +    // Note that if the order of panels changes, the worst case scenario is that panels appear in the wrong location in the layout.
Could the panel somehow end up with the wrong data? Like let's say you have `t1` and `t2` with some filters and then their order get flipped. Would `t1` now have `t2` filters trying to be applied?

2024-02-26 19:55 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  initialData?: ReadonlyWidgetData;
Yea I meant an `onDataChange` from a previous rendering of the widget.

2024-02-26 20:01 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  );
Yes I tried `structuredClone` first, but was getting issues in Jest tests then so just reverted it. I'll add the fix so that `structuredClone` works in jest.

2024-02-26 20:05 UTC, mofojed commented on plugins/ui/src/js/src/layout/PortalPanelEvent.ts
> +} = makeEventFunctions<PortalOpenedPayload>(PORTAL_OPENED);
That doesn't seem to work for me? I've tried inline comments as well as many other ways but can't seem to do it.

2024-02-26 20:13 UTC, mofojed commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +    function openIfNecessary() {
Would need to pass a `isMetadataChanged` flag into the `openIfNecessary` method as well, not really seeing much improvement there.

2024-02-26 20:27 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +    // Note that if the order of panels changes, the worst case scenario is that panels appear in the wrong location in the layout.
The panel could end up in the wrong place. We should allow a `key` (or `id`) to be passed in to `ui.panel` to allow for being more explicit about the key of your panel. I don't think that should be part of this ticket though.

2024-02-26 23:52 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +    function openIfNecessary() {
Hmm maybe some `handleMetadataChange` or something. Idk just felt like it could maybe be cleaner, but can also clean it up another time. Why/how does metadata change effect the panel? It's metadata of the top level widget, so not sure why the panel cares about it other than a default title (which won't react to changes)

Looking at the refs, the initial values depend on `portal`, but this effect that updates those refs does not depend on `portal`. Also, `title` change runs this effect, but does nothing unless the metadata also changes

2024-02-28 16:49 UTC, mattrunyon approved these changes

2024-02-28 19:20 UTC, mofojed commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +    function openIfNecessary() {
For posterity - we decided to clean this up in a follow up PR if needed. A recap from a bit of our discussion:
- The metadata changing can occur when you click the same button for an object multiple times in a row in the console. In that case it should "re-open" the object, and replace the existing panel.
- Portal is set when the panel is added to golden layout, which could occur _before_ the `ReactPanel` gets created on rehydration (as the golden-layout is created first). Otherwise this function triggers an `.openComponent` which will eventually set the portal.

2024-02-28 19:24 UTC, merged