fix: Type fixes and require pyright
deephaven/deephaven-plugins pull request #302
Opened 2024-02-20 19:06 UTC by jnumainville

Fixed remaining type issues and makes pyright a mandatory check via the pre-commit.

2024-02-21 16:48 UTC, mofojed requested changes

2024-02-21 16:48 UTC, mofojed commented on .pre-commit-config.yaml
> +  - repo: https://github.com/RobertCraigie/pyright-python
I don't like this as a pre-commit hook, or perhaps it's not working correctly or I'm misunderstanding it. I'm making a change that purposefully introduces (what I thought) was a pyright error, but it's letting me commit and says it "Passed":
```
diff --git a/plugins/ui/src/deephaven/ui/renderer/RenderedNode.py b/plugins/ui/src/deephaven/ui/renderer/RenderedNode.py
index db9b715..501fef2 100644
--- a/plugins/ui/src/deephaven/ui/renderer/RenderedNode.py
+++ b/plugins/ui/src/deephaven/ui/renderer/RenderedNode.py
@@ -11,7 +11,7 @@ class RenderedNode:
     _name: str
     _props: Optional[PropsType]
 
-    def __init__(self, name: str, props: Optional[PropsType] = None):
+    def __init__(self, name, props: Optional[PropsType] = None):
         """
         Stores the result of a rendered node
 
@@ -19,6 +19,7 @@ class RenderedNode:
             name: The name of the node.
             props: The props of the node.
         """
+        name.test()
         self._name = name
         self._props = props
```

Also - would this automatically fix the errors like black does? If not, how do I bypass it if I just want to commit my broken stuff to fix later (or for help from someone else)?

2024-02-21 16:56 UTC, jnumainville commented on .pre-commit-config.yaml
> +  - repo: https://github.com/RobertCraigie/pyright-python
Hmm, that doesn't induce an error with how it's currently set up, I think pyright is only catching if it is a wrong type, not a missing type. Let me look into forcing that.
This does not fix issues automatically. If you want to push something broken then you can commit bypass the pre-commit hook.
`git commit --no-verify`

2024-02-21 16:58 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +    pd_base_time = cast(pd.Timestamp, to_pd_timestamp(base_time))
Yes, originally I actually had the check instead but I figured casting was fine but I'll switch back to the check. I tried to use casting sparingly.

2024-02-21 17:22 UTC, jnumainville commented on .pre-commit-config.yaml
> +  - repo: https://github.com/RobertCraigie/pyright-python
I can't see a good way to do that in pyright, but I think this would be a good thing to add through ruff
ruff can do a lot include replace `black` as far as I understand but I think this could be a good place to start
https://docs.astral.sh/ruff/rules/missing-type-function-argument/

2024-02-21 20:34 UTC, jnumainville commented on .pre-commit-config.yaml
> +  - repo: https://github.com/RobertCraigie/pyright-python
I've added ruff, although in the interest of keeping this review terse I only added ANN001 and only for `ui` and `deephaven-express`. The rest can be done on a per-project and per-rule basis.

2024-02-22 15:27 UTC, mofojed requested changes

2024-02-22 15:48 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
> +            description=description,  # type: ignore # missing Optional type
Already filed at https://github.com/deephaven/deephaven-core/issues/5171

2024-02-22 17:09 UTC, jnumainville commented on .pre-commit-config.yaml
> +  - repo: https://github.com/RobertCraigie/pyright-python
Yes we'll still need pyright. Ruff doesn't do any type checking for correctness.

2024-02-22 18:37 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/DeephavenFigure.py
> +        if self._plotly_fig and (fig_json := self._plotly_fig.to_json()) is not None:
I don't use it much but when I do it's the perfect tool for the job

2024-02-22 18:37 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/PartitionManager.py
> +                partitioned_table = cast(Table, args["table"]).partition_by(
https://github.com/deephaven/deephaven-plugins/issues/307

2024-02-22 20:23 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_memo.py
>      """
any sequence should be fine I think

2024-02-22 20:23 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        return cast(StringSortDirection, direction)
yeah, good to keep in mind

2024-02-22 20:26 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +                cast(LivenessScope, self._top_level_scope).manage(wrapper.value)
I don't really like assertion statements since they can be disabled, but I've added a check

2024-02-22 20:27 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/_layer.py
> +    spec: dict[str, Any],
no, added a TypedDict

2024-02-23 14:07 UTC, mofojed approved these changes

2024-02-23 14:07 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/plots/_layer.py
> +class LayerSpecDict(TypedDict, total=False):
Nice

2024-02-23 15:28 UTC, merged