test: add e2e
deephaven/deephaven-plugins pull request #314
Opened 2024-02-23 19:26 UTC by wusteven815

2024-02-23 19:38 UTC, wusteven815 commented
## Caching Optimization Notes

- JS and Python packages are being reinstalled every action and can be cached
  - We can try caching Docker layers, but a few notes about that below
  - The bulk of the time is still spent on building the plugins
- Running `npm ci` on GitHub Actions is needed for Playwright, but that's the only dependency that needs to be installed
  - Could save roughly 500MB of cache

### Docker Layer Cache Notes

- We can use `docker buildx` to import and export cache, but this runs the `build` command instead of `compose up` (or `run`)
- Running the image right after in GHA (GitHub Actions will still cause a rebuild of the image
- The solution is to create a registry in the GHA, and then oull from it
  - Seems to take almost a minute to pull and start

```yaml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=min
          no-cache-filters: build
          tags: localhost:5000/deephaven-plugins/app:latest

      - name: Start Deephaven
        run: docker run --detach --publish 10000:10000 -v ./tests/app.d:/app.d --env "START_OPTS=-Xmx4g -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler -Ddeephaven.console.type=python -Ddeephaven.application.dir=./app.d" localhost:5000/deephaven-plugins/app:latest
```

2024-02-29 20:24 UTC, mofojed requested changes
We need to add instructions to the root README.md as well about how to run e2e tests, update snapshots, etc.

Also, if I run this and the tests fail, it seems to keep the report open, but I can't actually open it. I go to http://localhost:9323 but get a connection reset error - does this work for you? I haven't dug too much into it yet:
```
(.venv) ➜  deephaven-plugins git:(uncached-e2e-tests) ✗ curl http://localhost:9323
curl: (56) Recv failure: Connection reset by peer
```

2024-03-01 16:24 UTC, wusteven815 commented
> Also, if I run this and the tests fail, it seems to keep the report open, but I can't actually open it

Caused by the CI config, which doesn't serve an HTML report, being used in local Docker. Renamed to be `playwright-docker.config.ts` and added a check for `process.env.CI` in it.

2024-03-05 14:19 UTC, mofojed requested changes
Minor typo to fix up. Great work!

2024-03-05 14:19 UTC, mofojed commented on README.md
> +You should be able to pass arguments to these commands as if you were running Playwright via CLI directly. For example, to test only `table.spec.ts` you could run `npm run e2e:docker -- ./tests/matpl
```suggestion
You should be able to pass arguments to these commands as if you were running Playwright via CLI directly. For example, to test only `matplotlib.spec.ts` you could run `npm run e2e:docker -- ./tests/matplotlib.spec.ts`, or to test only `matplotlib.spec.ts` in Firefox, you could run `npm run e2e:docker -- --project firefox ./tests/matplotlib.spec.ts`. See [Playwright CLI](https://playwright.dev/docs/test-cli) for more details.
```

2024-03-06 18:21 UTC, mofojed approved these changes

2024-03-06 19:37 UTC, merged