feat: Export plotly-express as a dashboard plugin
deephaven/deephaven-plugins pull request #329
Opened 2024-02-28 17:26 UTC by vbabich

Tested with DHE V+ (1.20231218.167) Core 0.32.1
Closes #308

2024-02-28 20:07 UTC, mofojed requested changes

2024-02-28 20:07 UTC, mofojed commented on plugins/plotly-express/src/js/src/index.ts
> +export * from './DashboardPlugin.js';
I _think_ you could just add `DashboardPlugin` to `PlotlyExpressPlugin`, and then Enterprise should pick it up as a LegacyDashboardPlugin and load it like that.

Will need the `PlotlyExpressPlugin` type to extend `WidgetPlugin`, e.g.
```

export const PlotlyExpressPlugin: WidgetPlugin<Widget> & { DashboardPlugin: ... } = {
  name: '@deephaven/plotly-express',
  type: PluginType.WIDGET_PLUGIN,
  DashboardPlugin,
  supportedTypes: 'deephaven.plot.express.DeephavenFigure',
  component: PlotlyExpressChart,
  panelComponent: PlotlyExpressChartPanel,
  icon: vsGraph,
};
```

2024-02-28 21:03 UTC, mattrunyon commented
I think this will break plotly-express in DHC w/ dh.ui. We currently check if the plugin is the legacy format first when loading, so the legacy definition (named `DashboardPlugin` export) will override the preferred definition (default export of the plugin object)

2024-02-28 22:26 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/index.ts
> -export default PlotlyExpressPlugin;
The default export needs to stay so DHC can use the new plugin format still

The new format looks at the default export and uses the `type` field of the default to determine what kind of plugin it is. The old format used specifically named exports to differentiate what type of plugin it was

2024-02-29 21:28 UTC, vbabich commented
I added a named export for the legacy `DashboardPlugin` next to the `default` `WidgetPlugin`.
Updated DHE to prioritize legacy plugins until we implement `WidgetLoaderPlugin` in Enterprise.

2024-02-29 21:30 UTC, vbabich commented on plugins/plotly-express/src/js/src/index.ts
> +export * from './DashboardPlugin.js';
I just added `DashboardPlugin` as a named export next to the `default PlotlyExpressPlugin`, didn't have to extend the `WidgetPlugin`.

2024-03-04 18:43 UTC, mofojed requested changes

2024-03-04 18:43 UTC, mofojed commented on plugins/plotly-express/src/js/src/DashboardPlugin.tsx
> +            name,
Spread the whole widget descriptor here too, `...widget`

2024-03-04 19:16 UTC, vbabich commented on plugins/plotly-express/src/js/src/DashboardPlugin.tsx
> +            name,
Done. Should I mark this PR as a breaking change since the `widget` argument type has changed from `VariableDefinition` to `VariableDescriptor`?

2024-03-05 13:52 UTC, mofojed commented on plugins/plotly-express/src/js/src/DashboardPlugin.tsx
> +            name,
Yea - we should be sure to be emitting `VariableDescriptor` instead of `VariableDefinition`. I think I've already taken care of that on Enterprise though.

2024-03-05 13:56 UTC, mofojed approved these changes

2024-03-05 13:56 UTC, mofojed commented on plugins/plotly-express/src/js/src/DashboardPlugin.tsx
> +  const handlePanelOpen = useCallback(
Side note, we have a `useDashboardPanel` hook that should do what we're doing here, but it would require other changes as well (since it doesn't use `metadata` or `fetch` at all). No need to worry about it here.

2024-03-05 19:51 UTC, mattrunyon approved these changes
I think we'll actually want DHE to register both plugins. Otherwise plotly-express won't work in dh.ui in DHE

2024-03-05 19:55 UTC, vbabich commented
Why? What plugin type is needed for dh.ui in DHE?

2024-03-05 20:29 UTC, mattrunyon commented
dh.ui reads the plugin registry and looks for `WidgetPlugin`s to render widgets within panels. So if you have a dh.ui panel with a table and plotly-express plot, it needs both as `WidgetPlugin`s to render properly. Just the `DashboardPlugin` won't do anything since that's listening at the dashboard level for a plotly-express widget to be opened as a panel.

2024-03-05 20:36 UTC, vbabich commented
But it should work with just the `WidgetPlugin`, right? The plan is to phase out `DashboardPlugin` once we add support for `WidgetPlugin` in DHE.

2024-03-05 20:40 UTC, mattrunyon commented
Yes once we support `WidgetPlugin`s auto opening like in DHC, we'll only need the `WidgetPlugin`. I think we'll need both in the interim in DHE so that outside of dh.ui the `DashboardPlugin` will open the panel, but in dh.ui, the `WidgetPlugin` is needed so dh.ui knows how to render the widget

2024-03-05 20:41 UTC, merged