feat: Add utilities package
deephaven/deephaven-plugins pull request #331
Opened 2024-02-29 16:08 UTC by jnumainville

Adds a new utilities package. This can be used for cross-plugin functionality. This first version has functions that make it simpler to register js plugins.

Part of the work for #316 and #194

2024-02-29 17:04 UTC, jnumainville commented
I suppose some of these specific utilities could be in core or even deephaven-plugin, although I'm not sure of what benefit that would have. I like the idea of a cross-plugin utilities package in this repo sooner or later. `package_js` at least would be odd to have in core as it is used in `setup.py` for each plugin where js is bundled and it will need to be a build-system dependency.

2024-02-29 17:41 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +def package_js(js_dir: str, dest_dir: str) -> None:
IMO, this should not want or need this to be part of the runtime. It can be separated out into a build-time only dependency if we want to have it.

Something like:
```toml
[build-system]
requires = ["setuptools>=43.0.0", "wheel", "deephaven-js-packaging"]
```

2024-02-29 17:41 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +        if not os.path.exists("/usr/illumon/latest/bin"):
We should formalize this into a method and document. It may be useful in other contexts.

2024-02-29 17:41 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +            logger.warning(
I think we should prefer to re-raise in this case instead of logging?

2024-02-29 17:41 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +def attempt_registration(callback: Callback, js_plugin: JsPlugin) -> None:
Instead of a method, does it make sense to create a `DheSafeJsPluginWrapper` that encapsulates this logic?

2024-02-29 17:49 UTC, devinrsmith commented
> I wonder if these utilities should just be in deephaven-core.

Not deephaven-core; maybe deephaven-plugin. That said, I don't think I'm comfortable elevating this logic to that level yet. I think we could ultimately have a much better build-time plugin that enables the runtime to be very simply built. I think some of the complexity here still comes down to supporting development use cases.

2024-02-29 19:51 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +            logger.warning(
Ideally if this failed because the JS package was already registered it would be a warning as that could *possibly* be ok, but I'm sure there are plenty of other problematic errors that would be ignored. Do you know of any graceful way both could be handled?

2024-02-29 20:32 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +            logger.warning(
I guess I'm not sure exactly what is causing the double registration (not familiar enough w/ DHE setup). That said, I can't think of a community deployment where we might be OK with just logging a double registration as opposed to throwing the error.

2024-02-29 20:35 UTC, mofojed commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +            logger.warning(
Yea I think Devin's right, we can throw in the Community side. Enterprise we probably should log a debug message, users won't see it by default.
@devinrsmith is there a better way to detect an Enterprise env? Pretty sure installation could be in a different directory.

2024-02-29 20:49 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +            logger.warning(
The case I had in mind was if someone wanted a different version of the js then was stored in the wheel. But that is an edge development case so I am fine with the debug for enterprise and throw for community.

2024-02-29 21:16 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +def attempt_registration(callback: Callback, js_plugin: JsPlugin) -> None:
I think I'll make a callback wrapper - then we can also wrap (a passthrough for now) the python registration in case anything needs to be done there in the future.

2024-02-29 21:24 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +        if not os.path.exists("/usr/illumon/latest/bin"):
What is the agreed temporary solution until there is a better way to check?

2024-02-29 22:48 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +    return any("coreplus" in path or "dnd" in path for path in sys.path)
We should create and link a ticket for a better implementation.

2024-02-29 22:48 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +class DheSafeCallbackWrapper:
This should probably implement `Callback`?

2024-02-29 22:48 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +    def register(self, plugin: Plugin) -> None:
This should be typed `plugin: Union[Plugin, Type[Plugin]]`?

2024-02-29 22:48 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +            self._callback.register(plugin)
Why the bifurcation? Can everything go through the _register_js logic?

2024-02-29 22:48 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/__init__.py
> +from .dhe_safe_callback_wrapper import *
We should define appropriate `__all__` in utils / dhe_safe_callback_wrapper to make sure we only expose what is necessary.

2024-02-29 22:48 UTC, devinrsmith commented on plugins/packaging/src/deephaven/plugin/packaging/__init__.py
> +from .utils import *
utils should define `__all__`.

2024-02-29 22:48 UTC, devinrsmith commented on plugins/packaging/README.md
> +# Deephaven Plugin Packaging
Have you been able to try using this within a build-system requires?

2024-02-29 22:51 UTC, jnumainville commented on plugins/packaging/README.md
> +# Deephaven Plugin Packaging
I'll need to re test but I was able to with a local whl when I had them in one package
For example:
```
[build-system]
requires = ["setuptools>=43.0.0", "wheel", "deephaven-plugin-utilities @ file:///Users/josephnumainville/Documents/deephaven-plugins/plugins/utilities"]
build-backend = "setuptools.build_meta"
```

2024-02-29 23:00 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +            self._callback.register(plugin)
I would think that we want a failed register of the non JsPlugin variety to fail in enterprise?

2024-03-01 15:49 UTC, jnumainville commented on plugins/packaging/README.md
> +# Deephaven Plugin Packaging
Tested again with the new package and it works
pyproject.toml:
```
[build-system]
requires = ["setuptools>=43.0.0", "wheel", "deephaven-plugin-packaging @ file:///Users/josephnumainville/Documents/deephaven-plugins/plugins/packaging"]
build-backend = "setuptools.build_meta"
```

setup.py:
```
from setuptools import setup
import os

from deephaven.plugin.packaging import package_js

js_dir = "src/js/"
dest_dir = os.path.join("src/deephaven/ui/_js")

package_js(js_dir, dest_dir)

setup(package_data={"deephaven.ui._js": ["**"]})
```

2024-03-01 16:15 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +    return any("coreplus" in path or "dnd" in path for path in sys.path)
https://deephaven.atlassian.net/browse/DH-16573

2024-03-01 16:15 UTC, jnumainville commented
Created https://deephaven.atlassian.net/browse/DH-16573 for tracking of environment check

2024-03-04 18:40 UTC, mofojed requested changes

2024-03-04 18:40 UTC, mofojed commented on .github/workflows/release-python-package.yml
> +        if : ${{ inputs.package != 'utilities' && inputs.package != 'packaging' }}
I'd prefer a generic solution for this, such as checking for the package.json or something. Also, the previous step `npm ci` can be skipped if there's no npm packages to build.

2024-03-04 18:40 UTC, mofojed commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +def in_enterprise_environment() -> bool:
For a bool function, I'd prefer the prefix `is`, so name `is_enterprise_environment` as opposed to `in_enterprise_environment`.

2024-03-04 18:40 UTC, mofojed commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +    return any("coreplus" in path or "dnd" in path for path in sys.path)
Add that ticket as a TODO comment in here.

2024-03-05 14:25 UTC, mofojed requested changes

2024-03-05 14:25 UTC, mofojed commented on .github/workflows/release-python-package.yml
> +          files: "plugins/${{ inputs.package }}/src/deephaven/js/package.json"
I don't think `/deephaven` is on the path to the `package.json`
```suggestion
          files: "plugins/${{ inputs.package }}/src/js/package.json"
```

2024-03-05 14:25 UTC, mofojed commented on .github/workflows/release-python-package.yml
> +        run: npm install
Why the change from `npm ci` to `npm install` and removing the `--scope` before? Would've thought we'd want `npm ci` in CI in case the package-lock.json doesn't match, and the `--scope` so it builds only the necessary package.

2024-03-05 17:34 UTC, mofojed approved these changes
Looks good to me, need approval from @devinrsmith as wel

2024-03-05 19:56 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +            self._callback.register(plugin)
At least right now, we aren't handling the case where the user has passed a JsPlugin Type (and not an instance). I think `https://docs.python.org/3/library/functions.html#issubclass` is the check we'll want (so as to not force the plugin to be initialized here, leave that for the callback).

2024-03-05 21:46 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +            self._callback.register(plugin)
I don't think I understand. If a `JsPlugin` Type was passed, `isinstance(JsPlugin, JsPlugin)` would be False, so it would hit the `else` case.

2024-03-05 22:13 UTC, devinrsmith commented on plugins/utilities/src/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
> +            self._callback.register(plugin)
A user can pass the _type_ of the plugin they want the system to instantiate and register instead of an actual instantiation of it. 

For example, I might have:

```python
class MyJsPlugin(JsPlugin):
   ...
   
class MyRegistration(Registration):
    @classmethod
    def register_into(cls, callback: Callback) -> None:
        callback.register(MyJsPlugin)
        # instead of
        #callback.register(MyJsPlugin())
```

We should handle the case where the user passes the type instead of an instance.

2024-03-06 18:34 UTC, mofojed approved these changes

2024-03-06 18:35 UTC, devinrsmith approved these changes

2024-03-06 18:46 UTC, merged