feat: UI Picker JS
deephaven/deephaven-plugins pull request #333
Opened 2024-02-29 19:48 UTC by bmingles

#292

2024-03-01 15:24 UTC, mofojed requested changes
We need to add an example to the `examples/README.md` file, and should also add it to the `DEMO.md` script somewhere so we showcase it's functionality.
Add some details to the PR description as well. I'm assuming we want to merge https://github.com/deephaven/web-client-ui/pull/1847 at the same time.

Other than that, looking good.

2024-03-01 15:24 UTC, mofojed commented on plugins/ui/src/js/src/elements/spectrum/Item.tsx
We should re-export `Item`/`Section` from `@deephaven/components` and use that here instead anyway.
Eventually we depend only on `@deephaven/components` and don't reference `@adobe/react-spectrum` at all.

2024-03-01 15:24 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
>    }
Not part of your change... but in theory, we should just be treating fragment like the other elements, and use `React.Fragment`. I say this because you can also pass a `key` to `Fragment`, it's not just `children`.

2024-03-01 15:40 UTC, bmingles commented on plugins/ui/src/js/src/elements/spectrum/Item.tsx
Makes sense. I'll go ahead and do this in deephaven/web-client-ui/pull/1847 and try to get that merged first

2024-03-04 18:44 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
>    }
good call. Updated

2024-03-05 14:43 UTC, mofojed requested changes

2024-03-05 14:43 UTC, mofojed commented on plugins/ui/examples/README.md
> +    )
We should have consistency within our own examples, providing best practices. I've filed a ticket for this to iron out some examples: https://github.com/deephaven/deephaven-plugins/issues/341

I know we had a discussion about `children` being provided as a keyword arg, but everywhere else in these examples we currently provide `children` as positional args. I would rather keep it consistent, and we can have a further discussion ironing out some details in the documentations with ticket #341 (along with the other inconsistencies).

We want readers of the documentation to focus on the content of the examples, and not get distracted by different syntaxes/inconsistencies.

2024-03-05 14:43 UTC, mofojed commented on plugins/ui/src/js/src/elements/usePickerProps.ts
> +export interface SerializePickerEventProps {
Will need to update the references to this as well.
```suggestion
export interface SerializedPickerEventProps {
```

2024-03-05 14:43 UTC, mofojed commented on plugins/ui/src/js/src/elements/usePickerProps.ts
> +    // we are intentionally not wrapping `otherProps` in `mapSpectrumProps`
I'd also argue that by being in the `elements` folder instead of in the `spectrum` subfolder, the expectation is no longer that it is a "spectrum" component and therefore doesn't need `mapSpectrumProps`. Fine to have the comment to be more explicit though.

2024-03-05 15:38 UTC, bmingles commented on plugins/ui/examples/README.md
> +    )
fixed

2024-03-05 16:01 UTC, mofojed approved these changes

2024-03-05 16:11 UTC, merged