feat: Store server-side state for rehydration
deephaven/deephaven-plugins pull request #338
Opened 2024-03-04 19:22 UTC by mofojed

- deephaven.ui widgets now require the client to set the initial render state
  - On first widget open, an empty state is used
  - Server exports the current current state along with the rendered component
    - Only primitive state values (`int`, `bool`, `str`, `float`) are stored. To have something like a `Table` that is restored, the table should be derived from a primitive state variable
  - Client can then set the state again next time opening the widget to resume where they left off
- Update deephaven.ui widget architecture diagram with new initialization details

2024-03-06 00:21 UTC, mattrunyon requested changes

2024-03-06 00:21 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +      if (widget == null) {
I'd add a `|| jsonClient == null` here so you can remove some of the optional chaining. Looks like if `widget` is not null, `jsonClient` should also be not null

2024-03-06 00:21 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +        });
This makes me wonder if these should be separate effects since we've got multiple cleanups grouped together. Not something we need to address here, just a thought

2024-03-06 18:29 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +        });
Yea, there's probably some way to clean this up a bit...

2024-03-06 18:30 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +          },
No intent to do a deeper merge, if a deeper merge is necessary that should be done at a deeper level (e.g. if `ReactPanelManager` needs to merge a `panelIds`, then it does it there - it'd be the same if it were an object).

2024-03-07 20:46 UTC, jnumainville requested changes

2024-03-07 20:46 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            state: The state of the node to preserve
not sure if this or rename the variable is better
```suggestion
            context: The state of the node to preserve
```

2024-03-07 20:46 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementType.py
> +            raise ValueError(f"Expected Element, got {type(obj)}")
```suggestion
            raise TypeError(f"Expected Element, got {type(obj)}")
```

2024-03-07 20:46 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +    def send_state_update(self, state: RenderContext) -> None:
should this be used somewhere?

2024-03-07 20:46 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        }
when it gets to a couple conditions in a dict comprehension I prefer a generator function

2024-03-07 20:46 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        }
generator function here as well

2024-03-11 22:11 UTC, mattrunyon requested changes

2024-03-11 22:11 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +      if (widget == null || jsonClient == null) {
Remove the optional chaining checks on `jsonClient` after this

2024-03-12 17:01 UTC, mofojed commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        }
@jnumainville how would I write a generator function for this to clean it up? I'm not sure I quite follow.

2024-03-12 17:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +    def send_state_update(self, state: RenderContext) -> None:
Whoops, no it should be removed.

2024-03-12 17:09 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            state: The state of the node to preserve
Changed it to just take the exported state instead.

2024-03-12 17:32 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        }
something like
```
def retained_values(state):
  for key, value in self._state.items():
    if _should_retain_value(value):
      yield key, value
```
Then this becomes 
```
state = dict(retained_values(state))
```

2024-03-14 17:26 UTC, mattrunyon submitted a review, later dismissed
Only reviewed TS changes

2024-03-14 18:42 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        Import the state of this context. This is used to deserialize the state from the client.
missing Args: in doc string as well as returned value

2024-03-14 18:42 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        Export the state of this context. This is used to serialize the state for the client.
missing Returns: in doc string

2024-03-14 19:23 UTC, jnumainville approved these changes

2024-03-14 22:34 UTC, merged