bidirectional support
deephaven/deephaven-plugins pull request #34
Opened 2023-09-12 17:52 UTC by jnumainville

2023-10-04 19:03 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        exporter.acquire()
Am going to move this to a context manager. Although I wonder if I have a correct understanding that a TableListener can lead to a race condition. My understanding on how the java and python interact here is weak.

2023-10-07 00:03 UTC, mattrunyon commented
Added JS bidirectional support. Looks like I need to rebase on main though.

There are some issues w/ recreating a plot w/ the same name (i.e. run the same code twice in a row in the repl). There is an error printed to the user console because something is double closing I think and causing the error (no way to detect it's already been closed). This also seems to be an issue w/ our tables and charts, but it's a JS error/warning.

Turns out in `Pending.cancel` we call the cleanup on all promises, not just the pending promises. That causes the double close on unmount for everything I think.

2023-10-27 18:47 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        self._connection: MessageStream = connection
removed MessageStream type

2023-10-27 18:47 UTC, jnumainville commented on package-lock.json
> +  "lockfileVersion": 2,
fixed I think?

2023-10-27 18:48 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureConnection.py
> +        self._liveness_scope = JLivenessScope()
done

2023-10-27 19:27 UTC, jnumainville commented
@mattrunyon it seems like when I switch panels (from looking at one figure to not then back to looking at it) a new connection is set up but the old one is still there. Do you know how to stop that?

2023-10-30 22:45 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        exporter.acquire()
This lock may have been doing something else that is necessary. I'm getting fairly frequent deadlocks when plotting w/ the latest change. Usually on re-creating a figure, but have gotten it once on the first time I plotted something after a fresh server start

2023-10-30 22:50 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        exporter.acquire()
Nevermind I was able to deadlock even building off the commit before the lock was removed

2023-10-31 15:04 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        exporter.acquire()
I'm seeing those deadlocks too. I'm not sure where they're coming from. It seems to be the whole python interpreter that gets locked.

2023-10-31 15:22 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        exporter.acquire()
@mattrunyon It might have been some figure locks I had that shouldn't also be needed. I removed them and there doesn't seem to be deadlocks any more.
I am still seeing odd behavior when switching between figure tabs. Is there any possibility when switching on and off a figure that there is some lingering data in the window that could mess up the new figure creation? As far as I can tell the proper updates are being sent.

2023-10-31 20:16 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        exporter.acquire()
Pushed a fix for that stale data issue. Also fixed a double loader that appeared from some CSS changes to web-client-ui.

We'll need to update to non-beta packages on the next release to get TS fixes in for this. If there's no other issues w/ this PR though, could just ts-ignore the TS issue and fix it in a future PR when changing to a `WidgetPlugin`

2023-10-31 21:59 UTC, jnumainville commented
Everything seems to be working properly after Matt's fixes

2023-11-02 19:00 UTC, jnumainville commented
After discussion with Colin, the locks are something should be done, so I have added them back in. 
The locks in the figure DAG (DeephavenLayerNode and DeephavenFigureNode) were causing a deadlock because some table operations in the figure regeneration needed to lock but couldn't because of the lock in the node. 
I have worked around this by not locking the figure generation itself, only the update of the figure in the node, with a revision number to ensure that an older update doesn't overwrite a newer update.
I wrote a RevisionManager to deal with this issue, so I also converted the exporter-related locks to use the RevisionManager.

2023-11-03 22:17 UTC, jnumainville commented
@mattrunyon I have (hopefully correctly) added the tables to the liveness scope
I also did something I should have already had, where each session/listener makes a copy of the deephaven figure and the listener updates its specific figure. I think I removed I removed it because it seemed like overkill, but if you're going to have session specific liveness scopes that need to keep track of tables it makes sense anyways. This has the perhaps useful in the future benefit of making it much easier to make session specific updates to the figure, like one_clicks, if we ever wanted to implement those directly into the figure.
Essentially, the session liveness scope is carried along for the figure copy, adding any tables that are in the figure DAG. These are removed on del, either of the base figure or the copy (as well as the session, as before).

2023-11-07 01:06 UTC, jnumainville commented
@mattrunyon fixed #2 with an empty default figure in the partition case.
The only weird thing is that I have to click and drag the figures to get them to start working

code I used:
```
import deephaven.plot.express as dx
from deephaven import time_table
import random 

sourceh = time_table("PT1S").update(formulas=[
    "X = (int)random.gauss(20, 5)", 
    "Y = (int)random.gauss(20, 5)", 
    "Z = (float)random.gauss(30, 3)",
    "l1 = i % 20",
    "l2 = i % 30",
    ]).tail(5)

fig1 = dx.scatter(sourceh, x="Z", y="Y",
    by="l1",
    color_discrete_sequence=["lemonchiffon"]
)

fig2 = dx.scatter(sourceh, x="Z", y="Y",
    by="l2",
    color_discrete_sequence=["salmon"]
)

layered = dx.layer(fig1, fig2)
```

2023-11-07 22:03 UTC, mofojed requested changes

2023-11-07 22:03 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +      'message',
Use `this.dh.Widget.EVENT_MESSAGE`

2023-11-07 22:03 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    // this.widget?.close();
Is there a ticket already for this? I know Colin said he was going to fix it, but did it slide off his radar?

2023-11-08 19:34 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/communication/DeephavenFigureListener.py
> +        if message["type"] == "RETRIEVE":
created #109

2023-11-08 19:47 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/_private_utils.py
> +    groups = {"marker", "preprocess_violin", "supports_lists"}
Yes, violin, box, and strip all have some overlapping preprocessing steps as they have many shared steps. I named this group preprocess_violin originally because I couldn't think of a good category name for that grouping. I'll switch it to `preprocess_spread`. I'll also pull the groups in a constant.

2023-11-08 22:59 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        // log.warn('No tableData for this event. Skipping update');
I changed it to throw. It _shouldn't_ ever happen, but if it does then there's probably some out of sync state or stale state laying around

Can change back to a warning if you think that's right. It doesn't cause an issue to ignore it, but the plot might not be correct if this case were to happen. Prefer error over showing potentially incorrect data?

2023-11-08 23:02 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    // this.widget?.close();
https://github.com/deephaven/deephaven-core/issues/4604

I'm going to remove this comment and uncomment the code. Either way there's errors printed to the user's console, but I think once that bug is fixed this will be the correct way to do it

2023-11-09 15:00 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        // log.warn('No tableData for this event. Skipping update');
Yup error over showing incorrect.

2023-11-09 16:29 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        // log.warn('No tableData for this event. Skipping update');
I need to fix something for initial loading actually with this. The chart is finished loading after the model initializes, but before the tables are fetched which leads to this throwing

2023-11-09 21:18 UTC, jnumainville commented
At this point I have resolved all bugs and comments I am aware of in the python side of the application

2023-11-09 21:30 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        // log.warn('No tableData for this event. Skipping update');
Ok I have changed this to throw and set an empty tableData when the table is added. There could be states (like initial load) where the table is being fetched and doesn't have its data yet, so that's why I added the default empty tableData

The error should only throw if something bad happens or somehow gets out of sync. Mostly there so TS doesn't complain about the possibility of null

2023-11-09 21:35 UTC, mattrunyon commented
I believe the JS side has any known issues fixed as well

2023-11-10 15:30 UTC, mofojed approved these changes

2023-11-10 15:52 UTC, merged