feat: Package matplotlib and ui JS with wheel
deephaven/deephaven-plugins pull request #343
Opened 2024-03-06 21:31 UTC by jnumainville

Fixes #194, fixes #316 

Packages matplotlib and ui JS with wheel using new util packages. I also took the opportunity to refactor those two a bit to match the plotly express package by moving registration out of the `__init__.py` files.

I've verified the installed wheels work properly with basic examples.

By the way @devinrsmith I invited deephaven as an owner of the newly uploaded packages 
https://pypi.org/project/deephaven-plugin-utilities/
https://pypi.org/project/deephaven-plugin-packaging/

2024-03-07 14:59 UTC, mofojed approved these changes

2024-03-07 14:59 UTC, mofojed commented on plugins/plotly-express/setup.py
> +package_js(js_dir, dest_dir)
Nice.

2024-03-07 14:59 UTC, mofojed commented on plugins/ui/src/deephaven/ui/__init__.py
>  __version__ = "0.8.0.dev0"
So I know this is a rejected standard: https://peps.python.org/pep-0396/
But at the same time - what _is_ the standard now? Closest thing I can find is this: https://packaging.python.org/en/latest/guides/single-sourcing-package-version/
Which lists 7 (!) different ways to do it, many of them which actually use `__version__` :laughing:  

I'd be good just putting the version in the setup.cfg, or whatever, we should just be consistent. Doesn't have to be a change in this PR.

2024-03-07 15:07 UTC, mofojed requested changes
You'll need to update the Dockerfile configs now that you're registering the plugin with python.

Try running `npm run docker` to verify it works/starts up correctly. Right now it's throwing this error:

```
deephaven-plugins-deephaven-plugins-1  | Initiating shutdown due to: Uncaught exception in thread main
deephaven-plugins-deephaven-plugins-1  | java.lang.RuntimeException: Error in Python interpreter:
deephaven-plugins-deephaven-plugins-1  | Type: <class 'RuntimeError'>
deephaven-plugins-deephaven-plugins-1  | Value: Failed to register @deephaven/js-plugin-ui@0.8.0 embedded in Python plugin: java.lang.IllegalArgumentException: js plugin with name '@deephaven/js-plugin-ui' already exists. See https://github.com/deephaven/deephaven-core/issues/3048
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.jetty.JsPluginsZipFilesystem.checkExisting(JsPluginsZipFilesystem.java:82)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.jetty.JsPluginsZipFilesystem.add(JsPluginsZipFilesystem.java:61)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.jetty.JsPlugins.register(JsPlugins.java:38)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistrationVisitor.visit(PluginRegistrationVisitor.java:46)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistrationVisitor.visit(PluginRegistrationVisitor.java:19)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.plugin.js.JsPlugin.walk(JsPlugin.java:105)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistrationVisitor.register(PluginRegistrationVisitor.java:35)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistration$Counting.visit(PluginRegistration.java:70)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistration$Counting.visit(PluginRegistration.java:46)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.plugin.js.JsPlugin.walk(JsPlugin.java:105)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistration$Counting.register(PluginRegistration.java:53)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.python.CallbackAdapter.registerJsPlugin(CallbackAdapter.java:25)
deephaven-plugins-deephaven-plugins-1  |        at org.jpy.PyLib.callAndReturnValue(Native Method)
deephaven-plugins-deephaven-plugins-1  |        at org.jpy.PyProxyHandler.invoke(PyProxyHandler.java:120)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.python.$Proxy16.initialize_all_and_register_into(Unknown Source)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.python.PythonPluginsRegistration.registerInto(PythonPluginsRegistration.java:33)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistration.registerAll(PluginRegistration.java:41)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:150)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.jetty.JettyMain.main(JettyMain.java:24)
deephaven-plugins-deephaven-plugins-1  | 
deephaven-plugins-deephaven-plugins-1  | Line: 57
deephaven-plugins-deephaven-plugins-1  | Namespace: _register_js
deephaven-plugins-deephaven-plugins-1  | File: /opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py
deephaven-plugins-deephaven-plugins-1  | Traceback (most recent call last):
deephaven-plugins-deephaven-plugins-1  |   File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven_internal/plugin/__init__.py", line 18, in initialize_all_and_register_into
deephaven-plugins-deephaven-plugins-1  |   File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven_internal/plugin/register.py", line 20, in initialize_all_and_register_into
deephaven-plugins-deephaven-plugins-1  |   File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/__init__.py", line 95, in register_all_into
deephaven-plugins-deephaven-plugins-1  |   File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/ui/_register.py", line 27, in register_into
deephaven-plugins-deephaven-plugins-1  |   File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py", line 35, in register
deephaven-plugins-deephaven-plugins-1  |   File "/opt/deephaven/venv/lib/python3.10/site-packages/deephaven/plugin/utilities/dhe_safe_callback_wrapper.py", line 57, in _register_js
deephaven-plugins-deephaven-plugins-1  | 
deephaven-plugins-deephaven-plugins-1  |        at org.jpy.PyLib.callAndReturnValue(Native Method)
deephaven-plugins-deephaven-plugins-1  |        at org.jpy.PyProxyHandler.invoke(PyProxyHandler.java:120)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.python.$Proxy16.initialize_all_and_register_into(Unknown Source)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.python.PythonPluginsRegistration.registerInto(PythonPluginsRegistration.java:33)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.plugin.PluginRegistration.registerAll(PluginRegistration.java:41)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:150)
deephaven-plugins-deephaven-plugins-1  |        at io.deephaven.server.jetty.JettyMain.main(JettyMain.java:24)
```

2024-03-07 15:21 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/__init__.py
>  __version__ = "0.8.0.dev0"
I think despite being a rejected standard, many packages just do it anyways... I'll throw it in setup.cfg just to be consistent for now.

2024-03-13 14:29 UTC, mofojed requested changes
Minor change, looks good otherwise

2024-03-13 14:29 UTC, mofojed commented on docker/config/deephaven.prop
>  # Add all plugins that you want installed here
Either remove this comment
```suggestion
```
Or leave the comment and add an example, e.g.
```suggestion
# Add all JS-only plugins that you want installed here
# For a plugin named `my-plugin`:
#deephaven.jsPlugins.@deephaven/js-plugin-my-plugin=/opt/deephaven/config/plugins/plugins/my-plugin/src/js
```

Given that we're moving away from JS only plugins, I'm inclined to just remove the comment.

2024-03-14 18:26 UTC, mofojed approved these changes

2024-03-14 18:44 UTC, merged