docs: text field
deephaven/deephaven-plugins pull request #357
Opened 2024-03-12 20:46 UTC by ethanalvizo

Closes #300

2024-03-13 13:46 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/spectrum/layout.py
> +TextFieldLabelAlign = Literal["start", "end"]
not specfic to text field, I think any component that takes a label prop also uses these ex. picker also accepts a label and label alignment/position

2024-03-13 15:25 UTC, mofojed requested changes

2024-03-13 15:25 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/accessibility.py
> +Behaviour = Literal["aria", "native"]
Seems this would fit in `validate.py` better.

Also - be careful with spelling. Should be `Behavior`, and `validate_behavior`. We should use the US spelling. Another common gotcha is `Color`

2024-03-13 15:25 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/layout.py
> +TextFieldLabelAlign = Literal["start", "end"]
Yes, just name them `LabelPosition` and `LabelAlign`:
```suggestion
LabelPosition = Literal["top", "side"]
LabelAlign = Literal["start", "end"]
```

2024-03-13 15:25 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/text_field.py
> +    # missing properties that are clipboard or composition events
After reading the docs for `validate`:
> A function that returns an error message if a given value is invalid. Validation errors are displayed to the user when the form is submitted if validationBehavior="native". For realtime validation, use the isInvalid prop instead.
We're not going to be able to ever handle that `validate` function, since it needs to return a result synchronously. As such, we don't really need the `validationBehavior` arg either, since setting it to `native` won't work since you can't set `validate`.

2024-03-13 15:25 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/text_field.py
> +    validation_behaviour: Behaviour = "aria",
Remove, as seen in my other comment we can't really use this prop anyway.

2024-03-13 15:25 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/text_field.py
> +    validation_behaviour: Whether to use native HTML form validation to prevent form submission when the value is missing or invalid, or mark the field as required or invalid via ARIA.
Remove

2024-03-27 13:48 UTC, mofojed requested changes

2024-03-27 13:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/validate.py
> +Behavior = Literal["aria", "native"]
Unused, remove.
```suggestion
```

2024-03-27 13:48 UTC, mofojed approved these changes

2024-03-27 13:53 UTC, merged