feat: Add Python list_view implementation
deephaven/deephaven-plugins pull request #359
Opened 2024-03-14 16:07 UTC by jnumainville

fixes #337 

Adds Python list_view implementation

2024-03-26 20:32 UTC, mofojed requested changes
Think we should clear up how `action_button` is populated/used, then we should be good.
Will continue discussion about data sources in Slack team channel.

2024-03-26 20:32 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
Is the intent here that you pass one `button` instance, and then we clone it and just call the same handler with a different `data` arg? If it is, then we should be passing in something other than an `ActionButtonElement` that takes a different `onPress`, since `onPress` doesn't have a second argument.

That being said, instead of modifying the second argument, we could just populate the `target` of the `PressEvent` with the key of the list item. Usage would be something like:
```
my_list = ui.list_view(
  "Foo",
  "Bar",
  action_button=ui.action_button(icon="vsEdit", on_press=lambda e: print(f"Pressed button for {e.target}")
)
```

2024-03-26 20:32 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +    | None = None,
I wanted to have a wider discussion about these, I'll bring it up in the team channel.

2024-03-26 21:07 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
Yes that is my intent. Maybe a component `EmbeddableActionButtonElement` etc. that is the same besides taking a second arg for events?
My problem with modifying the event is that `ActionGroup` or `ActionMenu` events do not take an Event object of some kind.

2024-03-26 21:39 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
`ActionGroup` the event is fired from the key, so it'd just be:
```
my_list = ui.list_view(
  "Foo",
  "Bar",
  action_buttons=ui.action_group(
    ui.item("Edit", icon="vsEdit"),
    ui.item("Delete", icon="vsTrash"),
    on_action=lambda e: print(f"Pressed button for {e}"
  )
)
```
... oh but then you don't have the key from the item that was actually clicked (or you don't know which button was clicked). Now I see what you mean :smile: 

Hmm. Also what if we want different buttons to appear based on the table list item, or in a different state (e.g. disabled). I need to stew on this a bit.

2024-03-26 21:50 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
I was thinking that if you want different buttons you'll have to just create a much more complex item then we can support in this way, as you'll need to provide different event handlers anyways.

2024-03-27 13:28 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
Don't necessarily need different handlers... just one handler that takes the row key and the action name... also it's a little different than a single button - with an ActionButton press, you get the button event, whereas with an `ActionGroup`/`ActionMenu` you're just getting the action name... So in theory it would work for the `ActionButton` if we just passed the action as the `e.target`... but that would be inconsistent with `ActionGroup` and `ActionMenu`...
I don't particularly like having to extend each of `ActionButton`, `ActionGroup`, and `ActionMenu` for this to work... and actually, thinking about it further... if you provide ListViewItems, the action should be within that item (as you mentioned in your comment)... so really the only case we need an `action_buttons` prop would be when using a table as the data source (in theory you could if you provided ListViewItems without an element, but let's not bother with that since it's a bit confusing then (what do we do if you provide both?) and doesn't provide much value IMO, as you can map an array of items easily to include their appropriate actions on the server.
So instead of [my example](https://github.com/deephaven/deephaven-plugins/pull/359#discussion_r1540142726) above, it would just be something like:
```python
items = ["Foo", "Bar"]
my_list = ui.list_view(
  [ui.item(item, ui.action_button(icon="vsEdit", on_press=lambda: print(f"Edit pressed for {item}"))) for item in items],
)
```

Then if we consider this is only for table... I'd just name it `actions` and pass in our own custom thing, e.g.
```python
my_list = ui.list_view(
  table,
  actions=ui.list_action_group(  # or `ui.list_action_menu`, I don't think we need anything else - one ActionButton is just an ActionGroup with one button
    ui.item("Foo"),
    ui.item("Bar"),
    on_action(lambda key, action: print(f"Action {action} pressed for {key}")
  )
```

Eh I guess we could say it works for ListItems as well, I just don't like the ambiguity there. If we had the table data source thing I mentioned, it could maybe be included in that... but in any case, let's just go with `actions=ui.list_action_group` or `actions=ui.list_action_menu`, I think that's the simplest for now.

2024-03-27 13:30 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
Also that does not address having different actions for different rows of a table... for that we'd probably want to define some sort of `action_column` and `action_icon_column` or something. I'm choosing to ignore that for now (though I would consider it if we package all the table column props into a data source object that gets passed in).

2024-03-27 16:29 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +            so that the second argument is the key for the `list_view` item that the buttons are embedded in.
I don't love new objects like `ListActionGroupElement` because it's a lot of documentation and such that is maintained for a very small tweak to `ActionGroupElement`, but from a user perspective I don't see a simpler way that makes it explicit.

2024-04-01 16:17 UTC, bmingles commented on plugins/ui/DESIGN.md
> +| `**props`               | `Any`                                                      | Any other [ListView](https://react-spectrum.adobe.com/react-spectrum/ListView.html) prop, with the exception o
Should we call out `input_value`, `default_input_value`, and `on_input_change` for controlled scenarios of the search input?

2024-04-01 16:34 UTC, bmingles commented on plugins/ui/DESIGN.md
> +    actions=button,
It looks like actions are defined in Spectrum at the `Item` template level instead of at the ListView level. I think this will be fine since presumably, we want the same actions for each item. Just wanted to call it out in case there are any implications.

2024-04-01 17:44 UTC, bmingles commented on plugins/ui/DESIGN.md
> +    actions=button,
nvm, I see this is already called out in the props matrix

2024-04-01 18:10 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `**props`               | `Any`                                                      | Any other [ListView](https://react-spectrum.adobe.com/react-spectrum/ListView.html) prop, with the exception o
Could you elaborate? I don't see those in https://react-spectrum.adobe.com/react-spectrum/ListView.html

2024-04-01 18:34 UTC, bmingles commented on plugins/ui/DESIGN.md
> +| `**props`               | `Any`                                                      | Any other [ListView](https://react-spectrum.adobe.com/react-spectrum/ListView.html) prop, with the exception o
Oops, that should have been on the Combobox spec. Doesn't apply here

2024-04-03 14:07 UTC, mofojed requested changes
Looks good to me, minor doc spec fix. I think we should continue the discussion about item data source as well: https://github.com/deephaven/deephaven-plugins/issues/399
But doesn't need to hold this up.

2024-04-03 14:07 UTC, mofojed commented on plugins/ui/DESIGN.md
> +| `*children`             | `ActionGroupItem`                                          | The options to render within the picker.
```suggestion
| `*children`             | `ActionGroupItem`                                          | The actions to render within the action group.                                                                                                           |
```

2024-04-03 14:07 UTC, mofojed commented on plugins/ui/DESIGN.md
> +| `actions`               | `ListActionGroupElement \| ListActionMenuElement \| None`  | Only valid if children are of type Table. The action group or menus to render for all elements within the list
Created a ticket for the discussion about an `item_table_source` API: https://github.com/deephaven/deephaven-plugins/issues/399

I think `actions` would make sense in there as well. Would simplify these top level APIs IMO, but we can continue that discussion there without blocking this.

2024-04-03 15:05 UTC, mofojed approved these changes

2024-04-03 15:06 UTC, merged