docs: Updating examples
deephaven/deephaven-plugins pull request #378
Opened 2024-03-21 13:40 UTC by mofojed

- Adding some more basic examples, adding only one concept with each example
  - Start with a couple one-liners, show core concepts one at a time first
- Update all `import deephaven.ui as ui` to `from deephaven import ui`
- Clean up a lot of examples
- Fixes #341
- Next I think we _need_ a Components section that just details each component. Like copy over what we have with DESIGN.md, add an example. Would only be the things that have been implemented, while DESIGN.md has the full spec.
  - There are a few links to React Spectrum components, when instead we should just link our own Components section

2024-03-21 14:34 UTC, dsmmcken commented
>Next I think we need a Components section that just details each component. Like copy over what we have with DESIGN.md, add an example. Would only be the things that have been implemented, while DESIGN.md has the full spec.
There are a few links to React Spectrum components, when instead we should just link our own Components section

Let's start a docs folder that will eventually become the official docs.

`plugins > ui > docs > index.md` introduction/overview
`plugins > ui > docs > components > picker.md etc`
`plugins > ui > docs > hooks`

2024-03-21 16:17 UTC, dsmmcken commented on plugins/ui/examples/README.md
> +## Creating custom components
```suggestion
## Creating components
```

2024-03-21 16:20 UTC, dsmmcken commented on plugins/ui/examples/README.md
> +Use the `@ui.component` decorator to create your own custom components. We can display a heading above a button as our custom custom component:
A once sentence explanation of the decorator would be nice. Something like:

"This tells deephaven to render the value return from the function as a component, and re-render whenever a state or prop changes."

2024-03-21 16:22 UTC, dsmmcken commented on plugins/ui/examples/README.md
> +Often, you'll want to react to the button presses and update the display. For example, to count the number of times a button has been pressed, use `ui.use_state` to introduce a _state variable_ in yo
"Often, you'll want to"

Do we use "you" etc in our writing? I thought not. We could have @margaretkennedy review grammer.

2024-03-21 16:24 UTC, dsmmcken commented on plugins/ui/examples/README.md
> +        set_count(count + 1)
Maybe the classic increment/decrement example would fit better here?

2024-03-21 16:29 UTC, dsmmcken requested changes
> Most notably, all examples will only appear within one panel in the UI, the `ui.table` functionality (allowing interactivity and customization of displayed tables), and ability to use other plugins (such as deephaven.plot.express) is not yet implemented.

That could be updated too.

2024-03-22 00:39 UTC, mofojed commented on plugins/ui/examples/README.md
> +        set_count(count + 1)
Changed it up a bit, let me know what you think.

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +Often, you'll want to react to the button presses and update the display. For example, to count the number of times a button has been pressed, use `ui.use_state` to introduce a _state variable_ in yo
The Community docs use "you" (not the reference documentation). It seems ok to use a conversational tone in the README.

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +The first time the button is displayed, the count will be `0` because that's the initial value you passed into `ui.use_state`. Call `set_count` when you want to update the state:
```suggestion
The first time the button is displayed, the count will be `0` because that is the initial value passed into `ui.use_state`. Call `set_count` to update the state:
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +When state is updated, deephaven.ui will call your component again to re-render with the new value. After clicking once it will re-render with `count` set to `1`, then set to `2`, and so on.
```suggestion
When state is updated, deephaven.ui will call your component again to re-render with the new value. After clicking once, it will re-render with `count` set to `1`, then set to `2`, and so on.
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +Each individual component has it's own state:
```suggestion
Each individual component has its own state:
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +![Each counter has it's own state.](assets/counter.png)
```suggestion
![Each counter has its own state.](assets/counter.png)
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +> Functions are prefixed with `use_` are called _hooks_. `use_state` is built-in to deephaven.ui, and there are other hooks built-in shown below. You can also create your own hooks.
```suggestion
> Functions prefixed with `use_` are called _hooks_. `use_state` is built in to deephaven.ui; other built-in hooks are shown below. You can also create your own hooks.
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +> Hooks are special functions. They must only be used at the _top_ of a `@ui.component` or another hook. If you want to use in a conditional or a loop, extract that logic to a new component and put i
```suggestion
> Hooks are special functions. They must only be used at the _top_ of a `@ui.component` or another hook. If you want to use one in a conditional or a loop, extract that logic to a new component and put it there.
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +What if we wanted to have two buttons share the same count? To do this, we move the state `count` upward to a parent component:
```suggestion
What if we wanted to have two buttons share the same count? To do this, move the state `count` upward to a parent component:
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  You can have state with multiple different variables in one component. In this example, we have a [text field](https://react-spectrum.adobe.com/react-spectrum/TextField.html) and a [slider](https://r
```suggestion
You can have state with multiple different variables in one component. This example creates a [text field](https://react-spectrum.adobe.com/react-spectrum/TextField.html) and a [slider](https://react-spectrum.adobe.com/react-spectrum/Slider.html), and we display the values of both of them.
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  You can also create a form that user can click Submit on and react to that on a callback you specify. In this example, we create a [Form](https://react-spectrum.adobe.com/react-spectrum/forms.html) t
```suggestion
You can also create a form on which the user can click **Submit** and react to that on a specified callback. In this example, we create a [Form](https://react-spectrum.adobe.com/react-spectrum/forms.html) that takes a name and age, and when the user clicks **Submit**, the values entered in the form are sent to the user on the form's `on_submit` callback.
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  You can take input from a user to filter a table using the `where` method. In this example, we have a [text field](https://react-spectrum.adobe.com/react-spectrum/TextField.html) that takes input fro
```suggestion
User input can filter a table using the `where` method. In this example, a [text field](https://react-spectrum.adobe.com/react-spectrum/TextField.html) takes input from the user, and we filter the table based on the input. Simply returning the table `t` from the component will display it in the UI (as if we had set it to a variable name).
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  You can also filter a table based on a range. In this example, we have a [range slider](https://react-spectrum.adobe.com/react-spectrum/RangeSlider.html) that takes input from the user, and we filter
```suggestion
You can also filter a table based on a range. In this example, a [range slider](https://react-spectrum.adobe.com/react-spectrum/RangeSlider.html) takes input from the user, and we filter the table by price based on the input. Simply returning the table `t` from the component will display it in the UI (as if we had set it to a variable name).
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  In the previous example, we took a users input. But we didn't display anything if the user didn't enter any text. We can display a different message prompting the user for input if they haven't enter
```suggestion
In the previous example, we took a user's input. Nothing was displayed if the user didn't enter any text. Instead, we can display a different message prompting the user for input. We use a few new components in this example:
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  We can use the `use_memo` hook to memoize a value. This is useful if you have a value that is expensive to compute, and you only want to compute it when the inputs change. In this example, we create
```suggestion
We can use the `use_memo` hook to memoize a value. This is useful if you have a value that is expensive to compute and you only want to compute it when the inputs change. In this example, we create a time table with a new column, `y_sin,` which is a sine wave. We use `use_memo` to memoize the time table, so that it is only re-computed when the inputs to the `use_memo` function change (in this case, the function is a lambda that takes no arguments, so it will only re-compute when the dependencies change, which is never). We then use the `update` method to update the table with the new column, based on the values inputted on the sliders.
```

2024-03-22 11:18 UTC, margaretkennedy commented on plugins/ui/examples/README.md
>  You can use `ui.table` to add interactivity to a table, or give other instructions to the UI. Here's an example that will create two tables and a plot. The first table `t1` is an unfiltered view of t
```suggestion
You can use `ui.table` to add interactivity to a table, or give other instructions to the UI. Here's an example that creates two tables and a plot. The first table, `t1`, is an unfiltered view of the stocks table, with a row double-press listener so if you double-click on a row, it will filter the second table, `t2`, to show that row only and the plot to show that selected sym and exchange.
```

2024-03-22 12:16 UTC, mofojed commented on plugins/ui/examples/README.md
> +![Each counter has it's own state.](assets/counter.png)
Wow can't believe I made that same mistake twice 😬

2024-03-22 12:18 UTC, mofojed commented on plugins/ui/examples/README.md
> +> Functions are prefixed with `use_` are called _hooks_. `use_state` is built-in to deephaven.ui, and there are other hooks built-in shown below. You can also create your own hooks.
"built-in" or "built in"? With your change there's both in this sentence now, and I'm seeing in core docs both as well. Not the biggest concern but I should be consistent within the same sentence 😄

2024-03-22 12:41 UTC, margaretkennedy commented on plugins/ui/examples/README.md
> +> Functions are prefixed with `use_` are called _hooks_. `use_state` is built-in to deephaven.ui, and there are other hooks built-in shown below. You can also create your own hooks.
In this case, one is a verb - "these hooks are built into Deephaven" - and one is an adjective - "built-in" hooks. These are distinctions grammar nerds live by!

2024-04-02 17:18 UTC, dsmmcken approved these changes

2024-04-02 17:45 UTC, merged