fix: Re-opening widgets after re-hydrated
deephaven/deephaven-plugins pull request #379
Opened 2024-03-21 14:33 UTC by mofojed

- There was a race condition when replacing the widget, where the old panel content was getting removed before the new panel was being put up
  - This was because we were calling `LayoutUtils.openComponent` to open the panel, which would replace the existing panel; which triggered a panel close event, then a panel open event.
  - Was also adding panel IDs multiple times to the `panelIds` widget data, which would cause them to re-open even if you "closed" all the panels
- Instead, only call `LayoutUtils.openComponent` if the panel does not yet exist
  - If it needs a re-focus in case of metadata change (e.g. re-opening a widget), it will just set it as the active item in the stack, and update the key of the component so that it re-renders clean.
  - Add checks to ensure we're not adding `panelIds` multiple times, and we're removing it correctly on close
- Added some more unit tests
- Fixes #374
- Manually tested by following the steps in the ticket

2024-03-25 13:49 UTC, mattrunyon requested changes

2024-03-25 13:49 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
> +      const itemConfig = { id: panelId };
Update the comment here to add some explanation about the re-hydration case too

2024-03-26 17:42 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +          },
Extracted this to a method and added some comments/tests.

2024-03-26 17:55 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  const [panelIds] = useState<string[]>([]);
Added a comment about why I did it specifically for `widgetData`.
For `panelIds`, I could use `useRef`. Just means I'd be adding `.current` everywhere else.

2024-03-27 21:02 UTC, mattrunyon requested changes
Just a few small things. I also need to pull and test this still to see if I can break it

2024-04-03 20:39 UTC, mattrunyon requested changes
Looks good. Only issue I found is just a bug and not a regression, so can be fixed separately

Just the one minor thing

2024-04-03 20:39 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
>          portal
`createPortal` can take a key as a 3rd param which you could use here instead

2024-04-03 21:57 UTC, merged