chore: Upgraded @deephaven/jsapi-types to 1.0.0-dev0.33.2 (#389)
deephaven/deephaven-plugins pull request #390
Opened 2024-03-25 21:23 UTC by bmingles

resolves #389

2024-03-25 21:24 UTC, bmingles commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +        title: title ?? 'Untitled',
The type says this can be `null`. I'm assuming we desire to say `Untitled` in that case as well.

2024-03-26 16:09 UTC, mofojed requested changes

2024-03-26 16:09 UTC, mofojed commented on plugins/ui/src/js/src/elements/ObjectView.tsx
> +        .find(p => [p.supportedTypes].flat().includes(object.type as string)),
Instead of casting here... Above I'd just set `type` and then just check if it's `null` before going through plugins (since we will never be able to open the object if the type isn't defined). Also there's a `object == null` check that doesn't make sense below (since it's always defined).
So something like :
```
const { object } = props;
const { type } = object;

...

  const plugin = useMemo(
    () =>
      type != null ? [...plugins.values()]
        .filter(isWidgetPlugin)
        .find(p => [p.supportedTypes].flat().includes(type)) : undefined,
    [plugins, type]
  );
```

2024-03-26 16:09 UTC, mofojed commented on plugins/ui/src/js/src/elements/SpectrumElementView.tsx
>    }
Instead of this, we should `throw` in `getSpectrumComponent` if there is no type returned. Then this is just `const Component = getSpectrumComponent(name)` and it all makes sense.

2024-03-26 16:09 UTC, mofojed commented on plugins/ui/src/js/src/layout/ReactPanel.tsx
>    );
Ahhh good catch. I would've just returned `undefined` instead of `null`, since that matches the `ReactPanelControl['metadata']` type already.:
```suggestion
  const openedMetadataRef = useRef<ReactPanelControl['metadata']>(
    portal != null ? metadata : undefined
  );
```

2024-03-27 14:01 UTC, mofojed approved these changes

2024-03-27 14:02 UTC, merged