docs: start plotting docs including one-click behaviour
deephaven/deephaven-plugins pull request #431
Opened 2024-04-24 16:04 UTC by dsmmcken

Resolves #413

- Reename examples as docs
- Create a dh.ui plotting doc
- Rename assets as _assets for folder sort order
- Change links from assets to _assets
- Prettier changes on md files touched

2024-04-24 16:23 UTC, mofojed requested changes

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +Creating dynamic plots that respond to user input is a common task in data analysis. The `dh.ui` module provides a simple interface for creating interactive plots using the `deephaven-express` librar
Why are we using the name `dh.ui` here? `deephaven.ui`, we need to be consistent.
```suggestion
title: Plotting and deephaven.ui
---

Creating dynamic plots that respond to user input is a common task in data analysis. The `deephaven.ui` module provides a simple interface for creating interactive plots using the `deephaven-plugin-express` library. This guide will show you how to create plots that updates based on user input.
```

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +This example demonstrates how to create a simple line plot that updates based on user input. The plot will display the price of a stock filtered based on the stock symbol entered by the user. Here we
```suggestion
This example demonstrates how to create a simple line plot that updates based on user input. The plot will display the price of a stock filtered based on the stock symbol entered by the user. Here we have used a `ui.text_field` to get the value, but it could be driven by any deephaven.ui input, including double clicking on a value from a `ui.table`. We've previously referred to this sort of behaviour as a "one-click" component in enterprise, as the plot updates as soon as the user enters a filter.
```

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +        else ui.text("Please enter a valid parition."),
```suggestion
        else ui.text("Please enter a valid partition."),
```

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +            constituent_table, x="timestamp", y="price", title=f"Parition key: {text}"
```suggestion
            constituent_table, x="timestamp", y="price", title=f"Partition key: {text}"
```

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +## Combining a fitler and a parition by
```suggestion
## Combining a filter and a partition by
```

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +Deephaven express allows you to plot by a partition and assign unique colors to each key. Sometimes as a user you may also want to filter the data in addition to partitioning it. We've previously ref
We should really resolve our branding/nomenclature around Deephaven express (Deephaven Express? Deephaven express? Deephaven plotly express? What do we call the old plotting?).
No change necessary here but it's something we're messy/confusing about.

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +wtp = where_then_parition(_stocks, ["sym", "exchange"], "DOG")
Can you just do a find/replace for `parition` -> `partition` and `inital` -> `initial`

```suggestionimport deephaven.plot.express as dx
import deephaven.ui as ui

_stocks = dx.data.stocks()

# component using a partition_by[a,b] once, then filter on a
@ui.component
def partition_then_filter(table, by, initial_value):
    text, set_text = ui.use_state(initial_value)
    partitioned_table = ui.use_memo(lambda: table.partition_by(by), [table, by])
    filtered = ui.use_memo(
        lambda: partitioned_table.filter(f"{by[0]} = `{text.upper()}`"),
        [text, partitioned_table],
    )
    return [
        ui.text_field(value=text, on_change=set_text),
        dx.line(filtered, x="timestamp", y="price", by=[f"{by[1]}"]),
    ]


# component using a where on a, then re-partitions on b
@ui.component
def where_then_partition(table, by, initial_value):
    text, set_text = ui.use_state(initial_value)
    filtered = ui.use_memo(
        lambda: table.where(f"{by[0]} = `{text.upper()}`"), [text, table]
    )
    return [
        ui.text_field(value=text, on_change=set_text),
        dx.line(filtered, x="timestamp", y="price", by=[f"{by[1]}"]),
    ]


# outputs the same thing, done two different ways depending on how you want the work done
ptf = partition_then_filter(_stocks, ["sym", "exchange"], "DOG")
wtp = where_then_partition(_stocks, ["sym", "exchange"], "DOG")
```

2024-04-24 16:23 UTC, mofojed commented on plugins/ui/docs/Plotting.md
> +
No screenshots?

2024-04-24 16:29 UTC, dsmmcken commented on plugins/ui/docs/Plotting.md
> +
I want to hold of on adding more screenshots for now, in case we come up with a better way of doing that automatically.

2024-04-24 16:29 UTC, dsmmcken commented on plugins/ui/docs/Plotting.md
> +wtp = where_then_parition(_stocks, ["sym", "exchange"], "DOG")
doh.

2024-04-25 20:49 UTC, jnumainville requested changes

2024-04-25 20:49 UTC, jnumainville commented on plugins/ui/docs/Plotting.md
> +Deephaven express allows you to plot by a partition and assign unique colors to each key. Sometimes as a user you may also want to filter the data in addition to partitioning it. We've previously ref
I agree we're a bit inconsistent. Not sure what the right solution is. 
I'd say Deephaven Plot and Deephaven Express, but then the package is named `deephaven-plugin-plotly-express`. 
It supports `plotly.express`, but it also supports `plotly` and our "Express" library is based off but not strictly the same as `plotly.express`... I think how we import it (`deephaven.plot.express`) is fine but the package name could be different.
Maybe `deephaven-express`, and we just point out that it's our version of `plotly.express` and as such coincedentally supports all `plotly` plots. Not sure if it's worth the headache of a rename.

2024-04-25 20:49 UTC, jnumainville commented on plugins/ui/docs/Plotting.md
> +# component using a where on a, then re-partitions on b
Maybe capitalize these example variables to A and B (here and above)? The multiple uses of "a" is funky here

2024-04-26 20:21 UTC, jnumainville commented on plugins/ui/docs/Plotting.md
> +    Parition the table by both passed columns, then filter it by the value entered by the user
```suggestion
    Partition the table by both passed columns, then filter it by the value entered by the user
```

2024-04-26 20:23 UTC, mofojed approved these changes

2024-04-26 20:25 UTC, jnumainville approved these changes

2024-04-26 20:27 UTC, merged