feat: Display deephaven.ui widget errors in a panel so user can see them
deephaven/deephaven-plugins pull request #436
Opened 2024-04-25 21:19 UTC by mofojed

- Widget can now emit a `documentError` on the server to indicate there was an error rendering the document
- Client listens for `documentError` and will display the error message in a panel along with a Reload button to reload the widget
- Updated `@deephaven/*` packages to 0.76.0, which includes the `ErrorView` and is also in deephaven-core 0.34.1
- Fixes #437
- Fixes #85 
- Tested with a `ui_boom` and `ui_boom_counter` components:
```python
from deephaven import ui

@ui.component
def ui_boom():
    raise Exception("BOOM!")

@ui.component
def ui_boom_counter():
    value, set_value = ui.use_state(0)

    if value > 5:
        raise ValueError("BOOM! Value is bigger than 5.")
    
    return ui.button(f"Count is {value}", on_press=lambda: set_value(value + 1))

boom = ui_boom()
boom_counter = ui_boom_counter()
```

2024-04-26 15:03 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> +  });
Should probably call the ref hook and set `isUpdating.current = true` as the first 2 lines of the render. But keep the effect at the end. Should be more accurate.

I'd add comments to both that they should be the first and last things called in the render method

2024-04-26 15:10 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/ErrorView.tsx
> + */
Going to leave this for review in the web-client-ui PR

If you want to test w/ the component, you can externalize `@deephaven/components` in vite instead of copying the component into dh.ui. Then just import it from ` @deephaven/components`. It's provided via `remote-component.config.ts` in app-utils

2024-04-26 15:12 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetErrorView.tsx
> +  const displayMessage = `${error.message}\n\n${error.stack ?? ''}`.trim();
Might as well trim the message in case it has trailing whitespace/newlines

```suggestion
  const displayMessage = `${error.message.trim()}\n\n${error.stack ?? ''}`.trim();
```

2024-04-26 15:16 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetErrorView.tsx
> +        </Button>
Should add `icon={vsRefresh}`

2024-04-26 15:18 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +        }
Will/should this error be propagated to the user as well in the panel?

2024-04-26 15:23 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +            log.debug('Error receiving data', e);
Should be `log.error`?

2024-04-26 15:36 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +                }
Yes it should be, good call.

2024-04-26 15:50 UTC, mofojed commented on package.json
> +    "@deephaven/tsconfig": "^0.74.0",
Yea I thought I did but I didn't. Reverting.

2024-04-26 17:47 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +    log.info('handleWidgetClose', widgetId);
Ehhh I'll switch it back, but overall we should be log.info'ing more stuff. A lot of the logs we get from customers are pretty empty, because we log everything debug.

2024-04-26 17:52 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +            log.debug('Error receiving data', e);
Yup, and that comment no longer applies. That was something else I had tried doing but wasn't what I was looking for.

2024-04-26 18:12 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +        }
Yea it should be - I've set this up now.

2024-05-03 15:40 UTC, mattrunyon requested changes

2024-05-03 15:40 UTC, mattrunyon commented on plugins/ui/src/js/src/layout/ReactPanelContentOverlay.tsx
> +/** A panel that uses the ReactPanelContentOverlayContext and if that content is set, renders it in a view with a partially transparent background */
I think this comment needs to go above the component, not at the top of the file

2024-05-03 15:40 UTC, mattrunyon commented on plugins/ui/src/js/src/styles.scss
> +.ui-error-view {
Should be able to remove this now and use the `@deephaven/components` version

2024-05-03 15:40 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/ErrorView.tsx
> +function ErrorView({
Can remove this now

2024-05-03 19:39 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
> -        // It's possible that we update and then open another panel
No longer a concern, the overlay context just renders overtop of the existing panels instead.

2024-05-09 17:44 UTC, mattrunyon commented
Noticed #85 is also fixed by this PR

The styling is inconsistent between components that didn't render and components that did

Same background color
![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/9d35fd77-a30e-4201-b17f-f4ca5f090902)

Different background color on the right and darker looking overlay
![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/8aca9158-e3ab-4e98-9136-4de0fc8a8e0d)

2024-05-09 18:31 UTC, mofojed commented
@mattrunyon On the right it is overlaid on top of content, so it appears as a shade. This is akin to when we have a table that doesn't open because of an error, and a table that gets an error, e.g.:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/dc3f50ab-caa8-48a2-94f4-b9202b2cdc46)
...though it looks like the shade there isn't done at all. Looking into it a bit further, seems like we've got different values for all the scrims: https://github.com/search?q=repo%3Adeephaven%2Fweb-client-ui%20black-opacity&type=code

For IrisGrid we use 10% (which I think is incorrect): https://github.com/deephaven/web-client-ui/blob/3de52d6fa0512792c97928f65f0b4b1080da2c49/packages/components/src/LoadingOverlay.scss#L5

For ChartPanel we use 50% (which is probably better): https://github.com/deephaven/web-client-ui/blob/3de52d6fa0512792c97928f65f0b4b1080da2c49/packages/dashboard-core-plugins/src/panels/ChartPanel.scss#L5

And then here I've got 90%.

@dsmmcken Which scrim % should be used in these cases?

2024-05-09 18:37 UTC, mattrunyon commented
In my pictures with and without content, both panels have the same color (look at the bottom of the panels). So I think that the opacity is applied at the wrong element or is not being applied if there's no content.

2024-05-09 18:44 UTC, mofojed commented
@dsmmcken here it is with 50%, what do you think?

![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/ec0cb861-b2ff-4248-891f-e2353e0446e2)

2024-05-09 18:45 UTC, mofojed commented
Light theme we may want to use something different rather than black-opacity...:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/500a72c9-ebdf-4fe5-a3af-8f06e75cc205)

2024-05-09 18:46 UTC, mofojed commented
@mattrunyon the error overlays overtop of the content if it exists and that's when a transparency is applied.

2024-05-09 18:55 UTC, mofojed commented
Used `bg-content` instead so it themes correctly, and up'd it to 80%.
![image (16)](https://github.com/deephaven/deephaven-plugins/assets/4505624/85bb760d-d7c0-4ca7-83d5-8e278aee0049)
![image (15)](https://github.com/deephaven/deephaven-plugins/assets/4505624/77e059ac-6cb8-405f-a0de-c4b578aef01e)

2024-05-09 19:01 UTC, dsmmcken commented
:shipit:

2024-05-09 19:13 UTC, mattrunyon commented
The error box itself should be more opaque (the red). If you had a more complex component under it, I think it might be too low contrast and too hard to read

2024-05-10 13:21 UTC, mofojed commented
A bit of blur would achieve the same thing:
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/e54c16bc-c908-4477-bdc3-3961f18bde67)

2024-05-10 14:23 UTC, mofojed commented
@mattrunyon Don approved with the blur.

2024-05-10 16:33 UTC, mattrunyon commented
Ok. I'm still not a fan of the red text on transparent red background. Seems like it's still too low contrast, but I'll defer to Don on this one

2024-05-10 17:08 UTC, mattrunyon approved these changes
Both light and dark theme with and without content fail the chrome contrast ratio test for accessibility (I checked the contrast ratio on the "ValueError" span w/ dev tools).

That said, it's not worth holding this up since it should be fine in most cases still. And it would be a change in web-client-ui to fix the contrast of `ErrorView`

2024-05-10 17:31 UTC, mofojed commented
@mattrunyon there's a PR for improving error view in web-client-ui: https://github.com/deephaven/web-client-ui/pull/2001

2024-05-10 17:31 UTC, merged