docs: slider, range slider, checkbox, and content
deephaven/deephaven-plugins pull request #439
Opened 2024-04-28 05:03 UTC by ethanalvizo

Closes #297, #298, #299

2024-04-28 05:12 UTC, ethanalvizo commented
@mofojed I commented out each prop that I omitted along with the reason they're not included. I thought this would be easier to see which things were left intentionally but if it's preferred to not see them at all I can change it

I also couldn't test the Content component properly. Wasn't sure how to pass in a child component into it.

2024-04-30 13:50 UTC, mofojed requested changes
Need to fix imports, this does not install/run correctly and tests are not running as it is.

2024-04-30 13:50 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/picker.py
> +from spectrum.events import *
These are invalid imports. Should have the `.` in front of `spectrum` to indicate it's a relative directory:
```suggestion
from .spectrum.layout import *
from .spectrum.validate import *
from .spectrum.events import *
```

2024-04-30 13:50 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/content.py
> +    *children: Any,
I'm confused by your comment about not knowing how to pass a child component into `Content`. You pass it in just like a child to any other component (such as `Flex` or `View`).
```python
# basic content
my_content = ui.content("Hello world")

# With a Foo component
@ui.component
def Foo():
  value, set_value = ui.use_state(True)

  return ui.checkbox('Checked', value=value, on_change=set_value)

my_foo_content = ui.content(Foo(), UNSAFE_style={'background': 'red'})
my_foo_content2 = ui.content(Foo(), flex_grow=1, UNSAFE_style={'background': 'red'})
```

2024-05-23 19:03 UTC, mofojed requested changes

2024-05-23 19:03 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/basic.py
> +def contextual_help(*children, **props):
This isn't right - `contextual_help` was [already moved to it's own file](https://github.com/deephaven/deephaven-plugins/pull/480/files). Shouldn't be adding this back in to basic.py

2024-05-23 19:03 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +    { start: float, end: float }
This is redundant, given we already have the structure defined below.
```suggestion
```

2024-05-28 16:57 UTC, mofojed approved these changes

2024-05-31 01:13 UTC, merged