feat: DRAFT ListView actions
deephaven/deephaven-plugins pull request #448
Opened 2024-04-29 21:27 UTC by bmingles

2024-05-21 20:11 UTC, mofojed requested changes

2024-05-21 20:11 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/action_group.py
> +    return BaseElement(f"deephaven.ui.components.ActionGroup", *children, **props)
We need a follow-up TODO to explicitly add/document the props for this. @AkshatJawne could take that on, get him exposed to updating some Python code in a plugin.

@AkshatJawne as a precursor to what I mean, it would be similar to this change: https://github.com/deephaven/deephaven-plugins/pull/306/files
Right now this code accepts any keyword argument, but we want to explicitly add any prop that can be used and document it. They would generally map to the same props that are available on the UI component this maps to (in this case, the [Spectrum ActionGroup](https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html#props)).

2024-05-21 20:11 UTC, mofojed commented on plugins/ui/src/js/src/elements/ElementConstants.ts
> +};
The use of prefix in the key name is a little redundant, `ELEMENT_PREFIX.icon` would be fine.

2024-05-21 20:15 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/action_group.py
> +    return BaseElement(f"deephaven.ui.components.ActionGroup", *children, **props)
Sounds good, will take a look and get started!

2024-05-22 14:42 UTC, bmingles commented
@mofojed I made suggested changes and created follow up tickets for the pydocs.

2024-05-23 16:02 UTC, mofojed approved these changes

2024-05-23 16:03 UTC, merged