feat: Cookiecutter template
deephaven/deephaven-plugins pull request #449
Opened 2024-04-30 23:07 UTC by jnumainville

Adds a templates directory as well as an inital bidirectional widget plugin.
Can test with the following command
```
cookiecutter gh:jnumainville/deephaven-plugins --directory="templates/bidirectional-widget-plugin" --checkout=256_template
```

2024-05-03 13:54 UTC, mofojed commented
@jnumainville damn the test failed because of 1 pixel... likely because of the font changes in web-client-ui: https://github.com/deephaven/web-client-ui/pull/1944

I'll update the snapshots in another PR

2024-05-03 15:36 UTC, mofojed requested changes

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/README.md
> +The plugin can be installed into a Deephaven instance with `pip install <wheel file>`.
So - we can also do `pip install -e .` to install this plugin in editable mode. That way you don't have to rebuild, you just make changes to Python, restart the server and bam it's good to go.
Though we do still need to package the JS and include it... it would be awesome if we had some way for that to work in editable mode as well... hmm.

Side note, for installation, they've already got a venv... if they wanted an isolated Deephaven environment for developing/testing this plugin, all they would need to do is `pip install deephaven-server`, and then they can just run `deephaven server` from the CLI and bring it up. Might be worth including those as default instructions, and then link out for if they want to install in an existing Deephaven installation.

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/README.md
> +obj = {{ cookiecutter.__object_name }}()
Nice, I like this example. Pretty simple. We should also have a message going the other way though... perhaps a TextField that you can type something into, and a button to send the message. Otherwise we're missing out on one half of the bidirectional communication in the example.

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/README.md
> +```
We need to include instructions on how to publish or distribute this plugin. That's where the real power is.

Also include instructions on what source files are important/where to make changes, and then what to do when you make changes and need to update the plugin.

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/js/package.json
> +    "shortid": "^2.2.16"
```suggestion
    "@deephaven/plugin": "^0.58.0"
```

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/js/vite.config.js
> +        '@deephaven/jsapi-bootstrap',
Should externalize the other `@deephaven/` packages as well: https://github.com/deephaven/deephaven-plugins/blob/f342dade60c5b62f20bc1b9b1579dc99daeac5e2/plugins/ui/src/js/vite.config.ts#L22

Add a comment with a reason why we externalize them (save bundle size, ensures the contexts work correctly with theming, etc.

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/{{ cookiecutter.__src_folder_name }}/.gitignore
> +_js/
Add a comment why this is ignored (it's where the generated JS gets put when building python).

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/js/package.json
> +  },
We should specify an `engines` field to specify what version of npm to use, and maybe even a .nvmrc?
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/js/src/{{ cookiecutter.__js_plugin_view_obj }}.tsx
> +    <div className="{{ cookiecutter.__js_plugin_view_class }}" style={{ "{" }}{{ cookiecutter.__js_plugin_view_obj_style }}{{ "}" }}>
Hmmmm we're not providing any CSS or SCSS in this template - why bother with specifying a class name here?

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/{{ cookiecutter.__src_folder_name }}/__init__.py
> +The API is designed to be similar to React, but with some differences to make it more Pythonic.
Should be the project description here I think?

2024-05-03 15:36 UTC, mofojed commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/src/{{ cookiecutter.__src_folder_name }}/{{ cookiecutter.__object_file_name }}.py
> +class {{ cookiecutter.__object_name }}:
pydocs for the object based the description. The comment above could also probably just be the description.

2024-05-03 16:12 UTC, jnumainville commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/README.md
> +This is a Python plugin for Deephaven generated from a [deephaven-plugin](https://github.com/deephaven/deephaven-plugins) template.
I could go either way. This is nice so it's all in one and if we need to update a template and plugins because of a change we can do it at the same time, but I could be convinced otherwise.

2024-05-03 16:14 UTC, jnumainville commented on templates/bidirectional-widget-plugin/cookiecutter.json
> +  "project_name": "deephaven_plugin_template",
Yeah, I agree, not much point to a different project name, much easier to restrict.

2024-05-03 16:59 UTC, jnumainville commented on templates/bidirectional-widget-plugin/{{ cookiecutter.project_name }}/README.md
> +The plugin can be installed into a Deephaven instance with `pip install <wheel file>`.
I'm hesitant to put anything about editable mode until we figure out how to make it work with package data

2024-05-10 15:09 UTC, mofojed submitted a review, later dismissed
Minor comments, but looks good.

2024-05-10 15:09 UTC, mofojed commented on templates/widget/{{ cookiecutter.python_project_name }}/README.md
> +nvm use
Typically I think `nvm install` is better, since `nvm use` won't work if you don't already have it installed.

2024-05-10 15:09 UTC, mofojed commented on templates/widget/{{ cookiecutter.python_project_name }}/README.md
> +See the [Python packaging documentation](https://packaging.python.org/en/latest/tutorials/packaging-projects/#uploading-the-distribution-archives) for more information.
We can merge this as-is, but I think we should be more explicit in the steps here for publishing.

Looking at Jupyter's template, they tell you to run twine: https://github.com/jupyter-widgets/widget-ts-cookiecutter?tab=readme-ov-file#releasing-your-initial-packages
And Streamlit has documentation also detailing how to upload to pypi using Twine: https://docs.streamlit.io/develop/concepts/custom-components/publish#upload-your-wheel-to-pypi

So link to the PyPi docs, but then provide a concrete example for this template.

2024-05-10 17:49 UTC, mofojed approved these changes

2024-05-10 18:33 UTC, merged