feat: Plotly express downsampling
deephaven/deephaven-plugins pull request #453
Opened 2024-05-07 17:21 UTC by mattrunyon

Fixes #41 

Still need to add some tests

2024-05-10 20:18 UTC, mofojed submitted a review, later dismissed

2024-05-13 13:23 UTC, mofojed requested changes
Just clean up some of the docs for the magic values.

2024-05-13 13:23 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.test.ts
> +});
Why did you bother mocking this? Could check that these events are being fired by adding a listener and ignoring the internals. With this method we're not checking that the event is actually propagating to the listener that has subscribed.

2024-05-13 13:23 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +  static MAX_FETCH_SIZE = 1_000_000;
Add some docs for these values and why they are these values.
Also `30_000` instead of just `30000`

2024-05-13 13:55 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.test.ts
> +});
Those events are part of the super class so I figured it would be up to the super to test the subscription actually gets those events. Maybe this should be mocking `ChartModel` instead? These methods aren't modified in `PlotlyExpressChartModel`

That said, it shouldn't be hard to switch to checking on the subscription

2024-05-14 18:14 UTC, mofojed requested changes

2024-05-14 18:14 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.test.ts
> +    // expect(chartModel.fireDownsampleFinish).toHaveBeenCalledTimes(0);
```suggestion
```

2024-05-15 15:33 UTC, mofojed approved these changes

2024-05-15 16:57 UTC, merged