deephaven.ui plugin prototype initial checkin
deephaven/deephaven-plugins pull request #47
Opened 2023-09-13 21:17 UTC by mofojed

- deephaven.ui plugin prototype initial checkin has some extremely basic cases implemented
- Needs my ui-plugin-prototype branch to work correctly (as that how the JS side is loading components): https://github.com/mofojed/web-client-ui/tree/ui-plugin-prototype
- The examples in the `plugins/ui/examples` folder should work
- Included DESIGN.md which is the discussion/notes from the google doc discussion
- Added some TODO notes about things that require follow up
- Install as you would other plugins

Implemented so far:
- Basic `@ui.component` decorator
  - Creates a `UINode` object when called. UINode is then "rendered" (e.g. function is run) when the `UINode` object is exported (see `UINodeMessageStream`)
  - Just exports a flat array of objects now instead of a document tree
- Basic hooks are implemented, along with tests. See the `hooks` folder for the hooks available (`use_state`, `use_memo`, `use_effect`, etc)
- `text_field` and `text` types are implemented

Next Steps:
- Create DOM that gets exported when rendering the UI node and export that the UI (JSON of each component, it's type, it's children's result, etc)
- Create HTML Element type (so we can do div, flex boxes, etc)
  - Need to correctly build DOM for this to work

2023-09-26 13:55 UTC, dsmmcken commented on plugins/ui/examples/README.md
> +    )
t being defined twice here seems wrong or confusing

2023-10-02 21:05 UTC, mattrunyon reviewed
I only reviewed JS code

2023-10-02 21:05 UTC, mattrunyon commented on plugins/ui/src/js/src/spectrum_wrappers/TextField.tsx
> +  const [value, setValue] = useState(propValue ?? defaultValue ?? '');
```suggestion
    defaultValue = '',
    value: propValue,
    onChange: propOnChange = EMPTY_FUNCTION,
    ...otherProps
  } = props;

  const [value, setValue] = useState(propValue ?? defaultValue);
```

2023-10-02 21:05 UTC, mattrunyon commented on plugins/ui/src/js/src/spectrum_wrappers/TextField.tsx
> +  );
This might make sense as a separate hook if we start using this over and over

2023-10-03 15:11 UTC, mofojed commented on plugins/ui/src/js/src/ElementPanel.tsx
> +function ElementPanel(props: ElementPanelProps) {
Yes - I'll include that in the next PR that moves a bunch of this logic - it was just in ElementPanel to use the convenient `useDashboardPanel` hook, but we'll need to put a lot of this logic in to the `DashboardPlugin` level so that we can open multiple panels.

2023-10-03 15:14 UTC, mofojed commented on plugins/ui/src/js/src/ElementPanel.tsx
> +            new JSONRPCClient(request => {
Yes, it provides an existing standard for sending messages/notifications between client/server. The grpc layer does not require a response per request, but with json-rpc there is a spec for a message that requires a response which is useful for callbacks.

2023-10-03 15:24 UTC, mofojed commented on plugins/ui/src/js/src/FigureObject.tsx
> +        flexBasis: 100,
Hm, I thought it converted it to `100px`, but I'll double check. This PR doesn't address many of the flexbox issues with layouts though (it seems like Tables and Figures don't just work in a flexbox layout).

2023-10-03 15:30 UTC, mofojed commented on plugins/ui/src/js/src/spectrum_wrappers/ActionButton.tsx
> +  const { onPress: propOnPress, ...otherProps } = props;
onPress comes from the python side, we automatically pass through all snake case props so you would define an action_button with `on_press=my_callback` and that would get passed in as the `onPress` here.

Wrappers are only necessary when we need to massage the interaction a bit. In this case, it's because the `onPress` method from Spectrum passes in a `PressEvent`, and that doesn't serialize correctly automagically so it was throwing an error when calling the callback; this wrapper is just ignoring the `PressEvent` entirely and just calling the callback, which is also not great because it is losing information (e.g. if a modifier key such as `ctrlKey` was down when the button was pressed).

I'll add a comment below to that effect; we probably want a more general solution for automatically serializing `PressEvent` (and other events) such that we don't need to write wrappers for buttons.

2023-10-03 15:52 UTC, mofojed commented on plugins/ui/src/js/src/SpectrumElementUtils.ts
> +  Checkbox,
ToggleButton will need it for `onPress` to be handled correctly; in the examples I've used `onChange` though, which just provides a new `isSelected` boolean value that can be serialized.

I've added a TODO with #76 to properly serialize `PressEvent` and other events, and hopefully we can do it in a generic enough way that we don't need to provide wrappers for every component that has events in callbacks.

2023-10-03 16:12 UTC, mofojed commented on plugins/ui/src/js/src/spectrum_wrappers/TextField.tsx
> +  );
Yes, this and also event handlers will probably want some sort of hook or wrapper that we can re-use.

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/BaseElement.py
> +            raise ValueError("Cannot provide both children and props.children")
Just curious, is there any possibility that a prop could be named children that wasn't actually children or is that just something we are going to say is a no-no

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/BaseElement.py
> +        if len(children) == 1:
This seems a bit odd. Is there any benefit to convert a single child to an element instead of a list?

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/FunctionElement.py
> +    def __init__(self, name: str, render: Callable[[], List[Element]]):
General comment: I prefer using generics in types if valid such as with `list` instead of `List`, but I know that starts at 3.9 (PEP 585). We can use `from __future__ import annotations` on versions back to 3.7 though.

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/spectrum/flex.py
> +    gap: Optional[Union[str, int, float]] = None,
General comment: I prefer the PEP 604 way of defining unions, although it was added in 3.10. Can use from __future__ import annotations though.

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/FunctionElement.py
> +        context.start_render()
it might be a good idea to make context an actual context manager, then you can do 
```
with context:
    children = self._render()
```

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
> +        # If we don't, no error is reported but the listener never fires
Can take a look at my bidirectional plugin review for a better (well, kind of better as it's still hacky) way to manage liveness scope.

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        self._update_count += 1
it seems like there could be some race conditions in these updates, such as with this update count

2023-10-03 19:55 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/renderer/NodeEncoder.py
> +            callable_id = self._callables.index(cb)
Index functions here and on line 79 seem like they could be quite slow with lots of objects. Maintaining a dictionary with index might be a good idea. You can use the `id()` function as a key. There isn't really any reason you would need the try catch block either then. 
```
obj_id = id(callable)
callable_id = self._callables_dict.get(obj_id, len(self._callables_dict))
self._callables_dict[obj_id] = callable_id
```
Maybe you could use `id()` more directly as well depending on your goals, with a set instead.

2023-10-04 14:03 UTC, mofojed commented on plugins/ui/examples/samples/stock_rollup.py
> +    get_by_filter(sym=True, exchange=False) == ["sym"]
Not nitpicky at all. Is that a standard defined in the styleguide? I can't seem to find it in the Google styleguide: https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
Though I do think it makes sense, and better than what I have now.

2023-10-04 14:04 UTC, mofojed commented on plugins/ui/examples/samples/double_table.py
> +
Yea I wasn't sure about providing separate samples files, or just including the text inline in the examples/README.md. It's in both spots right now, which is not ideal. I probably don't need these sample files at all, and just include the text in the README.md, then it's with the explanations. Any objection/alternative to me just deleting these example files @jnumainville ?

2023-10-04 14:12 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_state.py
> +def use_state(initial_value):
React doesn't require it: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/570de940196213ea63e8544863a6076db94db75d/types/react/v17/index.d.ts#L959C17-L959C17
I'll default to `None`, that seems reasonable. I'll also add the generic typing in here.

2023-10-04 14:24 UTC, mofojed commented on plugins/ui/examples/samples/stock_widget_table.py
> +        else ui.illustrated_message(
How do you mean? It already is a component?
Or do you mean like an optional table view type of component? Perhaps we could do that in `ui.table`... hm

2023-10-04 14:28 UTC, jnumainville commented on plugins/ui/examples/samples/double_table.py
> +
I'm fine with deleting them

2023-10-04 14:38 UTC, jnumainville commented on plugins/ui/examples/samples/stock_rollup.py
> +    get_by_filter(sym=True, exchange=False) == ["sym"]
I don't see it in the style guide either, either in support or against, although they have examples without it. I think regardless it's a good paradigm.

2023-10-04 14:41 UTC, jnumainville commented on plugins/ui/examples/samples/stock_widget_table.py
> +        else ui.illustrated_message(
I meant as in this illustrated_message instance with it's children. Not a huge deal, but using conditional expressions with long functions like this isn't my favorite as it forces you to jump around. Then you'd have something like `source.where(... if sym and exchange else my_illustrated_message())`

2023-10-04 14:43 UTC, mofojed commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +        return component.__class__.__module__ + "." + component.__class__.__qualname__
Yea it's the same except for that - I wasn't sure I could write it more elegantly really with a shared function, so just kept it separate.

2023-10-04 14:44 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/flex.py
> +            "baseline" "first baseline",
Uhhh I'll blame Copilot - but why wasn't that an error? Python just auto concatenates two strings next to each other? Ugh

2023-10-04 14:44 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/flex.py
> +    direction: Literal["row", "column", "row-reverse", "column-reverse"] = None,
Yup bigtime. Whatever improvements you think we can include to automate how we define these things would be great.

2023-10-04 14:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/BaseElement.py
> +        if len(children) == 1:
Yes, some React elements explicitly require a single item as a child, and will fail even if you pass a list with one item. I'll add a comment, as that is odd.

2023-10-04 14:50 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/flex.py
> +    gap: Optional[Union[str, int, float]] = None,
Yup great idea. I prefer that syntax much better, and was simply unaware.

2023-10-04 14:57 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_table_listener.py
> +        # If we don't, no error is reported but the listener never fires
Yea - I thought there was also a fix going in for this, so I shouldn't even need this anymore? In any case, I think I'm just going to remove this hook for now - we can add it later (correctly).

2023-10-04 15:00 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        self._update_count += 1
I'm not sure there could be - if the stream receives a call for a callable that updates the state, the renderer will render again and call this right away, which will invalidate any previous callbacks. Or how would the race condition occur?

2023-10-04 15:12 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        self._update_count += 1
Since the updates use the update count, is it possible for this function to be called in rapid succession such as, for example, line 102 is hit by one call, then line 102 is hit by another call, then line 103 is hit by them but now that update count is the same for both updates and as such the `id_prefix` is the same as well. 
That's what I was thinking but I am not sure if that's a problem, I'm really looking at this in isolation.

2023-10-04 16:23 UTC, mofojed commented on plugins/ui/src/deephaven/ui/renderer/NodeEncoder.py
> +            callable_id = self._callables.index(cb)
I just did a dict like you were suggesting.

2023-10-04 19:51 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +        self._update_count += 1
It should not be a problem. Side note, we will want to batch state updates for the renderer at some point, but I think that's an optimization that isn't necessary for alpha.

2023-10-04 19:57 UTC, mofojed commented on plugins/ui/src/js/src/FigureObject.tsx
> +        flexBasis: 100,
This does convert to `100px`.

2023-10-04 20:05 UTC, mattrunyon commented on plugins/ui/src/js/src/FigureObject.tsx
> +        flexBasis: 100,
Interesting. I think we should use `100px` just to be explicit about it

2023-10-05 16:50 UTC, mattrunyon requested changes

2023-10-05 16:50 UTC, mattrunyon commented on plugins/ui/src/js/package.json
> +    "url": "git+https://github.com/deephaven/deephaven-js-plugins"
These URLs are out of date

2023-10-05 16:51 UTC, jnumainville approved these changes

2023-10-05 17:00 UTC, mattrunyon approved these changes

2023-10-05 17:08 UTC, merged