Update json plugin for deephaven plugin refactor
deephaven/deephaven-plugins pull request #48
Opened 2023-09-14 16:40 UTC by devinrsmith

2023-09-14 18:18 UTC, jnumainville commented
We're using the black code formatter now, through a pre-commit hook for easy use - https://github.com/deephaven/deephaven-plugins#development
That said, just running black directly in this case might be more convenient

2023-09-14 18:24 UTC, devinrsmith commented
> We're using the black code formatter now, through a pre-commit hook for easy use - https://github.com/deephaven/deephaven-plugins#development That said, just running black directly in this case might be more convenient

It might be better to hook up _git_ hooks? You could automate the venv or just call `pre-commit` and link to how to set it up if it wasn't already. https://github.com/deephaven/demo-app/tree/main/git-hooks

2023-09-14 19:04 UTC, devinrsmith commented
> The `pre-commit install` step does set up a git hook, but maybe we could simplify those steps further

Ah, okay. That seems okay. Haven't used that tool before, looks neat.

2023-09-14 20:21 UTC, jnumainville approved these changes

2023-09-20 16:00 UTC, mofojed requested changes

2023-09-20 16:16 UTC, devinrsmith commented on plugins/json/.flake8
> +[flake8]
flake8 is a linter, while black is a formatter. They can be used in combination, but they do serve separate purposes. https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8.

If we want to remove flake8 from here, we should do that as a separate PR IMO.

2023-10-04 13:53 UTC, mofojed approved these changes

2023-10-04 14:32 UTC, merged