fix: Reset state when new instance of widget created
deephaven/deephaven-plugins pull request #486
Opened 2024-05-22 15:45 UTC by mofojed

- We were using the same initial data regardless of how long the widget was opened
- We want to keep the same WidgetHandler and panelIds so that panels open in the same spot
- Want to start with a fresh state
- Freeze the initialData whenever the fetched widget is updated
- Fixes #401
- Tested using the steps in the description

2024-05-23 14:23 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +  // const [initialData] = useState(initialDataProp);
Should probably delete this line

2024-05-23 14:46 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  let fetchResolve1: (value: dh.Widget | PromiseLike<dh.Widget>) => void;
Not sure if / when we can use it, but `Promise.withResolvers` would be nice here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers

2024-05-23 15:04 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +      fetch: fetch2,
Is the change to `fetch` what you want to test here or just the change to `widget`?

2024-05-23 15:16 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +    listener({
I would probably break out a helper function to make this a little easier to read. Something like:

```suggestion
    listener(makeSetStateResponseEvent(1))
```

2024-05-23 15:16 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +    listener({
I would probably break out a helper function to make this a little easier to read. Something like:

```suggestion
    listener(makeDocumentUpdatedEvent(document1))
```

2024-05-23 15:18 UTC, bmingles requested changes
App code change looks good. Left a couple of comments / questions on the test

2024-05-23 15:19 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetTestUtils.ts
> +  state: Record<string, unknown>
Maybe rename `state` to `_state` if it is intentionally ignored

2024-05-24 13:31 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  let fetchResolve1: (value: dh.Widget | PromiseLike<dh.Widget>) => void;
That function looks very useful, about time!

2024-05-24 14:58 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetTestUtils.ts
> +  state: Record<string, unknown>
Don't need to pass it in at all

2024-05-24 15:14 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  let fetchResolve1: (value: dh.Widget | PromiseLike<dh.Widget>) => void;
Ah dangit, we can't use it until we update Node, or if we polyfill it, it's only in v22:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers#browser_compatibility

I'll omit for this change.

2024-05-24 15:28 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +    listener({
I think I missed this before, can these 2 listener calls use the new helpers?

2024-05-24 15:30 UTC, bmingles commented on plugins/ui/src/js/src/widget/WidgetHandler.test.tsx
> +  let fetchResolve1: (value: dh.Widget | PromiseLike<dh.Widget>) => void;
Ah yeah sorry. Was mostly musing. I think TypeScript typings don't have it yet either

2024-05-24 18:30 UTC, merged