initial draft of dx docs
deephaven/deephaven-plugins pull request #487
Opened 2024-05-22 20:44 UTC by dsmmcken

2024-05-23 19:47 UTC, dsmmcken commented
@jnumainville I am probably missing some types for rough-in too. I have the images, but not the .md files for all current types.

2024-05-28 16:49 UTC, jnumainville requested changes

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/icicle.md
> +4. **Data Hierarchy Understanding**: They provide an intuitive means to understand the hierarchical relationships between different categories or levels within a dataset, making them useful in variou
This is one where there's a lot of repeating the same point, just with different words.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line-3d.md
> +- **Surface Plots**: When visualizing continuous data over a 3D space, surface plots may be more appropriate, as they create a continuous surface representation.
We don't have surface plots currently

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line-polar.md
> +4. **Circular Data Exploration**: They can be used to explore and analyze data where the angular or periodic nature of the data is a significant aspect, making them useful in fields like meteorology,
This one strikes me as very repetitive

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line-ternary.md
> +3. **Optimization Studies**: Ternary line plots can be applied in optimization studies to understand how adjustments in the proportions of three components impact the overall composition, aiding in i
"Optimization studies" is a bit scholarly and broad. If we want to point that out I think a little more detail would be good.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +Visualize the relationship between two variables. Defined as an x and y pair supplied using column names.
```suggestion
Visualize the relationship between two variables. Column names are passed in directly as `x` and `y`.
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +# Create a basic scatter plot by specifying the x and y column
```suggestion
# Create a basic line plot by specifying the x and y column
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +dog_prices = my_table.where("sym = `DOG`")
It would be nice if we had an example where no filtering at all is required as it's not strictly "plotting" but it doesn't bother me that much.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +my_table = dx.data.stocks() # import the example stock market data set
```suggestion
stock_table = dx.data.stocks() # import the example stock market data set
```

I think a more descriptive variable name is helpful.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +Plot values by group. The query engine performs a `parition_by` on the column provide to the color argument and assigns a unique color to each group.
```suggestion
Plot values by group. The query engine performs a `partition_by` on the column provide to the color argument and assigns a unique color to each group.
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +    color_discrete_sequence=["salmon", "#fffacd", "rgb(100,149,237)"]
Excellent color choice

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +Symbols can be statically assigned, assigned to a group as part of a `parition_by` operation drawing from a sequence, or from a map. See the symbol list for all available symbols.
```suggestion
Symbols can be statically assigned, assigned to a group as part of a `partition_by` operation drawing from a sequence, or from a map. See the symbol list for all available symbols.
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +my_table = dx.data.iris() # import the example iris data set
```suggestion
iris_table = dx.data.iris() # import the example iris data set
```
This is more of a general comment, but another example of a more ilustrative table name

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +
I think it would be useful to have an example of `by` as well, controlling both color and symbol jointly.
At least one case of `by` is broken though.
https://github.com/deephaven/deephaven-plugins/issues/407

Size and numeric color axes are other useful ones.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +<!-- TODO: labels has a bug, check it works now -->
I think it's still open 
https://github.com/deephaven/deephaven-plugins/issues/6
Quick fix but haven't had capacity for dx

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +    # Parition color by sym
```suggestion
    # Partition color by sym
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +Combines a line plot and a scatter plot to use as event markers indicating the maximum peak in each series.
You could also do `markers=True` for some such cases. `line` should support `size` and such

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/line.md
> +density_heatmap = dx.density_heatmap(my_table, x="sepal_width", y="sepal_length")
We don't have this yet, and it's non-trivial. Maybe comment this Large Data Set section out for now.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/ohlc.md
> +OHLC (Open-High-Low-Close) plots, are a common data visualization tool used in finance to represent the price data of a financial instrument over a specific time frame. Similar to Candlesticks, they
A link to candlesticks and vice versa is a good idea since they're so similar

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/plot-by.md
> +To plot multiple series from a table into a single chart, use the `by` parameter. This parameter accepts a column name or a list of column names. The chart will be partitioned by the values in the sp
A bit more detail:
`by_vars` can be used to tweak which variable `by` targets, so you could pass `by_vars=["color", "symbol"]` for example.
`by` always does a plot by, whereas `color` (in cases where it makes sense, like scatter) will create a numeric color axis if the column is numeric. `color_discrete_map="by"` will force it to a plot by though.
In the part `The chart will be partitioned by the values in the specified column(s), with one series for each unique value` I think it's worth expanding that the "values" are a cartesian product of the values in the columns (although in a less jargony way)

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/README.md
> +
Themed would be good to specify here as well

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/scatter-polar.md
> +3. **Angular or Periodic Data Relationships**: Polar scatter plots aid in exploring relationships and correlations in data with angular or periodic dependencies, making them suitable for applications
Same comment as line_polar - very repetitive

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/scatter-ternary.md
> +3. **Optimization Studies**: Ternary scatter plots aid in optimization studies to understand how adjustments in the proportions of three components impact the overall composition, making them valuabl
Same comment as line_ternary

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/scatter.md
> +Symbols can be statically assigned, assigned to a group as part of a `parition_by` operation drawing from a sequence, or from a map. See the symbol list for all available symbols.
```suggestion
Symbols can be statically assigned, assigned to a group as part of a `partition_by` operation drawing from a sequence, or from a map. See the symbol list for all available symbols.
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/scatter.md
> +my_table = dx.data.iris() # import the example iris data set
Random thought I happened to have here - I know the datasets are very much tied to the examples we are making, but it could be worth having a separate page that explains a bit more about the data sets.

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/timeline.md
> +title: Timelint Plot
```suggestion
title: Timeline Plot
```

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/timeline.md
> +Timeline plots in offer a means to visualize time-related data, displaying events, durations, or activities along a time axis. Developers can utilize these plots for applications that require users t
Worth pointing out that this is also known as a Gantt plot

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/treemap.md
> +Treemap plots are a data visualization technique used to represent hierarchical data in a space-filling manner. They display data as nested rectangles or squares, where the size and color of each rec
Treemap, sunbursts, and icicles are more or less identical - worth linking?

2024-05-28 16:49 UTC, jnumainville commented on plugins/plotly-express/docs/violin.md
> +A violin plot is a data visualization that combines a box plot with a rotated kernel density plot to provide a comprehensive representation of the data distribution. It offers a detailed view of the
Hmm, for some of these plot groups where they are so similar (strip vs box vs violin or treemap vs icicle vs sunburst for example) it might be worth having a direct comparison page, maybe with a table or something. Doesn't have to be done now but could be worth it because some of the nuances with these are so subtle.

2024-05-28 18:43 UTC, mofojed commented on plugins/plotly-express/docs/README.md
> +[![Scatter plot](_assets/plot_icons/scatter.svg)](scatter.md)
We should probably have the name visible underneath as well, so that you can Find it in the doc easily.

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/CONTRIBUTING.md
> +# Contibuting to our plotting docs
```suggestion
# Contributing to our plotting docs
```

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/CONTRIBUTING.md
> +- Plot by
plotBy / plot_by? or explain what "plot by" means

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/README.md
> +This page contains a collection of links to examples demonstrating 24 different plot types and usage scenarios. You can explore these examples to gain a better understanding of how to leverage the li
do we need a specific number?

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/README.md
> +We would like to express our gratitude to the Plot.ly and the Plotly Express team for creating a remarkable plotting library and making it open-source. Their work forms the foundation of the Deephave
```suggestion
We would like to express our gratitude to the Plotly and the Plotly Express team for creating a remarkable plotting library and making it open-source. Their work forms the foundation of the Deephaven Plotly Express plugin.
```

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/area.md
> +
Advantages of area plots include:

for consistency

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/box.md
> +Advantages that make box plots a valuable tool in data visualization and statistical analysis are:
```suggestion
Advantages of box plots include:
```

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/candlestick.md
> +Interpreting a candlestick chart involves understanding the visual representation of price data within a specific time frame. Each candlestick consists of a rectangular "body" representing the price
chart or plot? maybe stick to plot

2024-05-30 20:22 UTC, margaretkennedy commented on plugins/plotly-express/docs/candlestick.md
> +Candlestick charts are particularly useful when:
again, stick to same phrasing; I can make edits like that once the examples are in.

2024-05-31 14:30 UTC, margaretkennedy commented on plugins/plotly-express/docs/README.md
> +
```suggestion

:::caution
Please note these docs are under active development. We plan to continue adding examples and descriptions in the coming weeks. 
:::

```

2024-05-31 14:35 UTC, dsmmcken commented on plugins/plotly-express/docs/README.md
> +
Rejecting this suggestion as these docs aren't being published on our site, so no warning is necessary.

Also, I intend for us to adopt github style markdown warnings going forward as it's a new standard. That would look like this:

```
> [!CAUTION]  
> Negative potential consequences of an action.
```

> [!CAUTION]  
> Negative potential consequences of an action.

2024-05-31 14:40 UTC, dsmmcken commented on plugins/plotly-express/docs/CONTRIBUTING.md
> +````
https://github.com/deephaven/deephaven-plugins/issues/501

2024-06-03 14:47 UTC, dsmmcken commented on plugins/plotly-express/docs/scatter.md
> +my_table = dx.data.iris() # import the example iris data set
yes, absolutely.

2024-06-03 14:47 UTC, dsmmcken commented on plugins/plotly-express/docs/README.md
> +This page contains a collection of links to examples demonstrating 24 different plot types and usage scenarios. You can explore these examples to gain a better understanding of how to leverage the li
no, and could remove.

2024-06-03 14:48 UTC, dsmmcken commented on plugins/plotly-express/docs/candlestick.md
> +Interpreting a candlestick chart involves understanding the visual representation of price data within a specific time frame. Each candlestick consists of a rectangular "body" representing the price
plot would be preferred wording for consistency.

2024-06-03 14:48 UTC, dsmmcken commented
Joe's suggestions are good and should be address in follow up PRs if we want to merge this now, and let Alex keep grinding.

2024-06-03 14:49 UTC, dsmmcken commented on plugins/plotly-express/docs/README.md
> +[![Scatter plot](_assets/plot_icons/scatter.svg)](scatter.md)
Yeah, I need to lookup how to add a caption using GFM.

2024-06-03 14:59 UTC, alexpeters1208 commented
> Joe's suggestions are good and should be address in follow up PRs if we want to merge this now, and let Alex keep grinding.

Noted. If we could do without resolving these comments so that I can navigate the feedback as I work through, that would be good.

2024-06-03 16:11 UTC, jnumainville approved these changes

2024-06-03 16:16 UTC, merged