feat: UI Tabs Improvement
deephaven/deephaven-plugins pull request #489
Opened 2024-05-23 17:57 UTC by AkshatJawne

Based on https://github.com/deephaven/deephaven-plugins/issues/191 and https://github.com/deephaven/deephaven-plugins/issues/273

**_Information about changes implemented:_**
- Modified `ui.tabs` component to now take in `ui.tab_panel` 's, where the content and title is required

- The `ui.tab_panel` now creates the corresponding `tab_list` and `tab_panel` components under-the-hood, eliminating the need for the user to explicitly create these

- The title can take in a string, or can be an icon, but regardless, **is required** (opted to not include logic for automatic naming, because there is no guarantee that the tabs are related, so thus, it becomes weird to have something like ie. Unnamed Tab 1, Unnamed Tab 2, etc.)

- Have a testing example in Design file (thought I would get some more clarity on the type of design desired before adding more)

**_Steps Moving Forward:_**

- I have currently taken the approach of not creating a separate JS component and having the logic there, because I was of the opinion that this way, we can leverage existing code to get the same functionality
&ensp; - Although, I do understand the idea behind doing this on the client-side (and that would make the development here &ensp;  a lot easier), so am open to switching approaches

- With regards to the key, I currently have it as **optional**, but would love to hear ideas as to how this could be implemented (does the tabs component itself require a key, do each of the tab_panel's require a key, should it be optional for the tab_panel 's but mandatory for the tabs -> **lots of different permutations here**)

- If we do choose to take the approach of implementing on the python-side, there is an important design decision of whether we want to completely eliminate the `tab_list` and `tab_panel` components as previously suggested, but I struggle to see how this could be implemented (given that natively, the `Tabs` component on spectrum expects `tab_list`'s and `tab_panel`'s)

2024-05-23 19:17 UTC, mofojed requested changes

2024-05-23 19:17 UTC, mofojed commented on plugins/ui/DESIGN.md
> +Potential example of how new tabs component could be implemented, no longer needing to specify tab_list and tab_panels
We should be showing/mocking out a couple more cases here, answering a few questions:
- How do I use with `on_selection_change`, how do I assign keys to each tab?
- How do I create a title with both an icon and text?
Check out the React Spectrum page for Tabs for some examples: https://react-spectrum.adobe.com/react-spectrum/Tabs.html
- There's a whole bunch of layout props on [`TabPanels`](https://react-spectrum.adobe.com/react-spectrum/Tabs.html#tabpanels-props) and [`TabList`](https://react-spectrum.adobe.com/react-spectrum/Tabs.html#tablist-props) that currently cannot be set. Need to validate that is okay or provide a way to pass in those props (e.g. a keyword arg on `ui.tabs` for `panel_props` and `list_props` maybe?

2024-05-23 19:17 UTC, mofojed commented on plugins/ui/DESIGN.md
> +            "Tab 1",
We should need to wrap the contents in `ui.flex`, and add the `flex_grow`s, it should be done automatically like default (similar to how we have tables size right now).

Also, add some comments about what should appear on screen in these cases, e.g. Header text displayed above a table.

2024-05-23 19:23 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +Potential example of how new tabs component could be implemented, no longer needing to specify tab_list and tab_panels
Sounds good, will do so. 

I had initially refrained from adding too many test cases with explanations, in the case we wanted to take a completely different approach, but I agree, in the interim, it is valuable to add more detailed explanations with more test cases.

2024-05-23 19:27 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +            "Tab 1",
> We should need to wrap the contents in ui.flex, and add the flex_grows, it should be done automatically like default (similar to how we have tables size right now).

Sorry, should or should't? Just wanted to clarify because currently the content is wrapped in a `ui.flex` and does not require for us to set the `flex grow`, it is done by default, but my assumption is that you are stating that the `flex grows` **should be** added by default and that we **do not need** to wrap the content in a `ui.flex`.

If that is the case, I just wanted to clarify that we do not need to wrap the content in the `ui.flex`, I had added it to show how we potentially could wrap it in one if we wanted, but in the tabs below this one, I have not wrapped it in a `ui.flex`, and it works both ways.

2024-05-24 13:43 UTC, dsmmcken commented
would it make sense to re-use ui.item as that currently is the primiative you stick inside tab_panels/tab_list

So one could do something like:

```py
ui.tabs(
   ui.item(...., label="C"), # label used as key.
   ui.item(..., label="B" )
 )
 ```

I don't like it as much but we could also assume position based and do something like:

```py
ui.tabs(
   ui.item(....),
   ui.item(...,)
   labels=["A", "B"]
 )
 ```

2024-05-24 13:51 UTC, mofojed commented on plugins/ui/DESIGN.md
> +Potential example of how new tabs component could be implemented, no longer needing to specify tab_list and tab_panels
Writing a few example cases now is quicker than writing an implementation and finding out it doesn't allow how we want to use it later.

2024-05-24 13:52 UTC, mofojed commented on plugins/ui/DESIGN.md
> +            "Tab 1",
Yea I had a typo above, fixed. We should _not_ have to explicitly add the wrap. We can show both cases as examples, but the first most basic example shouldn't require it.

2024-05-24 13:55 UTC, mofojed commented
First of all, we should document `ui.item` so it has proper autocomplete. Would use `title` instead of `label`, and we'd use the `key` prop for the key. We could potentially re-use `ui.item`, seems like `tab_panel` won't have anything special for it (since all the layout props will be on `ui.tabs` top level).
As for omitting the `ui.item` and having a `labels` prop... not sure I like that... hmm. Providing a title for a tab is required, since we can't really automatically name them (unless we just go with "Tab 1", "Tab 2", but that's lame)... having a separate `labels` prop means you need to make sure the array length matches the length of your children, and is kind of weird... I'd just stick with requiring explicitly add `ui.item` I think.

2024-05-24 13:57 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +            "Tab 1",
Right, that makes sense, thanks for the clarification

2024-05-24 13:58 UTC, dsmmcken commented
Having to specify a key and title sucks, if both are the same it could be assumed. I thought we did something similar with picker on assuming keys.

And I thought we were gonna not use title, and use label instead for everywhere to be consistent?

2024-05-24 14:00 UTC, dsmmcken commented
omitting ui.item feels equivalent to omitting ui.panel which you can also do... but end up with an "untitled" tab.

2024-05-24 14:04 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +Potential example of how new tabs component could be implemented, no longer needing to specify tab_list and tab_panels
Yeah, am currently working through, implementing the logic is seeming increasingly tougher on the python side. Seriously considering switching to having a React component handle this, because it is in incredibly difficult to try and pass values from one component to the other, and or use contexts. What do you think? @mofojed

2024-05-27 18:32 UTC, AkshatJawne commented
Close to completion here, struggling with some type issues when passing children to the TabPanels and TabList components, spent about 2.5 hours on different solutions to try and work around it, but still hav not been able to find a way. Will continue trying to solve this after lunch, and will update with progress. 

In the interim, I put up these two docs PR's: https://github.com/deephaven/deephaven-plugins/pull/492 and https://github.com/deephaven/deephaven-plugins/pull/493

2024-05-27 19:48 UTC, mofojed requested changes
This change should _just_ be in the `DESIGN.md` until we have the syntax nailed down and approved. As mentioned in my [previous comment](https://github.com/deephaven/deephaven-plugins/pull/489/files#r1613521280):
> Writing a few example cases now is quicker than writing an implementation and finding out it doesn't allow how we want to use it later.

Write some examples. Read the other comments on this PR from Joe and Don with their input. Some examples that were not addressed from another of my [previous comments](https://github.com/deephaven/deephaven-plugins/pull/489#discussion_r1612188641):

- How do I use with on_selection_change, how do I assign keys to each tab?
- How do I create a title with both an icon and text? Check out the React Spectrum page for Tabs for some examples: https://react-spectrum.adobe.com/react-spectrum/Tabs.html
- There's a whole bunch of layout props on [TabPanels](https://react-spectrum.adobe.com/react-spectrum/Tabs.html#tabpanels-props) and [TabList](https://react-spectrum.adobe.com/react-spectrum/Tabs.html#tablist-props) that currently cannot be set. Need to validate that is okay or provide a way to pass in those props (e.g. a keyword arg on ui.tabs for panel_props and list_props maybe?

You only have one example, and it does not address these concerns. We need to nail down the syntax and have it approved before doing the implementation, or you're likely going to need to re-do it.

2024-05-27 19:55 UTC, AkshatJawne commented
@mofojed My apologies, I misinterpreted your previous comment, thinking that when you said have the examples ready, that meant have the examples and also the code to test the examples. I will have the changes to the `DESIGN.md `pushed shortly.

2024-05-27 20:35 UTC, AkshatJawne commented
Have added examples that I feel all previously outlined questions, please let me know if you have any comments/suggestions/questions.

2024-05-28 13:39 UTC, mofojed commented on plugins/ui/DESIGN.md
> +import deephaven.ui as ui
```suggestion
from deephaven import empty_table, ui
```

2024-05-28 13:42 UTC, mofojed commented on plugins/ui/DESIGN.md
> +            key="Key 2",
In this first case, I think we should show the basic case - you shouldn't _need_ to pass in a `key` parameter, that's only necessary if you want to use `on_selection_change`. If not provided we should automatically generate it based on the title provided.

2024-05-28 13:44 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        ui.item(title="Tab 1", content="Content 1", key="Key 1"),
`ui.item` doesn't have a `content` keyword argument: https://github.com/adobe/react-spectrum/blob/2bda4c971dd557be7ecc44614569a8281e6cb6dd/packages/%40react-types/shared/src/collections.d.ts#L17
We should be passing this in as `children`, much like React. We handle children in the Python definitions as the `*args` parameters (e.g. first parameters before any keyword arguments), so should be like:
```suggestion
        ui.item("Content 1", title="Tab 1", key="Key 1"),
```

2024-05-28 13:45 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        on_selection_change=lambda key: print(f"Selected key: {key}"),
We may want to just use `on_change` instead of `on_selection_change` for brevity.

2024-05-28 13:45 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        ui.item("Tab 2", "Content 2", key="Key 2"),
Don't use position args for title, just for children.
```suggestion
        ui.item("Content 1", title="Tab 1", key=""),
        ui.item("Content 2", title="Tab 2", key="Key 2"),
```

2024-05-28 19:25 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        on_selection_change=lambda key: print(f"Selected key: {key}"),
It would just be an alias to `onSelectionChange`, similar to what we do `list_view`: https://github.com/deephaven/deephaven-plugins/blob/ef115c98f73b1d0dff5ace02d0eea9308b5b3687/plugins/ui/src/deephaven/ui/components/list_view.py#L61

2024-05-28 19:25 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        },
Could probably just name these `list_props` and `panel_props`, since they're already within the `.tabs` component.
@dsmmcken do you think this is an appropriate way to pass props to the `TabList` and `TabPanels` components?

2024-05-28 20:05 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +        },
If we don't deprecate the verbose way of creating tabs, we could exclude those props from here, and if you need them then do the verbose way of specifying tabs.

2024-05-28 20:39 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        },
I hadn't considered that, but that makes sense... just have a short form way of providing tabs using `ui.item`, or specify `tabs_list` and `tab_panels` if you need more options?

2024-05-28 20:49 UTC, mattrunyon commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1"),
I saw in a previous iteration this had `content` as a keyword arg. While I don't want it called content, we should check if `children=["Content 1"]` works. I think it should just by the nature of how we handle it in Python.

I tend to like props then children instead of children then props in cases like this

2024-05-28 20:50 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1"),
Hmm, yeah I think this is a good idea, will look into this.

2024-05-28 20:51 UTC, mattrunyon commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", title="Tab 2", key="Key 2"),
I'm confused why it says this causes an error? Is it just because the key is an empty string? Does key default to title? I think it should as I'd bet like 99% of use cases people have unique titles anyway

2024-05-28 20:51 UTC, mattrunyon commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", title="Tab 2", key="Key 2"),
I'm confused why it says this causes an error? Is it just because the key is an empty string? Does key default to title? I think it should as I'd bet like 99% of use cases people have unique titles anyway

2024-05-28 20:53 UTC, mattrunyon commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1"),
I think it should just work with how our component class is set up, but not entirely sure

2024-05-28 20:56 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        },
Would it be beneficial to have both though? It could cause confusion if we could have tabs that would be specified though `tabs_list` and `tab_panels`, and then also potentially, separately through `ui.item`.

Also, here would we allow both, or would it be such that you can either declare the `tabs_list` and `tab_panels` , or through the items? I feel like the latter is more clearer, but I also see the case for the former

2024-05-28 20:56 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", title="Tab 2", key="Key 2"),
I do have it such that the key defaults to the title, but I believe that if the user does not want to set the key (or wants to have it set by default), they should set the key to anything. Having an empty key cause an error makes it so that they must either choose a key, or let us set it by default to the title

2024-05-28 21:01 UTC, bmingles commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", title="Tab 2", key="Key 2"),
Our code uses `title` as the key if none is provided for `Section`, but we don't do any special handling for `Item` title. If you are seeing it become the key, then Spectrum must be doing that.

2024-05-28 21:04 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", title="Tab 2", key="Key 2"),
I understand, what I mentioned above is not actually happening, but is the behaviour that I would propose. So, if someone chose to not pass in key, it defaults to the title. If someone chooses to pass in a blank key, then I think it should cause an error, since either they should pass one in, or let the tab set it to the title by default.

2024-05-28 21:08 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", title="Tab 2", key="Key 2"),
Right, yeah that makes sense. I will adjust my example in the next commit accounting for all of the recent discussion, indicating that an empty string. key would be valid, but having two tabs with an empty string key would cause an issue.

2024-05-30 15:03 UTC, mofojed commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1"),
@mattrunyon / @bmingles Our docs pass in children as docs, that is the style we are using. Please don't promote passing it as a keyword argument.

2024-05-30 19:09 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +        },
I would say users should be able to either:
1. be lazy and pass ui.items directly to ui.tabs
2. use the current way with ui.tab_list ui.tab_panels if they need props for those elements

I wouldn't also expose these as props on tabs.

2024-05-30 19:29 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1", key="Key 1"),
I would expect this to error.

tabs should either receive a tab_lists and tab_panels or only items. A combiniation like this would be invalid.

2024-05-30 19:29 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +        },
Remove.

2024-05-30 19:29 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1", key="Key 1"),
Should have an example showing how one could do the verbose way though

2024-05-30 19:30 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        ui.item("Content 1", title="Tab 1", key="Key 1"),
Yeah had spoken to @mofojed and had this clarified, will have that example updated in new commit

2024-05-30 19:56 UTC, AkshatJawne commented
Issue with latest commit, not all changes came through, investigating.

2024-05-31 14:46 UTC, mofojed requested changes

2024-05-31 14:46 UTC, mofojed commented on plugins/ui/DESIGN.md
> +## New implementation of Tabs
Please change this PR (or open a separate one) with _just_ the changes to the DESIGN.md doc so we can get those approved and merged before working on the implementation.
The section should be a refactoring of the current ui.tabs section instead of a new section.

2024-05-31 15:19 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +## New implementation of Tabs
Design PR: https://github.com/deephaven/deephaven-plugins/pull/504

2024-06-06 17:12 UTC, AkshatJawne commented
Have functionality working as indicated in examples, the only thing that is different is the mismatching keys when specifying tabs through `ui.tab_list` and `ui.tab_panels`. I had previously indicated that if the code below would cause an error, but since have changed perspective, since this is different from the current, default behaviour of tabs from spectrum.

```
# Causes a KeyError, since there are mismatching keys for "Tab 2"
t3 = ui.tabs(
    ui.tab_list(ui.item("Tab 1", key="Key 1"), ui.item("Tab 2", key="Key 2")),
    ui.tab_panels(
        ui.item("Content 3", key="Key 1"),
        ui.item("Content 2", key="Key 3"),
        flex_grow=1,
        position="relative",
    ),
    flex_grow=1,
)
```

This renders the "Tab 2" with no content, which I think is correct behaviour, given that the item specifying "Tab 2" technically does not have a mismatching key, it just has no content specified (given that there is no item in the` tab_panels` with the same key).

Will make this change to the `DESIGN.md `if there are no opposing thoughts on this matter.

2024-06-07 17:31 UTC, mofojed commented
> This renders the "Tab 2" with no content, which I think is correct behaviour, given that the item specifying "Tab 2" technically does not have a mismatching key, it just has no content specified (given that there is no item in the tab_panels with the same key).
> Will make this change to the DESIGN.md if there are no opposing thoughts on this matter.

@AkshatJawne Yes please do

2024-06-07 17:38 UTC, mofojed requested changes

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/__init__.py
> +from .tabs import *
Duplicate import, you import the same thing below.
```suggestion
```

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/tab.py
> +    Tab item implemenation for tabs component.
```suggestion
    Tab item implementation for tabs component.
```

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/tab.py
> +        *children: The children of the button group.
```suggestion
        *children: Content of the tab item.
```

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/tab.py
> +        "deephaven.ui.components.Item",
We should be using `deephaven.ui.components.Tab` here instead of `.Item`.

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/js/src/elements/SpectrumElementUtils.ts
> +  Tabs,
Should import `Tab` here and include in the Supported Types below.

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/tabs.py
> +        raise ValueError("Tabs cannot have both Tab and TabList or TabPanels children.")
I think we should use a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) here, it seems more appropriate.

2024-06-07 17:38 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/spectrum/tabs.py
> +        *children: The children of the button group.
Copy paste error, this is not a button group.
Also should include details on what type of children can be passed in here (`ui.tab` or `ui.tab_list`/`ui.tab_panels`)

2024-06-14 15:36 UTC, AkshatJawne commented
BTW, this PR is ready for review 👍🏼

2024-06-17 20:14 UTC, mattrunyon requested changes

2024-06-17 20:14 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  tabItems = Children.map(
The linter rule is probably right here. Just use `const tabItems = ...` instead of declaring w/ `let` as undefined and then assigning later.

2024-06-17 20:14 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +            : `Key ${index}`
Not sure if we should be doing this in JS or Python. Not sure we have a great distincting/reason for either place really

I guess a possible argument for JS would be if we ever did try to write Deephaven UI for groovy, it would make the groovy API a little easier

2024-06-17 20:14 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  tabPanels = Children.map(
Same comment about the linter rule

2024-06-17 20:14 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tab.tsx
> +}
I don't think this component is actually used any more. Just the props which you could just move to `Tabs`

2024-06-17 20:21 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        key=key,
The logic for this is handled in the `Tabs.tsx` , because wanted to make this component as pass-through as possible.

2024-06-17 20:26 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        raise TypeError("Tabs cannot have both Tab and TabList or TabPanels children.")
The check for unique keys is done in the Tabs.tsx lines 55-57 , with regards to mismatched list/panel keys, it will cause unpredictable behaviour, but as I mentioned above https://github.com/deephaven/deephaven-plugins/pull/489#issuecomment-2153024929 , it is quite difficult to have a check here, since what do we quantify as a mismtaching panel. 

In the example in that comment, we have a Tab in the tab_list called "Tab 2", but I think it should render with no content, since it is not that there is a mismatching key, but it could be that there is simply no content specified. 

Thus, the demarcation between a tab in the tab_list with no content (and thus no item in the tab_panels) and mismatching keys becomes blurry IMO. Let me know if you think there is a better way

2024-06-17 20:27 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +            : `Key ${index}`
Yeah not sure if we have a preference, but since we wanted to keep this component as passthrough as possible, I thought the logic should be implemented in JS.

2024-06-17 20:35 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        raise TypeError("Tabs cannot have both Tab and TabList or TabPanels children.")
I think in that case we should throw (even if it's in JS). If the user really wants no content, they should provide an empty item in the content w/ a matching key.

I think most/almost all of the time that case would happen, it's a mistake or unintentional from the user.

2024-06-17 20:57 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        on_selection_change=on_selection_change if on_selection_change else on_change,
This logic is in both the Python and JS. Not sure which side it should be on

2024-06-17 21:04 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        on_selection_change=on_selection_change if on_selection_change else on_change,
Thinking about it, I think it should be on the python side, what do you think?

2024-06-17 21:05 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        on_selection_change=on_selection_change if on_selection_change else on_change,
Given we did something similar with flex grow

2024-06-17 21:06 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tab.tsx
> +}
Well the tab.py is using it right, so we would need it? The reason we cannot shift it to Tabs is because the children can be either of type Tab or of type TabPanels and TabList, so then, I cannot specify the children to just be Tab.

2024-06-17 22:11 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    children as ReactElement<TabProps>[],
Is there a way to narrow the type in checks above such that the compiler already knows the type by the time you do?

2024-06-17 22:14 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +import { CollectionChildren } from '@react-types/shared';
This is bringing in a Spectrum dependency which is something we just removed. Probably need to re-export this type from @deephaven/components if we need it in plugins.

2024-06-17 22:17 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +import { CollectionChildren } from '@react-types/shared';
Actually I do see this is not the only instance. We should consider how we can get rid of the dependencies though

2024-06-17 22:25 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +        (child as ReactElement).type === TabPanels ||
The types suggest that `child` can be a `ReactChild` which can be a `string` or `number`. If that is the case, then the type assertions are asserting something that may not be true. If it is not the case, we should change the props type to reflect what they can actually be.

2024-06-17 22:35 UTC, bmingles requested changes
Left some comments in Tabs.tsx

2024-06-18 21:39 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabChildrenConfig = (isTabList: boolean) => {
I would move `tabChildrenConfig` and `isTabElement` outside of the component. Good practice unless you really need a closure over a stateful variable. In this case `tabChildrenConfig` can just take in the `childrenArray` as a 2nd arg. Then the functions are unit testable, and the component is slimmer.

2024-06-18 21:40 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const keys = childrenArray.map(child => (child as TabProps).key);
I think the `as TabProps` is still potentially hiding an unhandled type. I think `childrenArray` can still contain primitive values.

2024-06-19 19:40 UTC, AkshatJawne commented
Ready for re-review

2024-06-20 14:27 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tab.tsx
> +export function Tab(props: TabProps): React.JSX.Element {
Is this component doing anything other than wrapping `Item`?

2024-06-20 14:28 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      throw new Error('Children must be of type TabPanel, TabList, or Tabå.');
There's a weird character that ended up in this error message

2024-06-20 14:32 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +function isTabElement(item: any): item is React.ReactElement {
We have an existing `isElementOfType` helper that can be used to identify React element types. It's possible this won't be necessary at all after fixing the props types, but if it is, I would look at using that util

2024-06-20 14:39 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +          {isTabList ? child.props.title : child.props.children}
There may be a bug here. If `title` is an `Item`, this results in nested `<Item>`. Is that expected?

This would probably be a good util function to have unit tests on to verify it returns what you expect in various scenarios.

2024-06-20 14:50 UTC, bmingles requested changes
Left some comments

2024-06-20 14:58 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +          {isTabList ? child.props.title : child.props.children}
Also, be sure to check console for React warnings. It's possible you may need to set `textValue` on Item to avoid accessibility warnings, but I haven't tested

2024-06-20 21:04 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +          {isTabList ? child.props.title : child.props.children}
That would be expected yes because every item within a tab panel or tab list has to be a default, and then we could pass in a title as an item, that did not cause a bug the last time I tested. However, I will look at it again, and then also look at extracting this into a util function.

2024-06-20 21:05 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tab.tsx
> +export function Tab(props: TabProps): React.JSX.Element {
I don't think the render function of this is actually used. We pull the children and props out of it elsewhere.

2024-06-20 21:07 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tab.tsx
> +export function Tab(props: TabProps): React.JSX.Element {
Hmm ok, yeah I will take another look at this.

2024-06-20 21:08 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +          {isTabList ? child.props.title : child.props.children}
I would suggest not nesting `Item`. If it is an `Item` just return it (or augment then return if needed)

2024-06-20 21:09 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +          {isTabList ? child.props.title : child.props.children}
Fair, ok, will try and modify logic accordingly.

2024-06-20 21:09 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tab.tsx
> +export function Tab(props: TabProps): React.JSX.Element {
We can still use the `Tab` name in dh ui. You can just map the element name to `Item`. If you really wanted to have a `Tab` React component could also just `export const Tab = Item`, but that's probably unnecessary.

2024-06-20 21:29 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tab.tsx
> +export function Tab(props: TabProps): React.JSX.Element {
So currently I believe it renders a `Tab` component from Python. That `Tab` component isn't actually rendered in JS, but is pulled apart into the separate header and content items.

We could map this in Python instead of in JS. Either way this `Tab` component doesn't really need to do anything.

It could be an `Item` from Python. We would still pull it apart regardless of what it is. Having a separate JS element for it at least lets us define some specific props for it even though its render isn't used.

In a future where we could use JSON schema to validate or keep these types in sync across Python and JS, a separate Tab component would be useful since an alias for `Item` would mean we expect the `Item` props, not the `Tab` props

2024-06-20 21:31 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tab.tsx
> +export function Tab(props: TabProps): React.JSX.Element {
Basically I think this component should just be `return null`

2024-06-21 06:03 UTC, AkshatJawne commented
Ready for re-review

2024-06-21 14:08 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  Item,
Unused import

2024-06-21 14:11 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  Item,
nvm, I had stale code

2024-06-21 14:19 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +type TabComponentProps = TabsProps<TabProps> & {
This is looking better, but I think CollectionChildren still includes things the component doesn't support. I think this type is more representative:

```typescript
type TabProps = {
  children: ReactElement;
  title: string;
  key: string | null;
  icon?: ReactElement;
};

type TabChild = ReactElement<
  TabProps | TabListProps<TabProps> | TabPanelsProps<TabProps>
>;

type TabComponentProps = Omit<TabsProps<TabProps>, 'children'> & {
  children: TabChild | TabChild[];
  onChange?: (key: Key) => void;
};
```

2024-06-21 14:20 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    const element = child as ReactElement<TabProps>;
This type assertion seems to be off. I think child can be a TabList or TabPanels right?

2024-06-21 14:25 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +type TabComponentProps = TabsProps<TabProps> & {
We would have to do `CollectionChildren` though, since the Tabs are not passed into an array when creating the `ui.tabs` component; regardless of whether we do the shorthand way with the `ui.tab`, or the longer way with the `ui.tab_panels`/`ui.tab_list,` given that the python will not convert it to an array, I have to expect them to be a collection of children, right?

2024-06-21 14:27 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    const element = child as ReactElement<TabProps>;
The reason why I have it as a ReactElement here is to check the .type property of it in the following lines, and then correspondingly, set the `hasTabPanelsOrLists` bool

2024-06-21 15:37 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    const element = child as ReactElement<TabProps>;
You shouldn't need the assertion to make the `type` property available. All of the possible child types should have that. This will be fixed once the `children` type is updated to not include primitive types.

There is also an `isElementOfType` util that can be used to narrow the types, although it currently has a bug (https://github.com/deephaven/web-client-ui/issues/2094) so you will still need an `as` assertion, but it can be moved lower down.

```typescript
if (
  isElementOfType(child, TabPanels<TabProps>) ||
  isElementOfType(child, TabList<TabProps>)
) {
  hasTabPanelsOrLists = true;
  return;
}

// TODO: web-client-ui#2094 to fix the `isElementOfType` type guard which
// which is not properly narrowing the child type. Once that is fixed, we
// should be able to remove the `as` ReactElement<TabProps> assertion.
const element = child as ReactElement<TabProps>;

const tabProps: TabProps = {
  ...element.props,
  key: element.key != null ? element.key : null,
};
childrenArray.push(tabProps);
```

2024-06-21 15:38 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const childrenArray: TabProps[] = [];
Typically we should wrap an array creation in a `useMemo`

2024-06-21 15:40 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const keys = childrenArray.map(child => child.key);
This would be better as a util function. Also should be memoized via `useMemo`

2024-06-21 15:43 UTC, bmingles requested changes
Left some comments

2024-06-21 17:24 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +type TabComponentProps = TabsProps<TabProps> & {
I don't think that is the case. It should pass in as either a single element or an array of elements.

2024-06-21 18:22 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const keys = childrenArray.map(child => child.key);
Not sure if there is a need to memoize this, I agree with the util function, but why would we memoize the keys, not using them otherwise?

2024-06-21 18:23 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const childrenArray: TabProps[] = [];
I do see that on the web-client-ui side, but not on plugins. Do you have any examples on the plugins side where we memoize array creation?

2024-06-24 14:31 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const childrenArray: TabProps[] = [];
I don't know of any specific examples, but in general it's not a bad idea to memoize things that get constructed based on props. `childrenArray` gets passed to multiple components which may cause re-renders any time it changes. In practice it may not represent any real perf issue, but as a pattern it's good to avoid constructing new references on every render if they get passed to other components

2024-06-24 18:50 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    const key = child.key ?? child.title;
I'm seeing some aria warnings in console due to missing `textValue` props on `Item` elements. I think we should make this example work:

```python
from deephaven import empty_table, ui
from deephaven.plot import express as dx


_stocks = dx.data.stocks()

@ui.component
def ui_tabs(source):
    return ui.tabs(
        # will need to include `text_value` prop in ui.tab
        ui.tab(source.where("sym=`CAT`"), title="CAT", key="CAT", text_value="Cat"),
        ui.tab(source.where("sym=`DOG`"), title="DOG", key="DOG", text_value="Dog"),
        # textValue is already present on the tab props for text cases, it's just not reflected 
        # in the TabProps type
        ui.tab("Content 1", title="Tab 1", key="Key 1", icon=ui.icon("vsGithubAlt")),
        ui.tab("Content 2", title="Tab 2", key="Key 2"),
        aria_label="Tabs",
    )


my_ui_tabs = ui_tabs(_stocks)
```

I think we can fix this by:
```typescript
const textValue = child.textValue ?? child.title;
const key = child.key ?? child.title;
...
<Item key={key} textValue={textValue}>
```

2024-06-24 18:51 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        density=density,
@mattrunyon did this ever get clarified?

2024-06-24 19:09 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  if (containsDuplicateKeys(childrenArray)) {
This seems to get checked twice?

2024-06-24 19:47 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +type TabComponentProps = TabsProps<TabProps> & {
Here's the original comment

2024-06-25 16:26 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    const key = child.key ?? child.title;
Changes fixed the aria warnings, and things look much cleaner. I am seeing an issue where ui.tab `key` doesn't actually seem to make it to the component:

```
from deephaven import empty_table, ui
from deephaven.plot import express as dx


_stocks = dx.data.stocks()

@ui.component
def ui_tabs(source):
    def on_change(key):
        print(key)

    return ui.tabs(
        ui.tab(source.where("sym=`CAT`"), title="CAT", key="GATO"),
        ui.tab(source.where("sym=`DOG`"), title="DOG"),
        aria_label="Tabs",
        on_change=on_change
    )


my_ui_tabs = ui_tabs(_stocks)
```

2024-06-25 16:28 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    const key = props.key ?? props.title;
It looks like `props.key` may always be undefined. I think you have to destructure `key` from the child instead of from the props:
```typescript
const items = childrenArray.map(({ key, props })
```

2024-06-25 16:31 UTC, bmingles requested changes
Left a comment about the `key` always being undefined

2024-06-25 16:33 UTC, bmingles commented on plugins/ui/docs/README.md
> +my_tabs = ui.tabs(stocks)
This should be `ui_tabs(stocks)`

2024-06-25 16:33 UTC, bmingles commented on plugins/ui/docs/README.md
> +my_tabs = ui.tabs()
Should be `ui_tabs()`

2024-06-25 20:43 UTC, AkshatJawne commented
Ready for rereview

2024-06-25 20:50 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <Item key={key} textValue={textValue}>
The destructuring looks good, but looks like you lost your fallback to `title`. Should be something like

```typescript
const newKey = key ?? props.title
```

2024-06-25 20:51 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <Item key={key} textValue={textValue}>
Right, yeah my bad, will change rn

2024-06-25 21:02 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        "Item", *children, title=title, key=key, icon=icon, text_value=text_value
Is this supposed to be `"Item"`?

2024-06-25 21:04 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        "Item", *children, title=title, key=key, icon=icon, text_value=text_value
Yes, since we do not have a Tab.tsx right, we are just mapping the props from the tab item to an item, effectively restricting what we can pass into item (to avoid unwanted behaviour), without creating a separate component.

2024-06-25 21:05 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        "Item", *children, title=title, key=key, icon=icon, text_value=text_value
I would assume it is supposed to be `"Tab"` and then your change to WidgetUtils maps it to item `[ELEMENT_NAME.tab]: Item`

2024-06-25 21:08 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        "Item", *children, title=title, key=key, icon=icon, text_value=text_value
Well I have the WidgetUtils map to an item, but I thought I would still have to have Item here, since there is no element in the Deephaven Spectrum library called "Tab", which is what the component-element function uses right? It uses the passed in string and then appends it to the end of the file path to get the component?

2024-06-25 21:16 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        "Item", *children, title=title, key=key, icon=icon, text_value=text_value
I believe it just maps to a string key. That key is then used in WidgetUtils to get the actual React component

2024-06-25 21:21 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        "Item", *children, title=title, key=key, icon=icon, text_value=text_value
Hmm ok, maybe I misunderstood, I will make the change.

2024-06-26 16:30 UTC, bmingles commented on plugins/ui/docs/README.md
> +def ui_tabs(source):
This example shows aria warnings. I think updating to the following will fix it:
```
from deephaven import ui
from deephaven.plot import express as dx

stocks = dx.data.stocks()


@ui.component
def ui_tabs(source):
    return ui.tabs(
        ui.tab_list(
            ui.item("Unfiltered", key="Unfiltered"),
            ui.item(ui.icon("vsGithubAlt"), "CAT", text_value="CAT"),
            ui.item("DOG", key="DOG"),
        ),
        ui.tab_panels(
            ui.item(source, text_value="Unfiltered"),
            ui.item(source.where("sym=`CAT`"), text_value="CAT"),
            ui.item(source.where("sym=`DOG`"), text_value="DOG"),
        ),
        flex_grow=1,
        aria_label="Tabs"
    )


my_tabs = ui_tabs(stocks)
```

2024-06-26 16:34 UTC, mattrunyon commented on plugins/ui/docs/README.md
> +def ui_tabs(source):
I would add a comment it's only for aria accessibility and is otherwise optional.

2024-06-26 16:36 UTC, bmingles commented on plugins/ui/docs/README.md
> +def ui_tabs(source):
Note that `text_value` for non-text `ui.item` children is also for aria here.

2024-06-26 16:38 UTC, AkshatJawne commented on plugins/ui/docs/README.md
> +def ui_tabs(source):
Right, so if text_value is also for aria here, then it would be slightly weird to have a comment on each item that it is only for aria accessibility and is otherwise optional right? And then also have a comment above the aria_label prop

2024-06-26 17:05 UTC, bmingles submitted a review, later dismissed
Looks good. Ship it

2024-06-26 17:07 UTC, AkshatJawne commented
Will need @mattrunyon 's and @mofojed 's approval to merge

2024-06-26 21:21 UTC, mattrunyon requested changes

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabListChildren = useMemo(
Are we allowing mixing `ui.tab_list` and `ui.tab` now? I don't see anything preventing that and it's not in the docs readme that we allow it

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +        onSelectionChange={onChange}
I think I would prefer destructuring both of these (`onChange` and `onSelectionChange`) and setting the value based on both props. This tripped me up at first because if the user sets `onSelectionChange` it will still take priority.

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      onSelectionChange={onChange}
Same comment about destructuring both `onChange` and `onSelectionChange`

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <TabPanels UNSAFE_className="dh-tabs">{tabPanelsChildren}</TabPanels>
Why does the panels and tabs component have the same classname? If they're supposed to have the same styling, I would still do 2 separate classnames and then just do `.class1, .class2` in the CSS selectors

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/hooks/useListViewProps.ts
> +// TODO: #2084 Re-export @react-types/shared types
`web-client-ui#2084`

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/hooks/usePressEventCallback.ts
> +// TODO: #2084 Re-export @react-types/shared types
`web-client-ui#2084`

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/hooks/useSelectionProps.ts
> +// TODO: #2084 Re-export @react-types/shared types
`web-client-ui#2084`

2024-06-26 21:21 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <TabPanels UNSAFE_className="dh-tabs">{tabPanelsChildren}</TabPanels>
This is also adding styling for the panels only if you use `ui.tab` and not if you use the long form. If that's default we want across both then need to use a better selector

2024-06-26 21:22 UTC, mattrunyon commented on plugins/ui/DESIGN.md
>      on_change=lambda key: print(f"Selected key: {key}"),
Ya looks like this is an alias for `on_selection_change`. I'd prefer documenting `on_selection_change` since it's much more clear what "change" is.

2024-06-26 21:23 UTC, bmingles commented on plugins/ui/DESIGN.md
>      on_change=lambda key: print(f"Selected key: {key}"),
We intentionally added `on_change` as our standard event name. Spectrum's is usually `on_selection_change`. We are marking that as deprecated consistently across components.

2024-06-26 21:25 UTC, bmingles commented on plugins/ui/docs/README.md
> +        aria_label="Tabs",  # aria_label is set for aria accessibility and is otherwise optional
There is not which is consistent with how we've implemented other components as well. Not sure if we've discussed the possibility though. Curious if @dsmmcken has any opinions on this.

2024-06-26 21:30 UTC, mattrunyon requested changes
Idk why my first review didn't mark as changes requested in the status.

Mostly clarifying docs and some other behavior that is inconsistent or not what is defined in docs

2024-06-27 14:16 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabListChildren = useMemo(
We are not, that's why we have this `hasTabPanelsOrList`, to render either the `tabPanelsChildren` and the `tabListChildren` is we have `ui.item` passed in, or if we have the longer way with `ui.tab_panels` or `ui.tab_list`, we render the component through lines 103-114.

2024-06-27 14:42 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +        onSelectionChange={onChange}
May want to hear @mofojed and @bmingles 's opinion on this, since it was mentioned [here](https://github.com/deephaven/deephaven-plugins/pull/489#discussion_r1617275920) and a couple of times in discussion that we do not want to use on_selection_change.

2024-06-27 14:42 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      onSelectionChange={onChange}
^^ response above

2024-06-27 15:00 UTC, AkshatJawne commented on plugins/ui/docs/README.md
> +            ui.item(source.where("sym=`DOG`"), text_value="CAT"),
Here, text_value is not required but we added it so that we can avoid the aria warnings in the console. I could revert it back to keys, but then if anyone would run the snippet, they would see the warnings. If we do not care about the warnings, not much meaning to having text_value prop at all.

2024-06-27 15:02 UTC, AkshatJawne commented on plugins/ui/docs/README.md
> +        aria_label="Tabs",  # aria_label is set for aria accessibility and is otherwise optional
There is not a default aria_label no, if we wanted to default the aria_label to the key, we would have to do that in a separate web-client-ui ticket (given the Item processing / normalization logic lives there). Have asked on the team channel to gauge whether this is something we would want to look into.

2024-06-27 15:05 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        flex_grow=flex_grow if flex_grow is not None else 1,
Tried to do this, but the issue is that we cannot have a literal in the signature, so setting it to 1 by default causes a bug. Not sure if there is any other way other than what is currently proposed, but if there is, I agree, it makes more sense from a semantics standpoint.

2024-06-27 15:07 UTC, AkshatJawne commented on plugins/ui/DESIGN.md
> +        ui.item("Content 2", key="Key 3"), # No header w/ "Key 3". Will be dropped
My bad, we do throw an error for this lines 155 of tabs.py, just not had updated the comment here. I will remove this example (or add it to the error-causing cases).

2024-06-27 15:10 UTC, AkshatJawne commented on plugins/ui/docs/README.md
> +- Using `text_value` instead of `key` on `ui.item `is an optional accessibility improvement for cases where `ui.item` contains non-text content
As mentioned above, have asked in team chat to see if this si something we would want to do. If so, would have to be done in a separate web-client-ui ticket, sicne we would have to modify the Item normalization / processing logic.

2024-06-27 16:27 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabListChildren = useMemo(
There's no longer a check though. Previously there was a check to see if it also had `ui.tab`. Right now you could do this and it wouldn't complain, but would probably render incorrectly because it would just pass through the children directly

```py
ui.tabs(
  ui.tab(...),
  ui.tab_list(...),
  ui.tab_panels(...)
)
```

2024-06-27 16:42 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabListChildren = useMemo(
I am not sure if that would work though, since if there is a tab, tab_panel, and tab_list passed in, when we filter the length will still be greater than 0, but we would still have the tab in there, which would be incorrect

2024-06-27 16:44 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabListChildren = useMemo(
it should with the length !== check right?

2024-06-27 16:56 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/tabs.py
> +        flex_grow=flex_grow if flex_grow is not None else 1,
If you set the default in the signature to `1`, then it should work just fine I think. The only difference would be a user setting `flex_grow=None` would not get the default, but instead the prop won't be passed to the client which I believe should default it to `0` then. That is fine since as a user `flex_grow=None` I would not be surprised by "no flex grow" which right now it would be the default of 1.

2024-06-27 16:59 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const tabListChildren = useMemo(
Or this also works and is quite clear logically

```ts
const hasTabPanelsOrLists = childrenArray.some(child =>
  isElementOfType(child, TabPanels) || isElementOfType(child, TabList)
);
const hasTabItems = childrenArray.some(child => isElementOfType(child, Tab));

if (hasTabPanelsOrLists && hasTabItems) {
  throw ...
}
```

2024-06-27 18:44 UTC, mattrunyon requested changes
Just a few more clarification/cleanup items

2024-06-27 18:44 UTC, mattrunyon commented on plugins/ui/docs/README.md
I would add a little explanation of what you can do with this form that you can't with the other. I think right now it's just more control over the tab header display and that's about it? Or control over the header and content styling on `tab_panels` and `tab_list`.

Also, instead of the list here which just explains the contents, explain what the props are. Something like

```
tab_list is the container of tab headers. It expects children of `ui.item` which have a unique key. `text_value` may be added for accessibility, but by default the `key` will be used for accessibility.

tab_panels is the content of the tabs. It expects children of `ui.item` which have a key matching a header.
```

2024-06-27 18:44 UTC, mattrunyon commented on plugins/ui/docs/README.md
> +            ui.item(source.where("sym=`DOG`"), key="CAT"),
`key="DOG"`

2024-06-27 18:44 UTC, mattrunyon commented on plugins/ui/docs/README.md
> +            ui.item("DOG", key="DOG"),
Just confirming. Key is required for the long form tabs? Totally fine if it is, just want to make sure we aren't documenting using props when they aren't needed

2024-06-27 18:44 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/tab.py
> +        key: The unique key of the tab item, defaults to title.
```suggestion
        key: The unique key of the tab item. Defaults to title.
```

2024-06-27 18:44 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const hasTabItems = childrenArray.some(child => isElementOfType(child, Item));
This should be `Tab`, no? Although I don't see that component any more, so I'm not sure what/how `ui.tab` is mapped to the client

2024-06-27 18:44 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  const hasTabItems = childrenArray.some(child => isElementOfType(child, Item));
Ok I see you've mapped `Tab` to `Item` which I guess is fine. The component isn't used directly so it doesn't matter, just a bit of a misdirection on what it's actually using

2024-06-27 19:04 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
Could also check if there's any unexpected children.

```ts
const tabPanelsOrLists = childrenArray.filter(child => isElementOfType(child, TabList) || isElementOfType(child, TabPanel));
const hasTabPanelsOrLists = tabPanelsOrLists.length > 0;

const tabItems = childrenArray.filter(child => isElementType(child, Item));
const hasTabItems = tabItems.length > 0;

const hasUnsupportedChild = tabPanelsOrLists.length + tabItems.length !== childrenArray.length;

if (hasTabPanelsOrLists && hasTabItems) {
  throw new Error('Cannot mix');
}

if (hasUnsupportedChild) {
  throw new Error('Tabs can only take ui.tab or ui.tab_list/ui.tab_panel');
}
```

2024-06-27 19:35 UTC, AkshatJawne commented on plugins/ui/docs/README.md
> +            ui.item("DOG", key="DOG"),
Yes key is required for long form tabs!

2024-06-27 19:36 UTC, AkshatJawne commented on plugins/ui/docs/README.md
> +            ui.item("DOG", key="DOG"),
That is how the items are matched between the tab_panels and tab_list.

2024-06-27 21:27 UTC, mattrunyon requested changes

2024-06-27 21:27 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    throw new Error('Tabs can only take ui.tab or ui.tab_list/ui.tab_panel');
I just put these messages as placeholders. The first one I'd revert to the previous error message of "Cannot declare tabs with ui.tab and ui.tab_list/ui.tab_panels at the same time."

Second one maybe "Unknown child in tabs component. Only use ui.tab or ui.tab_list/ui.tab_panels"

2024-06-27 21:42 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +    throw new Error('Tabs can only take ui.tab or ui.tab_list/ui.tab_panel');
Ahhh ok ok, I thought you actually wanted it that way (was a little confused how short the first one was, but thought you wanted it more succinct lol), will change rn.

2024-07-02 21:40 UTC, mattrunyon commented
@dsmmcken Should we default to `density='compact'`? The regular padding looks horrible to me. Way too much space between the title and divider. Exacerbated by the minimal margin/padding between the divider and content

![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/91da7cd6-8ae2-4767-834b-09c72874af77)

2024-07-02 22:06 UTC, mattrunyon requested changes
A few small things I've noticed so far while testing. Will continue to test and post any other bugs I find

2024-07-02 22:06 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
Something is wrong with this check and I can't use the longform syntax.

It seems that `TabList` is not checking its type properly and it thinks there's only a `TabPanels` element

2024-07-02 22:25 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
I haven't dug in here, but it's possible it's due to a `isElementOfType` bug fixed in:
https://github.com/deephaven/web-client-ui/pull/2099

Likely we've not done a release + version bump

2024-07-02 22:27 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
@mattrunyon can you clarify what you are trying that isn't working?

2024-07-02 22:28 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
That shouldn't be an issue. Looks like that ticket only changed types. This is a runtime issue so either there's another bug with the hook or something weird with this code. 

While inspecting the react elements, I noticed the type of tab list was a random GUID while tab panels was a TabPanels function.

2024-07-02 22:32 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
```py
from deephaven import ui

t = ui.tabs(
    ui.tab_list(
        ui.item("Table", key="Table")
    ),
    ui.tab_panels(
        ui.item(empty_table(100).update("X=ii"), key="Table")
    )
)
```

I commented out the throw code and this is what the children are. Notice the 1st is some random function while the 2nd is a function named `TabPanels`

![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/bc28b126-ff30-4b58-80f7-c2ed627c44c3)

2024-07-03 13:21 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
Yeah this is really weird, have been testing this for a little while, and I see an odd type for TabList as well. 🤔

2024-07-03 13:25 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
Also, after doing some more testing and thinking about it, this check is sub optimal because when we have declared a tab_panels component it still throws the same error, but in reality it should throw something identifying to specify a corresponding tab_list.

2024-07-03 14:06 UTC, dsmmcken commented
> @dsmmcken Should we default to `density='compact'`? The regular padding looks horrible to me. Way too much space between the title and divider. Exacerbated by the minimal margin/padding between the divider and content

Sure, but also tab panels might need default top padding?

2024-07-03 14:58 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
Yeah have tried digging into this, honestly not sure if there is a way we can check for this, because there is no type property on the child, so I cannot even do something like `typeof child.type == "symbol"` or leverage the description somehow. 

How do we currently handle passing in the wrong type of children into other spectrum components? I could not find any logic in any of the other components to handle when we pass in a wrong type of child, it seems that it just bugs.

2024-07-03 16:00 UTC, AkshatJawne commented
Ready for re-review @mattrunyon

2024-07-03 17:11 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +  }
Looks like this is checking the wrong `TabPanels` component. The one that is mapped via `WidgetUtils` is the custom one `plugins/ui/src/js/src/elements/TabPanels.tsx` but the `isElementOfType` check is using the `@deephaven/components` one. If you change the import, I think this will fix it.

2024-07-03 17:14 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      isValidElement(child) &&
This shouldn't be necessary. See comment I left on the thread.

2024-07-03 17:15 UTC, bmingles requested changes
See comments about incorrect import of TabPanels type

2024-07-03 17:16 UTC, bmingles commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      isValidElement(child) &&
Also, I wouldn't expect this to work at all. You are checking string types, but they should be function instances.

2024-07-03 17:26 UTC, mattrunyon commented
@AkshatJawne Don't worry about the padding or defaulting to compact for this PR. I'll create a ticket to address the styling separately

2024-07-03 17:50 UTC, AkshatJawne commented
@bmingles 's hypothesis about the import was correct, applied changes.

2024-07-05 21:12 UTC, mattrunyon approved these changes

2024-07-05 21:13 UTC, bmingles approved these changes
LGTM

2024-07-05 21:13 UTC, merged