feat: Use `useWidget` hook to load widgets
deephaven/deephaven-plugins pull request #502
Opened 2024-05-30 20:44 UTC by mofojed

- Needs https://github.com/deephaven/web-client-ui/pull/2030
- Uses the `useWidget` hook defined in https://github.com/deephaven/web-client-ui/pull/2030 to load widgets
- Allows for the errors/fetch implementation to be defined at the top level
- Needed for DH-16737
- Tested in Core with a bunch of widgets, works as expected
- Unit tests added

2024-05-31 03:21 UTC, mattrunyon requested changes
Haven't tested this yet, but just noticed a few small things

2024-05-31 03:21 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
>    widget: descriptor,
I think we should rename the `widget` prop to `widgetDescriptor`. Since it's not the actual widget. The types are fine, but might as well name the prop to match

2024-05-31 17:14 UTC, mofojed commented
e2e tests won't work until I've pushed the web-client-ui changes and deephaven-core has been updated.

2024-06-10 14:40 UTC, mattrunyon requested changes
Needs the package versions updated and conflict fixed

2024-06-13 17:06 UTC, mattrunyon requested changes
Just a few small things

2024-06-13 17:06 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +  log.debug2('WidgetHandler', widgetDescriptor, widget, widgetError);
Do you want this debug log still? It would print on every render which I guess shouldn't be that often?

2024-06-14 17:32 UTC, mattrunyon commented
Needs some max-height or shrinking on the error message. If panels are relatively small the disconnected overlay breaks out of the panel (see bottom right panels in this screenshot)

![image](https://github.com/deephaven/deephaven-plugins/assets/8619789/141a0b9d-b6f1-487e-9187-ab4662f95dc6)

2024-06-14 17:40 UTC, mofojed commented
Yea for the other panels that'll need to be taken care of when we move them to use `useWidget` (part of the [core-plugins-refactor](https://github.com/deephaven/web-client-ui/tree/feature/core-plugins-refactor) changes).

2024-06-14 19:50 UTC, mattrunyon approved these changes

2024-06-14 20:21 UTC, merged