refactor: Refctored ui.tabs component design
deephaven/deephaven-plugins pull request #504
Opened 2024-05-31 15:18 UTC by AkshatJawne

Resolves https://github.com/deephaven/deephaven-plugins/issues/191

**Changes Implemented:** 
- Outlines design for refactored ui.tabs component in DESIGN.md with examples

_Discussion threads that shaped design are in PR that will handle implementation_: https://github.com/deephaven/deephaven-plugins/pull/489

2024-06-02 20:21 UTC, mofojed requested changes

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +2. They can be of types `TabList` and `TabPanels`, which when combined, outline all tabs and the respective contents
Why would you use one over the other? Mention in the second case that you may want to use that case to have more control over the layout of the panels/lists.

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +    # Should render a tab with the title "Tab 1" with "Content 1" as tab content, that given no key passed, would be set to "Tab 1 Key"
Docs should be written in the imperative mood; no need to say "Should render", just say "Render".
```suggestion
    # Render a tab with the title "Tab 1" with "Content 1" as tab content, that given no key passed, would be fallback to the title "Tab 1" as the key
```

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +    # Should render a tab with the title "Tab 3" with "Hello World" header with a table beside it as the tab content
```suggestion
    # Render a tab with the title "Tab 3" with "Hello World" header with a table beside it as the tab content
```

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +    ui.item("Content 4", title=ui.item("Tab 3", ui.icon("vsGithubAlt")))
Your description does not match the code. Also the key cannot contain an icon; the key will just fallback to the text value.
```suggestion
    # Render "Content 4" in a tab called "<GITHUB LOGO> Tab 4". With no key provided, it will fallback to the text content of the title, "Tab 4".
    ui.item("Content 4", title=ui.item(ui.icon("vsGithubAlt"), "Tab 4"))
```

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +    # Should render a tabs that have an on_change, which prints the selected tab key when a tab is selected
```suggestion
    # Render tabs that have an `on_change`, which prints the selected tab key when a tab is selected
```

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +)
Show a successful case of using `ui.tabs` with `ui.tab_list` and `ui.tab_panels` before showing an erroneous case.

Also make it clear that in the `tab_list`/`tab_panels` case, you must specify the keys and they must match, or you may have an error (as you have described here).

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +from deephaven.plot import express as dx
```suggestion
```

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +# Elementary Cases
Instead of one large code-block, these should be separate code blocks with text description in-between them. E.g.

###### Tabs using `ui.item`

If you're just using the default tab layout and don't need to customize the appearance of the tabs, you can simply pass in `ui.item` directly to `ui.tabs` as a concise method of defining your tabs.
```python
ui.tabs(
  ui.item(...),
  ui.item(...),
)
```
... description of another ui.item case, and another code block, etc.

###### Tabs using `ui.tab_panels` and `ui.tab_list`

If you need to customize the appearance/layout of the tab headers/content, then use `ui.tab_list` and `ui.tab_panels` to allow for extensive customization.

```python
ui.tabs(
  ui.tab_list(...),
  ui.tab_panels(...)
)
```

###### Error cases

2024-06-02 20:21 UTC, mofojed commented on plugins/ui/DESIGN.md
> +def tabs_error_cases():
Not sure why you changed the format up here. As mentioned above, each case should have it's own block; no need to make a `ui.component` with three return's in it (which doesn't make sense)

2024-06-03 21:24 UTC, mattrunyon commented
On Friday we talked about `ui.item` and I think that it's being misused here or that we should opt for an item specific to tabs to clarify some muddiness in Spectrum.

Spectrum uses Item for any collection. It only has `children`, `title`, `textValue`, `aria-label`, `childItems`, and `hasChildItems` props.

They use `Item` inside of `TabList` (the header list) and `TabPanels` (the tab content). This wrapper is their way of distinguishing the distinct items.

Since that item is required everywhere, we could omit it for our wrapper. We already have to map into the separate `TabList` and `TabPanels` components, so why not also just wrap each item in `Item` at that point.

Instead of `ui.item`, something like `ui.tab` which is specifically for use inside of tabs. That way we can add something if we want (like `icon`) that isn't supported by `ui.item`. It also makes some of the documentation more clear as we don't have `ui.item` used in lists, menus, tabs, etc. where there are slight differences to their use.

Here's some possible examples

```py
return ui.tabs(
  ui.tab("My content", title="A"),
  ui.tab(some_other_component, title="B", icon="dhTruck"),
  ui.tab(comp_a, comp_b, comp_c, title=ui.text("C", color="green")),
  ui.tab("D", title=ui.fragment(ui.icon("dhTruck"), "D")),
  ui.tab(title="E", children=["A", "bunch", "of", "strings"]),
  ui.tab("F", title=[loader_component, "F"])
)
```

2024-06-04 19:47 UTC, AkshatJawne commented
Modified design to now use `ui.tab` instead of `ui.item `as per comment from @mattrunyon and discussion with @mofojed

2024-06-05 13:27 UTC, mofojed requested changes
Need to clean up the headings mainly. Looks like there's other place in the DESIGN doc the headings can be cleaned up, let's do that in a separate PR after this.

2024-06-05 14:03 UTC, mofojed approved these changes

2024-06-05 14:10 UTC, merged