re-write dx.data.iris() using px.data to calcuate mean/std
deephaven/deephaven-plugins pull request #509
Opened 2024-06-03 16:30 UTC by dsmmcken

Gets rid of the replayer, which is better for performance.

Also loads the original data for px.data, runs stats on it then uses that for the values of random.gaussian.

Takes about the same amount of time to run as before, but I guess we have less magic values declared, and might be easier to model other generators off of.

2024-06-04 21:27 UTC, dsmmcken commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        t.update("timestamp = base_time + (long)(index * SECOND)")
convention, generally we like to put constants at the top of the function for easier editing.

2024-06-04 21:27 UTC, dsmmcken commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +                    "species_id = get_index(species)",
Leaving as is for clarity. Zero noticeable difference in the time it takes to create the table, don't need to prematurely optimize.

2024-06-04 21:28 UTC, dsmmcken commented
@jnumainville I have some pyright errors that I am not sure how to resolve? I don't really understand python types yet.

2024-06-05 18:53 UTC, jnumainville requested changes

2024-06-05 18:53 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +    df.insert(0, "index", list(range(df_len)))
list should be an ndarray I think
https://github.com/pandas-dev/pandas/blob/main/pandas/_typing.py#L131

2024-06-05 18:53 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        std = float(species_descriptions[col]["std"][species])
Problem here is `species_descriptions[col]["mean"][species]` and `species_descriptions[col]["std"][species]` could theoretically be things that are not convertible to float.
Could use `typing.cast` although only if certain that it would be nothing but a float. Ideally would winnow down to something convertible to float, maybe by a check like 
`if not isinstance(species_descriptions[col]["mean"][species], whatever_it_should_be_that_isn't_already_float):`

2024-06-05 20:08 UTC, jnumainville approved these changes

2024-06-05 20:51 UTC, merged