feat: ui.table context menu items
deephaven/deephaven-plugins pull request #522
Opened 2024-06-05 22:42 UTC by mattrunyon

2024-06-06 20:33 UTC, mofojed requested changes

2024-06-10 14:22 UTC, dsmmcken commented
I feel strongly that the word "context menu" must appear in the name. 

context_actions or context_items are not things. It's not just a "context", it's a "context menu". There's no such thing as context having meaning without the word menu beside it. It's a compound noun.

It's like ice cream. You wouldn't label something as ice cone. That's not a thing, it's an ice cream cone. It's a compound noun.

2024-06-10 14:27 UTC, mattrunyon commented
`context_menu_items` and `column_header_context_menu_items`? `context_menu_column_header_items` to me sounds like the context menu has some `column_header` that I can put items in

Another option would be just `context_menu_items` and then a dict w/ keys `cell` and `column_header` and values for the items, but I think that's probably less Pythonic

2024-06-10 15:48 UTC, dsmmcken commented
what about just context_menu and context_header_menu?

2024-06-13 21:24 UTC, mattrunyon commented
Might be able to add async menu items to this PR if the callables returning callables PR merges first. Feels like that one is close

2024-06-14 15:32 UTC, mofojed commented on plugins/ui/src/js/src/elements/UITable.tsx
> +  const irisGridRef = useRef<IrisGridType>(null);
This isn't being used at all

2024-06-14 15:32 UTC, mofojed commented on plugins/ui/src/js/src/elements/UITable.tsx
> +
Unused

2024-06-17 16:55 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/UITable.tsx
> +  const irisGridRef = useRef<IrisGridType>(null);
It is used now. Guess I committed this part but not the change that actually used it

2024-06-18 19:47 UTC, mofojed requested changes

2024-06-18 19:47 UTC, mofojed commented on plugins/ui/docs/README.md
> +Items can be added to the bottom of the `ui.table` context menu (right-click menu) by using the `context_menu` or `context_header_menu` props. The `context_menu` prop adds items for each cell, while
I know we don't show the Row Headers right now, question is if we'd ever want to allow that on `ui.table` and if so, what would the context menu item be for that? `context_row_header_menu` I think would be acceptable, and `context_header_menu` is for column headers.

In any case, I think we should be explicit this is about column headers in the description here.

```suggestion
Items can be added to the bottom of the `ui.table` context menu (right-click menu) by using the `context_menu` or `context_header_menu` props. The `context_menu` prop adds items to the cell context menu, while the `context_header_menu` prop adds items to the column header context menu.
```

2024-06-18 19:47 UTC, mofojed commented on plugins/ui/src/js/src/elements/UITable.tsx
> +  const irisGridRef = useRef<IrisGridType>(null);
It's still not being used. You're calling `setIrisGrid` in the `<IrisGrid ref={ref => setIrisGrid(ref)} ...` bit below, and not actually using this `irisGridRef` anywhere.

2024-06-18 19:52 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/UITable.tsx
> +  const irisGridRef = useRef<IrisGridType>(null);
:man_facepalming: I initially had it in the `ref` and then realized it wouldn't trigger the update properly since it's conditionally rendered

2024-06-21 16:25 UTC, mofojed requested changes

2024-06-21 16:25 UTC, mofojed commented on plugins/ui/src/js/src/elements/UITableContextMenuHandler.ts
> +import { UITableProps, wrapContextActions } from './UITableUtils';
Wrong import path

2024-06-27 14:22 UTC, mofojed requested changes
Used a whole bunch of menus for testing:
```python
from deephaven import empty_table, ui
import time

t = empty_table(100).update(["x=i", "y=Math.sin(x)"])


def action_context_menu(e):
    return [
        {
            "title": f"Action for {e['value']}",
            "action": lambda d: print(d),
        }
    ]


def delayed_context_menu(e):
    time.sleep(2)
    return [
        {
            "title": f"Delayed action for {e['value']}",
            "action": lambda d: print(d),
        }
    ]


def sub_menus(e):
    return [
        {
            "title": f"Submenu for {e['value']}",
            "actions": [action_context_menu, delayed_context_menu],
        }
    ]


def delayed_sub_menus(e):
    time.sleep(2)
    return [
        {
            "title": f"Delayed submenu for {e['value']}",
            "actions": [action_context_menu, delayed_context_menu],
        }
    ]


def even_menu_only(e):
    if e["value"] % 2 == 0:
        return [
            {
                "icon": 'vsWarning',
                "title": f"Even menu for {e['value']}",
                "action": lambda d: print(d),
                "order": 1,
            }
        ]


action_t = ui.table(t, context_menu=[action_context_menu])

delayed_t = ui.table(
    t,
    context_menu=[delayed_context_menu],
)

all_t = ui.table(
    t,
    context_menu=[
        even_menu_only,
        action_context_menu,
        delayed_context_menu,
        sub_menus,
        delayed_sub_menus,
    ],
)
```

Looks like it works well so far. Great work!

2024-06-27 14:22 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/table.py
> +    context_menu: list[ResolvableContextMenuItem] | None = None,
So in web-client-ui, we accept an array or just a single item: https://github.com/deephaven/web-client-ui/blob/e13c9d78decdfba2ff76657a024b2df44f2ae0fc/packages/components/src/context-actions/ContextActionUtils.ts#L5

Would be nice if we could handle that. Right now doing this is throwing an error on the JS side on right-click and isn't reported to the user, we should at least handle that better:
```python
from deephaven import empty_table, ui

t = ui.table(
    empty_table(100).update(["x=i", "y=Math.sin(x)"]),
    context_menu=lambda e: {
        "title": f"Action for {e['value']}",
        "action": lambda d: print(d),
    },
)
```

Currently you need to wrap both the function and the return value from the function in arrays, and you don't need to do either in the ContextAction in web-client-ui:
```python
from deephaven import empty_table, ui

action_t = ui.table(
    empty_table(100).update(["x=i", "y=Math.sin(x)"]),
    context_menu=[
        lambda e: [
            {
                "title": f"Action for {e['value']}",
                "action": lambda d: print(d),
            }
        ]
    ],
)
```

2024-06-27 14:22 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +ResolvableContextMenuItem = Union[
We should be exporting these types so user can use them

2024-06-27 14:22 UTC, mofojed commented on plugins/ui/src/js/src/elements/utils/UITableContextMenuHandler.ts
> +  order = 890;
How'd you decide this? I think it should fire after the `GridSelectionMouseHandler`, no?
I guess we don't have any constants available for the order of the mouse handlers, but I don't think it needs to be this high-priority.

2024-06-27 14:22 UTC, mofojed commented on plugins/ui/src/js/src/elements/utils/UITableUtils.tsx
> +  return items.map(item => {
As mentioned in another comment - we should be able to just pass a single menu item or function in here, so I'd make sure it's wrapped in an array before doing this map.

2024-06-27 14:22 UTC, mofojed commented on plugins/ui/src/js/src/elements/utils/UITableUtils.tsx
> +    actions: item.actions ? wrapContextActions(item.actions, data) : undefined,
We should also allow `order` to be passed in here... right now it's implicitly sorting based on the title, which isn't the best.

2024-06-27 21:35 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/utils/UITableContextMenuHandler.ts
> +  order = 890;
I copied it from the `UITableMouseHandler` implementation.

I think I can just do `this.order -= 1` in the constructor to just make it just above the default handler in priority

2024-06-27 21:40 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/utils/UITableUtils.tsx
> +    actions: item.actions ? wrapContextActions(item.actions, data) : undefined,
Why do you say it is sorting by title? It should just be sorted by the order the actions are defined in Python.

We should allow `order`, but I figured that could be a followup. I don't really like just saying "well our current menu items are 500, 800, 1000" or whatever they are

Also I think you _could_ pass an order right now since the item gets spread before setting the action/actions

2024-06-27 22:17 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/types/types.py
> +ResolvableContextMenuItem = Union[
Everything in a Python module is exported by default? `from deephaven.ui.types import ResolvableContextMenuItem` works for me

2024-06-27 22:21 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/table.py
> +    context_menu: list[ResolvableContextMenuItem] | None = None,
Ya I was mostly trying to make the types a bit simpler for Python. I can make it support both though

2024-06-28 20:53 UTC, mofojed approved these changes

2024-06-28 21:26 UTC, merged