refactor: Cleanup component mappings and utils
deephaven/deephaven-plugins pull request #523
Opened 2024-06-06 13:41 UTC by bmingles

resolves #425

2024-06-06 14:36 UTC, bmingles commented on plugins/ui/src/js/src/elements/SpectrumElementUtils.ts
> +    name.substring(SPECTRUM_ELEMENT_TYPE_PREFIX.length) in
Added this check since the components are no longer differentiated by `.spectrum` namespace. All of this code will get removed in next PR anyway.

2024-06-07 18:03 UTC, mofojed requested changes

2024-06-07 18:03 UTC, mofojed commented on tests/app.d/ui_render_all.py
> +        ui.panel("Panel A", title="Panel A"),
Why are we bothering with two panels here?

2024-06-07 18:03 UTC, mofojed commented on tests/ui.spec.ts-snapshots/UI-all-components-render-1-chromium-linux.png
Seems like it's getting truncated (ends at Slider, pretty I don't see a Switch for example).

2024-06-07 18:05 UTC, bmingles commented on plugins/ui/src/js/src/elements/RadioGroup.tsx
> +  orientation: orientationMaybeUppercase,
It's for consistency with other components + docs where most of our string enumerations are uppercase. I just missed it on radio PR and slipped it in. Doesn't have to be in this PR

2024-06-10 15:08 UTC, bmingles commented on tests/ui.spec.ts-snapshots/UI-all-components-render-1-chromium-linux.png
I changed it to 3 columns. Should be good now

2024-06-10 15:08 UTC, bmingles commented on tests/app.d/ui_render_all.py
> +        ui.panel("Panel A", title="Panel A"),
removed

2024-06-10 15:45 UTC, bmingles commented
I addressed review comments. Split out #536 to separate the RadioGroup orientation prop

2024-06-13 16:20 UTC, merged