docs: function autodocs embedded in docs
deephaven/deephaven-plugins pull request #527
Opened 2024-06-06 18:16 UTC by jnumainville

Fixes #501 

No github action in this pr, but this allows a local build of docs as a starting point

2024-06-06 18:40 UTC, dsmmcken commented
Can we not scatter additional files in the docs folder? Those files aren't docs.

2024-06-06 18:53 UTC, dsmmcken commented on plugins/plotly-express/docs/index.rst
> +
whats this file for?

2024-06-06 20:06 UTC, jnumainville commented on plugins/plotly-express/docs/index.rst
> +
Sphinx complains if documents are not in a toctree for some reason

2024-06-07 17:51 UTC, mofojed commented
Getting an error when trying to run locally:
```
Building markdown
Running Sphinx v7.2.6
1 compiler directives added
# Starting io.deephaven.python.server.EmbeddedServer
deephaven.cacheDir=/home/bender/.cache/deephaven
deephaven.configDir=/home/bender/.config/deephaven
deephaven.dataDir=/home/bender/.local/share/deephaven
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: searching for 'io.deephaven.internal.log.LoggerFactory'...
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: found 'io.deephaven.internal.log.LoggerFactorySlf4j'
Server started on port 10075

Extension error:
Could not import extension sphinx_autodoc_typehints (exception: No module named 'sphinx_autodoc_typehints')
make: *** [Makefile:20: markdown] Error 2
Copying assets
cp: cannot create directory 'docs/build/markdown/_assets': No such file or directory
cp: cannot create regular file 'docs/build/markdown/sidebar.json': No such file or directory
rm: cannot remove 'docs/build/markdown/index.md': No such file or directory
```

2024-06-07 17:51 UTC, mofojed requested changes

2024-06-07 17:51 UTC, mofojed commented on plugins/plotly-express/README.md
> +Note that these built files should not be committed to the repository.
Where do the built files get outputted? Should include that info here.

I'm getting an error right now when building locally:
```
Building markdown
Running Sphinx v7.2.6
1 compiler directives added
# Starting io.deephaven.python.server.EmbeddedServer
deephaven.cacheDir=/home/bender/.cache/deephaven
deephaven.configDir=/home/bender/.config/deephaven
deephaven.dataDir=/home/bender/.local/share/deephaven
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: searching for 'io.deephaven.internal.log.LoggerFactory'...
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: found 'io.deephaven.internal.log.LoggerFactorySlf4j'
Server started on port 10075

Extension error:
Could not import extension sphinx_autodoc_typehints (exception: No module named 'sphinx_autodoc_typehints')
make: *** [Makefile:20: markdown] Error 2
Copying assets
cp: cannot create directory 'docs/build/markdown/_assets': No such file or directory
cp: cannot create regular file 'docs/build/markdown/sidebar.json': No such file or directory
rm: cannot remove 'docs/build/markdown/index.md': No such file or directory
```

2024-06-07 18:43 UTC, jnumainville commented on plugins/plotly-express/README.md
> +Note that these built files should not be committed to the repository.
Not sure why... double checked and works for me. Are you using 3.8? Looks like sphinx_autodoc_typehints will require 3.9. Should be fine since we only need it for building the docs.

2024-06-12 18:45 UTC, mofojed commented on plugins/plotly-express/README.md
> +Note that these built files should not be committed to the repository.
Weird, I just tried again and all good. For ref I'm on python 3.10.12

2024-06-12 18:46 UTC, mofojed approved these changes

2024-06-13 15:06 UTC, merged