docs: item
deephaven/deephaven-plugins pull request #531
Opened 2024-06-08 03:09 UTC by ethanalvizo

2024-06-14 19:46 UTC, mofojed requested changes

2024-06-14 19:46 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/item.py
> +    child_items: ItemList | None = None,
I don't think `child_items` is a prop that we can use? When is it used?

2024-06-21 14:19 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/item.py
> +    child_items: ItemList | None = None,
From the spectrum docs it seems like it's used for dynamic lists. I was assuming this would be used if any type of list (static or dynamic) was passed into item? 

```
/** A list of child item objects. Used for dynamic collections. */
  childItems?: Iterable<T>,
```

2024-06-21 20:21 UTC, mofojed requested changes

2024-06-21 20:21 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/item.py
> +    child_items: ItemList | None = None,
I can't think of any examples where we'd use it in deephaven.ui though, I think you can just take out `child_items` here.
```suggestion
```

2024-06-25 19:01 UTC, mofojed approved these changes

2024-06-25 20:03 UTC, merged