docs: illustrated message
deephaven/deephaven-plugins pull request #532
Opened 2024-06-10 13:11 UTC by ethanalvizo

Closes #474

2024-06-14 20:05 UTC, mofojed requested changes

2024-06-14 20:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/illustrated_message.py
> +            ui.content(f"{error}"),
The `f"{error}"` doesn't work correctly because `error` is undefined. Just use a string anyway.
```suggestion
            ui.heading("Warning"),
            ui.content("This is a warning message."),
```

2024-06-14 20:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/illustrated_message.py
> +        )
Drop this example... we need to wire up the props in `IconElementView.tsx` correctly, it should be:
```
    // eslint-disable-next-line react/jsx-props-no-spreading
    <Icon {...props}>
      <FontAwesomeIcon icon={icon} />
    </Icon>
```
Instead of passing the props into `FontAwesomeIcon`.
Then the example here would be:
```suggestion
        error_message = ui.illustrated_message(
            ui.icon("vsWarning", size="XXL", margin_bottom="size-10"),
            ui.heading("Invalid Input"),
            ui.content("Please enter 'Sym' and 'Exchange' above"),
        )
```

Though ideally we should be passing those in as defaults when an `Icon` is passed into `IllustratedMessage`. We can capture that in a separate ticket though.

2024-06-21 17:59 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/illustrated_message.py
> +        )
<img width="937" alt="image" src="https://github.com/deephaven/deephaven-plugins/assets/55671206/80879764-5b14-4009-a460-61bc3f2dec18">

Unit tests failing because of the prop spreading

2024-06-21 20:23 UTC, mofojed requested changes

2024-06-21 20:23 UTC, mofojed commented on plugins/ui/src/js/src/elements/IconElementView.tsx
>        {/* eslint-disable-next-line react/jsx-props-no-spreading */}
Right now the tests are failing:
```

/home/runner/work/deephaven-plugins/deephaven-plugins/plugins/ui/src/js/src/elements/IconElementView.tsx
Error:   20:11  error  Prop spreading is forbidden  react/jsx-props-no-spreading

✖ 1 problem (1 error, 0 warnings)
```
You should move this jsx-props-no-spreading line to above the `<Icon {...props}>` line above.

2024-06-25 19:02 UTC, mofojed approved these changes

2024-06-25 20:02 UTC, merged