feat: Return callables from callables in Deephaven UI
deephaven/deephaven-plugins pull request #540
Opened 2024-06-10 23:19 UTC by mattrunyon

Fixes #322

Right now this only supports returning a callable as the result from another callable. It does not support a callable as part of an array or object which will be required for #321. That should still be part of this PR I think, but wanted to put this up for review in its current state to get feedback.

Currently a little hard to test, but this should demonstrate it if you watch the JS debug logs on `WidgetHandler`.

Since we now must return the result of callables, I added a check for non-serializable so we don't spam the Python logs in that case. Not sure if it's something we will want to change in the future.

Run this Python code.
The `Normal` button should behave the same as latest dh.ui.
The `Nested` button will return and wrap a new callable, but does not call it. You can add a line to `WidgetUtils.tsx` like `nestedCallable('hello')` just before it's returned if you want to call it as well. After 5-10s there should be a log and request/response to `closeCallable`.
The `Not serializable` button will basically do nothing. The returned result will include that it was a serialization error though.

```py
from deephaven import ui

@ui.component
def my_comp():
    on_press = ui.use_callback(lambda d: print(d), [])
    on_press_nested = ui.use_callback(lambda: print, [])
    on_press_unserializable = ui.use_callback(lambda: set([1, 2, 3]), [])
    return [
        ui.button("Normal", on_press=on_press),
        ui.button("Nested", on_press=on_press_nested),
        ui.button("Not Serializable", on_press=on_press_unserializable)
    ]

c = my_comp()
```

2024-06-13 13:44 UTC, mofojed requested changes

2024-06-13 13:44 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +    _temp_callable_next_id: int
I'd call it `_next_temp_callable_id`, then the naming pattern matches NodeEncoder (`_callable_dict` and `_next_callable_id`). Seems to make more sense to me to? ("The next temporary callable ID" vs. "The temporary callable next ID" (which doesn't sound right? Would be "The temporary callables next ID"))

No biggie though.

2024-06-13 13:44 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            return {
Should probably log an error here with what the result is, since we won't be able to send it over the wire...

2024-06-13 13:44 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            }
As you mentioned in description, will need to handle nested callables as part of a dict/array or something.
Ideally we want to run it through the same sort of encoder we do with `NodeEncoder`... in a perfect world we'd also be able to send exported objects this way too, though that would be a little trickier to wire up with the JSON RPC (would need the `handle_message` above to somehow get the temp exported objects and return them). But in any case, I think we need to handle a dict or array that contains callables at different levels, meaning we should run it through the `NodeEncoder` logic. Could have a new instance of `NodeEncoder` for each response, or something to that effect.

2024-06-13 13:44 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +      }
Should just be an assertion - no reason the client should be null here.

2024-06-13 13:44 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
> +    if (isCallableNode(result)) {
Will need to parse the result here for nested callables.

2024-06-13 19:44 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetHandler.tsx
> +      }
Fair. We weren't asserting or checking anything here previously, but ya it shouldn't be null here.

2024-06-13 19:47 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            }
So my thought right now is to only support JSON serializable things + callables on the first pass. We can worry about returning exported objects and other nodes later I think (we'd need to add parsing for them on the client anyway).

I think I will just make an encoder for callable responses for now that just adds support for serializing callables in the JSON object

2024-06-13 20:48 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +            return {
I logged the error, but not the stack trace. Added a comment as to why, but basically the stack trace I think is useless log spam to a user because it just contains all the internal lines for `ElementMessageStream` and nothing related to the actual callable they ran

2024-06-18 20:26 UTC, mofojed requested changes

2024-06-18 20:26 UTC, mofojed commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +from hmac import new
Accidental import? Isn't used and imagine you were just trying to do like `new Error(...)` or something and it auto-imported, which you don't need `new` in Python
```suggestion
```

2024-06-18 22:29 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/object_types/ElementMessageStream.py
> +from hmac import new
Ya no idea where that came from

2024-06-18 22:33 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
> +      // As a result, any returned callables will never be GC'd and the finalization registry will never clean them up
Ya not sure what else would be covered in a blog post. Guess it could be on weakrefs in general

2024-06-19 01:36 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
> +      // As a result, any returned callables will never be GC'd and the finalization registry will never clean them up
WeakRef, FinalizationRegistry, garbage collection - would be short and interesting

2024-06-19 01:36 UTC, mofojed approved these changes

2024-06-19 05:36 UTC, merged