Ticking gapminder dataset
deephaven/deephaven-plugins pull request #541
Opened 2024-06-11 16:46 UTC by alexpeters1208

Still need to do the docstring and consider whether perf can be improved

2024-06-12 15:48 UTC, jnumainville requested changes

2024-06-12 15:48 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        return [val, *[np.nan for _ in range(reps - 1)]]
since we use `from __future__ import annotations` you can use `list[int]` instead of `typing.List[int]`
also, prefer just `Any` to `typing.Any`

2024-06-12 15:48 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +    gapminder_2007 = typing.cast(pd.DataFrame, gapminder[gapminder["year"] == 2007])
It it possible to check if `isinstance(pd.DataFrame, ...)` instead of cast? Better to use `typing.cast` sparingly
this is also a general comment for all `typing.cast` calls in this generator

2024-06-12 15:48 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +            [[month for month in range(1, 13)] for _ in range(len(gapminder_no_2007))],
Recommend moving this to another function - this complex of a list comprehension can be hard to parse

2024-06-12 15:48 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        lambda x: round(x)
`lambda x: round(x)` is equivalent to just passing round in this case
```suggestion
        round
```

2024-06-14 18:44 UTC, alexpeters1208 commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        return [val, *[np.nan for _ in range(reps - 1)]]
The `Any` change gives me this:
```
/Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:436:27 - error: "Any" is not defined (reportUndefinedVariable)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:436:51 - error: "Any" is not defined (reportUndefinedVariable)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:566:20 - error: "uby" is not defined (reportUndefinedVariable)
/Users/alexpeters/Documents/Web/deephaven-plugins/plugins/ui/src/deephaven/ui/_internal/RenderContext.py

```

2024-06-14 18:50 UTC, alexpeters1208 commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +    gapminder_2007 = typing.cast(pd.DataFrame, gapminder[gapminder["year"] == 2007])
The typing cast is the only way I managed to get around the typechecker. The result is definitely a pd.DataFrame by construction (and I checked it manually in several places), but Pyright and Pandas seem to not always get along. For example, this particular change gives:
```
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:445:68 - error: Cannot access member "apply" for type "ndarray[Any, Unknown]"
    Member "apply" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:445:68 - error: Cannot access member "apply" for type "NDArray[Unknown]"
    Member "apply" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:445:68 - error: Cannot access member "apply" for type "NDArray[Any]"
    Member "apply" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:445:23 - error: Cannot access member "loc" for type "ndarray[Any, Unknown]"
    Member "loc" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:445:23 - error: Cannot access member "loc" for type "NDArray[Unknown]"
    Member "loc" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:450:7 - error: Cannot access member "map" for type "ndarray[Any, Unknown]"
    Member "map" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:450:7 - error: Cannot access member "map" for type "NDArray[Unknown]"
    Member "map" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:450:7 - error: Cannot access member "map" for type "ndarray[Any, _dtype]"
    Member "map" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:448:23 - error: Cannot access member "loc" for type "ndarray[Any, Unknown]"
    Member "loc" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:448:23 - error: Cannot access member "loc" for type "NDArray[Unknown]"
    Member "loc" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:451:43 - error: Cannot access member "explode" for type "ndarray[Any, Unknown]"
    Member "explode" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:451:43 - error: Cannot access member "explode" for type "NDArray[Unknown]"
    Member "explode" is unknown (reportGeneralTypeIssues)
  /Users/alexpeters/Documents/Web/deephaven-plugins/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py:452:9 - error: No parameter named "column" (reportGeneralTypeIssues)
```
The type checker is thinking it's a numpy array. I guess dataframes are backed by numpy arrays in many cases, but the type of `gapminder_no_2007` is certainly a dataframe.

2024-06-14 20:38 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        return [val, *[np.nan for _ in range(reps - 1)]]
did you import `Any` directly as well? don't see the import but not sure if that's just because you didn't commit the new import because that error came up
`from typing import Any`

2024-06-14 20:39 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +    gapminder_2007 = typing.cast(pd.DataFrame, gapminder[gapminder["year"] == 2007])
very odd - not sure what's going on in particular here, maybe a pandas issue

2024-06-17 14:18 UTC, alexpeters1208 commented on plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py
> +        return [val, *[np.nan for _ in range(reps - 1)]]
Did not catch this, I would have thought that the `from __future__ import annotations` would have had this. I don't know a ton about Python type hinting.

2024-06-17 15:37 UTC, jnumainville submitted a review, later dismissed

2024-06-18 18:08 UTC, jnumainville approved these changes

2024-06-18 18:20 UTC, merged