docs: MVP plotly-express docs
deephaven/deephaven-plugins pull request #554
Opened 2024-06-14 14:52 UTC by alexpeters1208

Minimum required docs for the plotly-express plugin. Depends on https://github.com/deephaven/deephaven-plugins/pull/541

2024-06-24 17:41 UTC, dsmmcken requested changes
nothing huge jumps out on first read. I haven't tried running every block of code. @jnumainville should look through with sharper eyes on the code blocks.

2024-06-24 18:33 UTC, alexpeters1208 commented on plugins/plotly-express/docs/area.md
> +An area plot, also known as a stacked area chart, is a data visualization that uses multiple filled areas stacked on top of one another to represent the cumulative contribution of distinct categories
I think it's less that area under the curve is meaningful, and more that the height of the curve at a given x is meaningful, so the axis should not be shorted, in order to maintain the proportional relationships of all of the curves. I cannot think of an actual interpretation of "area under the curve" in this context. Maybe as a relative growth rate for a fixed interval of x? Probably don't want to write that. See what you think of the change.

2024-06-24 19:55 UTC, dsmmcken commented on plugins/plotly-express/docs/area.md
> +An area plot, also known as a stacked area chart, is a data visualization that uses multiple filled areas stacked on top of one another to represent the cumulative contribution of distinct categories
yeah that's better

2024-06-25 15:47 UTC, margaretkennedy commented on plugins/plotly-express/docs/box.md
> +#### What are box plots are useful for?
```suggestion
#### What are box plots useful for?
```

2024-06-26 15:13 UTC, jnumainville requested changes

2024-06-26 15:13 UTC, jnumainville commented on plugins/plotly-express/docs/area.md
> +gapminder = dx.data.gapminder() # import a ticking version of the Gapminder dataset
I'm not able to get the gapminder data set working
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'AttributeError'>
Value: 'DataFrame' object has no attribute 'map'
Line: 5989
Namespace: __getattr__
File: /Users/josephnumainville/Documents/deephaven-plugins/.venv/lib/python3.8/site-packages/pandas/core/generic.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/josephnumainville/Documents/deephaven-plugins/.venv/lib/python3.8/site-packages/deephaven/plot/express/data/data_generators.py", line 657, in gapminder
```

Seems like this map is not working on my setup for some reason:
https://github.com/deephaven/deephaven-plugins/blob/main/plugins/plotly-express/src/deephaven/plot/express/data/data_generators.py#L659

2024-06-27 20:30 UTC, alexpeters1208 commented on plugins/plotly-express/docs/box.md
> +total_bill_sex = dx.box(tips, y="total_bill", by="sex")
I'm gonna push back on this a little bit - I think we don't want these plot names to get unwieldy. Having three words like in `total_bill_smoke` and `total_bill_sex` is already pretty long - I don't see the benefit to `total_bill_smoke_hist_plot` and `total_bill_sex_hist_plot`, when a user reading this would already be aware of the plot type of the page they're on.

2024-07-10 16:00 UTC, dsmmcken commented on plugins/plotly-express/docs/plot-by.md
> +total_bill_tip_size = dx.scatter(tips, x="total_bill", y="tip", size="size")
@jnumainville size is by variable?

2024-07-12 20:49 UTC, jnumainville commented on plugins/plotly-express/docs/plot-by.md
> +total_bill_tip_size = dx.scatter(tips, x="total_bill", y="tip", size="size")
It depends on the type of data - if the column is numeric, it will be a bubble chart. If the column is not numeric, it will be a size by. There are ways to tweak this too, like `size_map="by"` forces a numeric size to a size by.

2024-07-15 11:02 UTC, margaretkennedy commented on plugins/plotly-express/docs/line-ternary.md
> +- **Optimization Studies**: Ternary line plots can be applied in optimization studies to understand how adjustments in the proportions of three components impact the overall composition, aiding in in
```suggestion
- **Optimization Studies**: They can be applied in optimization studies to understand how adjustments in the proportions of three components impact the overall composition, aiding in informed decision-making.
```

2024-07-15 11:02 UTC, margaretkennedy commented on plugins/plotly-express/docs/line-ternary.md
> +- **Optimization Studies**: Ternary line plots can be applied in optimization studies to understand how adjustments in the proportions of three components impact the overall composition, aiding in in
I'll probably do a final consistency edit once Don, Joe, and Chip are happy.

2024-07-15 13:17 UTC, margaretkennedy commented on plugins/plotly-express/docs/timeline.md
> +A timeline plot is appropriate when the data contain a categorical variable whose categories become relevant in different places across a timeline. An example may be the years that various members in
```suggestion
A timeline plot is appropriate when the data contain a categorical variable whose categories become relevant in different places across a timeline. An example may be the years that various members in a band have been active - some may have been active for the duration of the band's career, others may have only appeared in the early days and then left, some may have passed away and been replaced, and so on. Timeline plots are often used to display this data, such as [this timeline plot](https://en.wikipedia.org/wiki/Metallica#Timeline) detailing the member composition of the band Metallica throughout the years.
```

2024-07-15 21:14 UTC, alexpeters1208 commented on plugins/plotly-express/docs/candlestick.md
> +#### What are candlestick plots useful for?
I tried an alternative, and settled on the current version. I like the way it reads the best. Keeping this open to reassess when we get real renderings.

2024-07-23 16:10 UTC, chipkent commented on plugins/plotly-express/docs/line.md
`# group colors by a column` is gibberish

2024-07-23 16:10 UTC, chipkent commented on plugins/plotly-express/docs/line.md
`# When set to `identity`, the column data passed to the
    # color parameter will used as the actual color` is gibberish

2024-07-23 16:10 UTC, chipkent commented on plugins/plotly-express/docs/line.md
The `Color using custom discrete colors` section:
1. does not have any description sentence.  Is one needed.
2. The examples aren't even for `line`.

2024-07-23 16:10 UTC, chipkent commented on plugins/plotly-express/docs/line.md
The rest of the document has equivalent problems. 
1. The examples are not for `line`.
2. The text is gibberish.
3. The text talks about query engine stuff instead of plotting.
4. It is impossible for me to comment because most of this stuff is from prior commits.

Stopping the review here.

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/strip.md
> +bill_distr = dx.strip(tips, x="total_bill", by="day", color_discrete_sequence=["lightblue"])
Possible bug.
```python
import deephaven.plot.express as dx
tips = dx.data.tips() # import a ticking version of the Tips dataset

# create a strip plot by specifying the variable of interest
bill_distr = dx.strip(tips, x="total_bill", by="day", color_discrete_sequence=["lightblue"])

bill_distr2 = dx.strip(tips, x="total_bill", by="day")
```

If `color_discrete_sequence` is not explicitly specified, the plot is blank.

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/strip.md
> +> At the moment, `color_discrete_sequence` must be specified explicitly.
What does this mean?  What does this do?  Is there a ticket?

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/sub-plots.md
Above ...
```suggestion
Multiple sub plots can be combined into one plot using the `make_subplots` function. This function accepts multiple plot objects, and returns a single plot object. The plot objects can be any of the plot types supported by Deephaven Express. They can be arranged in a grid, single row, or column. The `shared_xaxes` and `shared_yaxes` parameters can be used to share axes between plots.
```

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/sub-plots.md
Note that this file also does not follow the style of the other methods.

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/sunburst.md
> +continent_population = dx.sunburst(gapminder_recent.update("world = `world`"), names="continent", values="pop", parents="world")
```suggestion
import deephaven.plot.express as dx
gapminder = dx.data.gapminder() # import a ticking version of the Gapminder dataset

# create table of only the most recent year of data, compute total population for each continent
gapminder_recent = (
    gapminder
    .last_by("country")
    .view(["continent", "pop"])
    .sum_by("continent")
    .update("world = `world`")
)

# create a basic sunburst plot by specifying the categories, the values of interest, and a single root 'world'
continent_population = dx.sunburst(gapminder_recent, names="continent", values="pop", parents="world")
```

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/timeline.md
> +jobs_resource_tracking = dx.timeline(jobs, x_start="StartTime", x_end="EndTime", y="Job")
This example is identical to the prior example and is not doing what it says it does.

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/treemap.md
> +continent_population = dx.treemap(gapminder_recent.update("world = `world`"), names="continent", values="pop", parents="world")
```suggestion
import deephaven.plot.express as dx
gapminder = dx.data.gapminder() # import a ticking version of the Gapminder dataset

# create table of only the most recent year of data, compute total population for each continent
gapminder_recent = (
    gapminder
    .last_by("country")
    .view(["continent", "pop"])
    .sum_by("continent")
    .update("world = `world`")
)

# create a basic treemap plot by specifying the categories, the values of interest, and a single root 'world'
continent_population = dx.treemap(gapminder_recent, names="continent", values="pop", parents="world")
```

2024-07-23 20:29 UTC, chipkent commented on plugins/plotly-express/docs/line.md
In another document, `color` and `by` are aliases for one another.  All of the other docs (I think) use `by`.  Any reason not to use `by` in this doc?

2024-07-24 18:26 UTC, alexpeters1208 commented on plugins/plotly-express/docs/icicle.md
Our impl currently does not accept a "path" argument, which is the thing needed to turn this plot into something pretty. See the "rectangular data frame" part of the linked plotly doc.

2024-07-24 21:11 UTC, alexpeters1208 commented on plugins/plotly-express/docs/timeline.md
> +jobs_resource_tracking = dx.timeline(jobs, x_start="StartTime", x_end="EndTime", y="Job")
I didn't notice this initially. Getting the example "right" gives some pretty bad results. Putting the code in but leaving this comment open.

2024-07-24 21:11 UTC, alexpeters1208 commented on plugins/plotly-express/docs/timeline.md
> +jobs_resource_tracking = dx.timeline(jobs, x_start="StartTime", x_end="EndTime", y="Job")
https://github.com/deephaven/deephaven-plugins/issues/665

2024-07-24 21:13 UTC, alexpeters1208 commented on plugins/plotly-express/docs/histogram.md
> +```python order=sep_length_multi,sep_length_multi_overlay,iris
This will need a new release of the plotly-express plugin to resolve.

2024-07-24 21:14 UTC, alexpeters1208 commented on plugins/plotly-express/docs/icicle.md
I don't think so. If someone is here, they're here for the specifics of our stuff. They probably know how to find plotly. I'm not opposed to linking the first mention of "Icicle charts" or something to the plotly doc.

2024-07-25 18:24 UTC, dsmmcken commented on plugins/plotly-express/docs/scatter.md
> +### Change axis scale
think about searchability in titles. I would keep these separate so the word "log" and the word "range" can both be used in the title rather than combine to one section. Sections are free.

2024-07-25 18:24 UTC, dsmmcken commented on plugins/plotly-express/docs/scatter.md
> -### Large Data Sets
Please keep and revise this section, it is useful information. Both conceptually on when to use opacity, and that the alternative exists can be shown. Density heatmap is now supported.

2024-07-26 15:23 UTC, dsmmcken requested changes
Sorry - I hadn't mentioned this previously but one of the reasons I pushed for all our example data sets to be deterministic was for testing.  This one example is not.

2024-07-26 15:23 UTC, dsmmcken commented on plugins/plotly-express/docs/density_heatmap.md
> +])
This example is non-deterministic. I don't want any non-deterministic examples in our docs, as my plan is to eventually use these docs as a set of regression tests and random results would prevent that.

2024-07-26 15:55 UTC, dsmmcken commented on plugins/plotly-express/docs/plot-by.md
Just noting for context, there's a subset of docs presented differently than the others that cover more general concepts that can be applied to multiple plot types. They are presented seperately, but that's not apparent in this  review:

![image](https://github.com/user-attachments/assets/b7f5a0ee-d057-4192-8150-80513b9cc395)

2024-07-26 16:49 UTC, alexpeters1208 commented on plugins/plotly-express/docs/multiple-axes.md
> +When two or more response variables appear in separate columns, passing multiple column names to `x` or `y` is the recommended way to create multiple axes.
I don't understand, I get this:
<img width="867" alt="Screenshot 2024-07-26 at 11 48 41 AM" src="https://github.com/user-attachments/assets/abb90313-db62-4104-98fb-322aad18ff02">
which has the "pop" axis on the left and the "gdpPercap" axis on the right

2024-07-26 16:58 UTC, alexpeters1208 commented on plugins/plotly-express/docs/multiple-axes.md
> +line_plot_by = dx.line(cat_dog, x="timestamp", y="price", by="sym", yaxis_sequence=[1, 2])
In the particular example I wrote down, the stock data is always done deterministically, so the same data will always come first. In general you're right, may need a dict argument to be useful.

2024-07-26 17:06 UTC, alexpeters1208 commented on plugins/plotly-express/docs/plot-by.md
> +)
https://github.com/deephaven/deephaven-plugins/issues/674

2024-07-26 17:07 UTC, alexpeters1208 commented on plugins/plotly-express/docs/strip.md
> +bill_distr = dx.strip(tips, x="total_bill", by="day", color_discrete_sequence=["lightblue"])
https://github.com/deephaven/deephaven-plugins/issues/674

2024-07-26 18:27 UTC, chipkent commented on plugins/plotly-express/docs/plot-by.md
Got it

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/area.md
> +### Color by group
```suggestion
### Area by group
```

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/line.md
>  ### Color line plot by group
```suggestion
### Line by group
```

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/scatter.md
>      # color parameter will used as the actual color
```suggestion
    # grouping/color parameter will used as the actual color
```

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/sidebar.json
`other.md` was deleted, but it is still in the sidebar.

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/violin.md
> +violin_plot = dx.violin(versicolor, x="SepalLength")
```suggestion
violin_plot_x = dx.violin(versicolor, x="SepalLength")
violin_plot_y = dx.violin(versicolor, y="SepalLength")
```

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/violin.md
> +Visualize the distribution of a single variable by passing the column name to the `x` or `y` arguments.
Explain the difference in x and y

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/multiple-axes.md
> +line_plot_by = dx.line(cat_dog, x="timestamp", y="price", by="sym", yaxis_sequence=[1, 2])
This needs a ticket to assess the library.  It is not a problem with your example.

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/scatter.md
> +Denote groups of data by using the color of the markers as group indicators by passing the grouping column to the `by` argument.
No objection to including a description in the plot-by doc.  That makes sense.

2024-07-26 19:39 UTC, chipkent commented on plugins/plotly-express/docs/multiple-axes.md
> +When two or more response variables appear in separate columns, passing multiple column names to `x` or `y` is the recommended way to create multiple axes.
Take this example:
```python
import deephaven.plot.express as dx
gapminder = dx.data.gapminder() # import a ticking version of the Gapminder dataset

# get a specific country
brazil = gapminder.where("country == `Brazil`")

# specify multiple y-axis columns and order axes left to right with yaxis_sequence
line_plot_multi = dx.line(brazil, x="year", y=["pop", "gdpPercap"], yaxis_sequence=[1, 2])
line_plot_multi_2 = dx.line(brazil, x="year", y=["pop", "gdpPercap"])
```

<img width="863" alt="image" src="https://github.com/user-attachments/assets/d2612b1e-4b37-4fc9-a24d-d223adddfd2f">
<img width="865" alt="image" src="https://github.com/user-attachments/assets/c078e033-3e2e-4026-9f98-2bc90bfe3c48">


Passing multiple value to y is **NOT** how the multiple axes are created.  That creates two lines.  To create separate axes for the lines, you need to specify `yaxis_sequence`.  This interaction is not clear in the prose or example.  The example would be better with two plots like I have.  Show that providing `y=[a,b]` gives two lines, and then adding `yaxis_sequence` puts them on different axes.  As it is, the prose is incorrect and doesn't show them how to do these two common cases.

2024-07-26 21:28 UTC, chipkent commented on plugins/plotly-express/docs/plot-by.md
> +Under the hood, the Deephaven query engine performs a `parition_by` table operation on the given color column to create each series. This efficient implementation means that plots with multiple group
```suggestion
Under the hood, the Deephaven query engine performs a `parition_by` table operation on the given grouping column to create each series. This efficient implementation means that plots with multiple groups can easily scale to tens of millions or billions of rows with ease.
```

2024-07-26 21:28 UTC, chipkent commented on plugins/plotly-express/docs/multiple-axes.md
> +```
```suggestion
When two or more response variables appear in separate columns, pass their column names to the `x` or `y` arguments.  The resulting chart will have shared axes.

```python order=line_plot_shared,brazil,gapminder
import deephaven.plot.express as dx
gapminder = dx.data.gapminder()

# get a specific country
brazil = gapminder.where("Country == `Brazil`")

# population and per capita gdp have very different scales and units
line_plot_shared = dx.line(brazil, x="Year", y=["Pop", "GdpPerCap"])
```

`xaxis_sequence` or `yaxis_sequence` can be used to create multiple axes.

```python order=line_plot_multi,brazil,gapminder
import deephaven.plot.express as dx
gapminder = dx.data.gapminder()

# get a specific country
brazil = gapminder.where("Country == `Brazil`")

# specify multiple y-axis columns and split axes with yaxis_sequence
line_plot_multi = dx.line(brazil, x="Year", y=["Pop", "GdpPerCap"], yaxis_sequence=[1, 2])
```
```

This is now in simple to complex order and doesn't try to imply usefulness.

2024-07-26 21:50 UTC, jnumainville requested changes

2024-07-26 21:50 UTC, jnumainville commented on plugins/plotly-express/docs/plot-by.md
> +To plot multiple series from a table into a single chart, use the `by` parameter. This parameter accepts a column name or a list of column names denoting other variables of interest in the dataset. T
it should be clarified that `by` is not simply an alias for `color`
it can be tweaked by using `by_vars` and passing in these other columns such as `symbol` and `size`
it also behaves slightly differently though, take this example
```
import deephaven.plot.express as dx
tips = dx.data.tips() # import the example iris data set

by_list = dx.scatter(tips, x="TotalBill", y="Tip", by=["Time", "Smoker"], by_vars=["color", "symbol"])
by_prod = dx.scatter(tips, x="TotalBill", y="Tip", by="Time", symbol="Smoker")
```
`by_list` just loops through color/symbol combos (jointly)
whereas `by_prod` assigns colors to specific column values, so, of the four joint values, `Lunch` and `Dinner` have the same color and `Yes` and `No` have the same symbol.

The first method is more useful to emphasize differences, whereas the second is more useful to emphasize similarities.

2024-07-26 21:50 UTC, jnumainville commented on plugins/plotly-express/docs/plot-by.md
> +Under the hood, the Deephaven query engine performs a `parition_by` table operation on the given color column to create each series. This efficient implementation means that plots with multiple group
```suggestion
Under the hood, the Deephaven query engine performs a `partition_by` table operation on the given color column to create each series. This efficient implementation means that plots with multiple groups can easily scale to tens of millions or billions of rows with ease.
```

2024-07-26 22:09 UTC, alexpeters1208 commented on plugins/plotly-express/docs/plot-by.md
> +To plot multiple series from a table into a single chart, use the `by` parameter. This parameter accepts a column name or a list of column names denoting other variables of interest in the dataset. T
I removed the "for which `by`" is an alias" part - hopefully that cleans up the confusion. As far as using `by_vars`, that seems like something that should belong in the expanded version of this doc once the full thing is written, and not necessarily in the introduction. What do you think?

2024-07-26 22:17 UTC, jnumainville commented on plugins/plotly-express/docs/plot-by.md
> +To plot multiple series from a table into a single chart, use the `by` parameter. This parameter accepts a column name or a list of column names denoting other variables of interest in the dataset. T
Yeah, shouldn't be in the intro, that's fine

2024-07-27 18:29 UTC, chipkent submitted a review, later dismissed

2024-07-27 18:29 UTC, chipkent commented on plugins/plotly-express/docs/plot-by.md
> +Under the hood, the Deephaven query engine performs a `partition_by` table operation on the given grouping column to create each series. This efficient implementation means that plots with multiple g
Ultimately, `partition_by` should be linked, but I don't know that @dsmmcken is far enough down the new impl to worry about this yet.

2024-07-29 15:19 UTC, dsmmcken commented on plugins/plotly-express/docs/sidebar.json
> +          },
It made more sense to me to organize this sidebar alphabetically, so this should be moved up.

2024-07-29 15:27 UTC, dsmmcken approved these changes

2024-07-29 15:32 UTC, jnumainville approved these changes

2024-07-29 15:40 UTC, merged