ci: Action to upload docs
deephaven/deephaven-plugins pull request #563
Opened 2024-06-18 18:19 UTC by jnumainville

Fixes #508 

Tested a bunch on my own fork.

We'll also need a secret added to store the config. I have the config but don't think I have permissions to add the secret.

2024-06-19 13:38 UTC, mofojed requested changes
I can add the secret when necessary, or we can get @devinrsmith to if we want it to be an organization wide secret (which maybe we do, if we're going to be publishing docs from other repos such as grid docs).

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/build-main-docs.yml
> +        type: string
Wonder if we should add a `workflow_dispatch` as well, in case we need to manually publish the docs for some reason?

```
  workflow_dispatch:
    inputs:
      package:
        description: 'Plugin to publish docs for'
        required: true
        type: choice
        options:
          - 'plotly-express'
          - 'ui'
```

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/build-main-docs.yml
> +      package:
Add a description
```suggestion
      package:
        description: 'Plugin to publish the docs for'
```

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/build-python-package.yml
> +              registry-url: 'https://registry.npmjs.org'
We should be using the `.nvmrc` file, which specifies node v20. We should update this in the other actions as well.
```suggestion
          - name: Setup Node
            uses: actions/setup-node@v4
            with:
              node-version-file: '.nvmrc'
              cache: 'npm'
```

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/build-python-package.yml
> +          - name: Check file existence
We should be able to do this before the Setup Node step I think? Shouldn't need Node if there's no package.json.
That being said, all our plugins are probably going to have JS anyway so we're not getting any sort of benefits there really.

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/make-docs.yml
> +          echo ${{ secrets.RCLONE_CONFIG }} | base64 -d > $HOME/.config/rclone/rclone.conf
I want more details about this rclone config - I'm assuming the only part that's really "secret" is our token or something? Can we have the rest of a config in a file and then just the token as a secret?

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/modified-plugin.yml
> +      version: ${{ steps.filter-tag.outputs.version }}
Hmm shouldn't we be getting the version from the package? Or are we expecting a version like a release branch (e.g. main, vplus, grizzly, or just v0.78, v0.82, etc)? Unsure how we're grouping packages.

2024-06-19 13:38 UTC, mofojed commented on .github/workflows/release-python-package.yml
> +    if: ${{ inputs.package == 'plotly-express' }}
We should just filter on if there's a `make_docs.py` in that folder instead of checking if it's in a whitelist.

2024-06-20 14:35 UTC, jnumainville commented on .github/workflows/make-docs.yml
> +          echo ${{ secrets.RCLONE_CONFIG }} | base64 -d > $HOME/.config/rclone/rclone.conf
there's three parts that are secret
```
[plugindocs]
type = s3
provider = Cloudflare
access_key_id = <secret 1>
secret_access_key = <secret 2>
endpoint = <secret 3>
no_check_bucket = true
acl = private
```
we certainly could have three secrets though if that's better

2024-06-20 15:20 UTC, mofojed commented on .github/workflows/make-docs.yml
> +          echo ${{ secrets.RCLONE_CONFIG }} | base64 -d > $HOME/.config/rclone/rclone.conf
Yea let's go with three secrets in the organization and have the config file in the repo.

2024-06-21 13:05 UTC, mofojed approved these changes

2024-06-21 17:41 UTC, jnumainville commented
Everything is working now

2024-06-25 18:51 UTC, mofojed approved these changes

2024-06-25 19:15 UTC, mofojed requested changes

2024-06-25 19:15 UTC, mofojed commented on .github/workflows/make-docs.yml
> +          endpoint = ${{ secrets.CLOUDFLARE_ENDPOINT }}
@dsmmcken suggested we prefix these keys with `DOCS_` so we know what the secrets are for

2024-06-25 19:17 UTC, dsmmcken commented on .github/workflows/make-docs.yml
> +          endpoint = ${{ secrets.CLOUDFLARE_ENDPOINT }}
yes please

2024-06-25 19:19 UTC, mofojed approved these changes

2024-06-25 19:30 UTC, merged