feat: Make autodoc output structured
deephaven/deephaven-plugins pull request #582
Opened 2024-06-25 20:24 UTC by jnumainville

Fixes #566 

This adds a custom sphinx directive (`dhautofunction`) that takes the output of sphinx `autofunction` and extracts relevant data. Here is a snippet of the generated item in the area doc (in the doc it is all on one line)
```
<ParamTable param={{
  "module_name": "deephaven.plot.express.", 
  "name": "area", 
  "description": "Returns an area chart", 
  "parameters": [{"name": "table", "type": "Table | None", "description": "A table to pull data from.", "default": "None"}, ...], 
  "return_description": "A DeephavenFigure that contains the area chart", 
  "return_type": "DeephavenFigure"}}
 />
```

2024-06-27 13:27 UTC, mofojed requested changes

2024-06-27 13:27 UTC, mofojed commented on .pre-commit-config.yaml
> +        files: (plugins.*\/src|sphinx_ext).*\.py
Was just digging into this a bit, there's a `types` filter in pre-commit: https://pre-commit.com/#filtering-files-with-types
So could in theory do `types: ['file', 'python']` instead of `.*\.py` at the end of the regex. That would avoid sym-links, but it also matches files with shebang:
> Files can also be matched by shebang. With types: python, an exe starting with #!/usr/bin/env python3 will also be matched.

Anyway, not saying we should do that, just thought it was interesting to know. Might be a little cleaner.

But here the regex is incorrect, it should be cleaned up for sure. There's no `/` after the plugins folder, so it would technically match something like `plugins-test/src-bad-file.py`. Should have the correct slashes:
```suggestion
        files: (plugins\/.*\/src|sphinx_ext)\/.*\.py
```

2024-06-27 13:27 UTC, mofojed commented on plugins/plotly-express/make_docs.py
> +                        if "<ParamTable param={{" in line:
Shouldn't we also check the comment marker? Is the comment marker always at the beginning and end of the line? Wondering if we should do `line.startswith("<!.......")` and .endswith so we're more restrictive.

2024-06-27 13:27 UTC, mofojed commented on sphinx_ext/.gitignore
> +__pycache__/*.pyc
Shouldn't we just `.gitignore` all of `__pycache__`?

2024-06-27 13:27 UTC, mofojed commented on sphinx_ext/deephaven_autodoc.py
> +    default: str | None
Can't `default` already be omitted because `total=False`? 

Actually I see what's up here. You want `name`, `type`, `description` required, but not `default`. I think the correct way to type this is to use [`typing.NotRequired`](https://docs.python.org/3/library/typing.html#typing.NotRequired)

```suggestion
class ParamData(TypedDict):
    name: str
    type: str
    description: str
    default: NotRequired[str]
```

2024-06-27 18:09 UTC, mofojed requested changes

2024-06-27 18:09 UTC, mofojed commented on plugins/plotly-express/make_docs.py
> +    os.chdir(dirname)
Should we use a pushd here? Something like https://gist.github.com/howardhamilton/537e13179489d6896dd3

2024-06-27 18:09 UTC, mofojed commented on plugins/plotly-express/requirements.txt
Rename sphinx-requirements.txt

2024-07-02 19:19 UTC, dsmmcken commented
Are those keys constant?

Like is it always "module_name" or could that be different if it's not a module?

Note we could also write it as actual params rather then a dict, to remove wrapper if it's any easier.

```
<ParamTable name="name" description="..." params=[{...}] />
```

2024-07-03 17:31 UTC, jnumainville commented
`module_name` was just an alias I created for info extracted from the `desc_addname` node as it seems like it would generally be the module
https://www.sphinx-doc.org/en/master/extdev/nodes.html#sphinx.addnodes.desc_addname
I don't think passing params directly would make anything easier on the extension side, but it could be done if it's preferable for the usage side

2024-07-05 19:35 UTC, dsmmcken approved these changes
approving in that, it does what I need. Haven't reviewed any code, so that's on @mofojed

2024-07-05 21:06 UTC, mofojed approved these changes

2024-07-05 21:06 UTC, merged