UI table layout hints
deephaven/deephaven-plugins pull request #587
Opened 2024-06-27 19:58 UTC by mattrunyon

Fixes #442

The layout hints will only be used as the initial state. Not sure how we'd want to try to combine a change in `ui.table` from the server w/ other changes the user may have made already. At least initially I think this is fine to give the same functionality as current `table.layout_hints`

2024-07-04 15:03 UTC, mofojed requested changes
Small change about the `color`

2024-07-04 15:03 UTC, mofojed commented on plugins/ui/src/js/src/elements/UITable/JsTableProxy.ts
> +  }) {
Any reason not to make `layoutHints` optional?
```suggestion
  constructor({
    table,
    layoutHints = {},
  }: {
    table: dh.Table;
    layoutHints?: UITableLayoutHints;
  }) {
```

2024-07-05 17:49 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/UITable/JsTableProxy.ts
> +  }) {
Right now we only need it from 1 spot, so I didn't want it to get accidentally left out if we had to create the table conditionally in the future for some reason. At least this way you have to be explicit that you're dropping `layoutHints`

I guess we could make it `| undefined` and then make undefined not set the value in the proxy class so it falls back to the underlying table. But that seems unnecessary right now

2024-07-08 12:38 UTC, mofojed approved these changes

2024-07-09 19:49 UTC, merged