feat: UI ComboBox component
deephaven/deephaven-plugins pull request #588
Opened 2024-06-27 20:11 UTC by bmingles

resolves #201

2024-07-03 12:55 UTC, mofojed requested changes

2024-07-03 12:55 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/combo_box.py
> +    **props: Any,
Why are you allowing additional props here? All props need to be documented, do not allow additional undocumented props here.

2024-07-09 13:11 UTC, mofojed requested changes
Minor change, looks good

2024-07-09 13:11 UTC, mofojed commented on plugins/ui/docs/README.md
> +A combo_box can also take an `item_table_source`. It will use the columns specified.
```suggestion
A `combo_box` can also take an `item_table_source`. It will use the columns specified.
```

2024-07-09 14:23 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/combo_box.py
> +    **props: Any,
fixed

2024-07-09 18:45 UTC, mofojed approved these changes

2024-07-09 19:22 UTC, merged