fix: remove Number type and replace with bool
deephaven/deephaven-plugins pull request #590
Opened 2024-06-27 21:35 UTC by AkshatJawne

Resolves #589 

**Changes Implemented:**
- Replaced all instances of Number with float, since float works for ints, and Number was just a union of int and float

2024-06-27 21:46 UTC, mattrunyon commented
@joe thoughts on banning this import via ruff?

ruff.toml I think would just need to be

```toml
[lint]
select = ["ANN001", "TID251"]

[lint.per-file-ignores]
"**/{test,matplotlib,json,plotly}/*" = ["ANN001"]

[lint.flake8-tidy-imports.banned-api]
"Number".msg = "Import from Number is likely an accident. `float` includes `int` and is likely the desired type."
```

2024-06-27 21:51 UTC, jnumainville commented
I think banning it is a good idea for now.

2024-06-27 21:53 UTC, mattrunyon commented
@AkshatJawne Update the root `ruff.toml` with what I commented and then try adding back one of those imports locally. Look in the readme for instructions on setting up `pre-commit` (you don't have to run `pre-commit install` if you don't want it to run before every commit).

Then you can run `pre-commit run --all-files` to test

2024-06-27 21:58 UTC, AkshatJawne commented
Modified the ruff.toml file, do not see the warning.

2024-06-27 22:12 UTC, mattrunyon requested changes
Comments apply to all `z_index` and `order`

2024-06-27 22:12 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/view.py
> +    z_index: float | None = None,
`z_index` actually needs to just be `int`. `float` is an illegal value for `z_index`

2024-06-27 22:12 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/components/view.py
> +    order: float | None = None,
`order` must be an `int`. `float` is not valid for `order`

2024-06-28 18:25 UTC, mattrunyon approved these changes

2024-06-28 19:08 UTC, merged