feat: Replace shortid with nanoid
deephaven/deephaven-plugins pull request #591
Opened 2024-06-28 15:43 UTC by AkshatJawne

Resolves https://github.com/deephaven/deephaven-plugins/issues/568

**Changes Implemented:**
- Replace `shortid` package with `nanoid`

2024-06-28 15:48 UTC, AkshatJawne commented
Looking into e2e

2024-07-02 13:49 UTC, mattrunyon requested changes
Looks like you have a package-lock conflict. Will need to merge main and then run `npm install --package-lock-only`

2024-07-02 14:17 UTC, AkshatJawne commented
Ready for re-review, resolved package.lock errors

2024-07-02 14:31 UTC, mattrunyon requested changes

2024-07-02 14:31 UTC, mattrunyon commented on plugins/dashboard-object-viewer/src/js/package.json
> +    "nanoid": "^5.0.7"
This one is still out of alphabetical order

2024-07-02 14:32 UTC, AkshatJawne commented on plugins/dashboard-object-viewer/src/js/package.json
> +    "nanoid": "^5.0.7"
Hmm that's weird that it did not fix when I reinstalled, will fix now

2024-07-02 16:58 UTC, mattrunyon approved these changes

2024-07-02 17:00 UTC, merged