feat: density heatmap
deephaven/deephaven-plugins pull request #598
Opened 2024-07-03 20:35 UTC by jnumainville

Fixes #22 
This doesn't add every argument, but does add the core ones and trivial ones

I have not fully tested everything and I still need unit tests, hence this being a draft, but wanted to get out this in a draft. 

Here is a good example of the basic ways this can be used, either with `x`, `y`, and `histfunc="count"`, or `x`, `y`, `z`, and any `histfunc`, as well as other arguments to control the binning as, like `histogram`, how someone chooses to bin has a large impact on the visualization

```
import deephaven.plot.express as dx
from deephaven import new_table, agg

from deephaven import time_table

result = time_table(period="PT1S").update(["X = randomGaussian(10, 3)", "Y = randomGaussian(10, 3)", "Z = randomGaussian(10, 3)"])

density_heatmap = dx.density_heatmap(result, "X", "Y", title="Test", range_bins_x=[0, 20], range_bins_y=[0, 20], nbinsx=20, nbinsy=20)
density_heatmap_z = dx.density_heatmap(result, "X", "Y", "Z", title="Test", histfunc="std", range_bins_x=[0, 20], range_bins_y=[0, 20], nbinsx=5, nbinsy=5)
```

2024-07-10 22:24 UTC, jnumainville commented
I've opened for review although I'm going to iron out one more parameter that I think is important to have before this ships
```
default_bin_value: The value to use for bins that have no data.
  If None and histfunc is 'abs_sum', 'count' or 'count_distinct', 0 is used.
  Otherwise, NaN is used.
```

2024-07-10 23:08 UTC, jnumainville commented
Put this up for review but going to add one more arg
```
      default_bin_value: The value to use for bins that have no data.
        If None and histfunc is 'count' or 'count_distinct', 0 is used.
        Otherwise, if None or 'NaN', NaN is used.
```

2024-07-12 13:44 UTC, mofojed requested changes
Some other `density_heatmap` functions I tested with, adapted from https://plotly.com/python/2D-Histogram/#density-heatmaps-with-plotly-express:
```python
import deephaven.plot.express as dx
tips = dx.data.tips()
f_tips = dx.density_heatmap(tips, x="total_bill", y="tip")
f_tips2 = dx.density_heatmap(tips, x="total_bill", y="tip", nbinsx=20, nbinsy=20, color_continuous_scale="Inferno")

iris = dx.data.iris()
f_iris = dx.density_heatmap(iris, x="petal_length", y="petal_width", z="sepal_length", histfunc="avg")
```

2024-07-12 13:44 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/custom_draw.py
> +    color_continuous_scale: str | None = "Viridis",
I think this is supposed to support `list[str]` as well as just `str`? I can specify something like `['red', 'green']` and it works as I would expect.
What pre-defined values are available? Looking in the plotly express docs: https://plotly.com/python/colorscales/#color-scales-in-plotly-express
They have some defined as constants, e.g. `px.colors.sequential.Viridis`. We should probably expose those through `dx` as well.
_Should_ we be defaulting to `Viridis`? Or something else.

2024-07-12 13:44 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/custom_draw.py
> +    color_continuous_midpoint: list[float] | None = None,
I don't think this allows a `list[float]`, getting an error when I specify an array:
```
r-Scheduler-Serial-1 | .c.ConsoleServiceGrpcImpl | Error running script: java.lang.RuntimeException: Error in Python interpreter:
Type: <class 'ValueError'>
Value: 
    Invalid value of type 'builtins.list' received for the 'cmid' property of layout.coloraxis
        Received value: [-5, 0]

    The 'cmid' property is a number and may be specified as:
      - An int or float
```

2024-07-12 13:44 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/plots/heatmap.py
> +    color_continuous_scale: str | None = None,
As per my other comment about `color_continuous_scale`, should be `list[str]` as well as `str`.
We should probably be defining the pre-defined constants as well in `dx.colors.sequential` like https://plotly.com/python/colorscales/#color-scales-in-plotly-express (though can be a separate ticket to create/define those.

2024-07-12 15:01 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/deephaven_figure/custom_draw.py
> +    color_continuous_scale: str | None = "Viridis",
Ah, no, we should be defaulting to "plasma"

2024-07-12 15:01 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/heatmap.py
> +    color_continuous_scale: str | None = None,
I agree. I'll create a ticket

2024-07-16 12:51 UTC, mofojed requested changes

2024-07-16 12:51 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/utilities.py
> +    empty_bin_default: float | str | None,
Should specify `Literal["NaN"]` here as well... since `empty_bin_default` does not accept any `str`, or if it does need to change the code below.
Maybe should use a `Sentinel` for `NaN` instead?

2024-07-16 12:51 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/plots/heatmap.py
> +        the bin will still be NaN if less than the required number of points are present.
Is there a point in distinguishing `None` vs `"NaN"`? In both cases it ends up showing `NaN`, right? If we don't _really_ need the `Literal["NaN"]` case, let's remove it.

2024-07-16 12:51 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/preprocess/utilities.py
> +            f"{agg_col} = replaceIfNull({agg_col}, {empty_bin_default})"
Currently this would fail if `empty_bin_default` was some other `str`. I don't think that's a valid case though, so my suggestion would be to update the type to just remove `str` (I don't think we really need the `Literal["NaN"]` case, as per my other comment). If we do, then check for a `str` value here and wrap with quotes as necessary (or raise an error).

2024-07-16 23:04 UTC, mofojed approved these changes

2024-07-16 23:04 UTC, merged