docs: form
deephaven/deephaven-plugins pull request #602
Opened 2024-07-05 03:54 UTC by ethanalvizo

Closes #579

2024-07-08 13:36 UTC, mofojed requested changes

2024-07-08 13:36 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # action # omitted because not sure what "server" the form is sending it's data to
We should leave this prop, it's possible to set up a form that communicates with a 3rd party server on submission. An example codepen showing this in action with regular forms: https://codepen.io/mofojed/pen/xxoxppW
And a codesandbox showing this in React Spectrum: https://codesandbox.io/p/sandbox/react-spectrum-playground-forked-rfctrs

I'm actually a little confused why this doesn't work already:

```python
from deephaven import ui

f = ui.form(
    ui.text_field( name="first_name", default_value="Mickey", label="First Name"),
    ui.text_field(name="last_name", default_value="Mouse", label="Last Name"),
    ui.button("Submit", type="submit"),
    action="https://postman-echo.com/get",
    method="get",
    target="_blank"
)
```

2024-07-08 13:36 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # on_invalid,
These are all valid and should already be wired up/working. We have an example in our README, but you can also test with something simple:
```python
from deephaven import ui

f = ui.form(
    ui.text_field( name="first_name", default_value="Mickey", label="First Name"),
    ui.text_field(name="last_name", default_value="Mouse", label="Last Name"),
    ui.button("Submit", type="submit"),
    on_submit=print
)
```

2024-07-12 13:13 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # on_invalid,
on_invalid is being called properly but the error message around field isn't working as expected. Using the example below the "Invalid form submission" statement is being printed but there is no error showing up around the email text_field. 

```
from deephaven import ui

f = ui.form(
    ui.text_field(name="email", label="Email", type="email", is_required=True),
    ui.button_group(
      ui.button("Submit", type="submit"),
      ui.button("Reset", type="reset"),
    ),
    on_submit=lambda e: print(f"Form submitted: {e}"),
    on_invalid=lambda e: print(f"Invalid form submission: {e}"),
    on_reset=lambda e: print(f"Form reset: {e}"),
    validation_behavior="native"
)
```

Think it's because something is always being passed into on_invalid prop. Tried passing undefined in 3 different spots but no luck

1. In `useFormEventCallback.ts`
```
export function useFormEventCallback(
  callback?: SerializedFormEventCallback
): (e: React.FormEvent<HTMLFormElement>) => void {
  return useCallback(
    (e: React.FormEvent<HTMLFormElement>) => {
      // We never want the page to refresh, prevent submitting the form
      e.preventDefault();

      if (!callback) {
        return;
      }

      // Return the data to the server
      const data = Object.fromEntries(new FormData(e.currentTarget));
      callback?.(data);
    },
    [callback]
  );
}
```
2. In `useFormEventCallback.ts`. Can't call hooks conditionally
```
export function useFormEventCallback(
  callback?: SerializedFormEventCallback
): (e: React.FormEvent<HTMLFormElement>) => void {
  return callback
    ? useCallback(
        (e: React.FormEvent<HTMLFormElement>) => {
          // We never want the page to refresh, prevent submitting the form
          e.preventDefault();

          // Return the data to the server
          const data = Object.fromEntries(new FormData(e.currentTarget));
          callback?.(data);
        },
        [callback]
      )
    : undefined;
}
```
3. In `Form.tsx`. Can't call hooks conditionally
```
const onInvalid = propOnInvalid
    ? useFormEventCallback(propOnInvalid)
    : undefined;
```

2024-07-12 14:07 UTC, mofojed requested changes

2024-07-12 14:07 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # on_invalid,
See my comment in review, the `validation_state` should default to `None` instead of a value; setting a value causes the validation state to be controlled, which is not what we're testing here. Spectrum docs seem to be incorrect saying the default is `"valid"` - default is `undefined`.

As for calling a hook unconditionally, correct, you can't call a hook unconditionally - however, you _can_ conditionally return an `undefined` value. E.g.
```
export function useFormEventCallback(
  callback?: SerializedFormEventCallback
): ((e: React.FormEvent<HTMLFormElement>) => void) | undefined {
  const formCallback = useCallback(
    (e: React.FormEvent<HTMLFormElement>) => {
      // We never want the page to refresh, prevent submitting the form
      e.preventDefault();

      // Return the data to the server
      const data = Object.fromEntries(new FormData(e.currentTarget));
      callback?.(data);
    },
    [callback]
  );

  // Just return `undefined` here instead of the callback
  return callback ? formCallback : undefined;
}
```

But it looks like the main issue is the `validation_state` default, so this wasn't actually causing problems... that being said, may as well return `undefined` when the prop passed in is `undefined`.

2024-07-12 14:07 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # action # omitted because not sure what "server" the form is sending it's data to
This still isn't working for some reason. I'm unsure why. For now I'd submit with this PR, but we should have a follow up ticket to investigate why it isn't submitting.

2024-07-13 04:09 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # action # omitted because not sure what "server" the form is sending it's data to
https://github.com/deephaven/deephaven-plugins/issues/625

2024-07-13 17:48 UTC, mofojed requested changes

2024-07-13 17:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/form.py
> +    # action: str | None = None,
Sweet, this is actually working correctly now that we are returning `undefined` from `useFormEventCallback`. Add `action` back, and mark this PR as fixing #625

2024-07-15 13:11 UTC, mofojed approved these changes

2024-07-15 13:17 UTC, merged