docs: picker
deephaven/deephaven-plugins pull request #603
Opened 2024-07-05 03:54 UTC by ethanalvizo

Closes #418

2024-07-05 03:56 UTC, ethanalvizo commented
Accidentally based this branch off of my form pydocs branch. Should merge https://github.com/deephaven/deephaven-plugins/pull/602 first then this one.

2024-07-12 14:21 UTC, mofojed requested changes

2024-07-12 14:21 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    # Layout
```suggestion
```

2024-07-12 14:21 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    # disabled_keys
```suggestion
```

2024-07-12 14:21 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    # validate # omitted because it has synchronous return
```suggestion
```

2024-07-12 14:21 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    validation_behavior: ValidationBehavior | None = None,
```suggestion
    validation_behavior: ValidationBehavior | None = "aria",
```

2024-07-12 14:21 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    # on_load_more # omitted because it has synchronous return
This is incorrect, `on_load_more` can actually be an async return: https://react-spectrum.adobe.com/react-spectrum/Picker.html#asynchronous-loading

That being said, we're not supporting `items`, and `on_load_more` works with `items`, so just drop this.
```suggestion
```

2024-07-12 18:30 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    validation_behavior: ValidationBehavior | None = None,
Yes will create this PR when I get back. But all the other comments are addressed

2024-07-12 18:32 UTC, mofojed approved these changes

2024-07-12 19:37 UTC, merged

2024-07-13 04:06 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/picker.py
> +    validation_behavior: ValidationBehavior | None = None,
https://github.com/adobe/react-spectrum/pull/6701