fix: add default styling to tabs component
deephaven/deephaven-plugins pull request #611
Opened 2024-07-08 19:45 UTC by AkshatJawne

Resolves #360 (and also the request for a seperate styling PR made here: https://github.com/deephaven/deephaven-plugins/pull/489#issuecomment-2206860382)

Also, with regards to the snippet, as mentioned in [Matt's comment](https://github.com/deephaven/deephaven-plugins/issues/360#issuecomment-2163587101), to have this properly working, we will need to have a height and width set on the view itself:

>  But that also depends on its parent display type and would still be broken by the view without a height set

So to have the snippet work, it would have to be something like the following:

```
import deephaven.plot.express as dx
import deephaven.ui as ui
from deephaven import empty_table

tabs = ui.view(
    ui.tabs(
        ui.tab_list(ui.item("My Tab", key="tab1")),
        ui.tab_panels(
            ui.item(dx.scatter(empty_table(10).update(["X = i", "Y = i"]), x="X", y="Y"), key="tab1"),
        ),
    ),
    height="100%",
    width="100%"
)
```

2024-07-09 13:51 UTC, mofojed reviewed
I'm not sure we actually need this change anymore - from the ticket #360 , we had this example:
```python
import deephaven.plot.express as dx
import deephaven.ui as ui
from deephaven import empty_table

tabs = ui.view(
    ui.tabs(
        ui.tab_list(ui.item("My Tab", key="tab1")),
        ui.tab_panels(
            ui.item(dx.scatter(empty_table(10).update(["X = i", "Y = i"]), x="X", y="Y"), key="tab1"),
        ),
    ),
    margin="size-100"
)
```

But I don't think it should be wrapped in a `ui.view` at all. Instead, if you just do:
```python
import deephaven.plot.express as dx
import deephaven.ui as ui
from deephaven import empty_table

tabs = ui.tabs(
      ui.tab_list(ui.item("My Tab", key="tab1")),
      ui.tab_panels(
          ui.item(dx.scatter(empty_table(10).update(["X = i", "Y = i"]), x="X", y="Y"), key="tab1"),
      ),
  )
```

It appears correctly, with and without this change. So not sure what exactly this change is addressing.
For example, it looks like this example with a plot and table look correct without wrapping in a `ui.view`:
```python
import deephaven.plot.express as dx
import deephaven.ui as ui
from deephaven import empty_table

_stocks = dx.data.stocks()

tabs = ui.tabs(
    ui.item(dx.scatter(_stocks, x="timestamp", y="price"), title="Plot"),
    ui.item(_stocks, title="Data")
)
```
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/998e7140-9776-4232-a0a7-7b051f284e25)
![image](https://github.com/deephaven/deephaven-plugins/assets/4505624/4971d0d9-b403-4453-af59-c887ccbfb41e)


So I don't think this change is actually needed anymore. Pinging @dsmmcken to confirm behaviour.

2024-07-09 13:59 UTC, AkshatJawne commented
@mofojed Right, that makes sense. From my perspective, this change mainly does two things:

1. Adds the "compact" density by default, which @dsmmcken and @mattrunyon agreed looks better -- https://github.com/deephaven/deephaven-plugins/pull/489#issuecomment-2204501724

2. Adds the styling to the tabs component, such that if a user _wanted to_ wrap the tabs component in a `ui.view`, they could have it display correctly, assuming that they have a `height` and `width` set, as I showed in the snippet above.

However, if the idea is that we want to discourage users from wrapping tabs in a _ui.view_, I agree, the scss is **_definitely not needed_**. May still want the `density = "compact"` though, @dsmmcken can confirm.

2024-07-09 14:55 UTC, dsmmcken commented
I would change just compact density, other changes seems unnecessary now.

I would add some "size-100" to the tablist margin bottom by default though.

Unsure how the new tab component works, if it is a python wrapper of the tab_list, if so I would add that as a default on tab_list in python rather than JS, so it's surfaced to users as a default

2024-07-09 16:29 UTC, AkshatJawne commented
Should be good now, had to set to 8px instead of size-100, given that the marginBottom on the python side expects a `DimensionValue`.

2024-07-10 14:01 UTC, dsmmcken requested changes

2024-07-10 14:01 UTC, dsmmcken commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <TabList UNSAFE_style={{ marginBottom: '8px' }}>
Remove this

2024-07-10 14:01 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/tab_list.py
> +    margin_bottom: DimensionValue | None = "8px",
```suggestion
    margin_bottom: DimensionValue | None = "size-100",
```

2024-07-12 13:09 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <TabList UNSAFE_style={{ marginBottom: '8px' }}>
Will change this to size-100, but will need to keep this because the python default does not apply here because in the shorthand way, we are actually never creating ui.tab_list from python, we are composing a <TabList> component   on the React side with the provided info.

2024-07-12 13:23 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <TabList UNSAFE_style={{ marginBottom: '8px' }}>
Just rechecked, and as it was originally, size-100 is not working when I pass it into react in the UNSAFE_style. If you want, we can remove this, but then there will be inconsistent styling between the two ways of declaring ui.tabs.

2024-07-12 14:35 UTC, mofojed commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +      <TabList UNSAFE_style={{ marginBottom: '8px' }}>
That's because you should be passing it into the `marginBottom` prop, not the `UNSAFE_style` prop:
```suggestion
      <TabList marginBottom="size-100">
```

2024-07-12 14:39 UTC, mofojed requested changes
Don't use `UNSAFE_style`, use the `marginBottom` prop instead, with `size-100`.
Also should add that this fixes #476 to link that ticket and close it.
Will need to follow up with #477 (pydocs for `tab_panels`)

2024-07-12 14:46 UTC, mofojed requested changes

2024-07-12 14:46 UTC, mofojed commented on plugins/ui/src/js/src/elements/Tabs.tsx
> +        density="compact"
We should be setting the default in `tabs.py`, not here. We can remove this line, and `density="compact"` line below, if we set it correctly in `tabs.py`.

2024-07-12 15:10 UTC, mofojed approved these changes

2024-07-12 15:11 UTC, AkshatJawne commented
Need @dsmmcken 's approval to merge

2024-07-12 15:35 UTC, dsmmcken approved these changes

2024-07-12 15:37 UTC, merged