fix: remove non-existent types
deephaven/deephaven-plugins pull request #613
Opened 2024-07-09 18:50 UTC by dsmmcken

`cta` and `overBackground` aren't variants

2024-07-09 18:51 UTC, dsmmcken reviewed
~No idea where you got `cta` and `overBackground`, co-pilot hallucinations?~

I see now they are deprecated spectrum legacy options:

```
/** @deprecated */
type LegacyButtonVariant = 'cta' | 'overBackground';
```

2024-07-11 20:30 UTC, mofojed requested changes

2024-07-11 20:30 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/button.py
> +        href: A URL to link to if element_type="a".
Kind of confusing since we don't allow the user to actually specify `element_type="a"`. Maybe change up the wording?
```suggestion
        href: A URL to link to when the button is pressed.
```

2024-07-11 20:36 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/button.py
> +        href: A URL to link to if element_type="a".
thanks, I missed that.

2024-07-11 21:01 UTC, mofojed approved these changes

2024-07-12 16:51 UTC, merged