build: UI docs and add plugin_builder.py
deephaven/deephaven-plugins pull request #630
Opened 2024-07-16 19:49 UTC by jnumainville

Fixes #627 

Also adds a new tool `plugin_builder.py` that can be used to make some tasks like installing and developing plugins easier. The basic principle is you can either target specific plugins or target all plugins, depending on the command(s). This is a basic version and we can add on capabilities. Maybe unit tests or something that emulates editable installs for example. Specifically in this case, `python tools/plugin_builder.py --docs ui` can help test (although the requirements need to be installed first still).

2024-07-17 15:06 UTC, mofojed requested changes

2024-07-17 15:06 UTC, mofojed commented on tools/plugin_builder.py
> +            run_command(f"{install} {plugins_dir}/{plugin}/dist/*")
As long as we're cleaning the dist directory beforehand this should be okay. Previously there could be multiple wheel files left in this dir.

2024-07-17 15:06 UTC, mofojed commented on tools/plugin_builder.py
> +import argparse
When implementing the CLI for deephaven, I ended up using `click` instead of `argparse`: https://click.palletsprojects.com/en/8.1.x/
Chip made some points as to why: https://github.com/deephaven/deephaven-core/pull/5275#discussion_r1535828634
Take a look at using `click` instead

2024-07-17 17:22 UTC, jnumainville commented on tools/plugin_builder.py
> +            run_command(f"{install} {plugins_dir}/{plugin}/dist/*")
yeah exactly, I ran into that while testing this so figured it safe to just wipe them in this script to be safe

2024-07-19 22:24 UTC, jnumainville commented
@mofojed one thing I'm struggling with is the fact that we still have the `plotly` plugin around. It conflicts with the `plotly-express` plugin, which is not great when the default behavior is to install all plugins, including both of those. I played around with some sort of deprecation object, but it would make some of the implementation uglier for a package we won't be developing anymore anyways. Thoughts? A warning in the readme? Deleting the plugin?

2024-07-22 12:34 UTC, mofojed commented
Keep a README to notify of deprecation, delete the rest of the plugin.

2024-07-22 12:37 UTC, mofojed approved these changes

2024-07-22 15:33 UTC, merged