ci: Add registry-url and remove cache from publish action
deephaven/deephaven-plugins pull request #638
Opened 2024-07-17 17:10 UTC by mofojed

- Just trying the same settings as publishing on web-client-ui (where it's working)
- Switch actions/checkout to v4

2024-07-17 22:20 UTC, mattrunyon requested changes

2024-07-17 22:20 UTC, mattrunyon commented on package.json
> +  },
Is this needed? I think that should at least be node 18 and not 6?

2024-07-17 22:20 UTC, mattrunyon commented on plugins/ui/DESIGN.md
> +UI: https://github.com/mofojed/deephaven-plugins/tree/interactive
These are old links (and also don't seem to work)

2024-07-18 18:01 UTC, mofojed commented on package.json
> +  },
Not needed, I'll remove.

2024-07-18 20:39 UTC, mattrunyon approved these changes

2024-07-18 21:08 UTC, merged