fix: color type
deephaven/deephaven-plugins pull request #647
Opened 2024-07-19 03:01 UTC by ethanalvizo

Closes #600

2024-07-19 12:46 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +# Color values for the DH color palette exposed to end users in spectrum components
May as well add a link here to where we're getting these colours from: https://github.com/deephaven/web-client-ui/blob/main/packages/components/src/theme/colorUtils.ts

2024-07-22 12:49 UTC, mofojed approved these changes

2024-07-22 14:12 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/types/types.py
> +    "lemonchiffon",
```suggestion
```

These aren't real theme colors

2024-07-26 15:14 UTC, dsmmcken requested changes
Our implementation of both `ui.heading` and `ui.text` should all so accept a "color" prop that accepts Color type. (this is already implemented in web-client-ui and is a non-spectrum feature), but was not added to the heading.py or text.py

2024-07-26 20:20 UTC, mofojed submitted a review, later dismissed

2024-07-26 20:21 UTC, mofojed commented
@ethanalvizo just need to address Don's comment

2024-07-26 20:24 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/types/types.py
>  Color = Union[DeephavenColor, HexColor]
```suggestion
CSSColor= str
Color = Union[DeephavenColor, CSSColor]
```

I would probably name this CSSColor or something, because it actually accepts any valid css color not just hex colors.

2024-07-29 14:41 UTC, dsmmcken approved these changes

2024-07-30 12:03 UTC, mofojed approved these changes

2024-07-30 17:24 UTC, merged