feat: ui.text_area
deephaven/deephaven-plugins pull request #652
Opened 2024-07-22 20:53 UTC by AkshatJawne

Closes #649 

**Need to clarify:**
- Did not include `validate` or `validation_state` prop based off this comment on Text Field PR: https://github.com/deephaven/deephaven-plugins/pull/357#discussion_r1523474450

2024-07-24 14:43 UTC, mofojed requested changes
Include some examples that you tested with. Looking good

2024-07-24 14:43 UTC, mofojed commented on plugins/ui/src/js/src/elements/TextArea.tsx
> +  );
We should be able to extract this into a hook and share it with `TextField`. Something like `const [value, onChange] = useDebouncedValue<T = string>(propValue, defaultValue, propOnChange)`

2024-07-24 14:43 UTC, mofojed commented on plugins/ui/src/js/src/elements/TextArea.tsx
> +  const onChange = useCallback(
Side note about `onChange` - we should only have it set to a defined value if the passed in `propOnChange` is defined. In some cases, simply passing in a function will change the behaviour of the component, so we don't want to _always_ pass in a function if the `propOnChange` function was not provided.

So in this case it'd be something like:
```
const onChangeCallback = useCallback( ... );
const onChange = propOnChange ? onChangeCallback : undefined;
```

See `useFormEventCallback.ts` as another example (and it's usage in Form.tsx).

2024-07-24 14:43 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/text_area.py
> +    icon: Element | None = None,
For convenience, we can probably allow an icon string here as well, and automatically convert it to a `ui.icon` element if it's provided.

2024-07-25 03:53 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/text_area.py
> +    icon: Element | None = None,
Do we want to do this though, seems inconsistent since we don't do it `tab.py `,` text_field.py`, `list_action_group.py` with `summary_icon`?

2024-07-26 15:53 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
This hook should probably be implemented in @deephaven/react-hooks. Doesn't seem to have anything plugins specific unless I'm missing someting.

2024-07-26 15:54 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
@AkshatJawne Does this add any functionality that `useDebouncedCallback` doesn't already provide?

2024-07-26 15:58 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
nvm, I see what it is doing.

2024-07-26 16:00 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
I don't think the `defaultValue` prop makes sense inside of this hook. I would just support `value` and `onChange` inputs and coalesce the `value ?? defaultValue` in the calling component.

2024-07-26 16:00 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
I can look into implementing on the DHC side, thought it would be more appropriate here, since Bender had referenced the `useFormEventCallback.ts`, and that lives in the plugins repo.

2024-07-26 16:01 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
Where is `useFormEventCallback` referenced?

2024-07-26 16:02 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
https://github.com/deephaven/deephaven-plugins/pull/652#discussion_r1689938380

2024-07-26 16:04 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
Good shout, yeah I think this makes sense, will make change.

2024-07-26 16:04 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
I think that's just an example of a hook that properly handles the undefined callback scenario and not necessarily tying it to plugins repo.

2024-07-26 16:07 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
There is a chance you can use `useDebouncedValue` and don't need a new hook at all.

2024-07-26 16:10 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
Gonna try rn

2024-07-26 16:11 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
nvm, I don't think that allows the debouncing in the change handler passed into the component

2024-07-26 16:11 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
Although, just on first sight, I will need onChange for the textField, which the `useDebouncedValue` doesn't give access to

2024-07-26 16:13 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
Wouldn't be opposed to it, if @mofojed has no issues with it, I can do it -- just holds up the process a little more, have to create a separate web-client-ui PR, wait for that to merge, and then wait for the version bump and then this will be able to be merged, right?

2024-07-26 16:15 UTC, bmingles commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +  defaultValue: T,
Yeah, disregard this idea :)

2024-07-29 14:54 UTC, bmingles commented on plugins/ui/src/js/src/elements/TextArea.tsx
> +const EMPTY_FUNCTION = () => undefined;
You can import this from `@deephaven/utils`

2024-07-29 15:24 UTC, mofojed commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
No need to move it to `@deephaven/react-hooks` - we can keep it in mind but there's no pressing need to, we don't need to wait for a bump/publish cycle to use it here, just add it here.

2024-07-29 15:32 UTC, mofojed requested changes

2024-07-29 15:32 UTC, mofojed commented on plugins/ui/src/deephaven/ui/types/types.py
> +# TODO: Use list of available icons once created
```suggestion
# TODO #601: Use list of available icons once created
```

2024-07-29 15:32 UTC, mofojed commented on plugins/ui/src/js/src/elements/TextArea.tsx
> +  const [value, onChange] = useDebouncedOnChange<string>(
Unnecessary to specify - TS is smart enough to infer the type correctly from the value passed in.
```suggestion
  const [value, onChange] = useDebouncedOnChange(
```

2024-07-29 15:32 UTC, mofojed commented on plugins/ui/src/js/src/elements/hooks/useDebouncedOnChange.ts
> +function useDebouncedOnChange<T = string>(
Don't define the default type, it can be inferred from the value passed in.
```suggestion
function useDebouncedOnChange<T>(
```

2024-07-29 15:32 UTC, mofojed commented on plugins/ui/src/js/src/elements/TextArea.tsx
> +    );
I would prefer this on the Python side. Just change `icon=icon` on text_area.py#187 to `icon=ui.icon(icon) if type(icon) == 'str' else icon` and it should be good.
It's better practice to do it Python side when possible as we may have default props set in the Python code.

2024-07-29 16:20 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/TextArea.tsx
> +    );
Been trying to work with this, causing an error on rendering, trying to debug:

![Uploading Screenshot 2024-07-29 at 10.20.51 AM.png…]()

2024-07-30 12:07 UTC, mofojed approved these changes

2024-07-30 17:13 UTC, merged