feat: ui.image
deephaven/deephaven-plugins pull request #670
Opened 2024-07-25 21:30 UTC by ethanalvizo

Closes #597

2024-07-26 13:39 UTC, AkshatJawne requested changes
Looks good, small cleanup

2024-07-26 13:39 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/image.py
> +        slot: A slot to place the image in.
A little confused about this `slot` prop, tried taking a look on the Spectrum docs as well, but are there other possible values here? 

If so, we could extract it to a type, and if not, is it always just `slot = 'image'` (if that is the case, maybe we don't want it ex?

Also, not exactly sure by what "place the image in" means here, does it mean that the image be placed outside of `ui.image`?

2024-07-26 13:39 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/image.py
> +        f"deephaven.ui.components.Image",
Should be using `component_element()` instead of `BaseElement()` here: that is what is being used by all other components

2024-07-26 13:39 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/image.py
> +from .._internal.utils import create_props
Stale import, can remove since you aren't using `create_props`

2024-07-26 13:39 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/image.py
> +    *children,
Curious why you have `children` and `props` here? Not being used when you are creating the component with the `BaseElement` call (which should be changed to `component_element`, refer to other comment)

2024-07-29 04:43 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/image.py
> +        slot: A slot to place the image in.
Yea I couldn't find too much on this in the docs I copied what they had in their description of the prop. When I was searching up the slot attribute it seems to be used for inserting things into templates: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/slot.

I can't think of why this component wouldn't use `slot = "image"`so I will not make it explicit.

2024-07-29 13:13 UTC, AkshatJawne submitted a review, later dismissed
LGTM!

I would probably wait till @mofojed also has a peek at this before merging

2024-07-29 15:48 UTC, mofojed requested changes

2024-07-29 15:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/image.py
> +    # on_load
They shouldn't be omitted - they just won't take any parameters.

2024-08-02 18:10 UTC, mofojed approved these changes

2024-08-05 22:35 UTC, merged