fix: deephaven.ui panel state management
deephaven/deephaven-plugins pull request #673
Opened 2024-07-26 16:27 UTC by mofojed

- Moved `DeferredApiBootstrap` into the `ReactPanel` itself
  - Otherwise none of the widget gets rendered at all, so we weren't showing errors on DHE before the worker was started up
- Show a loading spinner while the widget is in a loading state
- Show an error message on all panels if there's an error loading a re-hydrated widget (e.g widget no longer exists)
  - Before we would just show on one panel
  - Still show an error panel if the widget errors first, and then re-uses that panel once the widget does render
- Wait until the next render cycle to check if all panels are closed and widget is closed
  - We were firing it right away, even though another panel could have been opened in the same cycle
- Fixes #510, DH-17411, DH-17417, DH-17422
- Tested against Web UI v0.78 (this is a hotfix for V+)

Tested with a few different scenarios:
- The steps from ticket #510 
- Created a `multi_panel_test` component that you can add/remove panels within, and throws an error if you have less than 0 or more than 3 panels created:
```python
from deephaven import ui

@ui.component
def multi_panel_test():
    count, set_count = ui.use_state(0)

    if count < 0:
        raise ValueError("Can't have negative panel count")
    if count > 3:
        raise ValueError("Can't have more than 3 panels")

    return [
        ui.panel(
            ui.button("Add Panel", on_press=lambda: set_count(count + 1)),
            ui.button("Remove Panel", on_press=lambda: set_count(count - 1))
        ),
    ] + list(map(lambda i: ui.panel(f"Panel {i}"), range(count)))

mpt = multi_panel_test()
```
- Tested with a widget that sleeps while loading
  - Ensured it shows the loading spinner, and then appears correctly
  - Ensured it didn't disappear if we refresh the page while it's still loading
  - Ensured it didn't re-appear if we closed it while it was loading
```
from deephaven import ui
import time
@ui.component
def my_comp():
    state, set_state = ui.use_state(4)
    time.sleep(3)
    return state

c = my_comp()
c2 = my_comp()
```

2024-07-26 16:46 UTC, AkshatJawne requested changes
Still testing, but looks good so far.

2024-07-26 16:46 UTC, AkshatJawne commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
>  import shortid from 'shortid';
Should not be using `shortid`, we have deprecated the package -- it is not in the latest main, so maybe you had not merged in main.

Should be using `nanoid`

I see that it is being used across multiple files, but `nanoid() `should be a direct replacement for `shortid.generate()`

2024-07-26 17:00 UTC, AkshatJawne commented on plugins/ui/src/js/src/widget/WidgetErrorUtils.ts
> +  if (isWidgetError(error)) {
Could probably combine these two conditionals? Since both are returning error.message.trim()

2024-07-26 20:34 UTC, mofojed commented on plugins/ui/src/js/src/widget/DocumentHandler.tsx
>  import shortid from 'shortid';
Yup, this is into the older release branch. When I put it up for the `main` branch (which I'll open when this is approved) I'll switch to using `nanoid`.

2024-07-29 17:20 UTC, mofojed commented
This isn't working correctly for `ui.dashboard`. Taking a look.

2024-07-29 19:18 UTC, mofojed commented
Reducing scope and opened up a PR specifically for the dashboard crash/disappearing panels issue: https://github.com/deephaven/deephaven-plugins/pull/682

2024-07-29 19:19 UTC, closed without merging