docs: Add docs for use_state hook
deephaven/deephaven-plugins pull request #675
Opened 2024-07-26 18:35 UTC by mofojed

- First hook to be documented
- Added usage, API reference, and details of the hook

2024-07-26 20:09 UTC, dsmmcken requested changes

2024-07-26 20:09 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_state.md
> +4. Try and keep state data simple. While you can store any type of object in a state variable, deephaven.ui will attempt to serialize the state data and store it with the user's data running your com
Suggest having multiple states, as is the react recommendation.

2024-07-26 20:09 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_state.md
> +`use_state` is a hook you can use to add state to your component. Add it to the top-level of your component to get the current value of the state and a setter function for updating the state. Updatin
It *must* be added to the top-level.

I would probably use the word it "returns" the current value of the state and a setter...

2024-07-26 20:09 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_state.md
> +1. Convention is to name the state and setter function `something, set_something`
use the word destructure in here too

2024-07-26 20:09 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_state.md
> +# use_state
Can you added examples of storing and updating lists and dicts?

2024-07-26 20:09 UTC, dsmmcken commented
+ @margaretkennedy for copy editing

2024-07-26 20:29 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +`use_state` is a hook you can use to add state to your component. Add it to the top-level of your component to get the current value of the state and a setter function for updating the state. Updatin
```suggestion
`use_state` is a hook that adds state to your component. Add it to the top-level of your component to get the current value of the state and a setter function for updating the state. Updating state will cause the component to re-render (running the function again).
```

2024-07-26 20:46 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +`use_state` takes a parameter that will initialize the state to an initial value:
```suggestion
`use_state` takes a parameter that intializes the state to an initial value:
```

2024-07-26 20:46 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +In the example above, `set_answer` will be initialized to the value `42`. If you pass a function into the initializer, it will be called on the first intialization. This is useful if you have an expe
```suggestion
In the example above, `set_answer` initializes to the value `42`. If you pass a function into the initializer, it will be called on the first initialization. This is useful if you have an expensive computation you want to set as your state:
```

2024-07-26 20:46 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +Note the initializer function does not take any parameters, and should be deterministic. If you wish to store a function in your state, you'll need to return that function as a result of a function:
```suggestion
Note the initializer function does not take any parameters, and should be deterministic. If you wish to store a function in your state, return that function as a result of a function:
```

2024-07-29 19:50 UTC, mofojed commented on plugins/ui/docs/hooks/use_state.md
> +1. Convention is to name the state and setter function `something, set_something`
In python it's called an unpacking assignment, not destructuring. I'll use that terminology.

2024-07-30 02:03 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_state.md
> +1. Convention is to name the state and setter function `something, set_something`
tomato tomato.

2024-08-01 15:15 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +1. Convention is to use an unpacking assignment and name the state and setter function `something, set_something`
```suggestion
1. Convention is to use an unpacking assignment and name the state and setter function `something, set_something`.
```

2024-08-01 15:15 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +4. Try and keep state data simple. While you can store any type of object in a state variable, deephaven.ui will attempt to serialize the state data and store it with the user's data running your com
```suggestion
4. Try and keep state data simple. While you can store any type of object in a state variable, deephaven.ui will attempt to serialize the state data and store it with the user's data running your component. If the data is not serializable, your state is not maintained between sessions. If possible, use a state or multiple state variables that are serializable and build up any complex objects using a `use_memo` hook.
```

2024-08-01 15:15 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +You can instead pass in an updater function, that will allow you to use the previous value:
```suggestion
You can instead pass in an updater function that will allow you to use the previous value:
```

2024-08-01 15:15 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +## Setting state based on the previous value
The second one seems to be about setting?

2024-08-01 15:15 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_state.md
> +You can set state with a dictionary. Instead of modifying the dictionary in place, create a new dictionary with the updated values. In this example, `person` contains a dictionary of name and age. Wh
```suggestion
You can set state with a dictionary. Instead of modifying the dictionary in place, create a new dictionary with the updated values. In this example, `person` contains a dictionary of name and age. When the name or age is updated, the dictionary unpacking operator creates a new dictionary with the updated values:
```
Not sure if that's correct. or "When the name or age is updated, a new dictionary is created with the updated values."

2024-08-06 15:16 UTC, margaretkennedy approved these changes

2024-08-06 15:42 UTC, dsmmcken approved these changes

2024-08-06 16:46 UTC, merged