docs: ui.text_area
deephaven/deephaven-plugins pull request #683
Opened 2024-07-30 14:17 UTC by AkshatJawne

Closes #678

Assuming the changes proposed in #652

2024-07-30 14:30 UTC, dsmmcken requested changes
https://react-spectrum.adobe.com/react-spectrum/TextArea.html#visual-options

all the examples shown in the visual option section should also be ported.

2024-07-30 14:35 UTC, dsmmcken commented on plugins/ui/docs/components/text_area.md
> +3. Placeholder text should give users a clear indication of what needs to be typed in the text area, it should not be a replacement for a label.
https://spectrum.adobe.com/page/text-area/#Usage-guidelines

Placeholders are actually against spectrum guidelines, and favour using help text. For this section, basically summarize the guidelines into short list.

2024-08-01 15:01 UTC, dsmmcken requested changes

2024-08-01 15:01 UTC, dsmmcken commented on plugins/ui/docs/components/text_area.md
> +text_area_name_example = ui.text_area(label="Comment", name="comment")
Put it in a form, as a complete example.

2024-08-01 15:01 UTC, dsmmcken commented
Adding @margaretkennedy for copy editing

2024-08-01 15:19 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +
I'm not totally following that second line - TextAreas make all customizations available to text field? What are the "various purposes"?

2024-08-01 15:31 UTC, margaretkennedy requested changes

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +1. Text area should include a label, since without a label, the text area is ambiguous and not accessible.
```suggestion
1. Text area should include a label, or else the text area is ambiguous and not accessible.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +3. Identify the minority of text area's in a form (optional or required) and either mark fields as is_required, or use the necessity_indicator to mark as optional, based on whichever occurs less.
```suggestion
3. Identify the minority of text areas in a form (optional or required) and either mark fields as `is_required` or use the `necessity_indicator` to mark them as optional, based on whichever occurs less.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +4. A text area should not be made quiet if it has a fixed height, given that the field underline may be too far from the text to be considered part of the component.
quiet?

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Consider using [`text_field`](./text_field.md) for cases wher concise, single-line input is required. In cases where the input is numeric, consider using [`number_field`](./number_field.md)
```suggestion
Consider using [`text_field`](./text_field.md) for cases where concise, single-line input is required. In cases where the input is numeric, consider using [`number_field`](./number_field.md) 
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +To provide a visual label for the text area, the `label` prop should be used. In order to indicate that the text area is mandatory, use the `is_required` prop.
```suggestion
To provide a visual label for the text area, use the `label` prop. To indicate that the text area is mandatory, use the `is_required` prop. 
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +A Text area's can have an `on_change`, which is triggered whenever the value in the text area is edited.
```suggestion
The `on_change` property is triggered whenever the value in the text area is edited.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Text area's can support a `name` prop for integration with HTML form, allowing for easy identification of a value on form submission.
```suggestion
Text areas support a `name` prop for integration with HTML forms, allowing for easy identification of a value on form submission.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Text area's can be made to be "quiet" using the `is_quiet` prop. This can be useful when the text area should be more subdued.
```suggestion
The `is_quiet` prop makes text areas "quiet". This can be useful when the text area should be more subdued.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Text area's can be made to be "quiet" using the `is_quiet` prop. This can be useful when the text area should be more subdued.
define what you mean?

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Text area's can be disabled to prevent user interaction using the `is_disabled` prop. This is useful when the text area should be visible, but not available for input.
```suggestion
The `is_disabled` prop disables text areas to prevent user interaction. This is useful when the text area should be visible but not available for input.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Text area's can be made read only to prevent user interaction using the `is_read_only` prop. This is different then setting the `is_disabled` prop, since the text area remains focusable, and the cont
```suggestion
The `is_read_only` prop makes text areas read-only to prevent user interaction. This is different than setting the `is_disabled` prop since the text area remains focusable, and the contents of the text area remain visible.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +When positioned on the side, the `label_align` can be set to "start", refering to the left most edge of the text area, or to the "end, referring to the right most edge.
```suggestion
When positioned on the side, the `label_align` property can be set to "start", referring to the leftmost edge of the text area, or to "end, referring to the rightmost edge.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +While labels can be placed either on top or on the side of the text area, top labels are the default recommendation because they work better with longer copy, localization, and responsive layouts, wh
```suggestion
While labels can be placed either on top or on the side of the text area, top labels are the default recommendation. Top labels work better with longer copy, localization, and responsive layouts. Side labels are more useful when vertical space is limited.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +A `ui.contextual_help` can be placed next to the label, using the `contextual_help` prop, in order ot provide additional info about the text area.
```suggestion
Using the 'contextual_help' prop, a' UI.contextual_help` can be placed next to the label to provide additional information about the text area.
```

2024-08-01 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +The width of a text area can be adjusted by the `width` prop, and a max width for the content can be enforced using the `max_width` prop.
```suggestion
The `width` prop adjusts the width of a text area, and the `max_width` prop enforces a maximum width. 
```

2024-08-01 16:05 UTC, AkshatJawne commented on plugins/ui/docs/components/text_area.md
> +4. A text area should not be made quiet if it has a fixed height, given that the field underline may be too far from the text to be considered part of the component.
quiet is a setting/style of Text Area, where it is more subdued. It is controlled through the `is_quiet` prop

2024-08-01 16:08 UTC, AkshatJawne commented on plugins/ui/docs/components/text_area.md
> +A `ui.contextual_help` can be placed next to the label, using the `contextual_help` prop, in order ot provide additional info about the text area.
Will implement this change, would want to keep it as ui.contextual_help in my opinion, given that across the docs, when referencing a component from deephaven ui, we use lowercase.

2024-08-01 16:16 UTC, AkshatJawne commented
Ready for re-review @margaretkennedy @dsmmcken

2024-08-01 16:24 UTC, margaretkennedy commented on plugins/ui/docs/components/text_area.md
> +Using the 'contextual_help' prop, a `ui.contextual_help` can be placed next to the label to provide additional information about the text area.
My suggestion might have snuck in single quotes for backticks here.

2024-08-01 16:34 UTC, AkshatJawne commented
Quotes should be fixed @margaretkennedy

2024-08-01 16:38 UTC, margaretkennedy approved these changes

2024-08-06 19:33 UTC, dsmmcken commented on plugins/ui/docs/components/text_area.md
> +Consider using [`text_field`](./text_field.md) for cases where concise, single-line input is required. In cases where the input is numeric, consider using [`number_field`](./number_field.md)
Not everything needs to start "clear and effective". Shortened recommendations to just the strongest ones. I like the wording you wrote for error text vs help text for this 

```suggestion
Recommendations for creating text areas:

1. Text area should include a label, or else, the text area is ambiguous and not accessible.
2. Text area labels and placeholder text should follow sentence casing. 
3. A text area should not use `is_quiet` styling if it has a fixed height, given that the field underline may be too far from the text to be considered part of the component.
4. Use help text to provide instructions on input format, content, and requirements; the help text should not restate the same information as the label, or prompt a user to interact with the text area.
5. Dynamically switch between help text and error messages based on input, ensuring both convey essential input requirements.

Consider using [`text_field`](./text_field.md) for cases where concise, single-line input is required.
```

2024-08-07 14:44 UTC, dsmmcken approved these changes

2024-08-07 14:47 UTC, merged