docs: action button
deephaven/deephaven-plugins pull request #702
Opened 2024-08-06 03:42 UTC by ethanalvizo

Closes #679

2024-08-06 09:27 UTC, margaretkennedy commented on plugins/ui/docs/components/action_button.md
> +ActionButtons allow users to perform an action. The'yre used for similar, task-based options within a workflow, and are ideal for interfaces where buttons aren't meant to draw a lot of attention
```suggestion
Action Buttons allow users to perform an action. They are used for similar, task-based options within a workflow, and are ideal for interfaces where buttons aren't meant to draw a lot of attention
```

2024-08-06 09:32 UTC, margaretkennedy commented on plugins/ui/docs/components/action_button.md
> +ActionButtons accept a value to display and can trigger actions based on events such as setting state when pressed. See the [API Reference](#api-reference) for a full list of available events.
```suggestion
`action_button` accepts a value to display and can trigger actions based on events such as setting state when pressed. See the [API Reference](#api-reference) for a full list of available events.
```

2024-08-06 09:33 UTC, margaretkennedy commented on plugins/ui/docs/components/action_button.md
> +ActionButtons have different types that change their behaviour in an HTML form: button (default), submit, reset.
```suggestion
`action_button` supports different types that change the button's behavior in an HTML form: button (default), submit, reset. 
```
Similar to the two comments above, it should be "Action Buttons" or the component name in backticks.

2024-08-06 09:35 UTC, margaretkennedy commented on plugins/ui/docs/components/action_button.md
> +ActionButtons can be disabled to prevent user interaction. This is useful when the button is not available for interaction, but should still be visible.
```suggestion
ActionButtons can be disabled to prevent user interaction. This is useful when the action is not currently available, but the button should still be visible.
```

2024-08-06 19:42 UTC, dsmmcken requested changes

2024-08-06 19:42 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Consider using [`button`](./button.md) to draw attention to important actions users need to perform or for navigating to a different page. To represent a binary choice, use a [`toggle_button`](./togg
Not all the same guidelines apply to action button. For example there is not negative styling, and icon only action buttons are perfectly acceptable.

```suggestion
## UI Recommendations

Recommendations for creating effective action buttons:


1. Button text should be clear and concise. No more than 4 words or 20 characters is recommended.
2. Use verbs for button text to indicate the action that will be taken when the button is clicked. For example, "Save", "Delete", or "Add friend", rather than "Ok" or "Cancel". Nouns or adjectives tend to be less clear.
3. Use sentence case for button text with more than one word. For example, "Add friend" instead of "Add Friend" or "ADD FRIEND".
4. No punctuation is needed at the end of the button text.
5. For icon only buttons, include a tooltip.


Consider using [`button`](./button.md) to draw attention to important actions users need to perform or for navigating to a different page. To represent a binary choice, use a [`toggle_button`](./toggle_button.md) instead. If you have a collection of related action buttons, you can group them using a [`action_group`](./action_group.md).
```

2024-08-06 19:42 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Action Buttons allow users to perform an action. They are used for similar, task-based options within a workflow, and are ideal for interfaces where buttons aren't meant to draw a lot of attention
```suggestion
Action Buttons allow users to perform an action. They are used for similar, task-based options within a workflow, and are ideal for interfaces where buttons aren't meant to draw a lot of attention. Action buttons are the preferred button for taking actions on tables and plots that in some way alter tables, such as applying a filter.
```

2024-08-06 19:46 UTC, dsmmcken requested changes

2024-08-06 19:46 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +```
Remove this section, these aren't variants in that sense and this isn't a prop that needs an example at all.

2024-08-06 19:46 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +ActionButtons can have no visible background until they're interacted with. This style works best when a clear layout (vertical stack, table, grid) makes it easy to parse the buttons. Too many quiet
casing of action button.

2024-08-06 19:46 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Static-color buttons are available in white and black. They don't dynamically change in response to the user's theme. They should only be used over fixed-color backgrounds, not over theme colors that
Give this a title and place it last.

2024-08-06 19:46 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +
Please show examples of icon only buttons, and icon + buttons

2024-08-09 18:34 UTC, jnumainville commented on plugins/ui/docs/components/action_button.md
> +.. dhautofunction:: deephaven.ui.action_button
Since I see you have a new `dhautofunction` here (and in #703), please either
1. Create the docs locally and verify they are created correctly (the easiest way to do this is via `tools/plugin_builder.py`, check out the readme and let me know if you have problems).
2. Wait until #719 is merged then merge main in to this branch so the docs will be checked automatically
Thanks

2024-08-15 14:59 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +    iconAndLabel = ui.button_group(
should be action_group not button_group

2024-08-15 15:00 UTC, dsmmcken requested changes

2024-08-15 15:00 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Consider using [`button`](./button.md) to draw attention to important actions users need to perform or for navigating to a different page. To represent a binary choice, use a [`toggle_button`](./togg
sshould link to action_group not button_group

2024-08-16 17:06 UTC, ethanalvizo commented on plugins/ui/docs/components/action_button.md
> +    iconAndLabel = ui.button_group(
Sorry I should've made note of it before but I don't think ActionButtons go into ActionGroup. From the [spectrum docs](https://react-spectrum.adobe.com/react-spectrum/ActionGroup.html#actiongroup) the children they put into ActionGroup are items rather than buttons. It seems to behave more like a selector?

In the initial draft of the docs I did put ActionButtons in an ActionGroup but they don't render as expected. The code sample below shows the difference between using ActionButtons (first row) vs Items (second row) in ActionGroup. 

It is very confusing though, I would think that ActionButton belongs in ActionGroup rather than ButtonGroup. Is this a bug on our implementation of ActionGroup or just funny wording on the Adobe components?

```
from deephaven import ui

@ui.component
def ui_button_group():
    actionGroupWithButtons = ui.action_group(
        ui.action_button(ui.icon("vsDebugRestart"), aria_label="Restart"),
        ui.action_button(ui.icon("vsRecord"), aria_label="Record"),
        ui.action_button(ui.icon("vsDebugPause"), aria_label="Play"),
        ui.action_button(ui.icon("vsDebugStart"), aria_label="Pause"),
        ui.action_button(ui.icon("vsEdit"), aria_label="Edit"),
        ui.action_button(ui.icon("vsGear"), aria_label="Configure"),
    )
    actionGroupWithItems = ui.action_group(
        ui.item(ui.icon("vsDebugRestart"), aria_label="Restart"),
        ui.item(ui.icon("vsRecord"), aria_label="Record"),
        ui.item(ui.icon("vsDebugPause"), aria_label="Play"),
        ui.item(ui.icon("vsDebugStart"), aria_label="Pause"),
        ui.item(ui.icon("vsEdit"), aria_label="Edit"),
        ui.item(ui.icon("vsGear"), aria_label="Configure"),
    )
    return [actionGroupWithButtons, actionGroupWithItems]


my_action_buttons = ui_button_group()
```

![image](https://github.com/user-attachments/assets/8551c728-309f-4acf-936c-7d3a78d367c5)

2024-08-16 19:31 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/action_button.py
>      """
Might me worth a try, when I was trying to resolve the error with the other docs, one of the things that solved some of my errors, was adding a blank line after my doc string ended.

That might fix what you're seeing...?

2024-08-16 19:33 UTC, AkshatJawne commented on plugins/ui/src/deephaven/ui/components/action_button.py
>      """
Also, in my changes I added a return comment for the view component, that fixed one of my errors. I see that your code is stopping there, maybe try adding the same Returns comment I added in my PR for view, and that might fix it.

2024-08-16 19:48 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +    iconAndLabel = ui.button_group(
My bad, you are right. Though that is a little weird, I wonder if we should change that behaviour.

2024-08-16 19:48 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Consider using [`button`](./button.md) to draw attention to important actions users need to perform or for navigating to a different page. To represent a binary choice, use a [`toggle_button`](./togg
I would still link to action_group here though

2024-08-19 15:08 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Consider using [`button`](./button.md) to draw attention to important actions users need to perform or for navigating to a different page. To represent a binary choice, use a [`toggle_button`](./togg
```suggestion
Consider using [`button`](./button.md) to draw attention to important actions users need to perform or for navigating to a different page. To represent a binary choice, use a [`toggle_button`](./toggle_button.md) instead. If you have a collection of related buttons, you can group them using an [`action_group`](./action_group.md).
```

2024-08-22 02:27 UTC, dsmmcken requested changes

2024-08-22 02:27 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Action Buttons allow users to perform an action. They are used for similar, task-based options within a workflow, and are ideal for interfaces where buttons aren't meant to draw a lot of attention. A
```suggestion
Action buttons allow users to perform an action. They are used for similar, task-based options within a workflow, and are ideal for interfaces where buttons aren't meant to draw a lot of attention. Action buttons are the preferred button for taking actions on tables and plots that in some way alter tables, such as applying a filter.
```

2024-08-22 02:27 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Action Buttons can have icons when necessary to provide additional context. If no visible label is provided (e.g., an icon-only button), an alternative text label must be provided to identify the con
```suggestion
Action buttons can have icons when necessary to provide additional context. If no visible label is provided (e.g., an icon-only button), an alternative text label must be provided to identify the control for accessibility using the `aria-label` prop. See [icon](./icon.md) for a list of available icons.
```

2024-08-22 02:27 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Action Buttons can have no visible background until they're interacted with. This style works best when a clear layout (vertical stack, table, grid) makes it easy to parse the buttons. Too many quiet
```suggestion
Action buttons can have no visible background until they're interacted with. This style works best when a clear layout (vertical stack, table, grid) makes it easy to parse the buttons. Too many quiet components in a small space can be hard to read.
```

2024-08-22 02:27 UTC, dsmmcken commented on plugins/ui/docs/components/action_button.md
> +Action Buttons can be disabled to prevent user interaction. This is useful when the button is not currently available, but the button should still be visible.
```suggestion
Action buttons can be disabled to prevent user interaction. This is useful when the button is not currently available, but the button should still be visible.
```

2024-08-22 02:28 UTC, dsmmcken approved these changes

2024-08-22 10:22 UTC, margaretkennedy approved these changes

2024-08-26 13:58 UTC, merged