docs: ui.picker
deephaven/deephaven-plugins pull request #705
Opened 2024-08-06 13:23 UTC by AkshatJawne

Closes #685 

**Additional Info:**
- Did not include any of the sections containing dynamic items, since our picker does not support the `items` prop
- Did not include section with links, since we do not have a `ui.link`
- Did not include section with avatar, since we do not currently have a `ui.avatar`
- Changed "Asynchronous Loading Section" to "Loading", since we do not have a `on_load_more` prop exposed

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +Picker enables user to pick an option from a collapsible list of options, often used when the space is limited.
```suggestion
`picker` enables users to pick an option from a collapsible list of options, often used when the space is limited.
```
or The `picker` component enables...

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +1. Every picker should have a label specified, without one, the picker is both ambiguous and not accessible.
```suggestion
1. Every picker should have a [label](#labeling) specified. Without one, the picker is ambiguous and not accessible.
```

I might stop at "the picker is ambiguous" since accessible has two meanings.

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +2. In the rare case that context is sufficient, and thus, the label is not neccessary, make sure to still include an aria-label via the `aria_label` prop.
```suggestion
2. In the rare case that context is sufficient the label is unnecesary, you must still include an aria-label via the `aria_label` prop.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +3. Options in the picker should be kept short and concise, multiple lines is strongly discouraged.
```suggestion
3. Options in the picker should be kept short and concise; multiple lines are strongly discouraged.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +4. The width of the picker should be set such that the field button should not intefere with the options being displayed in full.
```suggestion
4. The picker's width should be set so that the field button does not prevent options being displayed in full.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +6. Identify the minority of picker's in a form (optional or required) and either mark fields as `is_required`, or use the `necessity_indicator` to mark as optional, based on whichever occurs less.
```suggestion
6. Identify which pickers are required or optional, and use the `is_required` field or the `necessity_indicator` to mark them accordingly.  
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +7. A picker's help text should provide actionable guidance on what to select and how to select it, offering additional context without repeating the label, and should only be included if relevant to
```suggestion
7. A picker's help text should provide actionable guidance on what to select and how to select it, offering additional context without repeating the label. 
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +7. A picker's help text should provide actionable guidance on what to select and how to select it, offering additional context without repeating the label, and should only be included if relevant to
Doesn't seem necessary. Or:

"If relevant to the user, a picker's help text should provide...."

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +The picker can be labeled using the `label` prop, and if no label is provided, an `aria_label` msut be provided to identify the control for accessibility purposes.
```suggestion
The picker can be labeled using the `label` prop. If no label is provided, an `aria_label` must be provided to identify the control for accessibility purposes.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +The `is_required` prop and the `necessary_indicator` props can be used to show whether selecting an option in the picker is required or option.
```suggestion
The `is_required` prop and the `necessary_indicator` props can be used to show whether selecting an option in the picker is required or optional.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +In a picker, a selected option can be set using the `default_selected_key` or `selected_key` prop.
```suggestion
In a picker, the `default_selected_key` or `selected_key` props set a selected option.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +Picker's can support a `name` prop for integration with HTML form, allowing for easy identification of a value on form submission.
```suggestion
Pickers can support a `name` prop for integration with an HTML form, allowing for easy identification of a value on form submission.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +Picker supports sections in order to group options. Sections can be used by wrapping groups of items in a Section element. Each Section takes a title and key prop.
```suggestion
Picker supports sections to group options. Sections can be used by wrapping groups of items in a `section` element. Each section takes a title and key prop.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +## Complex Items
```suggestion
## Complex items
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +Items within a Picker can include additional content to better convey options. You can add icons, avatars, and descriptions to the children of an `ui.item`. When adding a description, set the `slot`
```suggestion
Items within a picker can include additional content to better convey options. You can add icons, avatars, and descriptions to the children of an `ui.item`. When adding a description, set the `slot` prop to "description" to differentiate between the text elements.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +The picker has the `is_loading` prop that will display a progress a circle when in use, which could be used to give immediate visual feedback to users, indicating that the picker is loading or proces
```suggestion
The `is_loading` prop displays a progress circle indicating that the picker is loading or processing data, which can be used to give immediate visual feedback to users. It also prevents users from interacting with the picker while data is loading, avoiding potential bad states.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +The picker has the `is_required` prop in order to ensure that the user selects an option, and also has the `validation_behaviour` prop, that allows the user to specify aria or native verification.
```suggestion
The `is_required` prop ensures that the user selects an option. The related `validation_behaviour` prop allows the user to specify aria or native verification.
```

2024-08-06 15:36 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +By default, the position of a picker's label is above the picker, but it can be changed to the side using the `label_position` prop.
```suggestion
By default, the position of a picker's label is above the picker, but it can be moved to the side using the `label_position` prop. 
```

2024-08-06 15:55 UTC, AkshatJawne commented on plugins/ui/docs/components/picker.md
> +Picker enables user to pick an option from a collapsible list of options, often used when the space is limited.
I am not sure if we would want to do `picker` here, since that would be inconsistent with what @dsmmcken did with the Button docs, I think changing it to "Pickers" is more appropriate?

2024-08-06 15:56 UTC, AkshatJawne commented on plugins/ui/docs/components/picker.md
> +1. Every picker should have a label specified, without one, the picker is both ambiguous and not accessible.
I guess it would definitely not be accessible in terms of a user's ability to access the picker, but in terms of aria accessibility, may not actually impact. I agree, will stop at "the picker is ambiguous"

2024-08-06 16:01 UTC, AkshatJawne reviewed
Ready for re-review @margaretkennedy

2024-08-06 16:08 UTC, margaretkennedy submitted a review, later dismissed

2024-08-06 16:22 UTC, dsmmcken requested changes
This doesn't show any examples of using tables as the source of the list, which I expect is going to be one of the most common uses with deephaven.

Using tables have several column related options as well. It should be the first section after UI recommendations.

2024-08-06 16:23 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +## UI Recommendations
Titles should all be be sentence case.

2024-08-06 19:28 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +9. Write error messages in a clear, concise, and helpful manner, guiding users to resolve the issue without ambiguity; ideally, they should be 1-2 short, complete sentences.
```suggestion
Recommendations for creating pickers:

1. Every picker should have a [label](#labeling) specified. Without one, the picker is ambiguous. In the rare case that context is sufficient the label is unnecessary, you should still include an aria-label via the `aria_label` prop.
2. Options in the picker should be kept short and concise; multiple lines are strongly discouraged.
3. The picker's width should be set so that the field button does not prevent options being displayed in full.
4. The label, menu items, and placeholder text should all be in sentence case.
5. A picker's help text should provide actionable guidance on what to select and how to select it, offering additional context without repeating the label.
6. When an error occurs, the help text specified in a picker should be replaced by error text.
7. Write error messages in concise and helpful manner, guiding users to resolve the issue. Error text should be 1-2 short, complete sentences ending with a period.
```

2024-08-06 19:28 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +9. Write error messages in a clear, concise, and helpful manner, guiding users to resolve the issue without ambiguity; ideally, they should be 1-2 short, complete sentences.
Shortened it up a bit.

2024-08-06 19:51 UTC, AkshatJawne reviewed
@dsmmcken I added an example with the item table source, similar to one that is found in our `ui_render_all.py` file, were there any specific examples that you were thinking other than this for data sources?

2024-08-07 14:51 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +1. Every picker should have a [label](#labeling) specified. Without one, the picker is ambiguous. In the rare case that context is sufficient the label is unnecessary, you should still include an ari
```suggestion
1. Every picker should have a [label](#labeling) specified. Without one, the picker is ambiguous. In the rare case that context is sufficient, the label is unnecessary; you must still include an aria-label via the `aria_label` prop.
```

2024-08-07 14:52 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +7. Write error messages in concise and helpful manner, guiding users to resolve the issue. Error text should be 1-2 short, complete sentences ending with a period.
```suggestion
7. Write error messages in a concise and helpful manner, guiding users to resolve the issue. Error text should be 1-2 short, complete sentences ending with a period.
```

2024-08-07 14:52 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +Pickers can support a `name` prop for integration with HTML form, allowing for easy identification of a value on form submission.
```suggestion
Pickers can support a `name` prop for integration with HTML forms, allowing for easy identification of a value on form submission.
```

2024-08-07 14:53 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +Picker supports sections to group options. Sections can be used by wrapping groups of items in a `section` element. Each section takes a `title` and `key` prop.
```suggestion
Picker supports sections that group options. Sections can be used by wrapping groups of items in a `section` element. Each section takes a `title` and `key` prop.
```

2024-08-07 14:55 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +When positioned on the side, the `label_align` property can be set to "start", referring to the leftmost edge of the picker, or to "end, referring to the rightmost edge.
```suggestion
When positioned on the side, the `label_align` property can be set to "start", referring to the leftmost edge of the picker, or to "end", referring to the rightmost edge.
```

2024-08-07 14:57 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +
I would split these examples into two separate sub examples:

1. Using a straight table (no item_table_source). It's important to show that. See: https://github.com/deephaven/deephaven-plugins/blob/main/plugins/ui/docs/README.md#picker-table

I would use dx.data.stocks as the data source. It's important to mention that under this scenario it uses the first column as the key and the label and that any duplicate keys will cause the component to throw. If you are using values that maybe duplicative, then you can select_distinct first.

```
_stock_syms = dx.data.stocks().select_distinct("Sym")

ui.picker(_stock_syms, ...)
```

2. Explain for your example here that if you wish to manually specify keys and labels, you can use item_table_source which also allows per row icons.

I would use the column names Key, Label and Icon for the table being created.

@bmingles anything else critical to mention?

2024-08-07 14:58 UTC, dsmmcken commented
Added @bmingles, as this was his feature and I want make sure there's no important additional table related info to mention or document.

2024-08-07 15:17 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +    item_table_source, aria_label="Picker", default_selected_key=15
You should use the `label` prop instead of `aria_label` here. It's more user friendly, and `aria_label` is only required if you don't provide the label.

2024-08-07 15:26 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +
I agree with @dsmmcken here. I'm sure the column names were copied from one of my earlier examples, but they would be less confusing to be named for the props they are intended to source. I would also suggest the `ui_` and `my_` prefix convention of:

```python
def ui_picker_some_label():
  return ui.picker(...)

my_picker_some_label = ui_picker_some_label()
```

with optional `_some_label` suffix to differentiate examples.

2024-08-07 15:33 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +option, set_option = ui.use_state("Option 2")
This doesn't seem to be used by the component

2024-08-07 15:38 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +When the `necessity_indicator` prop is set to "label", a localized string will be generated for "(required)" or "(optional)" automatically.
Do we actually support this? I get an error when using it:

<img width="573" alt="image" src="https://github.com/user-attachments/assets/52947ab7-fbd1-43aa-b646-80f80736ef22">

2024-08-07 15:39 UTC, AkshatJawne commented on plugins/ui/docs/components/picker.md
> +When the `necessity_indicator` prop is set to "label", a localized string will be generated for "(required)" or "(optional)" automatically.
That's a typo, should be necessity_indicator **

2024-08-07 15:40 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +When the `necessity_indicator` prop is set to "label", a localized string will be generated for "(required)" or "(optional)" automatically.
Looks like this should be `necessity_indicator`

2024-08-07 15:41 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +            necessary_indicator="label",
`necessity_indicator`

2024-08-07 15:42 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +            necessary_indicator="label",
`necessity_indicator`

2024-08-07 15:44 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +loading, set_loading = ui.use_state("loading")
This example throws an error. I don't think you use `use_state`  outside of a component.

2024-08-07 15:45 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +picker_validation_example = ui.form(
This example throws an error

2024-08-07 15:46 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +@ui.component
This example throws an error

2024-08-07 15:52 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +            default_value="Awesome!",
`default_value` and `validation_state` throws errors

2024-08-07 15:54 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +open, set_open = ui.use_state(False)
Invalid outside of component. This throws an error.

2024-08-07 15:55 UTC, bmingles requested changes
Left comments on a few things. Biggest issue is that multiple examples throw errors. Would be good to make sure all examples run without errors. Possible some of them are due to things we missed in implementation, and appropriate tickets could be created to address, but most of them seem to be bugs in the examples.

2024-08-07 16:04 UTC, AkshatJawne commented
@bmingles Might have to create a ticket here, it appears that the label_alignment ="end" is not working as intended? Not sure if you are seeing the same thing, but if you run the following snippet, the label should be after the picker for the second picker:

```
from deephaven import ui


@ui.component
def picker_label_position_alignment_props():
    return [
        ui.picker(
            ui.section(ui.item("Option 1"), ui.item("Option 2"), title="Section 1"),
            label="Test Label",
            label_position="side",
            label_alignment="start",
        ),
        ui.picker(
            ui.section(ui.item("Option 1"), ui.item("Option 2"), title="Section 1"),
            label="Test Label",
            label_position="side",
            label_alignment="end",
        ),
    ]


picker_label_position_alignment_example = picker_label_position_alignment_props()
```

2024-08-07 16:11 UTC, bmingles commented
> @bmingles Might have to create a ticket here, it appears that the label_alignment ="end" is not working as intended? Not sure if you are seeing the same thing, but if you run the following snippet, the label should be after the picker for the second picker:
> 
> ```
> from deephaven import ui
> 
> 
> @ui.component
> def picker_label_position_alignment_props():
>     return [
>         ui.picker(
>             ui.section(ui.item("Option 1"), ui.item("Option 2"), title="Section 1"),
>             label="Test Label",
>             label_position="side",
>             label_alignment="start",
>         ),
>         ui.picker(
>             ui.section(ui.item("Option 1"), ui.item("Option 2"), title="Section 1"),
>             label="Test Label",
>             label_position="side",
>             label_alignment="end",
>         ),
>     ]
> 
> 
> picker_label_position_alignment_example = picker_label_position_alignment_props()
> ```

Seems to possibly be a Spectrum bug? See this example:
https://react-spectrum.adobe.com/react-spectrum/Picker.html#label-alignment-and-position

2024-08-07 16:13 UTC, AkshatJawne commented
@bmingles Yeah that is odd, not sure why they would have that on their official docs ... maybe I shouldn't add an example highlighting setting the label_alignment to end then

2024-08-07 16:16 UTC, bmingles commented
> label_alignment

Spectrum `Picker` docs show this as `label_align`. We may have a typo here.

2024-08-07 16:17 UTC, AkshatJawne commented
Ok that would make sense, because before this I did text area, and in that component, we use label_align.

2024-08-07 16:25 UTC, AkshatJawne commented
Created Ticket: https://github.com/deephaven/deephaven-plugins/issues/717

2024-08-07 18:28 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +A picker can have both a `description` and an `error_message`. The description remains visible at all times, use the error message to offer specific guidance on how to correct the input.
```suggestion
A picker can have both a `description` and an `error_message`. The description remains visible at all times. Use the error message to offer specific guidance on how to correct the input.
```

2024-08-07 18:29 UTC, margaretkennedy reviewed
One punctuation change, then LGTM.

2024-08-07 18:45 UTC, margaretkennedy submitted a review, later dismissed

2024-08-08 14:28 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +    option, set_option = use_state("")
Needs `ui.` prefix

2024-08-08 14:34 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +    option, set_option = use_state("")
also, `option` isn't actually used

2024-08-09 14:18 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +A picker can have both a `description` and an `error_message`. The description remains visible at all times. Use the error message to offer specific guidance on how to correct the input.
The picker can have both props set, but only one will ever be visible, so the description is not actually visible at all times. I would change this to clarify how the `is_invalid` value affects the output. It might also be good to show both props being set with `is_invalid=False` to show the description when no error is present.

2024-08-09 14:20 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +            validation_behavior="aria",
It's not clear to me what this actually does. There should be some description of the expected behavior, or if possible, the example should show it when you run it.

2024-08-09 14:26 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +my_picker_alignment_direction_examples = ui_picker_alignment_direction_examples()
I don't see any difference in how the `direction="top"` is different than the default. Might want to set it to a different value.

2024-08-09 14:28 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +.. dhautofunction:: deephaven.ui.picker
I've not seen this yet. What does it do?

2024-08-09 14:29 UTC, bmingles requested changes
Left a few comments

2024-08-09 14:31 UTC, AkshatJawne commented on plugins/ui/docs/components/picker.md
> +.. dhautofunction:: deephaven.ui.picker
I will defer to @dsmmcken , I had included this as a way to follow the format from his original Button Docs he put up. I would assume there is something to do with showing all of the props?

2024-08-09 14:34 UTC, bmingles commented on plugins/ui/docs/components/text_area.md
> +    value, set_value = ui.use_state("")
value seems to be unused

2024-08-09 14:39 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +.. dhautofunction:: deephaven.ui.picker
when compiled, it inserts the generated autodoc table

![image](https://github.com/user-attachments/assets/4c7659f5-ee52-4762-9e09-0b63c6d8788d)

2024-08-09 18:37 UTC, jnumainville commented on plugins/ui/docs/components/picker.md
> +.. dhautofunction:: deephaven.ui.picker
Since I see you have a new `dhautofunction` here, please either

1. Create the docs locally and verify they are created correctly (the easiest way to do this is via `tools/plugin_builder.py`, check out the readme and let me know if you have problems).
2. Wait until https://github.com/deephaven/deephaven-plugins/pull/719 is merged then merge main in to this branch so the docs will be checked automatically
Thanks

2024-08-12 19:50 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +                direction="bottom",
This still doesn't seem to produce a different result (presumably due to there not being enough top space to go up). Maybe `direction="end"`?

2024-08-13 14:56 UTC, bmingles approved these changes
LGTM

2024-08-13 15:58 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +For pickers, we can use a Deephaven table as a data source to populate the options. When using a table, it automatically uses the first column as both the key and label. If there are any duplicate ke
```suggestion
We can use a Deephaven table as a data source to populate the options for pickers. A table automatically uses the first column as both the key and label. If there are duplicate keys, an error will be thrown; to avoid this, a `select_distinct` can be used on the table before using it as a picker data source.
```

2024-08-13 15:58 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +If you wish to manually specify the keys and labels, you can use a  `ui.item_table_source` to dynamically derive the options from a table.
```suggestion
If you wish to specify the keys and labels manually, you can use a  `ui.item_table_source` to dynamically derive the options from a table. 
```

2024-08-13 15:58 UTC, margaretkennedy commented on plugins/ui/docs/components/picker.md
> +The picker can be labeled using the `label` prop, and if no label is provided, an `aria_label` must be provided to identify the control for accessibility purposes.
```suggestion
The picker can be labeled using the `label` prop. If no label is provided, an `aria_label` must be provided to identify the control for accessibility purposes.

```

2024-08-13 15:59 UTC, margaretkennedy reviewed
Approve my end, after the two small changes.

2024-08-13 16:53 UTC, margaretkennedy approved these changes

2024-08-14 16:13 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +    contextual_help=ui.contextual_help(ui.heading("Content tips")),
This might be a more API related question. Why does contextual_help here accept ui.contextual_help and not just a string or element?

Like couldn't I do:

```
ui.picker(
  ...
  contextual_help="my contextual help content"
  )
  
  @bmingles @mofojed

2024-08-14 16:21 UTC, AkshatJawne commented on plugins/ui/docs/components/picker.md
> +    contextual_help=ui.contextual_help(ui.heading("Content tips")),
I think your @ 's got included in the code snippet, so: @mofojed @bmingles 

I think we expect a Contextual Help there, to follow how Spectrum has it configured, they also have it so that you have to pass in a `<ContextualHelp>` into the `contextualHelp` prop, but maybe Brian or Bender can give some more context. 

https://react-spectrum.adobe.com/react-spectrum/Picker.html#contextual-help

2024-08-14 16:32 UTC, bmingles commented on plugins/ui/docs/components/picker.md
> +    contextual_help=ui.contextual_help(ui.heading("Content tips")),
I didn't implement anything special here, so whatever Spectrum supports should be what we support.

2024-08-14 16:35 UTC, dsmmcken commented on plugins/ui/docs/components/picker.md
> +    contextual_help=ui.contextual_help(ui.heading("Content tips")),
Ok. That would be outside this PR but I think we should support string | contextual_help and auto-wrap if it's a string like we do in other places like with ui.text.

2024-08-14 16:35 UTC, dsmmcken approved these changes

2024-08-14 16:37 UTC, AkshatJawne commented
Good to merge, but will wait until @jnumainville 's Broken Docs PR merges: #719

2024-08-15 17:55 UTC, merged