docs: ui.combo_box
deephaven/deephaven-plugins pull request #718
Opened 2024-08-07 21:13 UTC by AkshatJawne

Closes #687

2024-08-08 23:21 UTC, AkshatJawne reviewed
Ready for re-review @margaretkennedy

2024-08-09 12:30 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +By default, the combo boxs menu opens when the user types into the input field ("input"). This behavior can be changed to open on focus ("focus") or only when the field button is clicked ("manual") u
```suggestion
By default, the combo box's menu opens when the user types into the input field ("input"). This behavior can be changed to open on focus ("focus") or only when the field button is clicked ("manual") using the `menu_trigger` prop.
```

2024-08-09 12:30 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +By default, the position of a combo boxs label is above the combo box, but it can be moved to the side using the `label_position` prop.
```suggestion
By default, the position of a combo box's label is above the combo box, but it can be moved to the side using the `label_position` prop.
```

2024-08-09 12:30 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +The `is_disabled` prop disables a combo_box to prevent user interaction. This is useful when the combo_box should be visible but not available for selection.
```suggestion
The `is_disabled` prop disables a combo box to prevent user interaction. This is useful when the combo box should be visible but unavailable for selection.
```

or `combo_box` but I prefer combo box here.

2024-08-09 14:55 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +2. It's acceptable to suppress the popover when the combo box contains familiar entries. The popover can still be opened by clicking the field button with the chevron.
What does "suppress the popover" mean here? Does this mean don't automatically open as user types or something else?

2024-08-09 14:56 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +3. Immediately launch the popover if users are unfamiliar with the combo box content or if the data is particularly complex.
Same here, is this when the component is first shown, as the user types, ?

2024-08-09 15:02 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +5. Options in the combo box should be kept short and concise; multiple lines are strongly discouraged.
You may want to mention something about description elements here since they are one of the remedies for scenarios that may require multi-lines.

2024-08-09 15:06 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +6. Choose a `width` for your combo boxes that can accommodate most of the available options. When the combo box is focused and the typed input exceeds the field's width, allow the leftmost text to sc
Some of this line seems to be directed at combobox implementers vs users of what is already implemented. e.g. the scrolling behavior while typing and truncation behavior is not something a user will have control over.

2024-08-09 15:31 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +    return [
It could be helpful to display the selected value in a ui.text_field to show what happens with custom values.

2024-08-09 15:38 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +def ui_combo_box_form_examples():
I know this is based on the Spectrum example, but it's slightly confusing that there isn't actually a form involved in the example.

2024-08-09 15:43 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +def ui_combo_box_form_examples():
Maybe something like:

```python
def ui_combo_box_form_examples():
    return [
        ui.form(
            ui.combo_box(
                ui.item("Chocolate"),
                ui.item("Mint"),
                ui.item("Vanilla"),
                ui.item("Strawberry"),
                label="Ice cream flavor",
                allows_custom_value=True,
            ),
            ui.combo_box(
                ui.item("Panda"),
                ui.item("Cat"),
                ui.item("Dog"),
                label="Favourite Animal",
                name="favouriteAnimalId",
            ),
            ui.button("Submit", type="submit"),
            on_submit=lambda event: print(event),
        )
    ]
```

2024-08-09 17:27 UTC, AkshatJawne commented on plugins/ui/docs/components/combo_box.md
> +3. Immediately launch the popover if users are unfamiliar with the combo box content or if the data is particularly complex.
As the component is first shown.

2024-08-09 17:41 UTC, AkshatJawne commented on plugins/ui/docs/components/combo_box.md
> +2. It's acceptable to suppress the popover when the combo box contains familiar entries. The popover can still be opened by clicking the field button with the chevron.
Not automatically opening as the user types.

2024-08-09 17:42 UTC, AkshatJawne reviewed
Ready for re-review @bmingles  @margaretkennedy

2024-08-09 18:36 UTC, jnumainville commented on plugins/ui/docs/components/combo_box.md
> +.. dhautofunction:: deephaven.ui.combo_box
Since I see you have a new dhautofunction here, please either

Create the docs locally and verify they are created correctly (the easiest way to do this is via tools/plugin_builder.py, check out the readme and let me know if you have problems).
Wait until https://github.com/deephaven/deephaven-plugins/pull/719 is merged then merge main in to this branch so the docs will be checked automatically
Thanks

2024-08-13 15:20 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +icon_names = ["vsAccount"]
This was probably copied from one of my examples, but we don't really need an array here if there is only 1 icon.

2024-08-13 15:24 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +    return [
Oops, I mistakenly suggested `ui.text_field`. I meant to say `ui.text`. I think a readonly value would be preferred

2024-08-13 15:33 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +In a combo box, the `default_selected_key` or `selected_key` props set a selected option.
This should have some more details of when you would choose one over the other.

2024-08-13 15:39 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +    value, set_value = ui.use_state("")
`value` doesn't seem to be used here.

2024-08-13 15:40 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +The Combo Box component supports selection through mouse, keyboard, and touch inputs via the `on_selection_change` prop, which receives the selected key as an argument.
Any reason not to stick closer to Spectrum docs here?

```suggestion
ComboBox supports selection via mouse, keyboard, and touch. You can handle all of these via the onSelectionChange prop. ComboBox will pass the selected key to the onSelectionChange handler. Additionally, ComboBox accepts an onInputChange prop which is triggered whenever the value is edited by the user, whether through typing or option selection.
```

2024-08-13 15:52 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +The Combo Box component supports selection through mouse, keyboard, and touch inputs via the `on_selection_change` prop, which receives the selected key as an argument.
Note that we should prefer `on_change` over `on_selection_change` throughout.

2024-08-13 16:04 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +When a combo box has multiple controlled properties (e.g., `input_value`, `selected_key`), updates to one property do not automatically update the others. Each interaction triggers only its specific
A couple of things that seem off on this example:
`input_value`, and `selected_key` are mentioned in this paragraph but not actually used in the code below. As-is the example isn't actually controlled for either state.

I don't think controlled vs uncontrolled actually impacts the relationship of input / selection values. I believe they are both independent regardless. The nuance here is that if you explicitly provide a state value to a component, it now takes "control" of the particular state it represents and has to be explicitly updated. Setting `on_xxx` handlers has no bearing on controlled vs uncontrolled since you may want to listen for events and let the component maintain control of its state internally.

Anyway, I wouldn't try to document all of these details, just trying to provide context as to why this doesn't quite reflect how things work. Also, I could be wrong, but I don't see any relationship of how input vs selection values impact each other. I think whether they are controlled or not is isolated to themselves. If you find an example otherwise, let me know.

2024-08-13 16:29 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +Items within a combo box can include additional content to better convey options. You can add icons, avatars, and descriptions to the children of an `ui.item`. When adding a description, set the `slo
Can we add an avatar example?

2024-08-13 16:31 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +The `is_required` prop ensures that the user selects an option. The related `validation_behaviour` prop allows the user to specify aria or native verification.
The example doesn't really clarify what this actually does. Ideally the example should show it. If not, the description should describe it.

2024-08-13 16:33 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +2. It's acceptable to suppress the popover when the combo box contains familiar entries. The popover can still be opened by clicking the field button with the chevron.
It might be good to link to the `Trigger Options` section here

2024-08-13 16:36 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +            ui.section(ui.item("Option 1"), ui.item("Option 2"), title="Section 1"),
Unless there's a specific reason to have a ui.section in this example, I'd probably simplify to just using ui.item

2024-08-13 16:36 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +    ui.section(ui.item("Option 1"), ui.item("Option 2"), title="Section 1"),
Unless there's a specific reason to have a ui.section in this example, I'd probably simplify to just using ui.item

2024-08-13 16:39 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +The `is_read_only` prop prevents user input in a combo box, but the selected option should be visible.
Since this mentions selected option being visible, I would set the `default_selected_key`

2024-08-13 16:43 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +            is_open=open,
This seems to throw an error.

2024-08-13 16:44 UTC, bmingles requested changes
I tested all of the examples. Last one throws an error, but everything else works. Left some change suggestions for clarification purposes.

2024-08-13 17:21 UTC, AkshatJawne commented on plugins/ui/docs/components/combo_box.md
> +2. It's acceptable to suppress the popover when the combo box contains familiar entries. The popover can still be opened by clicking the field button with the chevron.
Not sure if we are linking to any spectrum docs, wasn't sure if @dsmmcken has any thoughts on it?

2024-08-13 17:22 UTC, AkshatJawne commented on plugins/ui/docs/components/combo_box.md
> +            is_open=open,
This example throws an error because the `is_open` and `default_open` props are not exposed for the combo box, created corresponding fix ticket: https://github.com/deephaven/deephaven-plugins/issues/730

2024-08-13 17:37 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +2. It's acceptable to suppress the popover when the combo box contains familiar entries. The popover can still be opened by clicking the field button with the chevron.
to clarify, I was meaning link to the "Trigger Options" section in your doc

2024-08-13 18:29 UTC, AkshatJawne commented on plugins/ui/docs/components/combo_box.md
> +Items within a combo box can include additional content to better convey options. You can add icons, avatars, and descriptions to the children of an `ui.item`. When adding a description, set the `slo
We do not have ui.avatar implemented yet, I had asked about it on the team channel a little while back.

2024-08-14 19:46 UTC, bmingles commented on docker/data/storage/notebooks/Untitled-0.md
Was this file committed on purpose?

2024-08-14 19:52 UTC, bmingles commented on plugins/ui/docs/components/combo_box.md
> +Each interaction done in the ComboBox will only trigger its associated event handler. For instance, typing in the input field will only trigger the `on_input_change`, not the `on_change`.
This is true for typing, but it contradicts earlier docs when user selects a value, that does actually fire `on_input_change`.

2024-08-14 19:54 UTC, bmingles requested changes
Looking better. Looks like you may have accidentally committed a file? Also see the comment about an inaccuracy in `## Control` section

2024-08-14 19:54 UTC, AkshatJawne commented on docker/data/storage/notebooks/Untitled-0.md
No, definitely was not. It's weird that it got committed, it wasn't on my VSCode Source Control Tab with the files I changed, will get rid of this.

2024-08-15 14:36 UTC, bmingles approved these changes
LGTM

2024-08-15 14:56 UTC, dsmmcken requested changes

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +3. Immediately launch the popover if users are unfamiliar with the combo box content or if the data is particularly complex.
These two points are pretty confusing, and contain UX/combo box specific language that most people won't be familiar with. Either re-word or remove entirely

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +        "Group = randomInt(1, 5)",
This non-deterministic. All examples must be deterministic for snapshotting later, also not sure why the group column exists?

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +my_combo_box_table_source_example = ui.combo_box(t, label="Sample ComboBox")
These lines should be swapped. It reads weird that the tables aren't in order with the combo boxes being created.

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +If you wish to manually specify the keys and labels, use a `ui.item_table_source` to dynamically derive the options from a table.
Add a heading for this.

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +            ui.section(ui.item("Option 1"), ui.item("Option 2")),
The examples on this page in general violate our own recommendations above by having only 2-5 options. We tell people that should be radio. Practice what we preach.

Note: I think the dx.data.gapminder().select_distinct("country") has a list of countries that would make a good example set.

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +Note that, when searching for options, searching by section will not result in the respective options within that section appearing.
should also note, sections can only be used directly, not from a table data source.

2024-08-15 14:56 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +Each interaction done in the ComboBox will trigger its associated event handler. For instance, typing in the input field will only trigger the `on_input_change`, not the `on_change`.
This seems pretty similar to the last section, not sure what the difference is intended to be?

2024-08-15 15:29 UTC, AkshatJawne commented on plugins/ui/docs/components/combo_box.md
> +Each interaction done in the ComboBox will trigger its associated event handler. For instance, typing in the input field will only trigger the `on_input_change`, not the `on_change`.
Agreed, will combine.

2024-08-16 21:37 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +        label="Favourite Animal",
```suggestion
        label="Favorite Animal",
```

Don't want to confuse the Americans.

2024-08-16 21:55 UTC, dsmmcken requested changes

2024-08-16 21:55 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +ComboBoxes combine a text input field with a picker menu, enabling users to filter and select from longer lists based on their query.
```suggestion
Combo boxes combine a text input field with a picker menu, enabling users to filter and select from longer lists based on their query.
```

Should be two words everywhere

2024-08-16 21:55 UTC, dsmmcken commented on plugins/ui/docs/components/combo_box.md
> +    ["Timestamp = '2024-01-01T00:00:00 ET' + 'PT1m'.multipliedBy(ii)"]
Thinking about this I would just include the one example in this block, and use the same gapminder set below which is a better example of when one would want a combo box

2024-08-19 15:11 UTC, dsmmcken approved these changes

2024-08-19 15:25 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +The combo box can be labeled using the `label` prop, and if no label is provided, an `aria_label` msut be provided to identify the control for accessibility purposes.
```suggestion
The combo box can be labeled using the `label` prop, and if no label is provided, an `aria_label` must be provided to identify the control for accessibility purposes.
```

2024-08-19 15:30 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +Combo box supports sections in order to group options. Sections can be used by wrapping groups of items in a Section element. Each Section takes a title and key prop.
```suggestion
Combo boxes support sections to group options. Sections can be used by wrapping groups of items in a Section element. Each Section takes a title and key prop.
```

2024-08-19 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +Combo Box supports selection via mouse, keyboard, and touch. You can handle all of these via the `on_change` prop, which receives the selected key as an argument. Additionally, Combo Box accepts an `
```suggestion
Combo boxes support selection via mouse, keyboard, and touch. You can handle all these via the `on_change` prop, which receives the selected key as an argument. Additionally, combo boxes accept an `on_input_change` prop, which is triggered whenever the search value is edited by the user, whether through typing or option selection.
```

2024-08-19 15:31 UTC, margaretkennedy commented on plugins/ui/docs/components/combo_box.md
> +Each interaction done in the Combo Box will trigger its associated event handler. For instance, typing in the input field will only trigger the `on_input_change`, not the `on_change`.
```suggestion
Each interaction done in the combo box will trigger its associated event handler. For instance, typing in the input field will only trigger the `on_input_change`, not the `on_change`.
```

2024-08-19 15:32 UTC, margaretkennedy approved these changes

2024-08-19 15:41 UTC, merged