fix: Prevent pushing broken docs to main
deephaven/deephaven-plugins pull request #719
Opened 2024-08-09 18:19 UTC by jnumainville

1. Plumbs through error codes so `make_docs.py` fails correctly
2. `make_docs.yml` now runs on pull request to main (without sync) so broken docs have to be cleaned up before merge
3. Fixed `text_area.py` so docs are able to build

Tested on my fork

2024-08-12 13:14 UTC, mofojed requested changes

2024-08-12 13:14 UTC, mofojed commented on .github/workflows/build-main-docs.yml
> +        type: string
Add in a `workflow_dispatch` as well so we can trigger this from the UI just in case? Doesn't need to be done as part of this PR

2024-08-12 13:14 UTC, mofojed commented on .github/workflows/make-docs.yml
> +        required: false
Why not required here but required in `build-main-docs.yml`?

2024-08-12 13:14 UTC, mofojed commented on .github/workflows/modified-plugin.yml
> +    if: ${{ needs.changes.outputs.packages != '[]' && needs.changes.outputs.packages != '' && (github.ref == 'refs/heads/main' || github.base_ref == 'main')}}
I can't find an exhaustive list of `event_name` constants. I think we should be more restrictive though, we only want this to run on PRs and pushes, so `github.event_name == 'push' || github.event_name == 'pull_request'`

2024-08-12 13:14 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +            return 1
Return the `code` instead of just `1` here to match your pydoc

2024-08-12 13:14 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +        None
Returns the code if `exit_on_fail` is true, or `0` if success. Something like that.

2024-08-12 13:14 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +        exit_on_fail: Whether to exit if a command fails. Default is True. If False, the code is returned.
```suggestion
        exit_on_fail: Whether to exit if a command fails. Default is True. If False, the code is returned for the failing command and no subsequent commands are run.
```

2024-08-12 13:14 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +def run_commands(commands: list[str], exit_on_fail: bool = False) -> int:
Not sure I like this function so much, it seems kind of unclear in behaviour (e.g. what happens when one command fails).

2024-08-12 13:14 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +        return 1
Return `code` instead of `1`?

2024-08-12 13:14 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
>      Make the markdown files and copy the assets in
Add `Returns:` pydoc

2024-08-12 15:40 UTC, jnumainville commented on sphinx_ext/make_docs_utilities.py
> +        return 1
This gets a little tricky. 
[This](https://stackoverflow.com/questions/6466711/what-is-the-return-value-of-os-system-in-python/35362488#35362488) post sums up the behavior. 
So often `code` is equal to 256 or 512 in the error case.
Since `make_docs.py` is called from the command line, the error code (the higher order bytes) are dropped and 0 is returned. We could shift to return the error code, but then we would also make sure we exit on signal such as interrupt (which is what the other byte is for), in which case we would want to return some error code such as 1 anyways... so thought I'd just return 1 since I didn't know cases where we really care about the specific error code. Is doing something like that worth a bit more complexity?

2024-08-12 16:01 UTC, jnumainville commented on .github/workflows/build-main-docs.yml
> +        type: string
#724

2024-08-12 16:06 UTC, jnumainville commented on .github/workflows/make-docs.yml
> +        required: false
`build-main-docs.yml` will now be called in the cases of both a push and pull request, and we of course need to know which to sync docs in the case of a push and not if a pull request.
This is also called from `release-python-package.yml` in which case we know it's a push and we want to sync release docs.
I could pass in the event from there, but was one less file to touch.

2024-08-12 16:17 UTC, jnumainville commented on sphinx_ext/make_docs_utilities.py
> +def run_commands(commands: list[str], exit_on_fail: bool = False) -> int:
In addition to your comments I also renamed it to `attempt_command_sequence` to more clearly convey the intention.

2024-08-12 17:45 UTC, mofojed requested changes

2024-08-12 17:45 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +        Returns the code if exit_on_fail is true, or 0 if success.
```suggestion
        If exit_on_fail is True, returns 0 if the command succeeded or the error code.
        If exit_on_fail is False, returns the result code from running the command.
```

2024-08-15 17:10 UTC, jnumainville commented
@mofojed any further thoughts?

2024-08-15 17:54 UTC, merged