docs: ui.checkbox
deephaven/deephaven-plugins pull request #722
Opened 2024-08-09 21:21 UTC by AkshatJawne

Closes #720

2024-08-12 13:58 UTC, dsmmcken requested changes
Each of checkbox, checkbox group and list_view should cross link to each other with an explanation of when to use each. (individual checkbox, a set of related checkbox, a list of checkboxes that can be driven from a deephaven table)

Similar to in button how we mention the difference between it and action_button.

2024-08-16 21:27 UTC, dsmmcken commented on plugins/ui/docs/components/checkbox.md
> +Checkboxes enable users to select multiple items from a list or mark a single item as selected.
```suggestion
Checkbox allows users to select or mark a single item as selected.
```

2024-08-19 15:14 UTC, dsmmcken commented on plugins/ui/docs/components/checkbox.md
> +If wanting to use multiple checkboxes, use `checkbox_group`.
```suggestion
To use multiple checkboxes together, use the `checkbox_group` component.
```

We should come back and link this when we have the checkbox group component

2024-08-19 15:59 UTC, dsmmcken commented on plugins/ui/docs/components/checkbox.md
> +        ui.text_field(value="Subscribed!" if selected else "Not subscribed!"),
should probably just be ui.text rather than text_field

2024-08-19 16:37 UTC, dsmmcken requested changes

2024-08-19 16:37 UTC, dsmmcken commented on plugins/ui/docs/components/checkbox.md
> +```
```suggestion
```python
from deephaven import ui


@ui.component
def ui_checkbox_event_example():
    selected, set_selected = ui.use_state(False)
    return [
        ui.checkbox("Subscribe", is_selected=selected, on_change=set_selected),
        ui.text("Subscribed!" if selected else "Not subscribed!")
    ]


my_checkbox_event_example = ui_checkbox_event_example()
```
```

ui.text doesn't take a value, this doesn't work with it. Also the flex is redundant.

2024-08-19 16:37 UTC, dsmmcken commented on plugins/ui/docs/components/checkbox.md
> +)
remove pointless ui.flex

2024-08-19 18:07 UTC, dsmmcken approved these changes

2024-08-19 18:08 UTC, margaretkennedy commented on plugins/ui/docs/components/checkbox.md
> +4. Checkboxes should be used when selecting (ie. multiple table rows), whereas, switches should be used for activation (ie. on/off states).
```suggestion
4. Checkboxes should be used when selecting (ie., multiple table rows), whereas switches should be used for activation (ie., on/off states).
```

2024-08-19 18:09 UTC, margaretkennedy commented on plugins/ui/docs/components/checkbox.md
> +A Checkbox can be set to an indeterminate state using the `is_indeterminate` prop, which overrides its appearance. The Checkbox remains visually indeterminate until prop is set to false, regardless o
```suggestion
A checkbox can be set to an indeterminate state using the `is_indeterminate` prop, which overrides its appearance. The Checkbox remains visually indeterminate until the prop is set to false, regardless of user interaction.
```

2024-08-19 18:10 UTC, margaretkennedy approved these changes

2024-08-19 19:06 UTC, dsmmcken approved these changes

2024-08-19 20:16 UTC, merged