fix: use_effect behaviour
deephaven/deephaven-plugins pull request #734
Opened 2024-08-14 21:23 UTC by mofojed

- `use_effect` hook was not actually triggering the effects and cleanup methods correctly based on the dependencies passed in
  - Was only being called when dependencies were changed, cleanup was not being called on unmount, and we didn't handle no dependencies being passed in correctly (should call previous cleanup/effect on each render)
  - Effects were being run during the render, instead of after the render as they are supposed to
- Re-wire `use_effect` to correctly implement the `use_effect` behaviour as defined in the React [useEffect docs](https://react.dev/reference/react/useEffect#examples-dependencies).
- Re-organized unit tests, and added tests for `use_effect`
- Manual with a counter component using the three different effect types, and also a "nested" component that tests unmount/mount behaviour:
```
from deephaven import ui

@ui.component
def ui_effect_test_counter(name = "test"):
    count, set_count = ui.use_state(0)

    def make_effect(effect_name: str):
        def cleanup():
            print(f"{name}-{effect_name}-cleanup")

        def effect():
            print(f"{name}-{effect_name}-effect")
            return cleanup
        
        return effect

    ui.use_effect(make_effect("no_deps"))
    ui.use_effect(make_effect("empty_deps"), [])
    ui.use_effect(make_effect("count_dep"), [count])

    return ui.action_button(f"Count is {count}", on_press=lambda: set_count(count + 1))

@ui.component
def ui_nested_effect():
    is_shown, set_is_shown = ui.use_state(True)

    return [
        ui.toggle_button("Show counter", is_selected=is_shown, on_change=set_is_shown),
        ui_effect_test_counter("nested") if is_shown else None
    ]

effect_test_counter = ui_effect_test_counter()
nested_effect = ui_nested_effect()
```

2024-08-19 21:31 UTC, jnumainville requested changes

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +            self._children_context[context].unmount()
```suggestion
        for context in self._children_context.values():
            context.unmount()
```

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_effect.py
> +EffectFunction = Callable[[], Union[CleanupFunction, None]]
Are these types supposed to be declared both here and in RenderContext.py as they are instead of a shared file?

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_effect.py
> +    cleanup_ref: Ref[Union[Callable[[], None], None]] = use_ref(lambda: None)
Would `Callable[[], None]` in this type be `CleanupFunction`?

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/renderer/Renderer.py
> +    return item
```suggestion
    return _render_item(item, context.get_child_context(key)) if key is not None else item
```

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/renderer/Renderer.py
> +    """
Missing `Returns:` section in docstring

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/test/deephaven/ui/hooks/render_utils.py
> +        The queue to put items on. If not provided, a new queue will be created.
unnecessary types in these args and missing `*args` and `**kwargs`

2024-08-19 21:31 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/renderer/Renderer.py
> +    """
no `Args:` in docstring

2024-08-20 13:00 UTC, mofojed commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +            )
In the Google style guide they explicitly say not to use f-strings in logging: https://google.github.io/styleguide/pyguide.html#3101-logging
Generally it's for optimization so it doesn't need to build the string unnecessarily. I think best practice is to stick with this style of formatting for logging, especially if it's going to be calling this code a lot.

2024-08-20 13:03 UTC, mofojed commented on plugins/ui/src/deephaven/ui/_internal/RenderContext.py
> +        logger.debug("Opening context %s (old context is %s)", self, old_context)
Purposely avoiding f-string as mentioned in the Google style pyguide.

2024-08-20 13:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_effect.py
> +EffectFunction = Callable[[], Union[CleanupFunction, None]]
The `CleanupFunction` is the same, but they are slightly different, in that the `EffectFunction` in `RenderContext` does not return a possible `CleanupFunction`.
I'll rename the types in RenderContext to be clear it's a different thing.

2024-08-20 15:25 UTC, jnumainville commented on plugins/ui/test/__init__.py
> +    #  Even if starting the server throws, we want to continue to try and run our tests
```suggestion
    # Even if starting the server throws, we want to continue to try and run our tests
```

2024-08-20 19:31 UTC, jnumainville approved these changes

2024-08-20 20:13 UTC, merged