docs: ui.illustrated_message
deephaven/deephaven-plugins pull request #739
Opened 2024-08-15 18:00 UTC by AkshatJawne

Closes #707

2024-08-15 18:07 UTC, AkshatJawne commented
Investigating failure

2024-08-16 15:37 UTC, AkshatJawne reviewed
@margaretkennedy @dsmmcken Please prioritize reviewing this Docs PR above the others, since this contains fixes for other docs that are breaking with our new tests

2024-08-16 15:58 UTC, margaretkennedy commented on plugins/ui/docs/components/illustrated_message.md
> +Recommendations for creating a IllustratedMessage:
```suggestion
Recommendations for creating an IllustratedMessage:
```

2024-08-16 16:00 UTC, margaretkennedy commented on plugins/ui/docs/components/illustrated_message.md
> +1. The message should be concise and, if applicable, describe the next step that a user can take.
```suggestion
1. The message should be concise and, if applicable, describe the next step a user can take.
```

2024-08-16 16:00 UTC, margaretkennedy commented on plugins/ui/docs/components/illustrated_message.md
> +2. The heading should no longer than 6 words, and should not be a replacement for the message text.
```suggestion
2. The heading should be no longer than 6 words and should not be a replacement for the message text.
```

2024-08-16 16:01 UTC, AkshatJawne reviewed
Ready for re-review @margaretkennedy

2024-08-16 21:34 UTC, dsmmcken requested changes
I would like to see an example of the common use case as a placeholder for a table or list to encourage the pattern of using this.

Like maybe a text_field that must have content before filtering a table.

Something like


my_illustrated_message = ... "please enter a filter"

@ui.component...
filter,set_filter
ui.text_field()

return [
 my_illustrated_message if filter == None else _stocks.where("sym = ...")

2024-08-16 21:34 UTC, dsmmcken commented on plugins/ui/docs/components/illustrated_message.md
> +An IllustratedMessage displays an illustration along with a message, typically used for empty states or error pages.
> IllustratedMessage

Casing.

2024-08-19 15:20 UTC, dsmmcken commented on plugins/ui/docs/components/illustrated_message.md
> +    ui.text_field(value=filter)
You aren't returning the text_field or setting an on change. This example wouldn't work.

2024-08-19 15:28 UTC, AkshatJawne commented on plugins/ui/docs/components/illustrated_message.md
> +    ui.text_field(value=filter)
It's weird, it removed my actual example that I had added in my `add review changes` commit when I merged main, should be fixed now.

2024-08-20 15:55 UTC, dsmmcken commented on plugins/ui/docs/components/illustrated_message.md
> +my_illustrated_message_placeholder_example = illustrated_message_placeholder_example()
```suggestion
from deephaven import ui
import deephaven.plot.express as dx

_stocks = dx.data.stocks()


@ui.component
def illustrated_message_placeholder_example():
    filter, set_filter = ui.use_state("")

    return [
        ui.text_field(
            value=filter, label="Sym Filter", is_required=True, on_change=set_filter
        ),
        ui.illustrated_message(
            ui.icon("vsFilter"),
            ui.heading("Filter required"),
            ui.content("Enter a filter to display filtered table"),
            width="100%",
        )
        if filter == ""
        else _stocks.where(f"Sym=`{filter.upper()}`"),
    ]


my_illustrated_message_placeholder_example = illustrated_message_placeholder_example()
```

I think we can improve styling, and no need to use a form here.

2024-08-20 16:33 UTC, dsmmcken requested changes

2024-08-20 16:33 UTC, dsmmcken commented on plugins/ui/docs/components/illustrated_message.md
> +Using an illustrated message as a placeholder for a table or list can clearly indicating the absence of data and provide context-specific guidance.
```suggestion
Using an illustrated message as a placeholder for a table or list can clearly indicate the absence of data and provide context-specific guidance.
```

2024-08-20 18:53 UTC, margaretkennedy commented on plugins/ui/docs/components/illustrated_message.md
> +4. Reserve illustrated message for situations where it adds value and clarity, rather than using it for minor notifications or messages.
```suggestion
4. Reserve illustrated messages for situations where they add value and clarity, rather than using them for minor notifications or messages.
```

2024-08-20 18:54 UTC, margaretkennedy commented on plugins/ui/docs/components/illustrated_message.md
> +If the heading of an illustrated message isn't specified, the illustration should have the `aria-label` prop set for accessibility purposes.
```suggestion
If the heading of an illustrated message isn't specified, set the `aria-label` prop for accessibility purposes.
```

2024-08-20 18:54 UTC, margaretkennedy approved these changes

2024-08-20 19:39 UTC, dsmmcken approved these changes

2024-08-20 19:40 UTC, merged