fix: Fix widget plugin python warnings
deephaven/deephaven-plugins pull request #740
Opened 2024-08-15 20:49 UTC by jnumainville

Fixes #713 
Mostly minor warnings
The main fix of consequence is a new class, `CommonJsPlugin`, in utilities. This should be inherited from by all plugins that use `JsPlugin` because `create_js_plugin` actually requires something of the form `CommonJsPlugin` as `JsPlugin` doesn't specify the inputs it takes. We should do this first and release a new `utilities` package. I will make a follow-up PR that will fix the inheritance on all our packages to ensure the typing is correct.

2024-08-20 19:56 UTC, mofojed requested changes

2024-08-20 19:56 UTC, mofojed commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +class CommonJsPlugin(JsPlugin):
What's the point of having all the individual plugin classes (`UiJsPlugin`, `ExpressJsPlugin`, `MatplotlibJsPlugin`)? They all do the exact same thing.

We should just get rid of the `plugin_class` parameter entirely (deprecate first, release, then remove), and then it can just create a `CommonJsPlugin` in there.

Or is there another reason to be able to specify a custom class?

2024-08-21 14:43 UTC, jnumainville commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +class CommonJsPlugin(JsPlugin):
No reason that I know of.
I've got #741 up to remove them from the plugins

2024-08-30 17:55 UTC, mofojed requested changes

2024-08-30 17:55 UTC, mofojed commented on plugins/utilities/src/deephaven/plugin/utilities/utils.py
> +    plugin_class: Type[CommonJsPlugin],
Just need to get rid of the `plugin_class` arg here then this should be good to go yeah?

2024-09-04 21:17 UTC, mofojed submitted a review, later dismissed

2024-09-05 18:58 UTC, mofojed approved these changes

2024-09-05 20:32 UTC, merged