fix: Correct type for generated JsPlugin
deephaven/deephaven-plugins pull request #741
Opened 2024-08-15 21:25 UTC by jnumainville

Followup for #740 

Won't pass everything yet.
Modifies our plugins to use `CommonJsPlugin` by dropping the arg (since it's made optional in #740) and using the default.

2024-08-27 19:43 UTC, mofojed requested changes

2024-08-27 19:43 UTC, mofojed commented on plugins/utilities/setup.cfg
> +version = 0.0.1.dev0
Dupe, I think you meant to increment the version?

2024-09-10 15:44 UTC, jnumainville commented
We will need a `utilities` release before this

2024-09-19 18:08 UTC, mofojed submitted a review, later dismissed

2024-09-19 21:45 UTC, mofojed approved these changes

2024-09-19 21:47 UTC, merged