docs: ui.range_slider
deephaven/deephaven-plugins pull request #755
Opened 2024-08-19 21:00 UTC by AkshatJawne

Closes #745

2024-08-20 11:06 UTC, margaretkennedy commented on plugins/ui/docs/components/range_slider.md
> +Consider using a `slider` when users should select a singular value or a `number_field` when the range is large and sliding between the upper and lower bound is no longer quick.
```suggestion
Consider using a `slider` instead of a `range_slider` when users should select a singular value or a `number_field` when the range is large and sliding between the upper and lower bound is no longer quick.
```

2024-08-20 11:06 UTC, margaretkennedy commented on plugins/ui/docs/components/range_slider.md
> +The `step` prop changes the increments that the range slider changes.
```suggestion
The `step` prop changes the increments in which the range slider changes.
```

2024-08-20 11:07 UTC, margaretkennedy approved these changes

2024-08-21 15:00 UTC, dsmmcken requested changes

2024-08-21 15:00 UTC, dsmmcken commented on plugins/ui/docs/components/range_slider.md
> +    gap="size-300",
```suggestion
    direction="column",
    gap="size-500",
```
How you have it looks weird to me, suggesting just making a column with a larger gap.
<img width="836" alt="Screenshot 2024-08-21 at 10 58 19 AM" src="https://github.com/user-attachments/assets/76648687-cc12-4eaa-8236-5ab8bded07c0">

2024-08-22 02:31 UTC, dsmmcken approved these changes

2024-08-22 15:23 UTC, merged