docs: ui.radio_group
deephaven/deephaven-plugins pull request #758
Opened 2024-08-20 19:22 UTC by AkshatJawne

Closes #756

2024-08-20 19:38 UTC, AkshatJawne reviewed
Failures here are unlike other PRs, still investigating docstring to determine how to fix failure.

2024-08-20 20:34 UTC, AkshatJawne commented
Should be good now to review

2024-08-20 21:13 UTC, margaretkennedy commented on plugins/ui/docs/components/radio_group.md
> +1. Every range slider should have a [label](#labeling) specified. Without one, the radio group is ambiguous. In the rare case that context is sufficient, the label is unnecessary; you must still incl
just confirming you mean range slider

2024-08-21 14:46 UTC, AkshatJawne commented on plugins/ui/docs/components/radio_group.md
> +1. Every range slider should have a [label](#labeling) specified. Without one, the radio group is ambiguous. In the rare case that context is sufficient, the label is unnecessary; you must still incl
Had a mistype when fixing a typo, should be corrected now.

2024-08-21 15:07 UTC, dsmmcken requested changes

2024-08-21 15:07 UTC, dsmmcken commented on plugins/ui/docs/components/radio_group.md
> +Consider using a [`checkbox_group`](./checkbox_group.md) to manage multiple selections or no selections within a group at once. If you need to display a list of items driven by a Deephaven table, use
```suggestion
Consider using a [`checkbox_group`](./checkbox_group.md) to manage multiple selections or no selections within a group at once. If you need to display a list of items driven by a Deephaven table, use a [`list_view`](./list_view.md) to dynamically generate the checkboxes with `selection_mode="single"` to mimic radio behaviour.
```

2024-08-22 02:33 UTC, dsmmcken commented
I see you added value everywhere. Is value always required? I thought it was optional and used the label? If so, I would show some options like that.

2024-08-22 03:45 UTC, AkshatJawne reviewed
@dsmmcken This is interesting, just tried some examples, and it appears that if we do not currently set the `value` to be the label if the `value` is not provided. 

The `value` by default is set to `None`, so I guess there are two options:

a. Create a ticket to make it so that it sets the `value` to the label by default, and then include the fact that the value is an optional prop.
b. Do not make any changes to the current logic, and enforce that users have to set `value`

I am more in favor of A, but open to either

2024-08-22 15:03 UTC, dsmmcken commented
I think it should work automatticaly as you describe with option A. I mean that's what you had initially actually tried, so it seems like thats how one would expect it to work. This of course only applies if contents of the label are a string, and not anything more complex (not sure if it accepts icons + text for example, in which case a value would be required.

@mofojed thoughts?

2024-08-22 15:12 UTC, AkshatJawne commented
<img width="255" alt="Screenshot 2024-08-22 at 9 10 00 AM" src="https://github.com/user-attachments/assets/9c9317aa-3b4c-4cdc-909c-0452206b96c5">

It appears that it accepts icons + text, so in cases like this, we would have to have a `value` set. 

So, I think we should create a ticket where we make the `value` default to the label, if the label is text. Otherwise, if the label is an icon + text for example, we make it so that `value` has to be passed in.

@dsmmcken @mofojed

2024-08-22 15:41 UTC, dsmmcken commented
@AkshatJawne Please ticket this, and also we should make sure checkbox/checbox_group also behaves the same way, as looking at checkbox docs I don't see it talking about the value prop at all.

2024-08-22 16:03 UTC, AkshatJawne commented
Created ticket: https://github.com/deephaven/deephaven-plugins/issues/765

2024-08-22 21:24 UTC, dsmmcken approved these changes

2024-08-22 21:48 UTC, margaretkennedy approved these changes

2024-08-22 22:37 UTC, dsmmcken approved these changes

2024-08-22 22:37 UTC, merged