docs: list view
deephaven/deephaven-plugins pull request #769
Opened 2024-08-23 15:11 UTC by ethanalvizo

Closes #686 

Note: Empty state example was intentionally omitted as this [bug](https://github.com/deephaven/deephaven-plugins/issues/744) was found when rendering an empty list view component. Can add in the example once that is fixed

2024-08-23 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +ListView displays a list of interactive items, and allows a user to navigate, select, or perform an action. They offer greater flexibility in the contents it can render and can distinguish between ro
```suggestion
ListView displays a list of interactive items and allows a user to navigate, select, or perform an action. It offers greater flexibility in the contents it can render and can distinguish between row selection and actions performed on a row. This makes ListView an ideal component for use cases such as file managers.
```

2024-08-23 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +ListView can also accept a handler that is called when the selection is changed
```suggestion
ListView can also accept a handler that is called when the selection is changed.
```

2024-08-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +To adjust the vertical padding of each row in the ListView, you can use the density prop.
```suggestion
To adjust the vertical padding of each row in the ListView, use the `density` prop.
```

2024-08-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +The default behaviour is to truncate content that overflows its row. Text can be wrapped instead by assing `wrap` to the `overflow_mode` prop.
```suggestion
The default behavior is to truncate content that overflows its row. Text can be wrapped instead by adding `wrap` to the `overflow_mode` prop.
```

2024-08-26 14:36 UTC, dsmmcken requested changes
Can you include the updating the docstring for list_view? That's missing.

2024-08-29 21:35 UTC, ethanalvizo commented
> Can you include the updating the docstring for list_view? That's missing.

<img width="424" alt="image" src="https://github.com/user-attachments/assets/9cafafbd-b0a3-48f0-b3ff-36841b781c5a">

This is what you're referring to right? @dsmmcken

2024-08-30 16:26 UTC, dsmmcken commented
> This is what you're referring to right

No, I mean ui.list_view pydoc string in the python source is incomplete. It's missing half its params.

2024-09-06 13:33 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +ListView displays a list of interactive items, and allows a user to navigate, select, or perform an action. It offers greater flexibility in the contents it can render and can distinguish between row
@dsmmcken The mention of this being ideal for a "file manager" doesn't seem like a common use case in DH (if at all)? Any other ideas of something more applicable to DH use cases? I see this mentioned in the ListView docs but not in the primary description. May be worth removing or changing.

2024-09-06 13:35 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +    action_item_keys, set_action_item_idx = ui.use_state(["", ""])
Any reason, the value + setter use different naming semantics? (keys vs idx)

2024-09-06 13:43 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +lv = ui_list_view()
I'd rename this the component / variable to `ui_list_view_quiet` and `my_list_view_quiet` respectively.

2024-09-06 13:44 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +lv = ui_list_view()
Same here, convention is typically `ui_some_component_some_label` and `my_some_component_some_label`

2024-09-06 13:48 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        disabled_keys: The keys that should be disabled. These cannot be selected, focused, or interacted with
We might want to include an example of `disabled_keys`

2024-09-06 13:50 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        grid_area: When used in a grid layout specifies, specifies the named grid area that the element should be placed in within the grid.
Looks like typo "specifies, specifies"

2024-09-06 13:59 UTC, bmingles reviewed
@ethanalvizo  The docs that are here look good overall (left some minor tweak comments), but I think we are missing some examples of different data sources. Namely we should have both static items + table backed examples. Looking at the `picker` docs, I also see a "UI Recommendations" section. @dsmmcken am I remembering correctly that this is something you requested for docs for each component?

2024-09-06 15:47 UTC, ethanalvizo commented on plugins/ui/docs/components/list_view.md
> +    action_item_keys, set_action_item_idx = ui.use_state(["", ""])
No not a particular reason I just grabbed some examples from the [DESIGN.md](https://github.com/deephaven/deephaven-plugins/blob/18078627f5f66cafe1e7624df1c19ad8e99e69e9/plugins/ui/DESIGN.md#L4) doc. But agreed it doesn't make sense to change between the two. Will default to keys.

2024-09-06 16:34 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        disabled_keys: The keys that should be disabled. These cannot be selected, focused, or interacted with
Agreed just added one to the markdown docs

2024-09-20 13:55 UTC, dsmmcken commented on plugins/ui/docs/components/list_view.md
> +ListView displays a list of interactive items, and allows a user to navigate, select, or perform an action. It offers greater flexibility in the contents it can render and can distinguish between row
```suggestion
List view displays a list of interactive items, and allows a user to navigate, select, or perform an action. It offers greater flexibility in the contents it can render and can distinguish between row selection and actions performed on a row. This makes list view an ideal component for turning table columns into interactive lists.
```

2024-09-20 14:10 UTC, dsmmcken commented on plugins/ui/docs/components/list_view.md
> +## Example
The first example and events example are exactly the same?

I would really strip down the first example to be a more basic example. The first example is supposed to be the minimum viable amount of code to make it work.

2024-09-20 14:11 UTC, dsmmcken commented on plugins/ui/docs/components/list_view.md
> +```python
Get rid of as much complexity in this example as possible leaving only the thing you are trying to show, `on_selection_change`

2024-09-20 14:11 UTC, dsmmcken commented on plugins/ui/docs/components/list_view.md
> +```python
Same comment as before, strip this example down to minimum required to show what is unique about it.

2024-09-20 14:12 UTC, dsmmcken requested changes
Missing example of constructing list with wrapped children in ui.item or list_item or wahtever it is.

2024-09-27 03:21 UTC, ethanalvizo commented
> Missing example of constructing list with wrapped children in ui.item or list_item or wahtever it is.

Made this the base example. I stripped down the event examples to be much simpler but I chose to still use table sources for the items in the list view. I think having keys makes for better examples of the possible actions and they're needed for the disabled options section

2024-09-30 22:14 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +        overflow_mode="wrap",
This is not expected. Variable item heights will cause bad behavior.

2024-10-02 00:41 UTC, ethanalvizo commented on plugins/ui/docs/components/list_view.md
> +        overflow_mode="wrap",
Wasn't sure if this meant I should take the example out entirely but I instead added the note below explaining that it is not currently supported. Not sure if I should add the details of what the bad behavior is, if so is there an easy example I could showcase @bmingles?

```
Note: Currently not supported if a table source is used.
```

2024-10-04 03:26 UTC, ethanalvizo commented on plugins/ui/docs/components/list_view.md
> +List view items can also be generated from a table.
`An item table source wraps a Table or PartitionedTable to provide additional information for
    creating complex items from a table.`
    
I couldn't really gather what a "complex item" is from the pydocs of `item_table_source`^. I know if you don't use table source it will just use the first column as the key and label but other than that I wasn't sure what the difference is.

2024-10-04 03:28 UTC, ethanalvizo commented on plugins/ui/docs/components/list_view.md
> +```
When I pass in an actions prop to a static list view the options are not rendering. Not sure if the issue is with my implementation or actions are not supported for non-table sources

```
 lv = ui.list_view(
        "Option 1",
        "Option 2",
        "Option 3",
        actions = ui.list_action_group(
            "Edit",
            "Delete",
            on_action=print("hello"),
        )
    )
   ```

2024-10-04 18:32 UTC, ethanalvizo commented on plugins/ui/docs/components/list_view.md
> +```
Spoke to Brian about this and it is not supported when the children are coming from a non-table source. The actiongroup functionality is added by useRenderNormalizedIem which only runs in table sourced list view.

 It's not always data being passed in it could be JSX elements as children. Using the renderItem function to add actions would involve wrapping JSX elements + creating new element trees. It's possible but it was simpler to just let it pass so right now there is no opportunity to inject the new elements required for action groups

2024-10-07 14:56 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +    return default_list, quiet_list
I would define these in the same order they are rendered.

2024-10-07 14:56 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +    return compact_list, spacious_list
Same here, any reason the rendering order is the reverse of the order they were defined with?

2024-10-07 15:01 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +        overflow_mode="wrap",
The example is fine for static source. The issue is only with table sources since the listview has to be able to calculate the total content height. We can do this if all items have the same height, since it's just multiplying item height * table size. Variable heights break this.

2024-10-07 15:08 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        on_selection_change: Handler that is called when the selection changes.
@dsmmcken trying to remember. Do we actually want to surface `on_selection_change` since we are encouraging `on_change`? We marked as deprecated in some places, but I think we wanted to remove it from new apis.

2024-10-07 15:10 UTC, bmingles commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        **props: Any other ListView prop, except items, dragAndDropHooks, and onLoadMore.
I think we are moving towards not support `**props` and having everything be explicit.

2024-10-07 15:33 UTC, bmingles requested changes
Left a couple of suggestions + questions

2024-10-07 17:57 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        on_selection_change: Handler that is called when the selection changes.
I am not sure one what our general pattern of deprecation is, or should be. But yes the on_change handler is the preferred one to show in examples, and on_selection_change can eventually be removed I think?

2024-10-07 17:57 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        **props: Any other ListView prop, except items, dragAndDropHooks, and onLoadMore.
Here is fine.

2024-10-11 03:32 UTC, ethanalvizo commented on plugins/ui/docs/components/list_view.md
> +        overflow_mode="wrap",
Changed the note to say

```
Note: Currently not supported if a table source is used and items have varying heights.
```

2024-10-11 03:59 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/list_view.py
> +        on_selection_change: Handler that is called when the selection changes.
Changed the examples and updated the pydocs to reflect the preference. Wasn't certain about fully omitting on_selection_change though

2024-10-11 14:40 UTC, bmingles approved these changes
LGTM

2024-10-11 14:43 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +Note: Currently not supported if a table source is used and items have varying heights.
Oh, I missed this. This is not quite accurate. Overflow wrap is not supported at all for table source. The variable heights is why, but it's not an additional qualifier.

2024-10-11 18:14 UTC, bmingles approved these changes
Looks good

2024-10-11 18:58 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +Ideal to quickly display a static dataset. The first column is used as the key and label by default.
```suggestion
This method is ideal for quickly displaying a static dataset. By default, the first column is used as the key and label.
```

2024-10-11 18:58 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +Used for creating complex items from a table (ie. defining which columns are the keys/labels of the data)
```suggestion
`item_table_source` is used to create complex items from a table (ie., defining which columns are the keys/labels of the data).
```

2024-10-11 18:58 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +To disable certain rows in the ListView component, use the `disabled_keys` prop. By setting this prop with an array of keys, you can prevent interaction with those rows, providing greater control and
```suggestion
To disable certain rows in the `ListView` component, use the `disabled_keys` prop. By setting this prop with an array of keys, you can prevent interaction with those rows, providing greater control and customization options for the `ListView` behavior.
```

2024-10-11 18:58 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +To adjust the vertical padding of each row in the ListView, use the `density` prop.
```suggestion
To adjust the vertical padding of each row in the list view, use the `density` prop.
```

2024-10-11 18:58 UTC, margaretkennedy commented on plugins/ui/docs/components/list_view.md
> +Note: Currently not supported if a table source is used.
```suggestion
Note: Currently not supported if a table source is used and items have varying heights.
```

2024-10-11 20:03 UTC, bmingles commented on plugins/ui/docs/components/list_view.md
> +Note: Currently not supported if a table source is used.
This is not quite accurate. Item heights are hard coded assuming a non-wrapped line for table sources, so even if all were consistently wrapped, it would cause problems. aka. wrapping is not supported for table sources at all.

2024-10-15 17:09 UTC, dsmmcken approved these changes

2024-10-15 20:33 UTC, merged