docs: Add use_effect docs
deephaven/deephaven-plugins pull request #772
Opened 2024-08-23 16:37 UTC by mofojed

- Give some examples of connecting to a server using requests and multi-threading
- Have an example of creating a custom hook
- Specify what the different dependency list options are
- Fixes #727

2024-08-23 20:17 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +`use_effect` is a hook that allows you to perform side effects in your components, allowing you to interact with an external system. It is similar to [`useEffect` in React](https://react.dev/referenc
```suggestion
`use_effect` is a hook that allows you to perform side effects in your components and to interact with an external system. It is similar to [`useEffect` in React](https://react.dev/reference/react/useEffect).
```

2024-08-23 20:18 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +Put a long running request on a background thread so it doesn't block the component from updating.
```suggestion
Put a long-running request on a background thread so it doesn't block the component from updating.
```

2024-08-23 20:18 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +An effect will run after the initial render (mount) and any subsequent render when a dependency has changed. The returned cleanup function will run before the next effect, and when the component is c
```suggestion
An effect will run after the initial render (mount) and any subsequent render when a dependency has changed. The returned cleanup function will run before the next effect and when the component is closed (unmount). It is important to specify all dependencies in the dependency list to ensure the effect runs when the dependencies change.
```

2024-08-23 20:23 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +If your Effect depends on an object or function that is recreated on every render, you may want to memoize it to avoid unnecessary re-renders.
```suggestion
If your effect depends on an object or function that is recreated on every render, you may want to memoize it to avoid unnecessary re-renders.
```

2024-08-27 16:09 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +If you use constant values in your effect, you can omit it from the dependency list. If the `host` was instead a constant outside of the component and not reactive, you can omit it from the dependenc
```suggestion
If you use constant values in your effect, you can omit them from the dependency list. If the `host` was instead a constant outside of the component and not reactive, you can omit it from the dependency list:
```

2024-08-27 16:09 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +If you use constant values in your effect, you can omit it from the dependency list. If the `host` was instead a constant outside of the component and not reactive, you can omit it from the dependenc
it being the values?

2024-08-27 16:12 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +To avoid this, you can move the function inside the effect:
```suggestion
To avoid this, move the function inside the effect:
```

2024-08-27 16:12 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +Alternatively, you can memoize the object using `use_memo`:
```suggestion
Alternatively, memoize the object using `use_memo`:
```

2024-08-27 16:12 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +To avoid this, you can declare the object inside the effect:
```suggestion
To avoid this, declare the object inside the effect:
```

2024-08-27 16:12 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +Alternatively, you can memoize the function using `use_callback`:
```suggestion
Alternatively, memoize the function using `use_callback`:
```

2024-08-27 18:53 UTC, mofojed commented on plugins/ui/docs/hooks/use_effect.md
> +If you use constant values in your effect, you can omit it from the dependency list. If the `host` was instead a constant outside of the component and not reactive, you can omit it from the dependenc
Yes

2024-08-28 21:43 UTC, margaretkennedy submitted a review, later dismissed

2024-08-29 19:42 UTC, dsmmcken requested changes

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +        print("Mounted")
```suggestion
        # prints "Mounted" once when component is first rendered
        print("Mounted")
```

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +        return lambda: print("Unmounted")
```suggestion
        # prints "Unmounted" when component is closed
        return lambda: print("Unmounted")
```

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +        ui_server(port),
port is not defined

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +        ui_server(port),
same

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +        print(f"Disconnected from {details}")
`Connected to <__main__.ServerDetails object at 0x7f5d896d05b0>`

printing the memoized object not the details.

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +Alternatively, memoize the object using `use_memo`:
cross link to the use_memo page (ok to link to non-existent page right now.

2024-08-29 19:42 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_effect.md
> +Alternatively, memoize the function using `use_callback`:
link to use_callback

2024-09-04 14:40 UTC, mofojed commented on plugins/ui/docs/hooks/use_effect.md
> +        print(f"Disconnected from {details}")
Added a `__str__` representation for `ServerDetails` so it prints out the details instead.

2024-09-04 16:34 UTC, mofojed commented on plugins/ui/docs/hooks/use_effect.md
> +import requests
Re-worked to not require `requests` package. Made a chat room example.

2024-09-04 16:34 UTC, mofojed commented on plugins/ui/docs/hooks/use_effect.md
> +request_login = ui_request_login()
Changed to the chat room example similar to in the react docs

2024-09-04 18:33 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +2. **Dependency list**: A list of reactive values that the effect depends on. The effect will run when the component is mounted, and when any of the dependencies change. If a dependencies list is not
Being nitpicky, since we avoid "will" in the main docs.

2024-09-04 18:36 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +However, if we specify an empty dependency list, the effect will only run once when the component is mounted, which is probably not what we want:
```suggestion
However, if we specify an empty dependency list, the effect runs only once when the component is mounted, which is probably not what we want:
```

2024-09-04 18:37 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_effect.md
> +An effect will run after the initial render (mount) and any subsequent render when a dependency has changed. The returned cleanup function will run before the next effect and when the component is cl
Even though Charles would disagree, "will" make sense when discussing if / when

2024-09-04 18:40 UTC, margaretkennedy approved these changes
We avoid "will" in the user guide since it's Charles's strong preference, but I changed my mind and resolved my comments because when talking about dependencies, it makes sense. So ignore. LGTM.

2024-09-04 21:09 UTC, dsmmcken approved these changes

2024-09-04 21:17 UTC, merged