ci: Add workflow dispatch to Build Docs
deephaven/deephaven-plugins pull request #773
Opened 2024-08-23 17:27 UTC by jnumainville

Fixes #724 

Have tested on my own fork. Adds a workflow dispatch to `build-main-docs.yml`. It's in a slightly funky spot because release docs are automatically synced separately in a different workflow, but this could still be used to sync docs from a specific release, without actually releasing the package itself.

2024-08-27 19:54 UTC, mofojed requested changes

2024-08-27 19:54 UTC, mofojed commented on .github/workflows/build-main-docs.yml
> +        type: string
Should we make this a `choice` type and just list the packages here? https://docs.github.com/en/enterprise-cloud@latest/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs

2024-08-27 19:54 UTC, mofojed commented on .github/workflows/build-main-docs.yml
> +        default: 'push'
Would we ever want anything else other than `push` here? Wondering if this can be defined some other way such that we can't set it incorrectly.
At the very least, can make it a `choice` type with the valid types.

2024-08-28 17:26 UTC, jnumainville commented on .github/workflows/build-main-docs.yml
> +        default: 'push'
I can't think of a great use case, because if you're using this the docs are probably broken, and you want them to sync, but if there was a case where you don't want them to sync and want to verify they built, we'd want that.
Either way, I'll add a choice

2024-08-28 20:13 UTC, mofojed approved these changes

2024-08-28 22:54 UTC, mofojed approved these changes

2024-08-29 16:36 UTC, mofojed approved these changes

2024-08-29 16:37 UTC, merged