docs: icon
deephaven/deephaven-plugins pull request #774
Opened 2024-08-26 13:32 UTC by ethanalvizo

Closes #732

2024-08-26 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/icon.md
> +Icons in Spectrum support four semantic colors: negative, notice, positive, and informative. While icons within React Spectrum components are usually styled with the appropriate colors, you can use t
```suggestion
Icons in Spectrum support four semantic colors: negative, notice, positive, and informative. While icons within React Spectrum components are usually styled with the appropriate colors, you can use the `color` prop to customize the color of standalone icons.
```

2024-08-29 19:47 UTC, dsmmcken requested changes
Update after #696 merges.

We should have an example that shows and searches all icons, similar to what we do in our internal style guide. Does how it's defined in types allow to iterate that?

2024-09-09 18:42 UTC, dsmmcken requested changes
update to use prefix less icons.

I would use "filter", "bell" or "squirrel"

2024-09-13 02:59 UTC, ethanalvizo commented
> update to use prefix less icons.
> 
> I would use "filter", "bell" or "squirrel"

I'm assuming this is for the search example with all the available icons. Does this mean I should remove the dh icons since we decided to always add the prefix for those to avoid conflict ([previous icon PR](https://github.com/deephaven/deephaven-plugins/pull/696#discussion_r1739068186))?

2024-09-16 21:15 UTC, dsmmcken commented
I meant that in context of instead of all the example saying "dhTruck".

The search thing should use a ui.grid to look orderly instead of flex.

2024-09-30 20:02 UTC, dsmmcken requested changes

2024-09-30 20:02 UTC, dsmmcken commented on plugins/ui/docs/components/icon.md
> +my_icons = icons()
Create a follow up ticket. Icons should accept our theme colors rather than just these from spectrum,

2024-09-30 20:02 UTC, dsmmcken commented on plugins/ui/docs/components/icon.md
> +Icons in Spectrum support four semantic colors: negative, notice, positive, and informative. While icons within React Spectrum components are usually styled with the appropriate colors, you can use t
```suggestion
Icons support four semantic colors: negative, notice, positive, and informative. While icons within components are usually styled with the appropriate colors, you can use the `color` prop to customize the color of standalone icons.
```

Don't mention spectrum, users don't need to know about it.

2024-10-01 17:15 UTC, dsmmcken commented on plugins/ui/docs/components/icon.md
> +    icon = ui.icon(name="filter")
named arg is optional no? Should we be showing it as just `ui.icon("filter")` everywhere without the named arg

2024-10-04 02:52 UTC, ethanalvizo commented on plugins/ui/docs/components/icon.md
> +    icon = ui.icon(name="filter")
Yup it is optional it would only cause an issue if they put the icon name after another prop but I don't think that would happen often (ie. `ui.icon(size="S", "bell")`) so I just removed the name arg from all the examples

2024-10-04 03:00 UTC, ethanalvizo commented on plugins/ui/docs/components/icon.md
> +my_icons = icons()
#923

2024-10-04 15:49 UTC, dsmmcken approved these changes

2024-10-04 18:12 UTC, merged