Create CODEOWNERS
deephaven/deephaven-plugins pull request #775
Opened 2024-08-26 17:48 UTC by margaretkennedy

2024-08-26 17:50 UTC, margaretkennedy commented
Would "chore" be more appropriate?

2024-08-26 17:53 UTC, dsmmcken commented
> Would "chore" be more appropriate?

`ci:`

2024-08-27 17:25 UTC, mofojed requested changes

2024-08-27 17:25 UTC, mofojed commented on .github/CODEOWNERS
> +**/docs/**.md @margaretkennedy
You need the `**` for the directory, then `*.md` for the file.
```suggestion
**/docs/**/*.md @margaretkennedy
```

2024-08-27 18:01 UTC, dsmmcken approved these changes

2024-08-27 18:51 UTC, mofojed submitted a review, later dismissed

2024-08-27 19:46 UTC, mattrunyon requested changes
We should not have anything with only 1 codeowner. Puts a complete stop if Margaret is out for any reason

2024-08-27 20:24 UTC, dsmmcken commented
That's a fair point. It's more like we wanted her to be auto-added as a reviewer for an doc change but you are right this would be a hard requirement which isn't necessarily what we want either. I am gonna recommend just closing this PR for now.

2024-08-27 20:33 UTC, mattrunyon commented
I think you could achieve this w/ a custom action that uses `github-script` ([info](https://github.com/actions/github-script)) and `github.rest.pulls.requestReviewers` ([docs](https://octokit.github.io/rest.js/v21/#pulls-request-reviewers))

If you want I can probably put that together pretty quickly. Seems pretty straightforward

2024-09-03 18:49 UTC, dsmmcken commented
Re-closing, we've decided we didn't want a blocking code owner as part of this repos workflow.

We did add an action though that adds you as a reviewer for any docs changes automatically. 

See:
#778

2024-09-03 18:49 UTC, closed without merging