docs: ui.table
deephaven/deephaven-plugins pull request #776
Opened 2024-08-27 21:48 UTC by mattrunyon

Fixes #750

First pass at ui.table docs. I only added sections for more complex props right now. Wasn't sure if we wanted a section dedicated to something like `reverse` which is a 1-2 sentence explanation and a boolean prop.

The props we've implemented that don't have their own sections
- quick_filters
- show_quick_filters
- show_search
- reverse

2024-08-28 18:53 UTC, dsmmcken requested changes
All props should be documented. For things that can be done by the engine, we should state why one might want to use the ui.table version of the same.

I would document quick_filters and show_filters for sure. Gives you a better place to talk about how quick filters work and why you might use them over a where statement on the table itself. like the desire to show the user that the filter is applied, and that they get initialized by the client back against the origin server, so in a multi-query scenario with URI tables, I believe the filter would be applied by the origin server of the table, where as a table filter would be applied by the parent server and have to copy the table.

For reverse, it's simple but still should be shown. Reverses the table and shows the table as reversed by the client.

2024-08-28 18:53 UTC, dsmmcken commented on plugins/ui/docs/components/table.md
> +You can listen for different user events on a `ui.table`. There is both a `press` and `double_press` event for `row`, `cell`, and `column`. These events typically correspond to a click or double clic
Do we have always fetch columns or whatever we were calling it? Should not that for row data you will only get columns within the users +/- horizontal viewport unless it's always fetched.

2024-08-28 18:53 UTC, dsmmcken commented on plugins/ui/docs/components/table.md
> +    hidden_columns=["random"]
I thought these had column names had been capitalized now.

2024-08-28 19:59 UTC, mattrunyon commented on plugins/ui/docs/components/table.md
> +You can listen for different user events on a `ui.table`. There is both a `press` and `double_press` event for `row`, `cell`, and `column`. These events typically correspond to a click or double clic
No we don't. Ya good call I forgot to mention the viewport limit for the retrieved data.

I think we should add `always_fetch_columns` next probably. It should be a very easy add

2024-08-29 16:48 UTC, mattrunyon commented on plugins/ui/docs/components/table.md
> +    hidden_columns=["random"]
Yep. I'm reopening #380 because I had an old version installed since we don't clean our build output before building. I accidentally installed 0.11.1 instead of 0.11.2 because I have both whls in my build directory

2024-08-29 19:58 UTC, dsmmcken requested changes
Tried to make it clear the operations are performed on the server still, but only at request time.

```
t.where("x = 10") # applied when query is run
ui.table(t, quick_filter={x : =10}) # applied when viewed by a client

2024-08-29 19:58 UTC, dsmmcken commented on plugins/ui/docs/components/table.md
> +Quick filters are an easy way to filter the table and show the user what filters are currently applied. These filters are applied by the client, so users may change the filters without affecting othe
```suggestion
Quick filters are an easy way to filter the table while also showing the user what filters are currently applied. These filters are still applied by the server, but at request time by the client, so users may change the filters without affecting other users. Unlike a `where` statement to filter a table on the server, quick filters can be easily changed by the user.
```

2024-08-29 19:58 UTC, dsmmcken commented on plugins/ui/docs/components/table.md
> +The table can be displayed in reverse order using the `reverse` prop. The reverse will be performed on the client and indicated to the user via a bar under the column headers. Users can disable the r
```suggestion
The table can be displayed in reverse row order using the `reverse` prop. Using the reverse prop visually indicates to the user that table is reversed via a colored bar under the column headers.  Users will able to disable the reverse with the column header context menu or via shortcut. The reverse will be applied on the server at request time by the client.
```

2024-08-29 20:57 UTC, mattrunyon commented
If a `where` is within the component, it's also only performed at request time because the render function isn't called until a client tries to view the widget.

2024-08-30 16:28 UTC, dsmmcken commented
> If a where is within the component, it's also only performed at request time because the render function isn't called until a client tries to view the widget.

That's also true, yes. We should probably cover that aspect in a different general purpose doc.

2024-08-30 16:30 UTC, dsmmcken reviewed
Approved, but pending @margaretkennedy review first

2024-09-04 12:20 UTC, margaretkennedy submitted a review, later dismissed

2024-09-05 20:41 UTC, dsmmcken submitted a review, later dismissed

2024-09-09 15:32 UTC, dsmmcken approved these changes

2024-09-09 15:35 UTC, merged