feat: Add watch mode to `plugin_builder.py`
deephaven/deephaven-plugins pull request #777
Opened 2024-08-28 16:40 UTC by jnumainville

Fixes #632 
Adds a `--watch` mode to `plugin_builder.py`
This goes beyond just editable installs with the goal of automatically running any command that is reasonable to rerun (not config, for example). So this can also be used to rebuild `--docs` automatically, and could rerun tests once I add those in, etc. 
Some of the rerun detection is crude in that "any" file anywhere in the plugins repo will trigger a rerun, but since this is a development script I don't see that as a blocker. It's reasonable that we would run the script in a way that hones in on only building what we want.
Some examples are in the readme

2024-08-28 19:49 UTC, jnumainville commented on tools/plugin_builder.py
> +IGNORE_REGEXES = [
That's an interesting idea - to hook in the `.gitignore` directly. Seems possible, but clunky at best and I'd need to investigate further. https://stackoverflow.com/questions/41130632/is-there-an-easy-way-to-match-files-against-gitignore-rules
For now though, I think a comment will do.

2024-08-28 20:07 UTC, jnumainville commented on tools/plugin_builder.py
> +IGNORE_REGEXES = [
ok it's actually not that clunky
https://git-scm.com/docs/git-check-ignore
integrating it now

2024-08-28 21:57 UTC, jnumainville commented on tools/plugin_builder.py
> +IGNORE_REGEXES = [
Ok, so I did try it out, but unfortunately ran into some issues.
Here's the code I had in `on_any_event`, for the sake of possibly revisiting this someday
```
# if a file is .gitignored, do not rerun
# dump the output to /dev/null to prevent printing to the console
check_ignore = os.system(f"git check-ignore {event.src_path} > /dev/null")
if check_ignore != 256:
    # git check-ignore returns 1 if the file is not ignored
    # 256 is python's way of returning 1 from a system call
    return
```
The problem is `on_any_event` runs in the main thread, so checking every built file against this check was congesting the main thread, causing inability 
I *could* create a bunch of threads or some sort of batching to handle this so that the checks can be ran off the main thread, but that's also a lot of overhead and complexity for something that works well enough, although with slightly more maintenance, when done through `watchdog`
So for now, I'll stick with the comment, and if we're really running into cases we have lots of infinite loops where we have to keep adding regexes to this script, it can be revisited.

2024-08-28 23:03 UTC, mofojed commented on tools/plugin_builder.py
> +IGNORE_REGEXES = [
Wasn't thinking about infinite loops at all - is that when the directory structure is symlinked?

2024-08-28 23:05 UTC, mofojed requested changes

2024-08-28 23:05 UTC, mofojed commented on .gitignore
> +
```suggestion
# When adding new files here, consider adding them to `tools/plugin_builder.py` as well.
# particularly for large build directories with lots of files or directories with sym links in a circular structure that may cause infinite loops
```

2024-08-28 23:05 UTC, mofojed commented on tools/plugin_builder.py
> +# njnhnuunnhunnuu
```suggestion
```

2024-08-29 14:35 UTC, jnumainville commented on tools/plugin_builder.py
> +IGNORE_REGEXES = [
since this script is listening to every file change in the plugins repo, if a change is made to a file by the script, it will trigger another rerun, which changes that file again, which triggers another rerun, etc. (if not filtered out)

2024-08-29 16:35 UTC, mofojed requested changes

2024-08-29 16:35 UTC, mofojed commented on tools/plugin_builder.py
> +        Handle any file system event
We need to filter on event type, it seems to be stuck in a loop for me because the "opened" event keeps firing.

2024-08-29 16:35 UTC, mofojed requested changes
We need to filter on event type, it seems to be stuck in a loop for me because the "opened" event keeps firing.

2024-08-29 17:20 UTC, jnumainville commented
I've narrowed the events to deleted, modified, created, and moved. Let me know if it works now @mofojed

2024-08-29 18:07 UTC, jnumainville commented on tools/plugin_builder.py
> +            self.stop_event.clear()
`rerun_lock` shouldn't be acquired until `deephaven server` has been killed as is... does killing `deephaven server` not properly kill the server? Moving the `process.kill()` here wouldn't really make a difference I think if that is the case. It seems to be killed properly for me. Are you seeing specific issues?

2024-08-29 21:20 UTC, jnumainville commented
Added in a few small improvements around generating docs as well.

2024-08-30 13:10 UTC, mofojed commented on tools/plugin_builder.py
> +            self.stop_event.clear()
I'm starting up with `python tools/plugin_builder.py --js --server --watch ui`, and when I make an edit to html.py, it re-builds, but it doesn't shut down the already running server. It actually stays open for a few seconds after this crash as well, so there may need to be some better handling as well.

```
(.venv) ➜  deephaven-plugins git:(632_editable) python tools/plugin_builder.py --js --server --watch ui                                                                                                                                                                              
Building JS for ui

> @deephaven/js-plugin-ui@0.20.0 build
> vite build

vite v4.1.5 building for production...
✓ 2796 modules transformed.
dist/style.css    0.08 kB │ gzip:  0.09 kB
dist/index.js   414.50 kB │ gzip: 86.99 kB
Running deephaven server
Starting Deephaven server...
1 compiler directives added
# Starting io.deephaven.python.server.EmbeddedServer
deephaven.cacheDir=/home/bender/.cache/deephaven
deephaven.configDir=/home/bender/.config/deephaven
deephaven.dataDir=/home/bender/.local/share/deephaven
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: searching for 'io.deephaven.internal.log.LoggerFactory'...
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: found 'io.deephaven.internal.log.LoggerFactorySlf4j'
Server started on port 10000
Deephaven is running at http://localhost:10000/?psk=71kxqg1cdxso with authentication type io.deephaven.authentication.psk.PskAuthenticationHandler
Press Control-C to exit
File /home/bender/dev/deephaven/iris-oss/deephaven-plugins/plugins/ui/src/deephaven/ui/components/html.py modified, new rerun scheduled
File /home/bender/dev/deephaven/iris-oss/deephaven-plugins/plugins/ui/src/deephaven/ui/components/html.py modified, rerun has already been scheduled
Building JS for ui

> @deephaven/js-plugin-ui@0.20.0 build
> vite build

vite v4.1.5 building for production...
✓ 2796 modules transformed.
dist/style.css    0.08 kB │ gzip:  0.09 kB
dist/index.js   414.50 kB │ gzip: 86.99 kB
Running deephaven server
Starting Deephaven server...
1 compiler directives added
# Starting io.deephaven.python.server.EmbeddedServer
deephaven.cacheDir=/home/bender/.cache/deephaven
deephaven.configDir=/home/bender/.config/deephaven
deephaven.dataDir=/home/bender/.local/share/deephaven
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: searching for 'io.deephaven.internal.log.LoggerFactory'...
# io.deephaven.internal.log.LoggerFactoryServiceLoaderImpl: found 'io.deephaven.internal.log.LoggerFactorySlf4j'
Traceback (most recent call last):
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/bin/deephaven", line 8, in <module>
    sys.exit(cli())
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/deephaven_server/cli.py", line 37, in server
    s.start()
  File "/home/bender/dev/deephaven/iris-oss/deephaven-plugins/.venv/lib/python3.10/site-packages/deephaven_server/server.py", line 175, in start
    self.j_server.start()
RuntimeError: java.io.IOException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:10000
        at io.deephaven.server.jetty.JettyBackedGrpcServer.start(JettyBackedGrpcServer.java:249)
        at io.deephaven.server.runner.DeephavenApiServer.run(DeephavenApiServer.java:216)
        at io.deephaven.python.server.EmbeddedServer.start(EmbeddedServer.java:142)
caused by java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:10000
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304)
        at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.eclipse.jetty.server.Server.doStart(Server.java:398)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at io.deephaven.server.jetty.JettyBackedGrpcServer.start(JettyBackedGrpcServer.java:245)
        ... 2 more
caused by java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:459)
        at java.base/sun.nio.ch.Net.bind(Net.java:448)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339)
        ... 17 more
```

2024-08-30 13:17 UTC, mofojed commented on tools/plugin_builder.py
> +            self.stop_event.clear()
I added some extra debug statements, and you are correct, it looks like `process.kill` _is_ being called... but I'm seeing the server stay up for some time.
Debug statements added:
```
diff --git a/tools/plugin_builder.py b/tools/plugin_builder.py
index 712e9971..ea0b3858 100644
--- a/tools/plugin_builder.py
+++ b/tools/plugin_builder.py
@@ -397,15 +397,19 @@ def handle_args(
 
         # waiting on either the process to finish or the stop event to be set
         while not stop_event.wait(1):
+            click.echo("Polling deephaven server")
             poll = process.poll()
             if poll is not None:
+                click.echo("Error thrown")
                 # process threw an error or was killed, so exit
                 os._exit(process.returncode)
 
         # stop event is set, so kill the process
         try:
+            click.echo("Waiting for deephaven server to exit")
             process.wait(timeout=1)
         except subprocess.TimeoutExpired:
+            click.echo("Killing deephaven server")
             process.kill()
```
And then in the terminal I see:
```
Server started on port 10000
Deephaven is running at http://localhost:10000/?psk=10u4hgwbd5ft5 with authentication type io.deephaven.authentication.psk.PskAuthenticationHandler
Press Control-C to exit
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
Polling deephaven server
File /home/bender/dev/deephaven/iris-oss/deephaven-plugins/plugins/ui/src/deephaven/ui/components/html.py modified, new rerun scheduled
File /home/bender/dev/deephaven/iris-oss/deephaven-plugins/plugins/ui/src/deephaven/ui/components/html.py modified, rerun has already been scheduled
Waiting for deephaven server to exit
Killing deephaven server              <----- Server should be killed....
Building JS for ui

> @deephaven/js-plugin-ui@0.20.0 build
> vite build
....
.... crashes after hits, server is still up
```

2024-08-30 14:59 UTC, jnumainville commented on tools/plugin_builder.py
> +            self.stop_event.clear()
Maybe a more graceful exit that actually waits on the server process to terminate?
```
while process.poll() is None:
    try:
        process.terminate()
        process.wait(timeout=1)
    except subprocess.TimeoutExpired:
        process.kill()
```

2024-08-30 15:04 UTC, mofojed commented on tools/plugin_builder.py
> +            self.stop_event.clear()
I tried that to, the added `.wait` after the `.kill` doesn't seem to wait on anything. For ref I'm on Linux, I haven't tried this on my MacBook yet. Is this working for you? You're on Mac, yeah?

2024-08-30 15:05 UTC, jnumainville commented on tools/plugin_builder.py
> +            self.stop_event.clear()
we should probably have it like that anyways so I added it

2024-08-30 15:06 UTC, jnumainville commented on tools/plugin_builder.py
> +            self.stop_event.clear()
yeah, this is working for me on mac... super weird, it shouldn't continue until the wait is done

2024-08-30 15:23 UTC, jnumainville commented on tools/plugin_builder.py
> +            self.stop_event.clear()
we also didn't need `shell=True` for the process... that could help

2024-08-30 20:29 UTC, jnumainville commented
Added "--no-browser" as well, I considered having it open on first load then "--no-browser" on subsequent but I don't think that really helps because of the need for a new token anyways. Easy enough to click on the link only when wanted.

2024-09-04 14:19 UTC, mofojed approved these changes
Seems to be working correctly now!
I think we could improve the flags we pass through to the server, at least having a way to set a port and a consistent key (or anonymous mode) would be very useful.

2024-09-04 18:10 UTC, jnumainville commented on tools/plugin_builder.py
> +        process = subprocess.Popen(["deephaven", "server", "--no-browser"])
So I added the `--no-params` after demoing this in the meeting because others seemed to find it more annoying that it would open up tons of tabs... I think I'm in agreement with that case as more annoying, especially if making lots of changes. What I'd really like is refreshing the currently open tab with the new key, but that's external to this script.
I agree it would be nice to provide some custom set of args
Unfortunately, after playing around with this, adding args to `--server` makes other use cases harder, because it conflicts with usage as a simple flag. So I'm thinking something like `--server-args` which would require a set of args, and would start the server as well.

2024-09-04 21:04 UTC, jnumainville commented on tools/plugin_builder.py
> +        process = subprocess.Popen(["deephaven", "server", "--no-browser"])
Turns out that solution would have been much more complex to implement and quite fragile due to the fact that we can't just use `shell=True`
There's some examples in the readme, but I think this `--server-arg/-sa` multiple arg is the best way to do it. No need for the quote escape, and you don't need to pass a single string, instead you pass each arg individually, which means you can pass them in any order. Finicky in a different way since you need to pass each arg, but I think is nicer as it more closely resembles "natively" supporting the server args that can be passed in without the maintenance of actually supporting them.

2024-09-04 21:13 UTC, mofojed commented on tools/plugin_builder.py
> +        process = subprocess.Popen(["deephaven", "server", "--no-browser"])
Yup I like that, that works. Good stuff.
For the record, working on the UI I'm running with:
```
python tools/plugin_builder.py --js --reinstall --server --server-arg --jvm-args="-DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler" --watch ui
```
I know the flags could be shortened, but this allows flexibility and works so I'm happy with it

2024-09-04 21:13 UTC, mofojed approved these changes

2024-09-04 21:21 UTC, merged