docs: use_memo docs
deephaven/deephaven-plugins pull request #779
Opened 2024-08-28 19:58 UTC by mofojed

- Add docs for use_memo
- Give some examples of using memoization, and recommendations of when to use it and when not to use it

2024-08-29 20:23 UTC, dsmmcken requested changes

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +`use_memo` is a hook to memoize a value. This is useful when you have a value that is expensive to compute, and you want to avoid re-computing it on every render. The value is computed once, and then
You say value, but is it better to say function?

I would also like to explicitly call out that if you a manipulating tables they probably should be memoized.

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +result = ui_todo_list(["Buy milk", "Walk the dog", "Do laundry"], "laundry")
```suggestion
from deephaven import ui


@ui.component
def ui_todo_list(todos: list[str], filter: str):
    filtered_todos = ui.use_memo(
        lambda: [todo for todo in todos if filter in todo], [todos, filter]
    )

    return [
        ui.text(f"Showing {len(filtered_todos)} of {len(todos)} todos"),
        *[ui.checkbox(todo) for todo in filtered_todos],
    ]


result = ui_todo_list(["Do grocery shopping", "Walk the dog", "Do laundry"], "Do")
```

I ran this and was initially confused what I was looking at. Added of len, and filtered by something that results in 2 of 3

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +
Should explicitly mention queries.

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        import time
importing time here seems gross, and not at the top?

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        time.sleep(min(len(search) + 1, 3))
```suggestion
        # Simulate delay
        time.sleep(2)
```

Unnecessary complexity in example that doesn't aid in understanding

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +theme_options = ["accent", "positive", "negative"]
```suggestion
# theme colors
theme_options = ["accent-200", "red-200", "green-200"]
```

bad contrast in light

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        ui.picker(*theme_options, selected_key=theme, on_change=set_theme),
```suggestion
        ui.text_field(value=search, label="Search", on_change=set_search),
        ui.picker(*theme_options, label="Theme", selected_key=theme, on_change=set_theme),
```

Or UX recommendations say to always label things or provide an aria-label.

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        background_color=theme,
```suggestion
        padding="size-200",
        background_color=theme,
```

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +from deephaven import ui
Apply previous suggestions

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +`use_memo` is a hook, and like any other hook, can only be called at the top level of a component. Suppose you are listing a number of items, and you want them to be memoized individually. However, y
Mention it will throw an error if component runs with different number of hooks or something.

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +theme_options = ["accent", "positive", "negative"]
use colors from above that work for light as well

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        ui.picker(*theme_options, selected_key=theme, on_change=set_theme),
label

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +    return ui.view(*[ui_fibonacci_item(i) for i in range(n)], background_color=theme)
padding

2024-08-29 20:23 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +
We should probably include the example with a table query as the second example, as it will likely be one of the most common use cases.

2024-09-03 20:01 UTC, mofojed commented on plugins/ui/docs/hooks/use_memo.md
> +
I'm adding a case with a `time_table`, so it's clear that the table is getting re-computed... I tried some examples with join/merge etc but they were all fairly quick already, it was hard to demonstrate why.

2024-09-05 17:48 UTC, dsmmcken requested changes

2024-09-05 17:48 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        flex_grow=1,
```suggestion
        align_self="stretch",
        flex_grow=1,
```

2024-09-05 17:48 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +        flex_grow=1,
```suggestion
        align_self="stretch",
        flex_grow=1,
```


We added align_items start by default on flex to prevent buttons from going ________________ weee________ but has the problem of causing non-buttons to not stretch.

2024-09-05 17:48 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +from deephaven import time_table, ui
I wonder if a more real example would work better of when I should an shouldn't memoize a query.

Also time tables will suck to auto generate screenshots.

Like _stocks

and memoize the rollup but not a filter?

with an option to selct rollup on sym or exchange and filter free-form?

2024-09-05 17:48 UTC, dsmmcken commented on plugins/ui/docs/hooks/use_memo.md
> +`use_memo` is a hook to cache the result of a calculation. This is useful when you have a value that is expensive to compute and you want to avoid re-computing it on every render. The value is comput
Is calculation the right word? The result of a calculation, function or table reference (handle?)?

2024-09-06 13:59 UTC, mofojed commented on plugins/ui/docs/hooks/use_memo.md
> +from deephaven import time_table, ui
The problem with rollups and filters is that they are both memoized by the engine, so it doesn't really demonstrate _why_ you need to memoize (since it's already memoized).
`_stocks` would have same issue as `time_table` for screenshots?

2024-09-06 14:00 UTC, mofojed commented on plugins/ui/docs/hooks/use_memo.md
> +`use_memo` is a hook to cache the result of a calculation. This is useful when you have a value that is expensive to compute and you want to avoid re-computing it on every render. The value is comput
Straight from the react.dev docs: https://react.dev/reference/react/useMemo

I could add some synonyms there.

2024-09-09 15:31 UTC, dsmmcken approved these changes
Needs conflicts resolved.

2024-09-09 17:03 UTC, margaretkennedy approved these changes

2024-09-13 13:27 UTC, dsmmcken approved these changes

2024-09-13 14:01 UTC, margaretkennedy approved these changes

2024-09-13 14:27 UTC, merged