docs: flex
deephaven/deephaven-plugins pull request #785
Opened 2024-08-29 21:33 UTC by ethanalvizo

Closes #688

2024-08-30 14:29 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `row` (default): the flex items are arranged horizontally from left to right
I like periods at the ends of bullets.

2024-08-30 14:30 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +Flexboxes can be nested to create more complicated layouts. By using the `flex` prop on the children, it can expand to fill the remaining space.
```suggestion
Flexboxes can be nested to create more complicated layouts. By using the `flex` prop on the children, the flexbox can expand to fill the remaining space.
```

2024-08-30 14:30 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +The `alignItems` prop can be utilized to align items along the cross axis. When the direction is set to "column", it controls horizontal alignment, and when the direction is set to "row", it controls
```suggestion
The `alignItems` prop can align items along the cross-axis. When the direction is set to "column", it controls horizontal alignment, and when it is set to "row", it controls vertical alignment.
```

2024-09-03 15:22 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +The `alignItems` prop can align items along the cross-axis. When the direction is set to "column", it controls horizontal alignment, and when it is set to "row", it controls vertical alignment.
```suggestion
The `alignItems` prop aligns items along the cross-axis. When the direction is set to "column", it controls horizontal alignment, and when it is set to "row", it controls vertical alignment.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `stretch` (default): the flex items are stretched to fill the container along the cross axis
```suggestion
- `stretch` (default): the flex items are stretched to fill the container along the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `start`: the flex items are aligned at the start of the cross axis
```suggestion
- `start`: the flex items are aligned at the start of the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `end`: the flex items are aligned at the end of the cross axis
```suggestion
- `end`: the flex items are aligned at the end of the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `center`: the flex items are centered along the cross axis
```suggestion
- `center`: the flex items are centered along the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `self-start`: the flex items are aligned at the start of their container
```suggestion
- `self-start`: the flex items are aligned at the start of their container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `self-end`: the flex items are aligned at the end of their container
```suggestion
- `self-end`: the flex items are aligned at the end of their container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `baseline`: the flex items are aligned based on their baselines
```suggestion
- `baseline`: the flex items are aligned based on their baselines.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `first baseline`: the flex items are aligned based on the first baseline of the container
```suggestion
- `first baseline`: the flex items are aligned based on the first baseline of the container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `last baseline`: the flex items are aligned based on the last baseline of the container
```suggestion
- `last baseline`: the flex items are aligned based on the last baseline of the container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `safe center`: the flex items are centered along the cross axis, ensuring they remain within the safe area
```suggestion
- `safe center`: the flex items are centered along the cross axis, ensuring they remain within the safe area.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `unsafe center`: the flex items are centered along the cross axis, without considering the safe area
```suggestion
- `unsafe center`: the flex items are centered along the cross-axis without considering the safe area.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +The `justifyContent` prop aligns items along the main axis. For a "column" direction, it controls vertical alignment, and for a "row" direction, it controls horizontal alignment.
```suggestion
The `justifyContent` prop aligns items along the main axis. "Column" direction controls vertical alignment, and "row" direction controls horizontal alignment.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +The `justifyContent` prop aligns items along the main axis. For a "column" direction, it controls vertical alignment, and for a "row" direction, it controls horizontal alignment.
does this capture the same meaning?

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `stretch` (default): the flex items are stretched to fill the container along the cross axis
```suggestion
- `stretch` (default): the flex items are stretched to fill the container along the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `start`: the flex items are aligned at the start of the cross axis
```suggestion
- `start`: the flex items are aligned at the start of the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `end`: the flex items are aligned at the end of the cross axis
```suggestion
- `end`: the flex items are aligned at the end of the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `center`: the flex items are centered along the cross axis
```suggestion
- `center`: the flex items are centered along the cross-axis.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `left`: the flex items are packed toward the left edge of the container
```suggestion
- `left`: the flex items are packed toward the left edge of the container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `right`: the flex items are packed toward the right edge of the container
```suggestion
- `right`: the flex items are packed toward the right edge of the container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `space-between`: the flex items are evenly distributed with the first item at the start and the last item at the end
```suggestion
- `space-between`: the flex items are evenly distributed with the first item at the start and the last item at the end.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `space-around`: the flex items are evenly distributed with equal space around them
```suggestion
- `space-around`: the flex items are evenly distributed with equal space around them.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `space-evenly`: the flex items are evenly distributed with equal space between them
```suggestion
- `space-evenly`: the flex items are evenly distributed with equal space between them.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `baseline`: the flex items are aligned based on their baselines
```suggestion
- `baseline`: the flex items are aligned based on their baselines.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `first baseline`: the flex items are aligned based on the first baseline of the container
```suggestion
- `first baseline`: the flex items are aligned based on the first baseline of the container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `last baseline`: the flex items are aligned based on the last baseline of the container
```suggestion
- `last baseline`: the flex items are aligned based on the last baseline of the container.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `safe center`: the flex items are centered along the cross axis, ensuring they remain within the safe area
```suggestion
- `safe center`: the flex items are centered along the cross-axis, ensuring they remain within the safe area.
```

2024-09-03 15:38 UTC, margaretkennedy commented on plugins/ui/docs/components/flex.md
> +- `unsafe center`: the flex items are centered along the cross axis, without considering the safe area
```suggestion
- `unsafe center`: the flex items are centered along the cross-axis without considering the safe area.
```

2024-09-05 20:39 UTC, dsmmcken requested changes
some of these examples cause bad overflow, which isn't your fault but they still look bad. I am down a rabbit hole on seeing if there's a global fix.

2024-09-06 03:35 UTC, ethanalvizo commented on plugins/ui/docs/components/flex.md
> +The `justifyContent` prop aligns items along the main axis. For a "column" direction, it controls vertical alignment, and for a "row" direction, it controls horizontal alignment.
I think "column" and "row" might be misinterpreted as values for the justify_content prop rather than an external factor that dictates how justify_content behaves but I didn't make that clear in my original phrasing either. I've reworded it to the following to convey that message more clearly:

_The `justify_content` prop is used to align items along the main axis. When the direction is set to "column", it controls the vertical alignment, and when the direction is set to "row", it controls the horizontal alignment._

Will defer to @dsmmcken for this one

2024-09-24 20:02 UTC, mofojed commented
@ethanalvizo can you separate the flex.py changes into their own PR so they can be merged to fix #824? Docs could still use more work but want to merge the flex props changes

2024-09-27 03:29 UTC, ethanalvizo commented
Should be merged after #912 since that contains the flex pydocs in this PR

2024-09-30 21:07 UTC, dsmmcken requested changes
please rebase/merge main so I can review against new panel overflow behaviour

2024-10-18 13:55 UTC, ethanalvizo commented
https://github.com/deephaven/deephaven-plugins/pull/814#discussion_r1784750389
@dsmmcken a comment from Matt regarding whether or not row/col behaviour should be mentioned in these flex docs

2024-11-01 20:48 UTC, dsmmcken requested changes

2024-11-01 20:48 UTC, dsmmcken commented on plugins/ui/docs/components/flex.md
> +    )
```suggestion
    return ui.flex(
        ui.view(1, background_color="red", height="size-800", width="size-800"),
        ui.view(2, background_color="green", height="size-800", width="size-800"),
        ui.view(3, background_color="blue", height="size-800", width="size-800"),
    )
```

I would add numbers to these so when you start flipping them around it's easier to follow the result of the changes. Would also need to change the yellow to blue so the text remains readable. Make that change through-out.

2024-11-01 20:48 UTC, dsmmcken commented on plugins/ui/docs/components/flex.md
> +        ),
```suggestion
    return [
       'direction="row"',
        ui.flex(
            ui.view(background_color="red", height="size-800", width="size-800"),
            ui.view(background_color="green", height="size-800", width="size-800"),
            ui.view(background_color="yellow", height="size-800", width="size-800"),
        ),
        'direction="row-reverse"',
        ui.flex(
            ui.view(background_color="red", height="size-800", width="size-800"),
            ui.view(background_color="green", height="size-800", width="size-800"),
            ui.view(background_color="yellow", height="size-800", width="size-800"),
            direction="row-reverse",
        ),
```

I would add a label before each of these sections through out the doc, it's easy to lose track

2024-11-01 20:48 UTC, dsmmcken commented on plugins/ui/docs/components/flex.md
> +    horizontal = ui.flex(
break this into two example blocks, I am fine with in the same section, just looks confusing with some many results together.

2024-11-01 20:48 UTC, dsmmcken commented on plugins/ui/docs/components/flex.md
> +        width="500px",
This width 500 seems unnecessary

2024-11-01 20:48 UTC, dsmmcken commented on plugins/ui/docs/components/flex.md
> +## Justification
Can you make this come before the previous section? Seems like we should document main axis before cross axis?

2024-11-01 20:48 UTC, dsmmcken commented on plugins/ui/docs/components/flex.md
> +def flex():
can you add a few more of the value in here, space-between and space-around?

2024-11-04 16:05 UTC, dsmmcken approved these changes

2024-11-04 21:15 UTC, margaretkennedy approved these changes

2024-11-05 14:38 UTC, merged