docs: ui.switch
deephaven/deephaven-plugins pull request #793
Opened 2024-09-03 14:12 UTC by AkshatJawne

Closes #771

2024-09-03 19:27 UTC, dsmmcken requested changes

2024-09-03 19:27 UTC, dsmmcken commented on plugins/ui/docs/components/slider.md
> +
why is this change in this review?

2024-09-03 19:27 UTC, dsmmcken commented on plugins/ui/docs/components/switch.md
> +Consider using a [`checkbox`](./checkbox.md) for individual selections or when marking a single item as selected. For a set of related options, use a [`checkbox_group`](./checkbox_group.md) to manage
Re-write based on https://spectrum.adobe.com/page/switch/#Usage-guidelines for suggestions that are more relevant

2024-09-04 14:25 UTC, AkshatJawne commented on plugins/ui/docs/components/slider.md
> +
Just noticed that there was an empty line missing, so thought I could add it here, since it isn't that major of a change.

2024-09-05 17:21 UTC, dsmmcken requested changes

2024-09-05 17:21 UTC, dsmmcken commented on plugins/ui/docs/components/switch.md
> +1. Emphasized switches are ideal for forms and settings where the switch being noticed is crucial, while non-emphasized switches suit monochrome application panels to maintain focus on the canvas.
```suggestion
1. Emphasized switches are ideal for forms and settings where the switch being noticed is crucial, while non-emphasized switches suit monochrome application panels to maintain focus on the content.
```

2024-09-05 17:21 UTC, dsmmcken commented on plugins/ui/docs/components/switch.md
> +4. When a switch represents multiple differing values, it should initially appear unselected; clicking it will select and unify all values, while a subsequent click will deselect and reset them.
```suggestion
4. When a switch represents multiple values from other switches, it should initially appear unselected; clicking it will select and unify all values, while a subsequent click will deselect and reset them.
```

2024-09-05 17:21 UTC, dsmmcken commented on plugins/ui/docs/components/switch.md
> +Consider using a [`checkbox`](./checkbox.md) for individual selections or when marking a single item as selected. For a set of related options, use a [`checkbox_group`](./checkbox_group.md) to manage
```suggestion
Consider using a [`checkbox`](./checkbox.md) for individual selections or when marking a single item as selected.
```

The other two links seem less relevant.

2024-09-09 15:29 UTC, dsmmcken submitted a review, later dismissed

2024-09-09 15:29 UTC, dsmmcken commented
Still needs @margaretkennedy review though

2024-09-09 16:58 UTC, margaretkennedy approved these changes

2024-09-10 14:29 UTC, merged