fix: text_area on_key_down throws errors
deephaven/deephaven-plugins pull request #798
Opened 2024-09-04 17:39 UTC by wusteven815

2024-09-04 20:24 UTC, mofojed requested changes
Minor correction with the comment about what prop types are returned, and a suggestion to fix a couple other callbacks. Can be spun off in a separate PR.

2024-09-04 20:24 UTC, mofojed commented on plugins/ui/src/js/src/elements/hooks/useTextAreaProps.ts
> +// returns SpectrumButtonProps
```suggestion
// returns SpectrumTextAreaProps
```

2024-09-04 20:24 UTC, mofojed commented on plugins/ui/src/js/src/elements/hooks/useTextAreaProps.ts
> +  const onFocus = useFocusEventCallback(propOnFocus);
I just noticed something that we should fix in `useFocusEventCallback`, `useKeyboardEventCallback`, and event `useDebouncedOnChange`. Initially found an issue with forms, when we were always returning a callback even if the user didn't set one: https://github.com/deephaven/deephaven-plugins/issues/625
The resolution was to return `undefined` instead of a callback if the user did not pass in a callback: https://github.com/deephaven/deephaven-plugins/blob/2558551036bca8146349588b1b6b66ecba917b46/plugins/ui/src/js/src/elements/hooks/useFormEventCallback.ts#L24
We should do the same in the other `use*Callback` methods - I'm not aware of any issues it is causing, but it's possible that a component changes behaviour whether it has a callback passed in or not, so we shouldn't always pass a callback in - only wrap a callback if the user actually passed a callback in.

Instead of:
```typescript
export function usePressEventCallback(...) {
  return useCallback(...);
}
```

It'd be like:
```typescript
export function usePressEventCallback(...) {
  const pressCallback = useCallback(...);
  return callback != null ? pressCallback : undefined;
}
```

2024-09-05 14:05 UTC, wusteven815 commented on plugins/ui/src/js/src/elements/hooks/useTextAreaProps.ts
> +  const onFocus = useFocusEventCallback(propOnFocus);
To clarify about `useDebouncedOnChange`'s `onChange` callback - should the new "undefined" value of `propOnChange` change from `EMPTY_FUNCTION` to `undefined`?

2024-09-05 17:07 UTC, mofojed requested changes

2024-09-05 17:07 UTC, mofojed commented on plugins/ui/src/js/src/elements/hooks/useKeyboardEventCallback.ts
>  ): DeserializedKeyboardEventCallback {
I'd rather return `DeserializedKeyboardEventCallback | undefined` here rather than baking the `| undefined` into the type.
Ditto with `DeserializedFocusEventCallback`

2024-09-06 18:00 UTC, mofojed submitted a review, later dismissed

2024-09-06 18:02 UTC, mofojed commented on plugins/ui/src/js/src/elements/hooks/useTextAreaProps.ts
> +  const onFocus = useFocusEventCallback(propOnFocus);
For `useDebouncedOnChange`, `propOnChange` should allow `undefined` to be passed in, and we shouldn't be initializing to `EMPTY_FUNCTION` in the components. (Ultimately that would be equivalent to treating `EMPTY_FUNCTION` as `undefined`, but that's a more roundabout way)

2024-09-06 19:18 UTC, mofojed approved these changes

2024-09-06 19:32 UTC, merged