Text field docs
deephaven/deephaven-plugins pull request #802
Opened 2024-09-05 13:52 UTC by AkshatJawne

Closes #770

2024-09-05 14:00 UTC, margaretkennedy commented on plugins/ui/docs/components/text_field.md
> +3. A text field should not use `is_quiet` styling if it has a fixed height, given that the field underline may be too far from the text to be considered part of the component.
I am not sure what the field underline is; however, if the typical user knows, you might not need an explanation.

2024-09-05 14:01 UTC, margaretkennedy commented on plugins/ui/docs/components/text_field.md
> +A text field's value is empty by default, but an initial, uncontrolled, value can be set using the `default_value` prop, or, a controlled value can be set via the `value` prop.
```suggestion
A text field's value is empty by default, but the `default_value` prop can set an initial, uncontrolled value, or a controlled value can be set via the `value` prop.
```

2024-09-05 14:04 UTC, margaretkennedy commented on plugins/ui/docs/components/text_field.md
> +By setting `is_required` to True, the `necessity_indicator` is set to "icon" by default, but this can be changed. Also, the `necessity_indicator` can be used indepdendently to indicate that the text
```suggestion
By setting `is_required` to True, the `necessity_indicator` is set to "icon" by default, but this can be changed. The `necessity_indicator` can also be used independently to indicate that the text field is optional.
```

2024-09-05 14:09 UTC, AkshatJawne reviewed
Ready for re-review @margaretkennedy

2024-09-05 15:46 UTC, margaretkennedy submitted a review, later dismissed

2024-09-05 18:23 UTC, mofojed submitted a review, later dismissed

2024-09-05 18:23 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/text_field.py
> +    Returns:
The CI action is throwing an error because `aria_labelled_by` in the docstring doesn't match the param name `aria_labelledby`. It should be `aria_labelledby`

2024-09-05 21:14 UTC, dsmmcken requested changes
I would change all the email examples to not be emails, as they should all have type="email" otherwise.

I think it's worth adding both a recommendation and an example showing the different types enumerated.

2024-09-06 14:15 UTC, AkshatJawne commented
@dsmmcken  For your comment: 

> I think it's worth adding both a recommendation and an example showing the different types enumerated.

Do you think this should be added to the form example, I think it could make sense, but I also see us separating this into its own example.

2024-09-09 15:18 UTC, dsmmcken commented
It's own section, `## Input Types` or something

2024-09-10 18:47 UTC, dsmmcken submitted a review, later dismissed

2024-09-10 19:46 UTC, margaretkennedy submitted a review, later dismissed
Please review the few suggestions but I approve conditionally

2024-09-10 19:46 UTC, margaretkennedy commented on plugins/ui/docs/components/text_field.md
> +Text fields are single-line text inputs, ideal for cases where users have a smaller amount of text to enter.
```suggestion
Text fields are single-line text inputs, ideal for cases where users have a small amount of text to enter.
```

2024-09-10 19:46 UTC, margaretkennedy commented on plugins/ui/docs/components/text_field.md
> +Text field's can support a `name` prop for integration with HTML forms, allowing for easy identification of a value on form submission.
```suggestion
Text fields can support a `name` prop for integration with HTML forms, allowing for easy identification of a value on form submission.
```

2024-09-10 19:46 UTC, margaretkennedy commented on plugins/ui/docs/components/text_field.md
> +The `type` prop can be used to change the type of text field to render to suit different input requirements.
```suggestion
The `type` prop changes the type of text field that is rendered to suit different input requirements. 
```

2024-09-13 14:13 UTC, merged