fix: Don't strip new lines in dhautofunction
deephaven/deephaven-plugins pull request #805
Opened 2024-09-05 18:18 UTC by jnumainville

No longer removes lines, residual from before we were using a table and they were messing with the formatting I believe

2024-09-05 18:52 UTC, dsmmcken commented
That's not automatically going to fix it. HTML will ignore those new lines unless we preserve spaces.

You are already inserting it into the doc, which WILL preserve new lines as markdown.

I would just pull the description and returns parts from inside the <ParamTable> and insert them directly above.


```md

<insert description if exists> This will be treated as markdown here, so even links and stuff would work.

**Returns: ** <insert returns if exists>

<Paramtable withoth those two things/>
```

2024-09-06 17:01 UTC, jnumainville commented
would that give you less control though if we wanted to change things?
and what about new lines within the parameters?

2024-09-09 15:16 UTC, dsmmcken commented
It's still under "our" control, so it would be fine.

Are new lines in the parameters valid docstrings?

2024-09-09 15:48 UTC, jnumainville commented
I wasn't precise - it doesn't give less control overall, it splits a task into two parts, giving less control in the next step after this script.
I see this step as take code -> output processed data that can be used to build the presentation layer.
So doing part of the processing for the presentation layer is creating a poorer abstraction by mixing concerns, and if we want to change both the format of, for example, the returns block and the parameters table, that's now done in two different spots.
If there's something I can do to make the new lines easier to process in the presentation layer building, that makes sense, but ideally it's still data.

New lines in the docstring parameters are valid

2024-09-09 18:52 UTC, dsmmcken commented
That's the easiest way to get full md support in descriptions. You are inserting into the presentation layer.

inserting 

{result.description}

*Returns:( {result.returns}

<ParamTable restults={results dict} />

doesn't seem that different to me.

and um. actually description and returns aren't params anyways.

2024-09-09 19:34 UTC, jnumainville commented
My point is, currently, `ParamTable` handles all of the actual presentation.
`ParamTable` is meaningless without the presentation layer.
The suggested change would make it so some presentation is handled here, some presentation is handled elsewhere.
You are right in that it isn't *much* different, but it is an architectural difference, and I think the wrong change to make, because it adds overall complexity, even if "easier" to do. 
But, if it's what you think is best, it's what I'll do.

My concern about newlines in params still remains. 
See this example to clarify (note that in the code I've got in this PR there is a subtle regex bug currently, but below is what the parameters will look like)
{"name": "by", "type": "str | list[str] | None", "description": "A column or list of columns that contain values to plot the figure traces by.\nAll values or combination of values map to a unique design. The variable\nby_vars specifies which design elements are used.\nThis is overriden if any specialized design variables such as color are specified", "default": "None"}

2024-09-10 18:49 UTC, dsmmcken commented
Embed it please. I acknowledge it's less ideal on your side. However it will be more performant on the front end as it avoids having the user waiting for it to be parsed.

2024-09-13 15:00 UTC, mofojed requested changes

2024-09-13 15:00 UTC, mofojed commented on sphinx_ext/make_docs_utilities.py
> +from deephaven_autodoc import AUTOFUNCTION_COMMENT_PREFIX
Shouldn't this be `from .deephaven_autodoc` ?
```suggestion
from .deephaven_autodoc import AUTOFUNCTION_COMMENT_PREFIX
```

2024-09-13 15:00 UTC, mofojed commented on sphinx_ext/deephaven_autodoc.py
> +    return_type = result.pop("return_type")
Why pop them instead of just `result['return_description']`? Then you don't need to change the type to `total=False` on `SignatureData`, which doesn't seem correct.

2024-09-16 18:39 UTC, jnumainville commented on sphinx_ext/deephaven_autodoc.py
> +    return_type = result.pop("return_type")
my original thought was just to remove the data since it's not used anymore, but I suppose that doesn't really provide any benefit

2024-09-16 18:45 UTC, jnumainville commented on sphinx_ext/make_docs_utilities.py
> +from deephaven_autodoc import AUTOFUNCTION_COMMENT_PREFIX
this is how you import if there's no `__init__.py` in the directory (and there doesn't really need to be in this case)

2024-09-26 19:42 UTC, mofojed approved these changes

2024-09-30 20:05 UTC, dsmmcken commented on sphinx_ext/deephaven_autodoc.py
> +        rf"<ParamTable param={{{dat}}} />"
Are these <br/> actually inserted in output?"

If so, it's markdown, new lines are respected.

Also should this output be conditional? If no return type or no description?

2024-09-30 20:08 UTC, dsmmcken commented on sphinx_ext/deephaven_autodoc.py
> +        rf"<ParamTable param={{{dat}}} />"
![image](https://github.com/user-attachments/assets/bfd02d7f-65c1-43a5-a732-4b46b938230a)

I would expect output that looks more like this.

2024-09-30 20:29 UTC, jnumainville commented on sphinx_ext/deephaven_autodoc.py
> +        rf"<ParamTable param={{{dat}}} />"
I'll see if I can get sphinx to render newlines somehow with the nodes instead

2024-09-30 20:37 UTC, jnumainville commented on sphinx_ext/deephaven_autodoc.py
> +        rf"<ParamTable param={{{dat}}} />"
done, that seems to have the needed output

2024-10-15 17:10 UTC, dsmmcken approved these changes

2024-10-15 17:20 UTC, merged