fix: ui.radio value defaulting
deephaven/deephaven-plugins pull request #818
Opened 2024-09-11 15:54 UTC by AkshatJawne

Closes #765 

Impacted by Checkbox Group issue introduced in latest core

2024-09-13 14:53 UTC, AkshatJawne commented
Investigating failures

2024-09-18 14:39 UTC, mofojed requested changes

2024-09-18 14:39 UTC, mofojed commented on plugins/ui/src/js/src/elements/Radio.tsx
> +      value={value as string}
You need to pass `children` down to `DHRadio` as well, as you've pulled it out of `props`. That's why your e2e tests are failing.
Run the script from the ticket and you'll see the issue.

2024-09-18 20:45 UTC, mofojed requested changes

2024-09-18 20:45 UTC, mofojed commented on plugins/ui/src/js/src/elements/Radio.tsx
> +      value={value as string}
You shouldn't need `as string`, `value` is already a string by this point.

2024-09-18 20:45 UTC, mofojed commented on plugins/ui/src/js/src/elements/Radio.tsx
> +      children={children}
Instead of disabling the warning, just pass the children in normally:
```typescript
<DHRadio ...>{children}</DHRadio>
```

2024-09-18 21:36 UTC, mofojed approved these changes

2024-09-18 21:38 UTC, mofojed commented
@AkshatJawne to fix the tests I think you just need to merge in the latest `main`.

2024-09-19 04:33 UTC, AkshatJawne commented
@mofojed Appears that merging main did not change it, will investigate further

2024-09-21 07:39 UTC, merged