WIP: Number field
deephaven/deephaven-plugins pull request #827
Opened 2024-09-13 14:05 UTC by ethanalvizo

Closes #695 

@mofojed was having some trouble with the formatOptions prop. I created a specific component for NumberField to try to log the props but I'm not seeing anything so I'm not sure if I set up the component wrong. This is the code I was running in the terminal.

```
from deephaven import ui

@ui.component
def number_fields_example():

    return [
        ui.number_field(format_options="{style: 'percent'}"), 
        ui.number_field(format_options="{{style: 'percent'}}"),
        ui.number_field(format_options="{{currency: 'EUR'}}"),
    ]

my_number_fields = number_fields_example()
```

As for the original purpose of the ticket which was to allow decimal input, I was also a little confused. I'm able to input a decimal number. Is it the step buttons that we want to increment by decimal values? Currently if you input a decimal and then use either of the arrows it'll go to the nearest integer.

<img width="149" alt="image" src="https://github.com/user-attachments/assets/2d425683-e823-4176-95ce-e23b6d103ee8">

2024-09-13 14:39 UTC, mofojed requested changes
Weird, I could have sworn this wasn't working but indeed you can input a decimal. I should have included more details in the issue when I filed it.

In any case, we should still add these formatting options, to explicitly show the decimal, or to restrict to only an integer, etc.

2024-09-13 14:39 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/number_field.py
> +    format_options: str | None = None,
Should take a TypedDict

2024-09-26 14:43 UTC, mofojed requested changes

2024-09-26 14:43 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/types/number_field.py
Instead of putting this in a `types/number_field.py` file, can you put it in a `types/Intl/NumberFormatOptions.py`? Other components use these options as well (e.g. ProgressBar: https://react-spectrum.adobe.com/react-spectrum/ProgressBar.html#props)

And there may be more `Intl` things we add later.

2024-09-26 14:43 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/types/number_field.py
> +    options: NotRequired[Options]
The `NumberFormatOptions` should just be what you have as `Options` here.
Didn't really need to define `locales`, that's not really needed.

You can take a look at the TypeScript definitions for `NumberFormatOptions` in the TS definitions source code if that helps: https://github.com/microsoft/TypeScript/blob/3ad0f752482f5e846dc35a69572ccb43311826c0/src/lib/es2020.intl.d.ts#L243

2024-10-11 15:40 UTC, jnumainville requested changes

2024-10-11 15:40 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/types/Intl/number_field.py
> +    For more information see the supported numbering systems in the getNumberingSystems page on MDN.
might be worth adding a direct link -  would hope those MDN pages would be stable enough where it won't go stale any time soon

2024-10-11 15:40 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/types/Intl/number_field.py
> +number_systems = Literal[
Any reason these aren't PascalCase like `NumberSystems`?

2024-10-11 18:15 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/types/Intl/number_field.py
> +number_systems = Literal[
No no reason for these ones but for the props in the TypedDict I kept them snake case because that's how they would be defining the object in the terminal

2024-10-11 18:24 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/types/Intl/number_field.py
> +number_systems = Literal[
yeah in the `TypedDict` that's fine for the keys

2024-10-11 18:25 UTC, jnumainville approved these changes

2024-10-15 13:37 UTC, mofojed approved these changes

2024-10-15 20:32 UTC, merged