feat: ui.panel
deephaven/deephaven-plugins pull request #88
Opened 2023-10-12 21:44 UTC by mofojed

- Move logic to display an element into DashboardPlugin, so it can open multiple panels
- Basic ui.table `on_row_double_press` functionality added
- Added some examples
- Still needs my branch: https://github.com/mofojed/web-client-ui/tree/ui-plugin-prototype

2023-10-31 18:49 UTC, jnumainville submitted a review, later dismissed
Made comments in #95

2023-11-03 06:02 UTC, mattrunyon commented on plugins/ui/src/js/src/WidgetTypes.ts
> +  sendMessage: (message: string, args: unknown[]) => void;
I think I suggested this in another PR so we don't accidentally send references without knowing the actual type
```suggestion
  sendMessage: (message: string, references?: never[]) => void;
```

2023-11-03 06:03 UTC, mattrunyon commented on plugins/ui/src/js/src/errors/MixedPanelsError.ts
> +    (error as MixedPanelsError).isMixedPanelsError === true
Could probably just instanceof check it since it's a class

2023-11-03 06:03 UTC, mattrunyon commented on plugins/ui/src/js/src/errors/NoChildrenError.ts
> +  );
instanceof?

2023-11-03 06:05 UTC, mattrunyon commented on plugins/ui/src/js/src/useResizeObserver.ts
> +export function useResizeObserver(
Should put this hook in our main `react-hooks` package and add the resize observers to the main components

2023-11-03 12:48 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        return dict_to_camel_case({**self._props, "table": self._table})
I'm thinking we should actually toCamelCase on the client side perhaps. Server should be agnostic?

2023-11-06 18:16 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +    </LayoutContext.Provider>
Yes, I should put `LayoutContext` in the main app. Wasn't there at the time so I did not.

As for emitting events - we need a way for the panels to update their content as the top level widget gets updated. I figured keeping it part of the React DOM was an easy way to manage the display of the full widget document.

2023-11-06 18:21 UTC, mofojed commented on plugins/ui/src/js/src/LayoutContext.ts
> +export const LayoutContext: React.Context<
I'm thinking `@deephaven/dashboard` mainly because it's more straightforward hooking into the react lifecycle there.

2023-11-06 18:50 UTC, mofojed commented on plugins/ui/src/js/src/DocumentHandler.tsx
> +        const elementType = getElementType(child);
They could be non-panel elements, which is basically anything but an element.

2023-11-06 18:56 UTC, mofojed commented on plugins/ui/src/js/src/ElementView.tsx
> +    }
Yes a WidgetPlugin would be appropriate. We will need to add more props to IrisGrid to handle some of the specs on `ui.table` though.

2023-11-06 18:59 UTC, mofojed commented on plugins/ui/src/js/src/FigureObject.tsx
> +      chart.current?.updateDimensions();
Yes along with the useResizeObserver.

2023-11-06 19:04 UTC, mofojed commented on plugins/ui/src/js/src/HTMLElementView.tsx
> +  );
Whoops, this should be passing down `children`.

2023-11-06 19:07 UTC, mofojed commented on plugins/ui/src/js/src/PanelUtils.test.ts
> +    [{ props: { title: 'test' }, __dh_elem: PANEL_ELEMENT_NAME }, true],
I'll change it to `__dh_elem_name`

2023-11-06 19:11 UTC, mofojed commented on plugins/ui/src/js/src/ReactPanel.test.tsx
> +  // Should not re-open if just the children change but the metadata stays the same
Yes, we need to be able to update the contents of the panel when user interaction occurs, but we don't want to replace the existing panel (as that may change the order in the stack). Basically once we've opened the widget, we place all the panels where they were specified, then user can move them/close them as they want and we won't reposition/re-open them if an input on the widget is updated.
User can re-open the widget which will then reset all the panel placements.

2023-11-06 19:15 UTC, mofojed commented on plugins/ui/src/js/src/ReactPanel.tsx
> +  return element ? ReactDOM.createPortal(children, element) : null;
We need to be able to update the children in the panel as the widget document updates. I figured this was a good way to be reactive to those changes.

2023-11-06 19:16 UTC, mofojed commented on plugins/ui/src/js/src/ReactPanel.tsx
> +      LayoutUtils.openComponent({ root, config });
Correct

2023-11-06 19:31 UTC, mattrunyon commented on plugins/ui/src/js/src/DocumentHandler.tsx
> +        const elementType = getElementType(child);
Based on the branches before this code, the only way to end up here is if `childPanelCount > 0 && childPanelCount === childrenArray.length`. So everything is a child panel here by that logic, no?

When you say non-panel elements, what do you mean by that? UI.panel?

2023-11-06 19:32 UTC, mattrunyon commented on plugins/ui/src/js/src/PanelUtils.test.ts
> +    [{ props: { title: 'test' }, __dh_elem: PANEL_ELEMENT_NAME }, true],
Any reason for snake case instead of camel case? Not Python code

2023-11-06 20:32 UTC, mofojed commented on plugins/ui/src/js/src/useResizeObserver.ts
> +export function useResizeObserver(
https://github.com/deephaven/web-client-ui/pull/1626 for adding it to the `react-hooks` package and updating `Grid` and `Chart` to have resize observers directly.

2023-11-07 22:10 UTC, mofojed commented on plugins/ui/src/js/src/DashboardPlugin.tsx
> +    </LayoutContext.Provider>
https://github.com/deephaven/web-client-ui/pull/1625

2023-11-07 22:11 UTC, mofojed commented on plugins/ui/src/js/src/DocumentHandler.tsx
> +        const elementType = getElementType(child);
Yup I was being dumb - forgot that I don't allow mixed panels anymore.
However, I do render with the key here so that the user can specify the key.

2023-11-07 22:23 UTC, mofojed commented on plugins/ui/src/js/src/PanelUtils.test.ts
> +    [{ props: { title: 'test' }, __dh_elem: PANEL_ELEMENT_NAME }, true],
Changed to camelCase as per discussion.

2023-11-07 22:27 UTC, mofojed commented on plugins/ui/src/js/src/ElementUtils.ts
> +  props?: Record<string, unknown>;
Yes the docs are with the extended types, like `HTMLElementNode` and `PanelElementNode`.

2023-11-07 22:32 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +        return dict_to_camel_case({**self._props, "table": self._table})
As discussed, the format over the wire will be JSON, so converting all python case to camel case.

2023-11-09 22:40 UTC, jnumainville requested changes

2023-11-09 22:40 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +RowDataMap = Dict[str, Any]
Not sure why this changed but I prefer the PEP 585 version from before

2023-11-10 19:19 UTC, mofojed commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +RowDataMap = Dict[str, Any]
So do I, but the 3.8 tests were failing to run with this for some reason. Wasn't sure how else to solve it...

2023-11-13 15:05 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/elements/UITable.py
> +RowDataMap = Dict[str, Any]
Looks like direct assignment to a type can't be done with the future imports
https://bugs.python.org/issue45117

I am OK with this for now

2023-11-13 17:37 UTC, jnumainville approved these changes

2023-11-13 20:20 UTC, mattrunyon approved these changes

2023-11-13 20:45 UTC, merged