feat: progress_bar and progress_circle
deephaven/deephaven-plugins pull request #892
Opened 2024-09-17 17:45 UTC by wusteven815

2024-09-19 13:50 UTC, vbabich commented
Approved js changes, haven't looked at python.

2024-09-19 13:50 UTC, vbabich submitted a review, later dismissed

2024-09-19 14:34 UTC, mofojed commented
@wusteven815 include docs for these as well. We should be adding docs for every new component we add. Will close #871 and #872 as well.
Something similar to https://react-spectrum.adobe.com/react-spectrum/ProgressCircle.html in our existing docs format (e.g. image.md)

2024-09-19 14:34 UTC, mofojed requested changes
Add docs

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_bar.md
> +1. Use the appropriate size based on parent's size
```suggestion
1. Use the appropriate size based on the parent's size.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_bar.md
> +2. Use `static_color="white"` or `static_color="white"` if necessary to make sure the progress circle has enough contrast with the background
```suggestion
2. Use `static_color="white"` or `static_color="white"` if necessary to ensure the progress circle has enough contrast with the background.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_bar.md
> +2. Use `static_color="white"` or `static_color="white"` if necessary to make sure the progress circle has enough contrast with the background
aren't these the same?

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_bar.md
> +3. If the value of the progress is unknown, use `is_indeterminate=True`
```suggestion
3. If the value of the progress is unknown, use `is_indeterminate=True`.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_bar.md
> +Progress Bar comes in 2 different sizes by the `size` prop: `"S"` and `"L"`. Furthermore, the `static_color` prop can be used to control the color of the progress circle.
```suggestion
Progress Bar comes in two different sizes determined by the `size` prop: `"S"` and `"L"`. Furthermore, the `static_color` prop can be used to control the color of the progress circle.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_circle.md
> +1. Use the appropriate size based on parent's size
```suggestion
1. Use the appropriate size based on the parent's size.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_circle.md
> +2. Use `static_color="white"` or `static_color="white"` if necessary to make sure the progress circle has enough contrast with the background
the two options are the same

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_circle.md
> +2. Use `static_color="white"` or `static_color="white"` if necessary to make sure the progress circle has enough contrast with the background
```suggestion
2. Use `static_color="white"` or `static_color="white"` if necessary to make sure the progress circle has enough contrast with the background.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_circle.md
> +3. If the value of the progress is unknown, use `is_indeterminate=True`
```suggestion
3. If the value of the progress is unknown, use `is_indeterminate=True`.
```

2024-09-20 16:12 UTC, margaretkennedy commented on plugins/ui/docs/components/progress_circle.md
> +Progress Circle comes in 3 different sizes by the `size` prop: `"S"`, `"M"`, and `"L"`. Furthermore, the `static_color` prop can be used to control the color of the progress circle.
```suggestion
Progress Circle comes in three different sizes determined by the `size` prop: `"S"`, `"M"`, and `"L"`. Furthermore, the `static_color` prop can be used to control the color of the progress circle.
```

2024-09-20 19:08 UTC, mofojed submitted a review, later dismissed

2024-09-20 19:08 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/progress_bar.py
> +    # format_options, # omitted because need to connect it to Deephaven formatting options as well
@ethanalvizo is adding this to `number_field` right now, can add it to `progress_bar` when he's done that.

2024-09-20 19:19 UTC, dsmmcken submitted a review, later dismissed

2024-09-20 19:19 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +## Visual Options
Split these examples by prop please, with headings and a minimal reproducible example for each.

2024-09-24 16:12 UTC, dsmmcken requested changes
Every example should be standalone runnable, therefor needs import statements.

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_circle.md
> +        column_gap="20px",
there's already default gap, this can be dropped.

```suggestion
```

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_circle.md
> +        column_gap="20px",
```suggestion
```

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_circle.md
> +            ui.view(ui.progress_circle(value=70, static_color="white", margin="10px")),
add background_color="black" to this example so it's static. 

Light theme users exist.

![image](https://github.com/user-attachments/assets/99949296-7d53-472e-92fd-db9718cbc94d)

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +    return ui.progress_bar(size="L", is_indeterminate=True)
```suggestion
    return ui.progress_bar(is_indeterminate=True)
```

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +progress_bar_value_examples = value_variants()
```suggestion
@ui.component
def value_variants():
    return [
        ui.progress_bar(value=50),
        ui.progress_bar(value=50, min_value=25, max_value=125),
    ]


progress_bar_value_examples = value_variants()
```

Similar output with less code.

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +    )
```suggestion
def indeterminate_variants():
    return ui.progress_bar(is_indeterminate=True)        
```

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +def size_variants():
use @ui.component simplification shown above.

Missing L example

2024-09-24 16:12 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +        ui.view(ui.progress_bar(value=70, static_color="white", margin="10px")),
add `background_color="black`

2024-09-24 19:40 UTC, wusteven815 commented on plugins/ui/docs/components/progress_bar.md
> +def size_variants():
The progress bar with no `size` prop is L - I wanted to show that L is the default. Should I explicitly add the prop?

2024-09-30 20:15 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +def size_variants():
acknowledgeed.

2024-09-30 20:15 UTC, dsmmcken commented on plugins/ui/docs/components/progress_bar.md
> +    )
```suggestion
    return [
        ui.progress_bar(value=70, size="S"),
        ui.progress_bar(value=70),
    ]
```

skimpily example to minimum necessary code.

2024-10-02 16:08 UTC, jnumainville submitted a review, later dismissed
Only reviewed the documentation and python. Mostly minor details.

2024-10-02 16:08 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/progress_bar.py
> +        max_value: 	The largest value allowed for the input.
Funky spacing here

2024-10-02 16:08 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/progress_bar.py
> +    key: str | None = None,
It seems like ideally the `UNSAFE` options are last. It's subtle, but it implies that those arguments are almost a separate category of arguments rather than interspersed with the rest of them, which I think should be the case.

2024-10-02 17:05 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/progress_bar.py
> +    key: str | None = None,
`key` is something that's also on every component, so I think it's even a more "separate" category, and should be last for every component. So I think this is fine.

2024-10-02 17:35 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/progress_bar.py
> +    key: str | None = None,
I think my point is more that the `UNSAFE` arguments are specifically ones we want users to be cautious about, and that's the most important (in terms of user separation) category distinction we would want to point out. Many groups are used across many components so there are other "categories" too.
But, this is all speculation , and we already mark the arguments `UNSAFE` so I don't feel so strongly that this has to change so I'll just resolve.

2024-10-04 13:57 UTC, wusteven815 commented on plugins/ui/docs/components/progress_circle.md
> +Progress circles show the progression of a system operation such as downloading, uploading, or processing, in a visual way. They can represent determinate or indeterminate progress.
I don't think so, React Spectrum doesn't say anything either

2024-10-04 21:18 UTC, merged