feat: allow overflow by default on ui.panel
deephaven/deephaven-plugins pull request #896
Opened 2024-09-19 20:44 UTC by dsmmcken

This improves the default layout experience across a number of layout cases. The primary goal was to allow overflow auto to happen on ui.panel by default while still filling space when passing multiple objects such as tables and plots.

Changes are as follows:
- ui.panel has an overflow property, and defaults to auto
- ui.grid now has default gap and flex auto
- iris-grid has a min height of 70px to improve cases where it would normally shrink to 0
- ui panel continues to wrap children by default in a flex with align start, but immediate flex children and grid have align-self stretch which is the normal default of a flex element
- iris grid canvas has position absolute set so it doesn't actually impact flow

BREAKING CHANGE: ui.panel now has overflow auto set by default and grid now has default padding

2024-09-20 19:31 UTC, mofojed approved these changes

2024-09-20 19:35 UTC, mattrunyon requested changes

2024-09-20 19:35 UTC, mattrunyon commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
> +      }
I think we should just make `Grid.tsx` and `Flex.tsx` components instead that handle this

The `shouldWrapTextChildren` also probably belongs in wrapper components instead of this file. There's not really any reason we should be doing any manipulation here IMO. It hides what actually happens with the components

The `contextualHelp` is an exception I guess since we're wanting any prop called `contextualHelp` to be modified

2024-09-23 19:44 UTC, dsmmcken commented
Edited to also address #544

2024-09-26 13:03 UTC, mofojed approved these changes

2024-09-26 20:59 UTC, mattrunyon approved these changes

2024-09-26 21:09 UTC, merged