docs: markdown component spec
deephaven/deephaven-plugins pull request #903
Opened 2024-09-23 16:26 UTC by wusteven815

- Adds spec for #890

2024-09-23 19:44 UTC, mofojed commented on plugins/ui/DESIGN.md
> +The markdown component should take a string and render it with Markdown formatting. The component should also support LaTeX with MathJax, and use all the props in the Layout, Spacing, Sizing, Positio
In general we may want to explicitly call out we'd support CommonMark: https://github.com/remarkjs/react-markdown?tab=readme-ov-file#syntax
I think we also want to call out what will _not_ be supported. Taking a look at react-markdown: https://github.com/remarkjs/react-markdown?tab=readme-ov-file#options

- `plugins`: we'll add the math/latex we need by default, but won't allow specifying a remark/rehype plugin otherwise.
- `components`: we have our own `code` component wired up, and in theory we could wire up custom components which would be interesting; however I think custom components could probably be a separate task unless we have a compelling/customer reason to do so (unless Don thinks otherwise): https://github.com/deephaven/web-client-ui/blob/86e16eec31eed6a4e89a18c6412d4396a724bac0/packages/dashboard-core-plugins/src/controls/markdown/MarkdownEditor.tsx#L69

2024-09-23 20:57 UTC, dsmmcken commented on plugins/ui/DESIGN.md
> +The markdown component should take a string and render it with Markdown formatting. The component should also support LaTeX with MathJax, and use all the props in the Layout, Spacing, Sizing, Positio
Yeah, that's fine with respect to other components.

2024-09-23 20:59 UTC, dsmmcken commented
Would we expect it to accept common props as well?

2024-09-23 21:01 UTC, dsmmcken commented
For reference: https://docs.streamlit.io/develop/api-reference/text/st.markdown#stmarkdown

Streamlit exposes unsafe_allow_html to turn off escaping.

Also supports emoji shortcodes which is just neat. Probably not something we need to do, but neat.

2024-09-26 13:28 UTC, mofojed submitted a review, later dismissed
Code blocks aren't rendering properly. You'll need to pass in a component for rendering code blocks, like we do in our [MarkdownEditor](https://github.com/deephaven/web-client-ui/blob/a24dc8c447bc892aea2947641c32371d348042dc/packages/dashboard-core-plugins/src/controls/markdown/MarkdownEditor.tsx#L15) component.

[ReactMarkdown shows an example of this in their page](https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use-custom-components-syntax-highlight) as well (side note, I didn't know you could use tildes to mark code blocks as well, thought it was just backticks).

Example that doesn't look right:
````python
from deephaven import ui

md = ui.markdown("""
# Code block example

```python
from deephaven import empty_table
t = empty_table(1000).update("x=i")
```
""")
````

![image](https://github.com/user-attachments/assets/82834360-ea58-41c5-b5e2-acc9bd8a688d)

2024-09-30 20:22 UTC, dsmmcken requested changes
Looking good. Add doc page.

2024-10-02 14:19 UTC, dsmmcken commented on plugins/ui/docs/components/markdown.md
> +
Should suggest ui.text and ui.heading for individual lines of text.

2024-10-15 17:52 UTC, mofojed approved these changes

2024-10-15 18:34 UTC, margaretkennedy commented on plugins/ui/docs/components/markdown.md
> +The markdown components renders a string in the CommonMark standard. The component also supports LaTeX (through MathJax), with `remark-math` and `rehype-mathjax`. Other plugins and markdown component
```suggestion
The markdown component renders a string in the CommonMark standard. It also supports LaTeX (through MathJax), with `remark-math` and `rehype-mathjax`. Other plugins and markdown components are not supported. The markdown is wrapped in a `View`, which all props are passed to except for `children`.
```

2024-10-15 18:34 UTC, margaretkennedy commented on plugins/ui/docs/components/markdown.md
> +When writing LaTeX, be careful on how Python handles backslashes with escape characters. It is recommended to use raw strings to minimize this issue.
```suggestion
When writing LaTeX, be careful how Python handles backslashes with escape characters. To minimize this issue, it is recommended to use raw strings.
```

2024-10-22 15:54 UTC, dsmmcken approved these changes

2024-10-22 16:58 UTC, margaretkennedy approved these changes

2024-10-22 18:34 UTC, merged