docs: ui.text
deephaven/deephaven-plugins pull request #907
Opened 2024-09-24 14:47 UTC by AkshatJawne

Closes #835

2024-09-24 17:04 UTC, dsmmcken requested changes

2024-09-24 17:04 UTC, dsmmcken commented on plugins/ui/docs/components/text.md
> +
I think the only unusual prop is color (something we added not spectrum).

Should show it as an example.

```
faded_text = ui.text("Faded text", color="gray-500")
negative_text = ui.text("Faded text", color="negative")
postive_text = ui.text("Faded text", color="positive")
hex_text = ui.text("Hex color", color="#FA8072")
sentence_with_color = ui.text("Hello ", ui.text("world", color="accent"), "!")
```

2024-09-24 17:04 UTC, dsmmcken commented on plugins/ui/docs/components/text.md
> +Text represents text with no specific semantic meaning, serving as a basic element.
```suggestion
Text represents text with no specific semantic meaning, serving as a basic element. It is equivalent to an HTML span element.
```

2024-09-30 20:23 UTC, dsmmcken commented on plugins/ui/docs/components/text.md
> +The text component is sometimes used within a parent container, like [`button`](./button.md) or [`picker`](./picker.md) to define text content when multiple children are passed (such as icons and des
```suggestion
The text component is sometimes used within a parent container, like [`button`](./button.md) or [`picker`](./picker.md) to define text content when multiple children are passed (such as icons and descriptions). It inherits styling from its parent container.
```

2024-10-01 23:58 UTC, AkshatJawne reviewed
Added to sidebar.json @dsmmcken , should be good for re-review

2024-10-02 01:14 UTC, dsmmcken approved these changes

2024-10-02 16:35 UTC, merged