docs: ui.heading
deephaven/deephaven-plugins pull request #908
Opened 2024-09-24 15:16 UTC by AkshatJawne

Closes #833 

**Additional Info:**
- Will update `text` link to link to ui.text docs, once https://github.com/deephaven/deephaven-plugins/pull/907 merges

2024-09-24 17:09 UTC, dsmmcken requested changes

2024-09-24 17:09 UTC, dsmmcken commented on plugins/ui/docs/components/heading.md
> +By default, it creates a level 3 (<h3>) heading.
```suggestion
By default, it creates a level 3 (`<h3>`) heading.
```

Need to wrap <h3> in a code block, otherwise it's invalid markdown. Markdown accepts html, so that would be a valid open tag with no closing tag.

2024-09-24 17:09 UTC, dsmmcken commented on plugins/ui/docs/components/heading.md
> +my_heading_basic = ui.heading("Unsubscribe")
```suggestion
my_heading_basic = ui.heading("Hello world")
```

2024-09-24 17:09 UTC, dsmmcken commented on plugins/ui/docs/components/heading.md
> +
Add a color section, see review in ui.text.

Only difference would be you would nest a sentenct with ui.text within it if you needed to colorize just one word.

```h1 = ui.heading("Hello ", ui.text("world", color="accent"), "!")```

2024-09-30 20:31 UTC, dsmmcken requested changes

2024-09-30 20:31 UTC, dsmmcken commented on plugins/ui/docs/components/heading.md
> +)
```suggestion
from deephaven import ui


my_heading_color_example = ui.flex(
    ui.heading("Faded heading", color="gray-500"),
    ui.heading("Negative heading", color="negative"),
    ui.heading("Positive heading", color="positive"),
    ui.heading("Hex color", color="#FA8072"),
    ui.heading("Nested ", ui.text("example", color="green"), "!"),
    direction="column"
)
```

Return as one element rather than a bunch of panels.

2024-10-02 01:15 UTC, dsmmcken approved these changes

2024-10-02 16:42 UTC, AkshatJawne commented
@dsmmcken Need reapproval, added link to text docs since they have now merged.

2024-10-02 17:04 UTC, dsmmcken approved these changes

2024-10-02 20:36 UTC, merged