docs: ui.button_group
deephaven/deephaven-plugins pull request #910
Opened 2024-09-25 19:25 UTC by AkshatJawne

Closes #836

2024-09-26 10:53 UTC, margaretkennedy commented on plugins/ui/docs/components/button_group.md
> +Consider using a [`action_group`](./action_group.md) to allow the user to select from a list of actions.
```suggestion
Consider using an [`action_group`](./action_group.md) to allow the user to select from a list of actions. 
```

2024-09-26 10:53 UTC, margaretkennedy commented on plugins/ui/docs/components/button_group.md
> +Button group is used used to handle button overflow, and thus, expects buttons as children. It switches to a vertical layout when horizontal space is limited.
```suggestion
A Button group is used to handle button overflow and, thus, expects buttons as children. It switches to a vertical layout when horizontal space is limited.
```

2024-09-26 17:32 UTC, margaretkennedy commented on plugins/ui/docs/components/button_group.md
> +Note that the button component can only be used within a button group.
worth formatting as a true note?

> [!NOTE]
> The button component can only be used with a button group.

2024-09-30 20:49 UTC, dsmmcken requested changes

2024-09-30 20:49 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +Note that the button component can only be used within a button group.
```suggestion
A button group is a UI component that groups buttons with related actions together and will automatically handle layout overflow nicely. Only buttons can be used within button group.
```

2024-09-30 20:49 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +)
```suggestion
from deephaven import ui


my_button_group_basic = ui.button_group(
    ui.button("Rate Now", variant="accent"),
    ui.button("No, thanks", variant="primary", style="outline"),
    ui.button("Remind me later", variant="primary", style="outline"),
)
```

Adjust to preferred styling.

2024-09-30 20:49 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +1. The most critical action in a button group should use an accent, primary, or negative button style, while other actions should be secondary outline buttons.
```suggestion
1. The most critical action in a button group should use an accent, or negative button style, while other actions should be primary outline buttons.
```

2024-09-30 20:49 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +)
```suggestion
from deephaven import ui


my_button_group_content_space_example = ui.view(
    ui.button_group(
        ui.button("Rate Now", variant="accent", style="outline"),
        ui.button("Remind me later", variant="primary", style="outline"),
        ui.button("No, thanks", variant="primary", style="outline"),
    ),
    width=200,
    border_width="thin",
    padding="size-100",
)
```

It's more about the parent being constrained in width, and the group auto switching orientation. This shows that better.

2024-09-30 20:49 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +    ui.button("Rate Now", variant="primary"),
```suggestion
    ui.button("No, thanks", variant="primary", style="outline"),
    ui.button("Remind me later", variant="primary", style="outline"),
    ui.button("Rate Now", variant="accent"),
```

2024-09-30 20:50 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +Note that the button component can only be used within a button group.
Changed suggested wording to note be a note.

2024-10-01 14:52 UTC, AkshatJawne reviewed
Ready for re-review @margaretkennedy @dsmmcken

2024-10-02 01:16 UTC, dsmmcken approved these changes

2024-10-03 12:57 UTC, margaretkennedy reviewed
One minor change.

2024-10-03 12:57 UTC, margaretkennedy commented on plugins/ui/docs/components/button_group.md
> +A button group is a UI component that groups buttons with related actions together and will automatically handle layout overflow nicely. Only buttons can be used within button group.
```suggestion
A button group is a UI component that groups buttons with related actions together and will automatically handle layout overflow nicely. Only buttons can be used within button groups.
```

2024-10-04 15:47 UTC, dsmmcken approved these changes

2024-10-07 21:07 UTC, dsmmcken requested changes

2024-10-07 21:07 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +        ),
Remove default align, don't need to show this again.

2024-10-07 21:07 UTC, dsmmcken commented on plugins/ui/docs/components/button_group.md
> +        ),
Use the variant + style combination as used in all the other examples pls.

2024-10-08 18:46 UTC, dsmmcken submitted a review, later dismissed

2024-10-08 18:49 UTC, margaretkennedy commented on plugins/ui/docs/components/button_group.md
> +4. Icons should be used for higher priority actions if used in the button group. If the most critical action does not have an icon, avoid using icons for the other lower priority actions.
```suggestion
4. Icons should be used for higher-priority actions if used in the button group. If the most critical action does not have an icon, avoid using icons for the other lower-priority actions.
```

2024-10-08 18:49 UTC, margaretkennedy commented on plugins/ui/docs/components/button_group.md
> +By default, button groups are start-aligned to be in accordance with content, but they can be set to have a different alignment using the `alignment` prop.
```suggestion
By default, button groups are start-aligned to accord with content, but they can be set to have a different alignment using the `alignment` prop.
```

2024-10-11 11:36 UTC, dsmmcken approved these changes

2024-10-11 19:35 UTC, merged