UI Calendar Component
deephaven/deephaven-plugins pull request #918
Opened 2024-10-01 19:45 UTC by dgodinez-dh

Closes https://github.com/deephaven/deephaven-plugins/issues/905 for implementation.
Closes https://github.com/deephaven/deephaven-plugins/issues/851 for docs.

2024-10-02 14:36 UTC, bmingles commented on plugins/ui/DESIGN.md
> +# the on_change handler is passed a zoned date time
Does this mean `placeholder_value` can impact the type passed to `on_chage`? I don't see this listed in the precedence list earlier in the doc.

2024-10-02 14:37 UTC, bmingles commented on plugins/ui/DESIGN.md
> +1. `value`
Examples below imply that `placeholder_value` should be somewhere in this list

2024-10-02 14:42 UTC, bmingles commented on plugins/ui/docs/components/calendar.md
> +By default, when pressing the next or previous buttons, pagination will advance by the `visibl_months` value. This behavior can be changed to page by single months instead, by setting `page_behavior`
typo `visibl_months`

2024-10-02 14:44 UTC, bmingles commented on plugins/ui/docs/components/calendar.md
> +4. `default_focused_value`
Does `placeholder_value` fall in this list somewhere?

2024-10-02 15:01 UTC, bmingles commented on plugins/ui/DESIGN.md
> +# the on_change handler is passed a zoned date time
oh actually is `placeholder_value` actually a supported prop?

2024-10-02 15:15 UTC, bmingles commented on plugins/ui/src/js/src/elements/utils/DateTimeUtils.test.ts
> +    expect(parseNullableCalendarValue(null)).toBeNull();
I would probably separate `parseNullableCalendarValue` tests into their own describe block

2024-10-02 15:24 UTC, bmingles requested changes
Looks good overall except for some minor doc issues.

2024-10-02 17:27 UTC, jnumainville requested changes

2024-10-02 17:27 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +
It looks like the internal functions within `wrap_local_date_callable `, `_wrap_date_range_callable`, `_wrap_date_callable` and `_wrap_time_callable` could be refactored to encapsulate this `try/except` logic

for example `wrap_local_date_callable` would just be something like
```
def no_error_date_callable(date: LocalDateConvertible) -> None:
    _wrap_date_time_callable_skip_errors(date_callable, converter)
return no_error_date_callable
```

2024-10-02 17:29 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/calendar.py
> +    key: str | None = None,
Per comment on other PR just going to close this, no action needed

2024-10-03 12:33 UTC, dgodinez-dh commented on plugins/ui/DESIGN.md
> +# the on_change handler is passed a zoned date time
It is not supported. I have updated the examples to use `default_value`

2024-10-03 12:34 UTC, dgodinez-dh commented on plugins/ui/docs/components/calendar.md
> +4. `default_focused_value`
No. There is no `placeholder_value` for calendar.

2024-10-03 12:41 UTC, dgodinez-dh commented on plugins/ui/src/js/src/elements/utils/DateTimeUtils.test.ts
> +    expect(parseNullableCalendarValue(null)).toBeNull();
Updated

2024-10-03 12:49 UTC, dgodinez-dh commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +
Do you mean create a new function called `_wrap_date_time_callable_skip_errors` that encapsulates the `try/except`? I'm not sure I see the advantage of this. I think it will create a bunch of single use functions that are only called in one place.

2024-10-03 12:51 UTC, dgodinez-dh commented on plugins/ui/docs/components/calendar.md
> +Calendars allow users to select a date.
Updated

2024-10-03 14:41 UTC, bmingles approved these changes
Changes LGTM

2024-10-03 14:52 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +
Yeah, wrapping the body of these `no_error_date_callable` and similar functions since  they have the same structure. There are already single use functions here, and they are a bit fragile in that they have the same content so that if one needed to be changed likely all would need to be changed separately

2024-10-03 14:57 UTC, bmingles commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +
The idea would be to somehow create a single function that encapsulates the error handling not 1 per wrapper correct?

2024-10-03 15:01 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +
yep - I know the typing might make this a bit tricky - but I figure at least the body of the internal function looks like it could by encapsulated

2024-10-03 16:55 UTC, dgodinez-dh commented on plugins/ui/src/deephaven/ui/_internal/utils.py
> +
Updated

2024-10-03 17:03 UTC, jnumainville submitted a review, later dismissed

2024-10-03 19:39 UTC, jnumainville approved these changes

2024-10-03 19:45 UTC, merged