feat: Add standard style props to UI table
deephaven/deephaven-plugins pull request #921
Opened 2024-10-01 23:26 UTC by mattrunyon

Fixes #606

The height/width of the `ui-table-container` is the browser specific keywords for `stretch`

2024-10-09 20:49 UTC, dsmmcken requested changes
Tried it, annoying that it escapes when you apply margin and would be difficult for your avg python dev to fix. I think we should re-map margin to padding in this case.

Might be able to do it via the userStyleProps named destructing?

I would add a few test cases to ui_flex.py tests to make sure we don't break it in future.

Something like:

```
flex_XX = ui.panel(ui.flex(ui.table(_t_flex, margin="20px"), _t_flex, direction="column"))
flex_XX = ui.panel(ui.flex(ui.table(_t_flex, margin="20px"), _t_flex, direction="row"))
flex_XX = ui.panel(ui.flex(ui.table(_t_flex, height="200px"), _t_flex, direction="column"))
```

2024-10-15 23:59 UTC, mattrunyon commented
If we wanted to use `padding` instead of `margin`, we can still use Spectrum's `useStyleProps` by passing the view handlers instead of base style handlers. That's what I did after mapping margin to padding since React was treating explicit undefined as `0` or `unset` it seems when I just destructured after `useStyleProps` and built the style object

2024-10-16 15:29 UTC, dsmmcken requested changes
What is going on with flex24 webkit test? It looks different and wrong?

2024-10-16 15:29 UTC, dsmmcken commented on plugins/ui/src/js/src/elements/UITable/UITable.tsx
> +  // const {
remove comments

2024-10-16 15:29 UTC, dsmmcken commented on plugins/ui/src/js/src/elements/UITable/UITable.tsx
> +    margin,
Shouldn't these be:

margin
marginTop
marginBottom
marginStart
marginEnd
marginX
marginY

2024-10-16 18:42 UTC, mattrunyon commented
We could alias width/height to set both min and max width/height so the table should be fixed in size. The issue with `flex_24` is it seems Chrome and Firefox use `200px` and `100%=300px` for the 2 elements. Then shrinks them accordingly into a 300px space. The 200px table is actually never 200px in this case because of the 100% table. As you expand the panel, the calculation shifts so the top table gets bigger, but never gets to 200px since the 100% table always includes the 200px in its desired size.

2024-10-16 19:23 UTC, mattrunyon commented
Setting min/max height/width to the height/width (if the min/max is not already specified) doesn't work either. In the case where you specify a height and min-height, you will never reach the height w/ a 2nd table with defaults.

2024-10-24 15:06 UTC, dsmmcken approved these changes
This is odd, but I guess it works

```tsx
minHeight: restStyleProps.minHeight ?? restStyleProps.height,
maxHeight: restStyleProps.maxHeight ?? restStyleProps.height,
minWidth: restStyleProps.minWidth ?? restStyleProps.width,
maxWidth: restStyleProps.maxWidth ?? restStyleProps.width,
```

2024-10-24 19:49 UTC, mattrunyon commented
> This is odd, but I guess it works
> 
> ```tsx
> minHeight: restStyleProps.minHeight ?? restStyleProps.height,
> maxHeight: restStyleProps.maxHeight ?? restStyleProps.height,
> minWidth: restStyleProps.minWidth ?? restStyleProps.width,
> maxWidth: restStyleProps.maxWidth ?? restStyleProps.width,
> ```

Basically decided if the user sets an explicit height they probably want for it to just be that height. With the way grid determines its height and the default flex wrapper/grow/shrink, this makes it so the grid shouldn't grow/shrink in these cases.

The alternate is to set flex grow/shrink on the table based on props set by the user. But they could be in a non-flex environment, so I thought this might be more robust if not in a flex environment.

2024-10-24 19:50 UTC, merged