docs: form
deephaven/deephaven-plugins pull request #925
Opened 2024-10-04 04:55 UTC by ethanalvizo

Closes #831 

Bug found with necessity_indicator prop (#924). Can omit that section from these docs or is it crucial for form?

2024-10-24 15:22 UTC, dsmmcken commented
testing blocked by #948

2024-10-28 14:16 UTC, dsmmcken requested changes

2024-10-28 14:16 UTC, dsmmcken commented on plugins/ui/docs/components/form.md
> +        ui.button("Submit", type="submit"),
```suggestion
        ui.button("Submit", type="submit"),
```

We probably want to somehow do nothing with this submit event, not sure how though. @mofojed ?

While some forms will probably be traditional and go to an external end point, I imagine most would be back to dh.ui. So we should show how to handle that in more of the examples.

2024-10-28 14:16 UTC, dsmmcken commented on plugins/ui/docs/components/form.md
> +```
for quiet and emphasized, show a few more component types mixed in so the output actually shows what were are talking about.

Emphasized has no effect on text_fields, so the example shows nothing. Needs other components.

2024-10-28 16:18 UTC, mofojed commented on plugins/ui/docs/components/form.md
> +        ui.button("Submit", type="submit"),
Yes we should use the `on_submit` event. Could just be something like:
```python
from deephaven import ui


@ui.component
def ui_form():
    return ui.form(
        ui.text_field(name="name", label="Enter name"),
        ui.button("Submit", type="submit"),
        on_submit=lambda e: print(f"Form submitted: {e}")
    )

my_form = ui_form()
```

We should also have examples using the `on_reset` and `on_invalid` events as well.

2024-10-31 15:16 UTC, ethanalvizo commented on plugins/ui/docs/components/form.md
> +```
![image](https://github.com/user-attachments/assets/77648b83-fafc-4e48-834c-5250937faede)
[The spectrum docs](https://react-spectrum.adobe.com/react-spectrum/Form.html#emphasized) are pretty funny for this example too. Idk if it's just my eyes but I don't think emphasized does anything for RadioField either

2024-10-31 15:39 UTC, dsmmcken commented on plugins/ui/docs/components/form.md
> +```
Fills the circle with the accent color instead of gray.

2024-11-01 19:42 UTC, mofojed approved these changes

2024-11-02 15:16 UTC, dsmmcken commented on plugins/ui/docs/components/form.md
> +my_form_submit = ui_form_submit()
Should show with more than one component in the form.

2024-11-04 16:07 UTC, dsmmcken submitted a review, later dismissed

2024-11-04 21:17 UTC, margaretkennedy commented on plugins/ui/docs/components/form.md
> +Forms allow users to enter data that can be submitted while providing alignment and styling for form fields
```suggestion
Forms allow users to enter data that can be submitted while providing alignment and styling for form fields.
```

2024-11-04 21:17 UTC, margaretkennedy commented on plugins/ui/docs/components/form.md
> +By default, validation errors will be displayed in real-time as the fields is edited but form submission is not blocked. To enable this and native HTML form validation, set `validation_behavior` to "
```suggestion
By default, validation errors will be displayed in real-time as the fields are edited, but form submission is not blocked. To enable this and native HTML form validation, set `validation_behavior` to "native".
```

2024-11-04 21:17 UTC, margaretkennedy commented on plugins/ui/docs/components/form.md
> +The `necessity_indicator` prop dictates whether form labels will use an icon or a label to outline which form fields are required. The default is "icon"
```suggestion
The `necessity_indicator` prop dictates whether form labels will use an icon or a label to outline which form fields are required. The default is "icon".
```

2024-11-07 20:19 UTC, dsmmcken approved these changes

2024-11-07 23:42 UTC, margaretkennedy approved these changes

2024-11-08 02:54 UTC, merged