docs: ui.toggle_button
deephaven/deephaven-plugins pull request #927
Opened 2024-10-08 00:38 UTC by AkshatJawne

Closes #838

2024-10-08 13:39 UTC, margaretkennedy commented on plugins/ui/docs/components/toggle_button.md
> +A toggle button accepts a label, an icon, or both as children
```suggestion
A toggle button accepts a label, an icon, or both as children.
```

2024-10-08 19:31 UTC, dsmmcken requested changes
Minor, but otherwise good.

2024-10-08 19:31 UTC, dsmmcken commented on plugins/ui/docs/components/toggle_button.md
> +        ui.heading("Toggle Button (controlled)"),
```suggestion
        ui.text("Toggle Button (uncontrolled)"),
        ui.toggle_button("Pin", default_selected=True, width="90px"),
        ui.text("Toggle Button (controlled)"),
```

shhh.

2024-10-08 19:31 UTC, dsmmcken commented on plugins/ui/docs/components/toggle_button.md
> +    return ui.flex(
```suggestion
    return [
```

it's implicitly wrapped in a flex column, no need to add one.

2024-10-08 19:31 UTC, dsmmcken commented on plugins/ui/docs/components/toggle_button.md
> +    )
```suggestion
    ]
```

2024-10-08 19:31 UTC, dsmmcken commented on plugins/ui/docs/components/toggle_button.md
> +The `static_color` prop can be used when the toggle button is placed over a color background.
```suggestion
The `static_color` prop can be used when the toggle button is placed over a colored background.
```

2024-10-11 11:43 UTC, dsmmcken approved these changes

2024-10-14 19:17 UTC, margaretkennedy commented on plugins/ui/docs/components/toggle_button.md
> +If there is no text that is passed into the toggle button, and hence, it has no visible label, the `aria_label` prop should be set for accessibility.
```suggestion
If no text is passed into the toggle button, and hence, it has no visible label, the `aria_label` prop should be set for accessibility.
```

2024-10-14 19:17 UTC, margaretkennedy commented on plugins/ui/docs/components/toggle_button.md
> +The `on_change` property is triggered whenever the value in the toggle button group selection is changed.
```suggestion
The `on_change` property is triggered whenever the toggle button group selection value is changed.
```

2024-10-15 20:15 UTC, dsmmcken approved these changes

2024-10-15 20:31 UTC, merged