docs: ui.action_menu
deephaven/deephaven-plugins pull request #928
Opened 2024-10-08 16:18 UTC by AkshatJawne

Closes #844

2024-10-11 14:05 UTC, margaretkennedy commented on plugins/ui/docs/components/action_menu.md
> +The `align` prop positions the action menu relative to the trigger, while the `direction` prop determines the direction in which the action menu will render.
"relative to the trigger" - I'm not 100% sure what that means. Is the usual trigger simply clicking the button? or do you mean the action triggered

2024-10-11 14:05 UTC, margaretkennedy commented on plugins/ui/docs/components/action_menu.md
> +The `is_open` and `default_open` props on the action menu control whether the menu is open by default. They apply controlled and uncontrolled behavior on the Menu respectively.
```suggestion
The `is_open` and `default_open` props on the action menu control whether the menu is open by default. They apply controlled and uncontrolled behavior on the menu, respectively.
```

2024-10-11 19:34 UTC, AkshatJawne commented on plugins/ui/docs/components/action_menu.md
> +The `align` prop positions the action menu relative to the trigger, while the `direction` prop determines the direction in which the action menu will render.
I mean relative to the button, but don't want to add confusion by mentioning a "button", since the children are items, not buttons. So the best way I thought to get around that is to generalize it by stating the "trigger".

2024-10-14 19:21 UTC, margaretkennedy commented on plugins/ui/docs/components/action_menu.md
> +Consider using an [`action_group`] to group multiple action buttons together.
no link

2024-10-14 19:23 UTC, margaretkennedy commented on plugins/ui/docs/components/action_menu.md
> +The `align` prop positions the action menu relative to the trigger, while the `direction` prop determines the direction in which the action menu will render.
I think button is fine, but defer to Don and the other reviewers.

2024-10-15 20:35 UTC, AkshatJawne commented on plugins/ui/docs/components/action_menu.md
> +The `align` prop positions the action menu relative to the trigger, while the `direction` prop determines the direction in which the action menu will render.
@dsmmcken Any thoughts?

2024-10-15 20:44 UTC, dsmmcken commented on plugins/ui/docs/components/action_menu.md
> +The `align` prop positions the action menu relative to the trigger, while the `direction` prop determines the direction in which the action menu will render.
parent button? trigger was fine with me though.

2024-10-15 20:45 UTC, AkshatJawne commented on plugins/ui/docs/components/action_menu.md
> +The `align` prop positions the action menu relative to the trigger, while the `direction` prop determines the direction in which the action menu will render.
Yeah, either relative to the "trigger", or relative to the "button", I personally think trigger makes sense?

2024-10-23 20:52 UTC, dsmmcken requested changes

2024-10-23 20:52 UTC, dsmmcken commented on plugins/ui/docs/components/action_menu.md
> +        text_value="Azure",
```suggestion
        ui.icon("github_alt"),
        ui.text("Github"),
        ui.text("Github Option", slot="description"),
        text_value="Github",
    ),
    ui.item(
        ui.icon("azure_devops"),
        ui.text("Azure"),
        ui.text("Azure Option", slot="description"),
        text_value="Azure",
```

Icons now support python snake_case. For backwards compatibility they also support JS style icon names, but we should show python snake case style icon names from now on.

2024-10-23 20:52 UTC, dsmmcken commented on plugins/ui/docs/components/action_menu.md
> +    )
```suggestion
@ui.component
def ui_action_menu_open_example():
    is_open, set_is_open = ui.use_state(True)
    return ui.action_menu(
        "Cut",
        "Copy",
        "Paste",
        is_open=is_open,
        on_open_change=set_is_open,
    )
```

I would actually show an example with the props you listed.

2024-10-28 14:29 UTC, dsmmcken commented on plugins/ui/docs/components/action_menu.md
> +        ui.action_menu(
```suggestion
def ui_action_menu_open_examples():
    is_open, set_is_open = ui.use_state(False)
    return [
        ui.text(f"Controlled menu open state: {is_open}"),
        ui.action_menu(
```

We should try to visually show changes if we can, in this case we are trying to show that you can use a controlled component, so show the state being changed.

2024-10-31 20:56 UTC, dsmmcken approved these changes

2024-11-01 10:31 UTC, margaretkennedy commented on plugins/ui/docs/components/action_menu.md
> +An action menu can be disabled to prevent user interaction through the `is_disabled` prop. This is useful when the action menu is not currently available, but the button should still be visible.
```suggestion
Through the ' is_disabled ' prop, an action menu can be disabled to prevent user interaction. This is useful when the action menu is currently unavailable, but the button should still be visible.
```

2024-11-04 19:17 UTC, merged