feat: ui.table always_fetch_columns
deephaven/deephaven-plugins pull request #929
Opened 2024-10-08 20:29 UTC by mattrunyon

Fixes #513

Tested with the snippet I added to the docs for `on_row_press`. Also tested by using a context menu.

2024-10-08 21:15 UTC, dsmmcken commented
No comment, just saw that you updated the docs at same time and this makes me happy.

2024-10-09 18:11 UTC, bmingles commented on plugins/ui/src/js/src/elements/UITable/UITable.tsx
> + * Mostly put this here to avoid ignoring the exhaustive-deps rule where there are more deps in the component.
Is there any practical limit of array length that should be used with this hook? If so, might be worth mentioning in the comment block.

2024-10-09 18:14 UTC, bmingles commented on plugins/ui/src/js/src/elements/UITable/UITable.tsx
> +      return modelColumns.map(column => column.name);
Should we set some sort of max column count here to avoid doing something bad on a server if there were a ridiculous number of columns?

2024-10-09 18:18 UTC, bmingles commented on plugins/ui/src/js/src/elements/UITable/UITableContextMenuHandler.ts
> +type UIContextItem = Omit<ContextAction, 'action' | 'actions'> & {
Not necessary in this PR, but it might be nice to create a helper util something like:
```typescript
Optional<ContextAction, 'action' | 'actions'>
```
I've run into the need for this multiple times.

2024-10-09 18:22 UTC, bmingles commented on plugins/ui/src/js/src/elements/UITable/UITableContextMenuHandler.ts
> +type UIContextItem = Omit<ContextAction, 'action' | 'actions'> & {
Would it be worth making `ContextAction` generic? Something like:

```typescript
export interface ContextAction<
  TAction = ResolvableContextAction,
  TActionEvent = Event,
> {
  ...
  action?: (event: TActionEvent) => void;
  actions?: TAction[];
  ...
}

2024-10-09 18:33 UTC, bmingles commented on plugins/ui/src/js/src/elements/UITable/UITableContextMenuHandler.ts
> +export function wrapContextActions(
It would probably be good to have some unit tests on this one since there's multiple mappings + conditionals. Snapshot tests could be a decent option.

2024-10-09 18:38 UTC, bmingles requested changes
Left a couple of questions / 1 unit test suggestion

2024-10-09 21:27 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/UITable/UITableContextMenuHandler.ts
> +type UIContextItem = Omit<ContextAction, 'action' | 'actions'> & {
Possibly, but it could also cause other confusion since anywhere `ContextAction` is expected, you can't control the payload. The `ContextAction` interface in `@deephaven/components` takes a generic event which is provided by the context menu component. That event is not customizable AFAIK and is a general browser event.

What we end up doing is usually defining the action as `() => actualAction(actualParams)`. So in this case `UIContextItem` includes the function params the server expects to receive.

2024-10-10 20:45 UTC, merged