feat: UI Component Range Calendar
deephaven/deephaven-plugins pull request #930
Opened 2024-10-09 13:56 UTC by dgodinez-dh

closes https://github.com/deephaven/deephaven-plugins/issues/904
closes https://github.com/deephaven/deephaven-plugins/issues/854

2024-10-09 15:26 UTC, dsmmcken requested changes
docs/sidebar.json should be updated to link to relevant page (alphabetical order).

I think we've missed that for some of your previous components as well though.

2024-10-09 16:46 UTC, jnumainville requested changes

2024-10-09 16:46 UTC, jnumainville commented on plugins/ui/DESIGN.md
> +| `value`                 | `{ "start": Date, "end": Date } \| None`                   | The current value (controlled).                                                                    |
This typing is a bit odd to me - any reason we don't just use the `DateRange` type here?

2024-10-09 18:44 UTC, bmingles commented on plugins/ui/DESIGN.md
> +# simple range calendar that takes list view items directly and is controlled
Did you mean to say "list view items" here, or is this a copy / paste artifact?

2024-10-09 19:09 UTC, dsmmcken commented on plugins/ui/docs/sidebar.json
> +          },
that doesn't look right, label and paths are swapped

2024-10-09 19:11 UTC, dgodinez-dh commented on plugins/ui/DESIGN.md
> +| `value`                 | `{ "start": Date, "end": Date } \| None`                   | The current value (controlled).                                                                    |
Updated

2024-10-09 19:12 UTC, dgodinez-dh commented on plugins/ui/DESIGN.md
> +# simple range calendar that takes list view items directly and is controlled
Yes. That was a copy / paste artifact. Updated.

2024-10-09 19:12 UTC, dgodinez-dh commented on plugins/ui/docs/sidebar.json
> +          },
Fixed

2024-10-09 19:47 UTC, bmingles commented on plugins/ui/src/js/src/elements/RangeCalendar.tsx
> +  const [value, onChange] = useDebouncedOnChange<RangeValue<DateValue> | null>(
This seems to make the component always controlled. If the `default_value` prop is updated, it changes the value.

e.g.

```python
from deephaven import ui


@ui.component
def example():
    default_value, set_default_value = ui.use_state({"start": "2020-02-03", "end": "2020-02-08"})

    return ui.range_calendar(
        aria_label="Date range (uncontrolled)",
        default_value=default_value,
    ), ui.button('Update default', on_press=lambda _: set_default_value({"start": "2020-02-09", "end": "2020-02-20"}))


my_example = example()
```

2024-10-09 20:02 UTC, margaretkennedy commented on plugins/ui/docs/components/range_calendar.md
> +By default, the range calendar displays a single month. The `visible_Months` prop allows displaying up to 3 months at a time.
```suggestion
By default, the range calendar displays a single month. The `visible_months` prop allows displaying up to 3 months at a time.
```

2024-10-09 20:04 UTC, bmingles commented on plugins/ui/src/js/src/elements/utils/DateTimeUtils.test.ts
> +    expect(dateValuetoIsoString(date)).toEqual('2021-03-04T05:06:07Z');
I like the sequential numbering. Makes it easy to see the relationship of the input / output.

2024-10-09 20:08 UTC, bmingles requested changes
All looks good except there may be a bug with the `default_value` being controlled instead of uncontrolled.

2024-10-09 20:48 UTC, bmingles submitted a review, later dismissed
LGTM

2024-10-09 20:52 UTC, dgodinez-dh commented on plugins/ui/src/js/src/elements/RangeCalendar.tsx
> +  const [value, onChange] = useDebouncedOnChange<RangeValue<DateValue> | null>(
Updated

2024-10-10 17:01 UTC, jnumainville approved these changes

2024-10-11 11:38 UTC, dsmmcken approved these changes
approving docs.

2024-10-11 12:06 UTC, merged