fix: `dx` now respects the webgl flag
deephaven/deephaven-plugins pull request #934
Opened 2024-10-15 20:54 UTC by jnumainville

Fixes #612 

The current implementation has the following behavior, although note that this will not work fully until https://github.com/deephaven/web-client-ui/pull/2255 is merged
1. If webgl is enabled, nothing happens
2. If webgl is disabled and the webgl chart trace type can be replaced, it will be (such as `scattergl` -> `scatter`) and replaced again if reenabled (`scatter` -> `scattergl`)
3. If webgl is disabled and the webgl chart trace can't be replaced (such as `scatter3d` or `scattermapbox`) the prompt in the image below will appear. Once accepted, the acceptance persists for this specific chart, even if webgl is toggled again.
Note that disabling and reenabling through the settings without clicking Continue doesn't count as an acceptance, so if the prompt appears, the setting is enabled, then the setting is disabled again, the prompt will still appear.

![image](https://github.com/user-attachments/assets/75e81f41-b629-44f7-81f1-9ceaeb69d713)

2024-10-21 17:42 UTC, mofojed reviewed
Will need package bump but looks okay.

2024-10-25 18:01 UTC, jnumainville commented
I think this is almost ready, but is there anything else I need for the package bump? I'm unsure if I've done everything because as is this doesn't work locally due to the web-client-ui changes I made. Do I need to require a future engine version that would would itself use at least 0.97.0 web-client-ui?

2024-10-25 21:25 UTC, mofojed approved these changes

2024-10-25 21:25 UTC, mofojed commented on plugins/plotly-express/src/js/src/PlotlyExpressChartUtils.ts
> + * Traces that are at least partially powered by WebGL and have no SVG equivalent.
Add a link to the plotly documentation here if possible.

2024-10-25 21:29 UTC, mofojed approved these changes

2024-10-28 15:07 UTC, mattrunyon requested changes

2024-10-28 15:07 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    if (webgl != null) {
Rather than wrapping this entire implementation in `if (webgl != null)`, I would do 1 of 2 things.

1. Set a default for `webgl` in the props if undefined means default. I think the default behavior is `true` since setting w/ null/undefined would just skip the logic.
2. If you want undefined to have a separate meaning, use an early return instead
   ```ts
   if (webgl == null) {
     return;
   }
   // Rest of logic is now less indented
   ```

2024-10-28 15:07 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    this.webGlTraceIndices = getReplaceableWebGlTraceIndexes(this.plotlyData);
Change the function to `getReplaceableWebGlTraceIndices` to be consistent?

2024-10-28 20:21 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        this.fireBlocker([
Nice, I'll do the conditional calling.

2024-10-28 20:46 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        this.fireBlocker([
on second thought, there's no great way to work in the optional chaining when the function overrides is there? might need to require a version bump

2024-10-28 21:02 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        super.fireBlockerClear();
I don't love it either, but I'm having a tough time thinking of a good way to do this while keeping `fireBlockerClear` overriding the method inherited from `ChartModel` that doesn't have the same problem. `fireBlockerClear` is intentionally fired from `Chart` so that this component can keep control of the acknowledgement.

2024-10-28 21:14 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    this.webGlTraceIndices = getReplaceableWebGlTraceIndexes(this.plotlyData);
done

2024-10-28 21:14 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +    if (webgl != null) {
done

2024-10-28 21:26 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        this.fireBlocker([
`overrides` is just a TS keyword and doesn't actually do anything at runtime. It's just a compile step to check the base class defines the method and the signatures are compatible.

So you could do `super.fireBlocker?.(...)` in those calls. Or we can require 0.37.0 which is also reasonable to me. I think in that case maybe we want to publish the plugins w/ 0.37.0 as a requirement before 0.37.0 is published so we can release w/ the updated plugin. But I'm not sure if automated tests will like that if it tries to pull 0.37.0.

Without the optional chaining the user would just get a worse error if they needed webgl and had it disabled. And wouldn't be able to clear the warning. So not the biggest deal IMO since it's only a few charts and should still respect the flag on 0.36.1, just with worse error message

2024-10-28 21:29 UTC, mattrunyon commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        super.fireBlockerClear();
You should be able to use `overrides fireBlockerClear(isAcknowledged = true) {...}` and the types should be compatible. When `Chart` fires without a param it will just use the default. Unlike Python, JS does not care if you omit params and TS should be fine with adding optional params in a child class

2024-10-29 16:35 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        this.fireBlocker([
I think I'll go with requiring 0.37.0 then. We already require 0.36.0 anyways so not asking for much I think.

2024-10-29 17:14 UTC, jnumainville commented on plugins/plotly-express/src/js/src/PlotlyExpressChartModel.ts
> +        super.fireBlockerClear();
done

2024-11-23 00:18 UTC, mattrunyon approved these changes

2024-11-23 00:26 UTC, mattrunyon approved these changes

2024-11-23 00:42 UTC, merged