docs: ui.tabs
deephaven/deephaven-plugins pull request #943
Opened 2024-10-17 18:37 UTC by AkshatJawne

Closes #861

2024-10-23 15:58 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +Tabs can be created using `ui.tab` or `ui.tab_list` and `ui.tab_panels`, but not both combined.
using `ui.tab`, or `ui.tab_list` with `ui.tab_panels`? It's not clear which can't be combined.

2024-10-23 16:01 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +When specifying tabs using the `ui.tab_list` and `ui.tab_panels`, keys must be provided and match for each of the respective tabs.
```suggestion
When specifying tabs using `ui.tab_list` and `ui.tab_panels`, keys must be provided that match each of the respective tabs.
```

2024-10-23 16:01 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +The `is_quiet` prop makes tabs "quiet", by removing the line seperating the tab titles' and panel contents. This can be useful when the tabs  should not distract users from surrounding content.
```suggestion
The `is_quiet` prop makes tabs "quiet" by removing the line separating the tab titles' and panel contents. This can be useful when the tabs should not distract users from surrounding content.
```

2024-11-01 15:00 UTC, dsmmcken commented on plugins/ui/docs/components/tabs.md
> +3. Avoid nesting tabs more than three levels deep, as it can become overly complicated.
```suggestion
3. Avoid nesting tabs more than two levels deep, as it can become overly complicated.
```

I would count stacks as one level already.

2024-11-01 15:03 UTC, dsmmcken commented on plugins/ui/docs/components/tabs.md
> +        "Pick a tab (controlled)",
f string in the selected_tab key as "Pick a tab (controlled), selected tab: {...}"

2024-11-01 15:04 UTC, dsmmcken commented on plugins/ui/docs/components/tabs.md
> +            on_selection_change=set_selected_tab,
This is basically the same as the last example, anything we could show different?

2024-11-01 15:07 UTC, dsmmcken commented on plugins/ui/docs/components/tabs.md
> +            density="regular",
implementation question:

It doesn't error if I pass an invalid density prop, should it?

@jnumainville

2024-11-01 15:08 UTC, dsmmcken commented on plugins/ui/docs/components/tabs.md
> +        ),
No need to show the regular state here, that's already clear.

2024-11-02 16:31 UTC, AkshatJawne commented on plugins/ui/docs/components/tabs.md
> +from deephaven import ui
Hmmm yeah, should I create a ticket to change this?

2024-11-04 16:45 UTC, dsmmcken commented on plugins/ui/docs/components/tabs.md
> +            background_color=get_background_color(selected_tab),
```suggestion
            background_color=get_background_color(selected_tab),
            flex="auto",
            width="100%",
```

For additional styling only, makes it take the full space.

2024-11-06 19:16 UTC, dsmmcken approved these changes

2024-11-07 01:27 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +Tabs can be created using `ui.tab`, or usiing `ui.tab_list` and `ui.tab_panels`, but not the two options combined.
```suggestion
Tabs can be created using `ui.tab`, or using `ui.tab_list` with `ui.tab_panels`, but not the two options combined. 
```

2024-11-07 01:29 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +The `is_quiet` prop makes tabs "quiet" by removing the line separating the tab titles' and panel contents. This can be useful when the tabs should not distract users from surrounding content.
```suggestion
The `is_quiet` prop makes tabs "quiet" by removing the line separating the tab titles and panel contents. This can be useful when the tabs should not distract users from surrounding content.
```

2024-11-07 01:30 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +By default, tabs are horizontally oriented. To have tabs be vertically orientated, the `orientation` prop can be set to "vertical".
```suggestion
By default, tabs are horizontally oriented. To change the tabs' orientation, set the `orientation` prop to "vertical".
```

2024-11-07 01:31 UTC, margaretkennedy commented on plugins/ui/docs/components/tabs.md
> +Note this only occurs when tabs have a horizontal orientation; for vertical orientation of tabs, the list continues to extend downwards.
```suggestion
Note that this only occurs when tabs are horizontally oriented; when tabs are vertically oriented, the list continues to extend downwards.
```

2024-11-07 01:31 UTC, margaretkennedy requested changes
one typo; other suggestions

2024-11-07 16:17 UTC, margaretkennedy approved these changes

2024-11-07 17:38 UTC, merged