docs: Add architecture document
deephaven/deephaven-plugins pull request #949
Opened 2024-10-22 19:17 UTC by mofojed

- Provide details about the overall high-level architecture of deephaven.ui
- Diagram a couple work flows

2024-10-22 19:25 UTC, dsmmcken commented on plugins/ui/docs/architecture.md
> +5. [DocumentHandler](./src/js/src/DocumentHandler.tsx) - Handles the root of a rendered document, laying out the appropriate panels or dashboard specified.
These links won't work on the external site.

They would need to be https://github.com/deephaven/deephaven-plugins....

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +When you call a function decorated by `@ui.component`, it will return an `Element` object that has a reference to the function it is decorated; that is to say, the function does _not_ run immediately
```suggestion
When you call a function decorated by `@ui.component`, it will return an `Element` object that references the function it is decorated by; that is to say, the function does _not_ run immediately. The function runs when the `Element` is rendered by the client, and the result is sent back to the client. This allows the `@ui.component` decorator to execute the function with the appropriate rendering context. The client must also set the initial state before rendering, allowing the client to persist the state and re-render in the future.
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +When you call a function decorated by `@ui.component`, it will return an `Element` object that has a reference to the function it is decorated; that is to say, the function does _not_ run immediately
Note: what I prefer as better English might not be technically accurate, but you an always dismiss that suggestion. The "by" appears to be needed.

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +deephaven.ui is built to be a flexible and extensible [React-like](https://react.dev/learn/thinking-in-react) UI framework that can be used to create complex UIs in Python. You can create UIs using o
```suggestion
deephaven.ui is a flexible and extensible [React-like](https://react.dev/learn/thinking-in-react) UI framework that can create complex UIs in Python. You can create UIs using only the components provided by deephaven.ui, or you can create your own components using the `@ui.component` decorator.
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +deephaven.ui is built to be a flexible and extensible [React-like](https://react.dev/learn/thinking-in-react) UI framework that can be used to create complex UIs in Python. You can create UIs using o
I like the assertive version

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +Which should result in a UI like this:
```suggestion
This should result in a UI like:
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +When a component is rendered, the render task is [submitted to the Deephaven server as a "concurrent" task](https://deephaven.io/core/pydoc/code/deephaven.server.executors.html#deephaven.server.execu
wonder if numbers are helpful?
```suggestion
When a component is rendered, the render task is [submitted to the Deephaven server as a "concurrent" task](https://deephaven.io/core/pydoc/code/deephaven.server.executors.html#deephaven.server.executors.submit_task). This ensures that rendering one component does not block another component from rendering. A lock is then held on that component instance to 1) ensure it can only be rendered by one thread at a time, 2) a root [render context](#render-context) is set in the thread-local data, and  3) the component is rendered.
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +While rendering components, "hooks" are used manage state and other side effects. The magic part of hooks is they work based on the order they are called within a component. When a component is rende
```suggestion
While rendering components, "hooks" are used to manage state and other side effects. The magic part of hooks is they work based on the order they are called within a component. When a component is rendered, a new context is set, replacing the existing context. When the component is done rendering, the context is reset to the previous context. This allows for nested components to have their own state and side effects, and for the parent component to manage the state of the child components, re-using the same context when re-rendering a child component.
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +1. [Element](./src/deephaven/ui/elements/Element.py) - The basis for all UI components. Generally a [FunctionElement](./src/deephaven/ui/elements/FunctionElement.py) created by a script using the [@u
```suggestion
1. [Element](./src/deephaven/ui/elements/Element.py) - The basis for all UI components. Generally, a [FunctionElement](./src/deephaven/ui/elements/FunctionElement.py) created by a script using the [@ui.component](./src/deephaven/ui/components/make_component.py) decorator that does not run the function until it is rendered. The result can change depending on the context that it is rendered in (e.g., what "state" is set).
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +2. [ElementMessageStream](./src/deephaven/ui/object_types/ElementMessageStream.py) - The `ElementMessageStream` is responsible for rendering one instance of an element in a specific rendering context
```suggestion
2. [ElementMessageStream](./src/deephaven/ui/object_types/ElementMessageStream.py) - The `ElementMessageStream` is responsible for rendering one instance of an element in a specific rendering context and handling the server-client communication. The element is rendered to create a [RenderedNode](./src/deephaven/ui/renderer/RenderedNode.py), which is an immutable representation of a rendered document. The `RenderedNode` is then encoded into JSON using [NodeEncoder](./src/deephaven/ui/renderer/NodeEncoder.py), which pulls out all the non-serializable objects (such as Tables) and maps them to exported objects, and all the callables to be mapped to commands that JSON-RPC can accept. This is the final representation of the document sent to the client and ultimately handled by the `WidgetHandler`.
```

2024-10-23 15:39 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +3. [DashboardPlugin](./src/js/src/DashboardPlugin.tsx) - Client side `DashboardPlugin` that listens for when a widget of type `Element` is opened, and manage the `WidgetHandler` instances that are cr
```suggestion
3. [DashboardPlugin](./src/js/src/DashboardPlugin.tsx) - Client-side `DashboardPlugin` that listens for when a widget of type `Element` is opened and manages the `WidgetHandler` instances that are created for each widget.
```

2024-10-24 15:23 UTC, mofojed commented on plugins/ui/docs/architecture.md
> +When a component is rendered, the render task is [submitted to the Deephaven server as a "concurrent" task](https://deephaven.io/core/pydoc/code/deephaven.server.executors.html#deephaven.server.execu
Mmm the numbering here doesn't quite make sense, and maybe my sentence doesn't really either.
What I'm trying to say is "A lock is held on that component instance to ensure it can only be rendered by one thread at a time, then a root context is set in the thread-local data, and then the component is rendered". So a sequence of events, rather than all three things being the effect of the lock being held. How should I word that?

2024-10-24 15:27 UTC, mofojed commented on plugins/ui/docs/architecture.md
> +5. [DocumentHandler](./src/js/src/DocumentHandler.tsx) - Handles the root of a rendered document, laying out the appropriate panels or dashboard specified.
True... also there's no guarantee those files don't move later ... Should I bother linking to them? Should I link to the file on `main` branch? Or what do you think.

2024-10-24 15:34 UTC, dsmmcken commented on plugins/ui/docs/architecture.md
> +5. [DocumentHandler](./src/js/src/DocumentHandler.tsx) - Handles the root of a rendered document, laying out the appropriate panels or dashboard specified.
you could link to main, there's a risk they break. A link checker might pick that up for us though when we have that.

2024-10-24 19:06 UTC, mattrunyon commented on plugins/ui/docs/architecture.md
> +While rendering components, "hooks" are used to manage state and other side effects. The magic part of hooks is they work based on the order they are called within a component. When a component is re
I would maybe reorder this paragraph (or add to the start of it) to start with something about what a render context is. It's a little confusing that the section on render context starts by talking about hooks

"Each component renders in its own render context which helps keep track of state and side effects". Or something like that

2024-10-24 19:06 UTC, mattrunyon commented on plugins/ui/docs/architecture.md
> +    SP->>UIP: documentUpdated(Document, State)
This is an optional step if the callback triggered a re-render/state change. Not sure if we want to notate that in some way

2024-10-24 19:06 UTC, mattrunyon commented on plugins/ui/docs/architecture.md
> +4. [WidgetHandler](./src/js/src/WidgetHandler.tsx) - Uses JSON-RPC communication with an `ElementMessageStream` instance to load the initial rendered document and associated exported objects. Listens
This sends the initial state to the server and then gets the initial render, right? Or is the state sent in a different layer

2024-11-04 14:26 UTC, mofojed commented on plugins/ui/docs/architecture.md
> +5. [DocumentHandler](./src/js/src/DocumentHandler.tsx) - Handles the root of a rendered document, laying out the appropriate panels or dashboard specified.
Linking to main for now.

2024-11-04 17:33 UTC, dsmmcken requested changes

2024-11-04 17:33 UTC, dsmmcken commented on plugins/ui/docs/architecture.md
> +    return ui.flex(ui.text("Hello, world!"), my_button(), direction="column")
to be runnable, would also need to call and assign my_app()

2024-11-04 17:33 UTC, dsmmcken commented on plugins/ui/docs/architecture.md
> +import deephaven.plot.express as dx
I would put imports at the top like a sane person.

2024-11-04 17:51 UTC, mattrunyon commented on plugins/ui/docs/architecture.md
> +Each component render in its own render context, which helps keep track of state and side effects. While rendering components, "hooks" are used to manage state and other side effects. The magic part
```suggestion
Each component renders in its own render context, which helps keep track of state and side effects. While rendering components, "hooks" are used to manage state and other side effects. The magic part of hooks is they work based on the order they are called within a component. When a component is rendered, a new context is set, replacing the existing context. When the component is done rendering, the context is reset to the previous context. This allows for nested components to have their own state and side effects, and for the parent component to manage the state of the child components, re-using the same context when re-rendering a child component.
```

2024-11-06 14:16 UTC, dsmmcken submitted a review, later dismissed

2024-11-06 15:09 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +Each component renders in its own render context, which helps keep track of state and side effects. While rendering components, "hooks" are used to manage state and other side effects. The magic part
should you define hooks more explicitly before discussing their magic?

2024-11-07 15:09 UTC, mofojed commented on plugins/ui/docs/architecture.md
> +Each component renders in its own render context, which helps keep track of state and side effects. While rendering components, "hooks" are used to manage state and other side effects. The magic part
Hmm they likely deserve their own instructional page, in the `hooks` folder. Right now I have pages for specific hooks (`use_state`, `use_effect`, `use_memo`) but having a top level hooks pages similar to the [React docs](https://react.dev/reference/react/hooks) would be handy.
I'll capture this as part of https://github.com/deephaven/deephaven-plugins/issues/996

2024-11-07 15:26 UTC, margaretkennedy commented on plugins/ui/docs/architecture.md
> +Each component renders in its own render context, which helps keep track of state and side effects. While rendering components, "hooks" are used to manage state and other side effects. The magic part
sounds good to me!

2024-11-07 15:26 UTC, margaretkennedy approved these changes

2024-11-07 18:09 UTC, mattrunyon approved these changes

2024-11-07 18:45 UTC, merged