feat: First pass of ui.table functionality
deephaven/deephaven-plugins pull request #95
Opened 2023-10-25 19:37 UTC by mofojed

- Basic ui.table on_row_double_press functionality added
- Does not include the JS side that can handle the ui.table for now

2023-10-25 20:37 UTC, jnumainville requested changes

2023-10-25 20:37 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/_internal/utils.py
>  def get_component_name(component):
some missing types in these functions, might as well add them now

2023-10-25 20:37 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/panel.py
> +def panel(*children, title=None):
missing types

2023-10-25 20:37 UTC, jnumainville commented on plugins/ui/test/deephaven/ui/test_ui_table.py
> +    def expect_render(self, ui_table, expected_props: dict[str, Any]):
missing type for `ui_table`

2023-11-03 12:57 UTC, mofojed commented on plugins/ui/test/deephaven/ui/test_ui_table.py
> +    def expect_render(self, ui_table, expected_props: dict[str, Any]):
I'm actually not really sure how to type this properly - if I import the type to early, I get an error when writing the tests (because importing deephaven before the server starts causes an error). Any idea how I should handle this?

2023-11-03 14:51 UTC, jnumainville commented on plugins/ui/test/deephaven/ui/test_ui_table.py
> +    def expect_render(self, ui_table, expected_props: dict[str, Any]):
I think you can do this with postponed evaluation (PEP 563). Try importing `from __future__ import annotations
` 
https://stackoverflow.com/questions/70883599/type-hints-for-types-from-modules-which-may-not-be-loaded

2023-11-06 14:25 UTC, mofojed commented on plugins/ui/test/deephaven/ui/test_ui_table.py
> +    def expect_render(self, ui_table, expected_props: dict[str, Any]):
I think I've cleaned this up, though my editor is still complaining about it...

2023-11-06 18:07 UTC, merged