feat: UI table formatting
deephaven/deephaven-plugins pull request #950
Opened 2024-10-22 21:14 UTC by mattrunyon

Fixes #596. Adds UI table formatting based on the spec.

### Features

- Multiple formatting rules allowed on one table
- First matching rule for a formatting type is applied
- Single dataclass (ui.TableFormat) which encompasses the potential formatting options
- The `cols` parameter applies formatting to specific columns. The `where` parameter provides further filtering for rows
- DH theme color keywords supported in addition to hex and CSS keyword colors
- If a background color is specified with no text color, a contrasting black/white text color is applied

### Missing

- [ ] Docs
- [ ] Unit tests (should pull out some of the model code around formatting to test it easier)
- [ ] E2e tests
- [ ] Testing/setting good error messages if `where` is bad. Other potential error points we might want to add
- [ ] Databars through formatting option (follow-up PR?)
- [ ] Default as a keyword for all values. Could be useful if  you want to apply a background color and not a font color that may have no `where` clause later in the list. (follow-up PR?)
- [ ] Regex/wildcard column name matching (follow-up PR)
- [ ] Number formatting rules can be applied to date columns since they're actually longs. I think this is fine as just something to note instead of trying to determine if a formatting option is date/number specific

### Example Code

```py
from deephaven import ui
import deephaven.plot.express as dx

t = ui.table(
    dx.data.stocks(),
    formatting=[
        ui.TableFormat(background_color="positive", where="Sym=`DOG`", color='negative'),
        ui.TableFormat(
            cols=["Sym", "Exchange"], background_color="negative", where="Sym=`CAT`"
        ),
        ui.TableFormat(cols=["Sym", "Exchange"], alignment="center"),
        ui.TableFormat(cols="Size", color="notice", where="Size > 100"),
        ui.TableFormat(cols="Size", color="info", where="Size < 10"),
        ui.TableFormat(cols="Timestamp", value="E, dd MMM yyyy HH:mm:ss z"),
        ui.TableFormat(value="0.00%"),
    ],
)
```

2024-10-25 13:01 UTC, mofojed commented
> Default as a keyword for all values. Could be useful if you want to apply a background color and not a font color that may have no where clause later in the list. (follow-up PR?)

@mattrunyon Perhaps this could tie into the work for https://github.com/deephaven/deephaven-plugins/issues/549 (setting `Undefined` instead of `None` to get the default, for example). @wusteven815 will be working on that ticket soon.

2024-10-25 17:21 UTC, mattrunyon commented on plugins/ui/docs/components/table.md
> +
I think it would make more sense to do `Formatting Colors` and `Formatting Values` unless you want each of those sections to be 1 or 2 sentences. That feels like overkill to me to show someone what "changing the background color to red" does or "changing text alignment to left".

I think formatting colors would explain what kind of color values you can use and what values can take colors.

Formatting values would link out to appropriate docs about value format strings (I think they're Java formatting strings, but need to verify)

2024-10-29 14:54 UTC, mofojed requested changes
Looks good, a couple of minor fixes/notes. Would be nice if we could pass in a column name for the column or format value as well (with those taking precedent; e.g. if you have a column named `RED`, that value would take precedent over the colour `RED`).

I also tested with a large number of columns to make sure weren't getting caught with stuff out of the viewport, and it seems to work correctly:
```python
from deephaven import empty_table, ui
colors=["RED", "GREEN", "BLUE"]
cols = [f"C_{i}=i" for i in range(1, 100)]
t = empty_table(1000).update([*cols, "x=i", "c=`` + colors[i%3]", "RED=`` + colors[(i + 1)%3]"])
ut = ui.table(t, formatting=[ui.TableFormat(where="C_3%2==0", color="RED")])
```

2024-10-29 14:54 UTC, mofojed commented on plugins/ui/docs/components/table.md
> +            color="white",
We could look up if this matches a column name and get that value to use here.

2024-10-29 14:54 UTC, mofojed commented on plugins/ui/src/deephaven/ui/renderer/Renderer.py
> +                item, dict_factory=lambda x: {k: v for (k, v) in x if v is not None}
Should use the same util method we use to omit keys, e.g. `dict_to_camel_case`.
We're going to have some sort of `Undefined` vs. `None` soon: https://github.com/deephaven/deephaven-plugins/issues/549
So want to make sure we're not removing intentional `null`s.

2024-10-29 14:54 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/table.py
> +        formatting: list[TableFormat] | None = None,
Should we just name this `format` instead of `formatting` ? None of the other props are ing

2024-10-29 14:54 UTC, mofojed commented on plugins/ui/src/js/src/elements/UITable/UITable.tsx
>    const [databars] = useState(databarsProp ?? []);
Add a TODO here - we shouldn't need to do this when #123 is implemented. And then we won't get that issue where you need to open the table twice to get formatting applied.

2024-10-29 15:02 UTC, mattrunyon commented on plugins/ui/src/deephaven/ui/renderer/Renderer.py
> +                item, dict_factory=lambda x: {k: v for (k, v) in x if v is not None}
This is actually why I asked about if everything should be camel case recently. By using the util, it will change something that is not a prop from snake case to camel case. It would mean dataclasses and dicts are not interchangeable if they had snake case keys

2024-10-31 17:29 UTC, mattrunyon commented on plugins/ui/src/js/src/elements/UITable/UITable.tsx
>    const [databars] = useState(databarsProp ?? []);
We could check the equality via stringify. It wouldn't be 100% foolproof, but should work most/all the time.

Or use `deep-equals`. Maybe we add a `useDeepEquals` hook that returns a stable value until the value changes

2024-10-31 17:29 UTC, mattrunyon commented on plugins/ui/docs/components/table.md
> +            color="white",
Do you want that in this PR or as a follow-up?

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +### Formatting Rows and Columns
```suggestion
### Formatting rows and columns
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +Every formatting rule may optionally specify `cols` and `if_` properties. The `cols` property is a column name or list of column names to apply the formatting rule to. If `cols` is omitted, then the
```suggestion
Every formatting rule may optionally specify `cols` and `if_` properties. The `cols` property is a column name or list of column names to which to apply the formatting rule. If `cols` is omitted, then the rule will be applied to the entire row. The `if_` property is a Deephaven formula to which to apply the formatting rule. The `if_` property _must_ evaluate to a boolean. If `if_` is omitted, then the rule will be applied to every row. These may be combined to apply formatting to specific columns only when a condition is met.
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +> The `if_` property is a Deephaven formula evaluated in the engine. You can think of it like adding a new boolean column using [`update_view`](https://deephaven.io/core/docs/reference/table-operatio
```suggestion
> The `if_` property is a Deephaven formula evaluated in the engine. You can think of it like adding a new boolean column using [`update_view`](https://deephaven.io/core/docs/reference/table-operations/select/update-view/).
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +
Formatting colors and Formatting values sound reasonable in terms of avoiding super short sections; however, if a user is likely to search "Formatting table dates" and similar, it might be worth it.

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +### Formatting Rule Priority
```suggestion
### Formatting rule priority
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +### Formatting Color
```suggestion
### Formatting color
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +#### Formatting Text Color
```suggestion
#### Formatting text color
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +The following example will make all text the foreground color except the `Sym` column, which will be white. In dark mode the foreground color is white, and in light mode the foreground color is black
```suggestion
The following example will make all text the foreground color except the `Sym` column, which will be white. In dark mode, the foreground color is white, and in light mode, it is black. In light mode, the `Sym` column will be nearly invisible because it is not a theme color.
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +#### Formatting Background Color
```suggestion
#### Formatting background color
```

2024-11-01 10:28 UTC, margaretkennedy commented on plugins/ui/docs/components/table.md
> +#### Formatting Background Color
In the main docs, we use sentence case, which I think is the same for most of the plugin docs as well.

2024-11-01 17:23 UTC, mattrunyon commented on plugins/ui/docs/components/table.md
> +
I ended up adding `Formatting Colors` as an h3 to describe you can (and should) use theme colors. Then text/background color as h4.

For values I added an h3 for numeric and datetime

2024-11-01 17:37 UTC, mofojed submitted a review, later dismissed
Looks good to me. Curious what @dsmmcken thinks of using `if_` and `format_`

2024-11-01 17:37 UTC, mofojed commented on plugins/ui/src/deephaven/ui/components/table.py
> +        format_: list[TableFormat] | None = None,
Should we also accept `TableFormat` for cases without providing an array of formats?

2024-11-01 18:26 UTC, dsmmcken commented
> Curious what @dsmmcken thinks of using if_ and format_

I kinda hate it. I assume that's because those are both in python? Did I miss a discussion somewhere?

2024-11-01 20:51 UTC, dsmmcken approved these changes
Approving docs, not a fan of if_ or format_ but I defer to you guys.

I wouldn't hate cond=

2024-11-04 16:51 UTC, mattrunyon commented on plugins/ui/docs/components/table.md
> +Every formatting rule may optionally specify `cols` and `if_` properties. The `cols` property is a column name or list of column names to apply the formatting rule to. If `cols` is omitted, then the
I made different changes here to avoid ending in a preposition, but also avoid `to which to` since that felt awkward to me. Also clarified the `if_` param a bit

2024-11-04 17:10 UTC, margaretkennedy submitted a review, later dismissed

2024-11-05 19:21 UTC, mofojed approved these changes

2024-11-05 20:53 UTC, merged