feat: UI Dialog and DialogTrigger Components
deephaven/deephaven-plugins pull request #953
Opened 2024-10-23 17:33 UTC by dgodinez-dh

closes https://github.com/deephaven/deephaven-plugins/issues/933
closes https://github.com/deephaven/deephaven-plugins/issues/863

Note that there is a bug in the spectrum theme that causes the underlay to render as transparent. It is fixed here:
https://github.com/deephaven/web-client-ui/pull/2267
The underlay may render incorrectly depending on your version of `web-client-ui`
Because of this bug, we are waiting for a new version before adding a render test for dialog. See https://github.com/deephaven/deephaven-plugins/issues/952

2024-10-24 15:56 UTC, bmingles commented on plugins/ui/DESIGN.md
> +# Open and cloased using flag (controlled)
typo "cloased"

2024-10-24 15:58 UTC, bmingles commented on plugins/ui/DESIGN.md
> +            ui.content("Dismiss usin the X button."),
typo "usin".

2024-10-24 15:59 UTC, bmingles commented on plugins/ui/DESIGN.md
> +        ui.dialog(ui.heading("Dialog"), ui.content("Dismiss usin the X button."), is_dismissable=True, size="S"),
typo "usin"

2024-10-24 16:00 UTC, bmingles commented on plugins/ui/DESIGN.md
> +            ui.content("Dismiss usin the X button."),
typo "usin"

2024-10-24 16:04 UTC, bmingles commented on plugins/ui/DESIGN.md
> +# Open and cloased using flag (controlled)
typo "cloased"

2024-10-24 16:04 UTC, bmingles commented on plugins/ui/DESIGN.md
> +            ui.content("Dismiss usin the X button."),
typo "usin"

2024-10-24 16:11 UTC, bmingles commented on plugins/ui/docs/components/dialog.md
> +        set_closed()
The Spectrum component passes a `close` callback to `on_press`. I'm assuming we opted not to implement this due to nuances of async funtions in dh ui, but I wanted to double check?

2024-10-24 16:16 UTC, bmingles commented on plugins/ui/docs/components/dialog_trigger.md
> +If your modal fialog doesn't require the user to make a confirmation, you can set `is_dismissable` on the `dialog_trigger`. This adds a close button that the user can press to dismiss the `dialog`.
```suggestion
If your modal dialog doesn't require the user to make a confirmation, you can set `is_dismissable` on the `dialog_trigger`. This adds a close button that the user can press to dismiss the `dialog`.
```

2024-10-24 16:32 UTC, bmingles commented on plugins/ui/src/deephaven/ui/hooks/use_flag.py
> +def use_flag(
I'm happy to see this hook. Seems helpful.

2024-10-24 16:38 UTC, bmingles commented on plugins/ui/docs/components/dialog.md
> +                ui.form(ui.text_field(label="Name"), ui.checkbox("Make private"))
For some reason, I can't type in the text field here which seems strange.

2024-10-24 16:47 UTC, bmingles requested changes
The code looks good to me. The only functional issue I observed was that text_fields inside of dialog don't seem to allow typing. Everything else is minor typos in docs.

2024-10-24 18:16 UTC, dgodinez-dh commented on plugins/ui/docs/components/dialog.md
> +        set_closed()
Yes, I had a discussion with Matt and Bender about this on slack. The conclusion was to use controlled mode because of the difficulties involved in using the callback.

2024-10-24 18:22 UTC, dgodinez-dh commented on plugins/ui/docs/components/dialog.md
> +                ui.form(ui.text_field(label="Name"), ui.checkbox("Make private"))
Per your comment below, will look at https://github.com/deephaven/deephaven-plugins/issues/948

2024-10-24 19:01 UTC, bmingles commented on plugins/ui/docs/components/dialog.md
> +                ui.form(ui.text_field(label="Name"), ui.checkbox("Make private"))
Yeah, this is unrelated to your PR. You can ignore.

2024-10-24 20:36 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog.md
> +Dialogs are windows containing contextual information, tasks, or workflows that appear over the user interface. Depending on the kind of Dialog, further interactions may be blocked until the Dialog i
I don't think Dialog needs to be capitalized.

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog.md
> +Dismissable dialogs support an optional `on_dismiss` prop which is triggered whenever the dialog's close button is clicked. Similar to non-dismissable dialogs, you must chain the close function with
```suggestion
Dismissable dialogs support an optional `on_dismiss` prop that is triggered whenever the dialog's close button is clicked. Like non-dismissable dialogs, you must chain the close function with whatever callback you provide as `onDismiss`. If this event callback is not needed, the dismissable dialog will behave normally without passing this callback through.
```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog.md
> +Dialogs can be rendered as modals, popovers, or trays. See the `dialog_trigger` docs for more information.
link

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +If your `dialog` has buttons within it that should close the Dialog when pressed, you must use controlled mode in order to propagate the close function to the dialog's children. Dialogs that do not c
```suggestion
If your `dialog` has buttons within it that should close the dialog when pressed, you must use controlled mode to propagate the close function to the dialog's children. Dialogs that do not contain such interactive elements can provide the `dialog` component as is to the `dialog_trigger` as its second child.
```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +Modal dialogs create an underlay that blocks access to the underlying user interface until the dialog is closed. Sizing options can be found on the `dialog` page. Focus is trapped inside the Modal as
```suggestion
Modal dialogs create an underlay that blocks access to the underlying user interface until the dialog is closed. Sizing options can be found on the `dialog` page. Focus is trapped inside the modal as per the accessibility guidelines laid out by W3C.
```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +The popover dialog's offset can be adjusted using the `offset` and `cross_offset` props. The `offset` prop controls the spacing applied along the main axis between the element and its anchor element
```suggestion
The popover dialog's offset can be adjusted using the `offset` and `cross_offset` props. The `offset` prop controls the spacing applied along the main axis between the element and its anchor element, whereas the `cross_offset` prop handles the spacing applied along the cross axis.
```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +The example below will flip the dialog from above the trigger button to below the trigger button if the Dialog cannot render fully while maintaining 50px of padding between itself and the top of the
```suggestion
The example below will flip the dialog from above the trigger button to below the trigger button if the dialog cannot render fully while maintaining 50px of padding between itself and the top of the browser.
```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +The example below will flip the dialog from above the trigger button to below the trigger button if the Dialog cannot render fully while maintaining 50px of padding between itself and the top of the
or `dialog`?

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +Dialog trigger accepts an `on_open_change` handler which is triggered whenever the Dialog is opened or closed.
```suggestion
Dialog triggers accept an `on_open_change` handler that is triggered whenever the dialog is opened or closed. The example below updates a separate element with the dialog's current open state.

```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +The example below uses `on_open_change` to update a separate element with the current open state of the Dialog.
```suggestion
```

2024-10-24 20:45 UTC, margaretkennedy commented on plugins/ui/docs/components/dialog_trigger.md
> +```python
pausing here

2024-10-25 10:31 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_flag.md
> +`use_flag` is a hook used to add a boolean flag to your component. Since it is a hook, it must be used at the top level of your component. It returns a tuple with exactly three items: the current fla
```suggestion
`use_flag` is a hook that adds a boolean flag to your component. Since it is a hook, it must be used at the top level of your component. It returns a tuple with exactly three items: the current flag value, a function to set the flag to `True`, and a function to set the flag to `False` . Updating state will cause the component to re-render (running the function again). This is a convenience hook for when you only need functions to set a flag to `True` or `False`. For more complex state management, use `use_state`.
```

2024-10-25 12:08 UTC, dgodinez-dh commented on plugins/ui/docs/components/dialog.md
> +Dialogs can be rendered as modals, popovers, or trays. See the `dialog_trigger` docs for more information.
How do I link to one of the `dialog_trigger.md` doc which is in the same directory?

2024-10-25 12:09 UTC, dgodinez-dh commented on plugins/ui/docs/components/dialog.md
> +Dialogs are windows containing contextual information, tasks, or workflows that appear over the user interface. Depending on the kind of Dialog, further interactions may be blocked until the Dialog i
Updated

2024-10-25 13:04 UTC, dgodinez-dh commented on plugins/ui/docs/components/dialog.md
> +Dialogs can be rendered as modals, popovers, or trays. See the `dialog_trigger` docs for more information.
Ok, I tried something. I think it works.

2024-10-25 15:10 UTC, jnumainville requested changes

2024-10-25 15:10 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/dialog.py
> +    A dialog allows the user to select a date.
Looks like the incorrect description

2024-10-25 15:10 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/components/dialog_trigger.py
> +        mobile_type: 	The type of Dialog that should be rendered when on a mobile device.
```suggestion
        mobile_type: The type of Dialog that should be rendered when on a mobile device.
```

2024-10-25 15:25 UTC, dgodinez-dh commented on plugins/ui/src/deephaven/ui/components/dialog.py
> +    A dialog allows the user to select a date.
Updated

2024-10-25 15:39 UTC, mofojed commented on plugins/ui/src/deephaven/ui/hooks/use_flag.py
> +        set_flag(False)
Wrap these using `use_callback` so the callbacks provided from this hook are stable.

2024-10-25 16:08 UTC, dgodinez-dh commented on plugins/ui/src/deephaven/ui/hooks/use_flag.py
> +        set_flag(False)
Updated

2024-10-25 17:14 UTC, mofojed requested changes

2024-10-25 17:14 UTC, mofojed commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
The main draw for this hook is so we don't need to have lambdas like the following, correct?
```python
    flag, set_flag = ui.use_flag(False)
    return [
        ui.text(f"{flag}"),
        ui.button("Set True", on_press=lambda: set_flag(True)),
        ui.button("Set False", on_press=lambda: set_flag(False)),
    ]
```
Seems convenient for these cases, particularly around something like opening/closing a dialog... My only concern is that for each public hook we publish, careful consideration is required about the API of said hook and it's future usability/maintainability.

With that in mind, I have a couple concerns about this hook as is:
- `use_flag` is a name that doesn't make it immediately apparent what's up - the name `flag` to me implies a setting of some sort, like reading a global flag that's set. I'd rather name this something like `use_boolean`
- It's returning two setters instead of one (as typical with `use_state`), and it would be easy to accidentally mix up the setters (e.g. I do `value, set_false, set_true = ui.use_boolean()`, no warnings/errors in the code but my boolean will now be the opposite of what I want).
- Another really common use case with a boolean would be to have a `toggle` function, which this does not address. You could have _another_ setter function, but that's exacerbating the previous issue

Doing a search for existing React hooks for `useBoolean`, seems there are a couple hooks that have done something similar: 
1. https://marcoghiani.com/blog/react-custom-hooks-usetoggle-useboolean
2. https://dev.to/iamludal/react-custom-hooks-useboolean-3m6c
3. https://usehooks-ts.com/react-hook/use-boolean

I don't want to check in this hook as is... let me check something out first.

What's nice about this

2024-10-25 17:53 UTC, mofojed commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
Okay, take a look at this (@dgodinez-dh, @bmingles, @dsmmcken, and @jnumainville):

```python
from deephaven import ui
from deephaven.ui._internal import InitializerFunction, UpdaterFunction
from typing import Callable, cast, overload, Protocol, Tuple

class BooleanCallable(Protocol):
    on: Callable[[], None]
    off: Callable[[], None]
    toggle: Callable[[], None]

    def __call__(self, new_value: UpdaterFunction[bool]) -> None: ...

def use_boolean(
    initial_value: bool | InitializerFunction[bool] = False,
) -> Tuple[bool, BooleanCallable]:
    """
    Hook to add a boolean flag variable to your component. The flag will persist across renders.
    This is a convenience hook for when you only need functions to set a flag to True or False.
    For more complex state management, use use_state.

    Args:
        initial_flag: The initial value for the flag.
            It can be True or False, but passing a function will treat it as an initializer function.
            An initializer function is called with no parameters once on the first render to get the initial value.
            After the initial render the argument is ignored.
            Default is False.

    Returns:
        A tuple containing the current value of the flag, a function to set the flag to True, and a function to set the flag to False.
    """
    flag, set_flag = ui.use_state(initial_value)

    on = ui.use_callback(lambda: set_flag(True), [set_flag])
    off = ui.use_callback(lambda: set_flag(False), [set_flag])
    toggle = ui.use_callback(lambda: set_flag(lambda old_value: not old_value), [set_flag])

    def init_callable():
        boolean_callable = cast(BooleanCallable, set_flag)
        boolean_callable.on = on
        boolean_callable.off = off
        boolean_callable.toggle = toggle
        return boolean_callable

    boolean_callable = ui.use_memo(init_callable, [set_flag, on, off, toggle])

    return flag, boolean_callable

# Example usage:
@ui.component
def ui_boolean_example():
    value, set_value = use_boolean()

    return [
        ui.text(f"{value}"),
        ui.checkbox("My value", is_selected=value, on_change=set_value),
        ui.switch("My value", is_selected=value, on_change=set_value),
        ui.button("Set True", on_press=set_value.on),
        ui.button("Set False", variant="negative", on_press=set_value.off),
        ui.button("Toggle", variant="secondary", on_press=set_value.toggle)
    ]

my_boolean_example = ui_boolean_example()
```

Some things I like about this:
- Still returns a value/set_value tuple like a regular use_state, so you can still use it with our controls like checkboxes/switches.
- Can pass convenient `.on`, `.off`, `.toggle` callables still, for the use case you're using it for

Thoughts?

2024-10-25 18:07 UTC, dgodinez-dh commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
This seems good. I really wanted an open / close, but decided to try to generalize it. I also wanted a toggle, but  I didn't want to return a third setter.

2024-10-25 20:33 UTC, bmingles commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
The proposed api makes sense to me.

2024-10-25 20:41 UTC, dgodinez-dh commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
@mofojed We could add a fourth method to `BooleanCallable`:
`set: Callable[[bool], None]`
For the case where the user wants to set the value directly perhaps using the return value from another call?

2024-10-25 20:44 UTC, jnumainville commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
I like this. Keeps the api both flexible and clean.

2024-10-28 15:42 UTC, dgodinez-dh commented on plugins/ui/src/deephaven/ui/hooks/use_boolean.py
>  from .._internal import InitializerFunction, UpdaterFunction
That worked. Thanks.

2024-10-28 15:42 UTC, dgodinez-dh commented on plugins/ui/docs/hooks/use_flag.md
> +    ]
Updated

2024-10-28 16:34 UTC, bmingles approved these changes
I reviewed the new boolean hook. Changes look good to me.

2024-10-31 17:23 UTC, jnumainville requested changes

2024-10-31 17:23 UTC, jnumainville commented on plugins/ui/src/deephaven/ui/hooks/use_boolean.py
> +        boolean_callable.toggle = toggle
I'd invert the cast order here since at the time of this cast the `set` function does not technically conform to the `Protocol`.
```suggestion
        set.on = on
        set.off = off
        set.toggle = toggle
        boolean_callable = cast(BooleanCallable, set)
```

2024-10-31 18:18 UTC, jnumainville submitted a review, later dismissed

2024-10-31 20:12 UTC, mofojed submitted a review, later dismissed

2024-11-01 10:14 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_boolean.md
> +`use_boolean` is a hook that adds a boolean variable to your component. Since it is a hook, it must be used at the top level of your component. It returns a tuple with tow items: the current boolean
```suggestion
`use_boolean` is a hook that adds a boolean variable to your component. Since it is a hook, it must be used at the top level of your component. It returns a tuple with two items: the current boolean value and a callable to set the variable. Updating state will cause the component to re-render (running the function again). This is a convenience hook for when you only need functions to set a boolean variable. For more complex state management, use `use_state`.
```

2024-11-01 10:16 UTC, margaretkennedy commented on plugins/ui/docs/hooks/use_boolean.md
> +The boolean callable can be used to set the value of the boolean directly. It also includes convience methos `on` to set the variable to `True`, `off` to set the variable to `False`, and `toggle` to
```suggestion
The boolean callable can be used to set the boolean value directly. It also includes the convenience methods `on` to set the variable to `True,` `off` to set the variable to `False,` and `toggle` to set the variable to the opposite of its current state.
```

2024-11-01 12:30 UTC, margaretkennedy approved these changes

2024-11-01 13:18 UTC, merged