fix: Remove `frequency_bar`
deephaven/deephaven-plugins pull request #955
Opened 2024-10-23 20:20 UTC by jnumainville

Fixes #66 

BREAKING: frequency_bar is no longer supported. Instead, only pass one of x or y into bar.

2024-10-23 20:53 UTC, mattrunyon approved these changes

2024-10-23 20:55 UTC, margaretkennedy submitted a review, later dismissed

2024-10-24 15:18 UTC, mofojed requested changes
Does `frequency_bar` no longer work at all? We shouldn't just remove APIs and cause breaking changes, we should be deprecating it first.

2024-10-24 15:34 UTC, jnumainville commented
Yes in the current version of this PR it was completely removed. I'll deprecate the existing path instead. Is there a way to document deprecations so they show up clearly in the CHANGELOG? I suppose I could rename this to 'Deprecate frequency_bar"

2024-10-24 19:53 UTC, mofojed submitted a review, later dismissed

2024-10-24 19:53 UTC, mofojed commented on plugins/plotly-express/src/deephaven/plot/express/plots/bar.py
> +        FutureWarning,
```suggestion
        DeprecationWarning,
```

2024-10-24 20:26 UTC, mofojed approved these changes

2024-10-25 15:17 UTC, merged