docs: fragment
deephaven/deephaven-plugins pull request #962
Opened 2024-10-25 10:39 UTC by ethanalvizo

Closes #885 

The [react fragment docs](https://react.dev/reference/react/Fragment#rendering-a-list-of-fragments) have an example of grouping an input field with text elements in the fragment. I could show a similar one here but it seemed odd to me. If I wanted to show text by an input field I'd add a label to the component instead rather than using a text element.

<img width="697" alt="image" src="https://github.com/user-attachments/assets/7837cef8-5651-4ce8-b9c7-0d541ee60ced">

2024-10-28 14:31 UTC, dsmmcken requested changes
update sidebar.json

2024-10-28 14:49 UTC, mofojed commented on plugins/ui/docs/components/fragment.md
> +my_fragment = ui_fragment_list()
This example seems a little contrived - why bother wrapping the text in a `ui.text` event? Also should be using an id from an object rather than an array index.
Something more like the example you linked would be better:
```python
from deephaven import ui


@ui.component
def ui_post_list(items):
    posts = (
        ui.fragment(ui.heading(p["title"]), ui.text(p["body"]), key=p["id"])
        for p in items
    )
    return ui.flex(
        *posts,
        direction="column",
    )


my_post_list = ui_post_list([
    {"id": 1, "title": "About me", "body": "I am a developer"},
    {"id": 2, "title": "Contact", "body": "I want to hear from you!"},
])
```

2024-10-31 20:55 UTC, dsmmcken approved these changes

2024-11-01 10:29 UTC, margaretkennedy submitted a review, later dismissed

2024-11-04 19:13 UTC, dsmmcken approved these changes

2024-11-04 21:19 UTC, margaretkennedy approved these changes

2024-11-05 14:39 UTC, merged