docs: panel
deephaven/deephaven-plugins pull request #964
Opened 2024-10-28 03:02 UTC by ethanalvizo

Closes #922

2024-10-28 14:03 UTC, ethanalvizo commented on plugins/ui/docs/components/panel.md
> +`direction`: The direction of the panel's content layout, either "row" or "column".
The style props available for panel are a combination of the props available from flex and view. I was thinking of pointing the users to view each of those docs if they wanted to see examples. But if it's better to include visual examples here I can do that as well

2024-11-01 14:21 UTC, dsmmcken requested changes

2024-11-01 14:21 UTC, dsmmcken commented on plugins/ui/docs/components/panel.md
> +Note: By default, the top-level `@ui.component` is automatically wrapped in a panel. Therefore, you only need to define it if you want to customize the panel, such as setting a custom tab name, color
```suggestion

The `panel` component is a versatile [flex](./flex.md) container designed to group and organize elements within a layout. Panels are presented as individual tabs that can be moved to different positions by dragging the tabs around. By default, the top-level return of a `@ui.component` is automatically wrapped in a panel, so you only need to define a panel explicitly if you want to customize it. Customizations can include setting a custom tab title, background color or customizing the flex layout.
```

2024-11-01 14:21 UTC, dsmmcken commented on plugins/ui/docs/components/panel.md
> +A panel cannot be nested within other components (other than the layout ones such as [ui.row](#uirow), [ui.column](#uicolumn), [ui.stack](#uistack), [ui.dashboard](#uidashboard)).
```suggestion
Panels can only be nested within [ui.row](./dashboard.md#row-api-reference), [ui.column](./dashboard.md#column-api-reference), [ui.stack](./dashboard.md#stack-api-reference) or [ui.dashboard](#./dashboard.md).
```

Prefer positive wording and fixed links.

2024-11-01 14:21 UTC, dsmmcken commented on plugins/ui/docs/components/panel.md
> +
Why isn't this using autodoc? This should not be done manually.

2024-11-01 14:21 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/panel.py
> -    **props: Any,
Hmm, this is missing some the exposed view/flex props. They were being permitted by the **props, but now should be manually made available.

background_color is missing for example, can you check and add whatever else is missing?

2024-11-01 14:21 UTC, dsmmcken commented on plugins/ui/docs/components/panel.md
> +`direction`: The direction of the panel's content layout, either "row" or "column".
This should be the autodoc, but no you don't need to show examples of any of the common props.

2024-11-04 05:04 UTC, ethanalvizo commented on plugins/ui/docs/components/panel.md
> +
Removed this section entirely

2024-11-04 05:23 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/panel.py
> -    **props: Any,
background_color was the only one missing from the tests. Was it only the missing test props that I should add in or all of the missing props from view/flex?

2024-11-04 17:37 UTC, dsmmcken requested changes

2024-11-04 17:37 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/panel.py
> -    **props: Any,
Still missing
'UNSAFE_style'
'UNSAFE_className'

Needs to be specified or they can be passed.

2024-11-05 20:44 UTC, ethanalvizo commented on plugins/ui/src/deephaven/ui/components/panel.py
> -    **props: Any,
Mb I realized I should be referring to the React implementation of panel to find all the props we should be supporting. Added the UNSAFE props and confirmed no other missing ones

2024-11-05 22:01 UTC, dsmmcken approved these changes

2024-11-06 11:33 UTC, margaretkennedy approved these changes

2024-11-07 15:29 UTC, merged