feat: Allow passing in a pandas dataframe to dx plots
deephaven/deephaven-plugins pull request #967
Opened 2024-10-28 19:46 UTC by jnumainville

Fixes #8 

Allows passing in a pandas dataframe to all plots that take a table.

Example:
```import plotly.express as px
import deephaven.plot.express as dx
df = px.data.iris()
fig = dx.scatter(df, x="sepal_width", y="sepal_length", color="species", symbol="species")
```
<img width="844" alt="Screenshot 2024-10-28 at 2 36 19 PM" src="https://github.com/user-attachments/assets/2716c662-a5dd-49ae-b6de-6ce8a445373f">

Also now require a table (or similar) passed in for all plot types, as is already done for `density_heatmap`. This was part of #1, although not the full changes needed, but made sense to do now. This doesn't break anything as the plot isn't expected to work without a table anyways.

Additionally adds a test utility for chart comparisons. Not so essential that all tests need to change per se but reduces future  test boilerplate.

2024-10-28 20:10 UTC, margaretkennedy approved these changes

2024-10-28 21:50 UTC, mattrunyon requested changes

2024-10-28 21:50 UTC, mattrunyon commented on plugins/plotly-express/src/deephaven/plot/express/plots/line.py
>      y: str | list[str] | None = None,
Makes sense as a followup ticket, but do we want to start requiring some of these props? A line with just a table prop doesn't make any sense

2024-10-28 21:50 UTC, mattrunyon commented on plugins/plotly-express/test/deephaven/plot/express/BaseTest.py
> +        pop_template: bool = True,
If none of these are strictly required, can you add something that verifies at least 1 assertion is run? You could do `assert_chart_equals(chart)` which would effectively do nothing, so might be nice to have a warning that you need to provide at least 1 other value

Not sure if this is a thing in Python unittest. I know Jest for JS has a way to at least say "expect 4 assertions" usually based around async testing. But not sure if it is applicable to helpers.

You could also just track it yourself in the function and raise an error at the end if you haven't done any assertions

2024-10-29 14:34 UTC, jnumainville commented on plugins/plotly-express/src/deephaven/plot/express/plots/line.py
>      y: str | list[str] | None = None,
Yeah this is part of #1

2024-10-29 14:42 UTC, jnumainville commented on plugins/plotly-express/docs/README.md
> +[Deephaven Express](https://github.com/deephaven/deephaven-plugins) is a powerful plotting library built on top of [Plotly Express](https://plotly.com/python/plotly-express/) that enhances its capabi
You are right. I misremembered the conversation we had and thought I was cleaning something up. I'll change it back.

2024-10-29 15:20 UTC, jnumainville commented on plugins/plotly-express/docs/README.md
> +[Deephaven Express](https://github.com/deephaven/deephaven-plugins) is a powerful plotting library built on top of [Plotly Express](https://plotly.com/python/plotly-express/) that enhances its capabi
done

2024-10-29 15:21 UTC, jnumainville commented on plugins/plotly-express/test/deephaven/plot/express/BaseTest.py
> +        pop_template: bool = True,
done

2024-10-29 18:40 UTC, mattrunyon approved these changes

2024-10-29 19:17 UTC, merged