fix:
deephaven/deephaven-plugins pull request #972
Opened 2024-10-29 21:28 UTC by jnumainville

fixes #965 

Default to test with 3.8

Also adds other environments to run. A tiny bit more maintenance when we add/remove version support but useful for both the gh action and easily running different versions locally

2024-10-30 00:33 UTC, mattrunyon commented
I would change the PR title to `test` instead of `fix`

How does this affect users? Will tox install Python for you or should we update the readme to suggest what version of Python to install or suggest something to manage different Python versions? 

I guess since it uses the versioned Python executable we could just recommend installing the specific version for testing.

2024-10-30 14:13 UTC, jnumainville commented
`tox` sets up an independent python version so it doesn't matter which one is installed. What this does now is allow you to easily test with different versions
Currently, if you just run with `tox -e py` it will use whatever version you are using in your environment. 
With this change, if you run `tox -e py` it will always run 3.8. You can also run specific other versions easily though, such as `tox -e py3.9`, `tox -e py3.10` etc.

2024-10-30 18:20 UTC, mattrunyon commented
Is there something I'm missing for tox to set up my Python version? I just ran `tox -e py` with this branch and it quit with "could not find python interpreter with spec(s): python3.8"

2024-10-30 18:51 UTC, jnumainville commented
Oh yeah, you do need to have whatever version your looking for already. I can add that note to the tox directions. I should expand on those anyways. 
How you have that version is currently dependent on your setup though. Maybe we could standardize that.

2024-11-04 17:42 UTC, mattrunyon requested changes

2024-11-04 17:42 UTC, mattrunyon commented on README.md
> +Note that `tox` sets up an isolated environment for running tests.
This might have been true previously, but "above" is now e2e tests. Should link to the section instead

2024-11-04 17:42 UTC, mattrunyon commented on README.md
> +Be default, `tox` will run against Python 3.8, which will need to be installed on your system before running tests.
This seems to be causing me an issue after I installed 3.8. Tox says it is going to recreate the env because the Python version changed, then throws because `distutils.cmd` is not found. I'm not sure if I need to re-run some setup with `python3.8` specifically or if there's some other issue

2024-11-04 19:59 UTC, jnumainville commented on README.md
> +Note that `tox` sets up an isolated environment for running tests.
fixed

2024-11-04 19:59 UTC, jnumainville commented on README.md
> +Be default, `tox` will run against Python 3.8, which will need to be installed on your system before running tests.
added note for linux setup

2024-11-04 20:45 UTC, mattrunyon commented on README.md
> +```
I would put this in an important callout just so it stands out a bit.

````
> [!IMPORTANT]
> Linux, and possibly other setups such as MacOS depending on method, may require additional packages to be installed to run Python 3.8.
> ```shell
> sudo apt install python3.8 python3.8-distutils libpython3.8
> # or just full install although it will include more packages than necessary
> sudo apt install python3.8-full
> ```
````

2024-11-05 16:17 UTC, jnumainville commented on README.md
> +```
done

2024-11-05 20:30 UTC, mattrunyon approved these changes

2024-11-05 22:54 UTC, merged