feat: ui.badge
deephaven/deephaven-plugins pull request #973
Opened 2024-10-29 23:36 UTC by AkshatJawne

Closes #935 and Closes #868

2024-11-01 17:33 UTC, mofojed requested changes

2024-11-01 17:33 UTC, mofojed commented on plugins/ui/docs/components/badge.md
> +    ui.icon("vsWarning"), "Rejected", variant="negative"
This Rejected example doesn't look right:
![image](https://github.com/user-attachments/assets/351f9c1e-5df4-46f0-9e92-2ec60a001dbc)
If "Rejected" is wrapped in `ui.text` it looks correct:
![image](https://github.com/user-attachments/assets/23202c4d-2fc0-444d-9575-ec6ac5321bfc)

We probably need to autowrap strings in a `Text` element.

2024-11-01 17:33 UTC, mofojed commented on plugins/ui/src/js/src/widget/WidgetUtils.tsx
> +  Badge,
You're not actually using the `Badge` wrapper that you created, since you're importing directly from `@deephaven/components` here. You should be importing from `../elements` below so you actually use your wrapper.

2024-11-01 17:33 UTC, mofojed commented on plugins/ui/src/js/src/elements/Badge.tsx
> +export default Badge;
Right now this wrapper isn't doing anything, and for some reason you're pulling `variant` out of the props just to pass it right into DHCBadge (which is unnecessary, since it was in props and you're passing all of them through already).
We do want to wrap text children though as per my other comments:
```suggestion
import React from 'react';
import {
  Badge as DHCBadge,
  BadgeProps as DHCBadgeProps,
} from '@deephaven/components';
import { wrapTextChildren } from './utils';

export function Badge(props: DHCBadgeProps): JSX.Element {
  const { children } = props;
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <DHCBadge {...props}>{wrapTextChildren(children)}</DHCBadge>
  );
}

Badge.displayName = 'Badge';

export default Badge;
```

2024-11-01 19:33 UTC, dsmmcken commented on plugins/ui/src/js/src/elements/Badge.tsx
> +export default Badge;
This is on spectrum, but that sub-set of colors supported by variant is pretty weird. I wouldn't be opposed to expanding the implementation to manually pass in variant as backgroundColor UNSAFE_style then accept any color. We would also have to pick a proper contrasting fg color though.

2024-11-04 19:25 UTC, AkshatJawne commented on plugins/ui/src/js/src/elements/Badge.tsx
> +export default Badge;
@dsmmcken Would this be something we wanted to look into?

2024-11-05 21:48 UTC, mofojed submitted a review, later dismissed

2024-11-06 11:30 UTC, margaretkennedy approved these changes

2024-11-06 14:18 UTC, dsmmcken commented on plugins/ui/src/js/src/elements/Badge.tsx
> +export default Badge;
Unsure if we should hold this until that, or follow ticket. Because it would be a breaking change.

@mofojed thoughts?

2024-11-07 20:18 UTC, dsmmcken approved these changes

2024-11-08 18:16 UTC, dsmmcken approved these changes

2024-11-08 18:51 UTC, merged