docs: ui.contextual_help
deephaven/deephaven-plugins pull request #974
Opened 2024-10-29 23:54 UTC by AkshatJawne

Closes #832

2024-11-01 18:21 UTC, dsmmcken requested changes

2024-11-02 15:53 UTC, AkshatJawne commented on plugins/ui/docs/components/contextual_help.md
> +The contextual help feature shows extra information about the state of a component, or a total view.
I had meant view as in an intentional a grouping of components, sort of related to ui.view. But yeah, getting rid of this, not super helpful.

2024-11-04 19:10 UTC, dsmmcken requested changes

2024-11-04 19:21 UTC, dsmmcken approved these changes

2024-11-04 21:20 UTC, margaretkennedy commented on plugins/ui/docs/components/contextual_help.md
> +The contextual help component supports different placement options for when the positioning of the popover needs to customized.
```suggestion
The contextual help component supports different placement options for when the positioning of the popover needs to be customized.
```

2024-11-04 21:20 UTC, margaretkennedy commented on plugins/ui/docs/components/contextual_help.md
> +The contextual help componenthas an `on_open_change` prop, triggered when the the popover opens or closes.
```suggestion
The `on_open_change` prop is triggered when the popover opens or closes.
```

or at least: The contextual help component has an `on_open_change` prop, triggered when the popover opens or closes.

2024-11-06 19:17 UTC, dsmmcken submitted a review, later dismissed

2024-11-07 01:32 UTC, margaretkennedy commented on plugins/ui/docs/components/contextual_help.md
> +The contextual help component supports different placement options for when the positioning of the popover needs to be customized.
```suggestion
The contextual help component supports different placement options for when the popover's positioning needs to be customized.
```

2024-11-07 15:53 UTC, margaretkennedy approved these changes

2024-11-07 15:59 UTC, merged