fix: Switch to salmon-sync action and fix action warnings
deephaven/deephaven-plugins pull request #978
Opened 2024-10-30 20:20 UTC by jnumainville

Fixes #969 - Switches to use the `salmon-sync` action for docs uploads 
Fixes #970 - Cleans up warnings. For the most part this was just version bumps. The most significant change was in caching for `test-js-packages.yml`. I followed [these](https://github.com/actions/cache/blob/main/save/README.md#always-save-cache) directions to migrate that.

Tested on my fork

2024-10-30 23:14 UTC, mattrunyon requested changes

2024-10-30 23:14 UTC, mattrunyon commented on .github/workflows/make-docs.yml
> +          destination: deephaven/deephaven-plugins/${{ inputs.package }}/${{ inputs.version }}/
Unrelated to this PR, but is the trailing slash required for the destination? If not, does it have different behavior/meaning if it's omitted?

2024-10-30 23:14 UTC, mattrunyon commented on .github/workflows/pre-commit.yml
> +          python-version: '3.x'
Should this be our lowest supported Python version? Not sure how Python version affects pre-commit

2024-10-30 23:14 UTC, mattrunyon commented on .github/workflows/test-js-packages.yml
> +        if: always() && steps.restore-node-modules.outputs.cache-hit != 'true'
Not sure if this should go at the end of the action instead. I'm not sure if `npm run test:ci` will generate any cacheable things in `node_modules` that we would want updated. Some packages cache there, but not sure if our testing packages do.

2024-10-31 15:38 UTC, jnumainville commented on .github/workflows/make-docs.yml
> +          destination: deephaven/deephaven-plugins/${{ inputs.package }}/${{ inputs.version }}/
[Appears to be the same it omitted](https://rclone.org/commands/rclone_copy/#:~:text=If%20you%20are%20familiar%20with,about%20the%20source%20or%20destination.)

2024-10-31 15:47 UTC, jnumainville commented on .github/workflows/test-js-packages.yml
> +        if: always() && steps.restore-node-modules.outputs.cache-hit != 'true'
moved it to the end just to be safe

2024-10-31 15:47 UTC, jnumainville commented on .github/workflows/pre-commit.yml
> +          python-version: '3.x'
good point, I think it could, moved to 3.8

2024-10-31 18:39 UTC, mattrunyon approved these changes
I changed the type from fix to ci. Mostly it's just this is something that doesn't need to go in the changelog, and I believe ci is ignored in our changelog generation.

2024-10-31 20:05 UTC, mofojed approved these changes

2024-10-31 21:08 UTC, merged