feat: ui.link
deephaven/deephaven-plugins pull request #980
Opened 2024-10-31 13:37 UTC by AkshatJawne

Closes #977 and Closes #860

**Need to clarify:**
- Omitted implementation of `download`, `ping`, `href_lang`, `referrer_policy`, `router_options` since they do not appear to be working in the spectrum implementation, and they do not seem super needed (given that this is meant to serve as a basic link component)
    -  If we want to implement said props, I can implement special logic for them

2024-11-01 15:47 UTC, dsmmcken commented on plugins/ui/docs/components/link.md
> +
extra new lines

2024-11-01 16:25 UTC, dsmmcken requested changes

2024-11-01 16:25 UTC, dsmmcken commented on plugins/ui/docs/components/link.md
> +        ui.link(ui.icon("github_alt"), href="https://github.com/deephaven"),
```suggestion
        ui.link(ui.icon("github"), href="https://github.com/deephaven"),
```

2024-11-01 16:25 UTC, dsmmcken commented on plugins/ui/docs/components/link.md
> +            href="https://deephaven.io/landing-page/one-on-one/",
```suggestion
            href="https://deephaven.io/contact",
```

2024-11-01 16:25 UTC, dsmmcken commented on plugins/ui/docs/components/link.md
> +        variant="over_background",
I don't think this is working, text should display white but it's not.

2024-11-01 16:25 UTC, dsmmcken commented on plugins/ui/docs/components/link.md
> +)
```suggestion
from deephaven import ui


my_link_is_quiet_example = ui.text(
    "You can ", ui.link("use quiet", is_quiet=True), " links inline."
)
```

2024-11-01 16:28 UTC, dsmmcken commented on plugins/ui/src/deephaven/ui/components/link.py
> +    # omitted download, ping, href_lang, referrer_policy, router_options
download, ping, href_lang, referrer_policy should be supported and are native browser behaviours. 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes

2024-11-01 19:33 UTC, mofojed requested changes

2024-11-01 19:33 UTC, mofojed commented on plugins/ui/src/js/src/elements/Link.tsx
> +Link.displayName = 'Link';
You're not modifying any of the props here, so I don't think you need to make this wrapper and in WidgetUtils you can just import straight from `@deephaven/components`.

2024-11-06 19:19 UTC, dsmmcken commented on plugins/ui/docs/components/link.md
> +
still there

2024-11-07 14:59 UTC, mofojed submitted a review, later dismissed

2024-11-07 16:03 UTC, AkshatJawne commented on plugins/ui/docs/components/link.md
> +
Should be good now.

2024-11-07 16:11 UTC, margaretkennedy approved these changes

2024-11-07 20:20 UTC, dsmmcken approved these changes

2024-11-07 20:43 UTC, merged